### ISSUE TITLE
Oddities in on rig display

### ISSUE THREAD

**Issue by tim2000s** [openaps/oref0#1004]
Running the latest developments and getting the attached. Strange lines in the on rig display. 
![screenshot_20180514-085510](https://user-images.githubusercontent.com/14833174/39985040-07881b32-5755-11e8-8fa4-d6e982a51aa3.png)

**Comment by danamlewis** [comment]
@tim2000s we have https://github.com/openaps/oref0/issues/979 open, can you post your image there? Closing this to to streamline discussion into one place related to webpage display. Thanks!
