### ISSUE TITLE
Improvements on recovering from a low

### ISSUE THREAD

**Issue by eyim** [openaps/oref0#101]
In order to recover from a low, many times OpenAPS will turn off his basal for a long time - 1 to 3 hours.  If during the night, this will result in a net negative iob  - sometimes a net negative 2+ units before his blood sugars start to rise.

The issue is just as he is getting back to a normal range, OpenAPS will give him insulin to offset the net negative iob which results in pushing him back down to another low.  And the cycle continues.

In our case, the preferred behavior would be to ignore the net negative iob.  This often happens after he has a lot of exercise that day or studies a lot that evening.  The body seems to want to recover extra sugar leading to the low and requiring a significant net negative iob to recover.
![image](https://cloud.githubusercontent.com/assets/4616134/14822701/74e0a34e-0b84-11e6-970f-47235a680d97.png)

**Comment by scottleibrand** [comment]
Autosens is designed to help deal with this, so I'd like to examine what it was doing at the time. Do you have details from the log on what basal and ISF adjustments it was making at the time?

If it was successfully detecting excess sensitivity, but not reducing high-temps enough as a result, one thing we could do would be to figure out how to apply the higher ISF only to net positive IOB (and high temps), not to net negative IOB (and low temps). 

If it wasn't detecting much sensitivity, you might want to try adjusting your autosens reports to use a shorter timeframe (so it can more quickly detect the onset of sensitivity). Or there may be some autosens algorithm tweaks we can make...

**Comment by eyim** [comment]
I don't have auto sens running.  When I tried it before, it didn't appear to be helpful and made some adjustments I was totally comfortable with but that was several versions ago.  I'll turn it on again and see how it goes.  Your suggestion on using a shorter timeframe might work better.

**Comment by jasoncalabrese** [comment]
I saw patterns like this before, but it seems that the combination of new pump sites (mio-90 vs inset-30) and autosens have helped.  At the time I was thinking it was an insulin absorption issue, where dia would become longer.

**Comment by scottleibrand** [comment]
I would start with 24h of glucose data and 24h+DIA of pump data. The algorithm will be most consistent when it has a full daily meal cycle at all times. If that is insufficiently responsive, we can try shorter samples of glucose data, but that will come at the expense of being less prone to detect sensitivity in the evening (when there are lots of positive post-meal deviations that aren't large enough to meet the exclusion cutoff) and more prone to detect sensitivity in the morning.

**Comment by scottleibrand** [comment]
I think the solution to this is to use autosens.  Please reopen or open a new issue if you still see this after autosens is in place.
