### ISSUE TITLE
554 pump will not loop when programmed with 24 basal rates [0.7.0-DEV]

### ISSUE THREAD

**Issue by Alzibiff** [openaps/oref0#1020]
If basal rates in the pump are set at every hour from 00:00 to 23:00, which makes it easy to compare and adjust rates in the pump when viewing autotune logs, the 554 pump fails to loop.

Fixed when the number of basal rates in the pump is reduced from 24 to 14 (may be able to go higher but not tested - certainly not as high as 24).

**Comment by cluckj** [comment]
I think this was resolved in: https://github.com/ecc1/medtronic/commit/e7b965b916dc05c8cfe83ea4aa202af321c46b17
