### ISSUE TITLE
Need to add a bolus status check before changing pump clock to sync to rig time

### ISSUE THREAD

**Issue by danamlewis** [openaps/oref0#1022]
**An issue occurs if pump time (set clock) is changed during a bolus**: additional bolus record(s) is created in pump history, which would cause OpenAPS to perceive double the IOB from that bolus. (Only a single bolus is delivered to the body, however). 

**Details**: Issues was spotted with a 1u easy bolus (manual bolus) which then showed up in pump as multiple boluses; and in NS as a 2u bolus. OpenAPS recorded IOB prior to bolus as 0.845 and after the 1u bolus (seeing the 2u record) as 2.894. Reservoir levels also confirmed it was actually a single 1u bolus delivered. 

**Proposed solution**: add a bolus status check and do not change clock if a bolus is active.

**Comment by hilarykoch** [comment]
Yes. This happened to my son the other night. He boluses for one unit, but NS and IOB indicated two units were given, and bolus history also indicated multiple boluses. But reservoir levels confirmed only one unit was delivered. However, OpenAPS registered the delivery as two units and continued to make decisions using those two units as part of IOB. Logs showed a time change at the same time of bolus. 
<img width="1218" alt="ns" src="https://user-images.githubusercontent.com/11912289/40637154-2d9f9318-62d1-11e8-9554-7e68851a804a.png">
<img width="1259" alt="iob pre" src="https://user-images.githubusercontent.com/11912289/40637156-30868604-62d1-11e8-96aa-38481d48467b.png">
<img width="1257" alt="iob post" src="https://user-images.githubusercontent.com/11912289/40637157-32d0c2da-62d1-11e8-994d-f3abe6741a75.png">
![img_7400-1](https://user-images.githubusercontent.com/11912289/40637241-aab0c868-62d1-11e8-83ad-e08c53382045.jpeg)
![img_7398-1](https://user-images.githubusercontent.com/11912289/40637242-aac1f638-62d1-11e8-9f96-73635fcc1077.jpeg)
![img_7399-1](https://user-images.githubusercontent.com/11912289/40637243-aad88e2a-62d1-11e8-962a-6f081050c619.jpeg)
![img_7402-1](https://user-images.githubusercontent.com/11912289/40637244-aaecf072-62d1-11e8-8626-a610bc52e083.jpeg)

**Comment by jmcrawford** [comment]
This occurred to us tonight.  Was giving a 2.2u bolus, but with the time changes it reported as giving 5.65, with pump records showing boluses of 2.2, 1.7 and 1.75.  

Is there a way to programatically determine if the pump is bolusing?  I'm thinking no, which is why we need the ESCESCESC prior to issuing an SMB.  So would it make sense to do the ESCESCESC thing prior to a time change also?

**Comment by scottleibrand** [comment]
It is possible to check status (which will show if it’s bolusing) but there’s also the potential for a race condition there. It might be best to do both the status check and the ESC ESC ESC ESC before time change. Would you like to code up and PR those checks?

**Comment by JELCRAWFORD** [comment]
If there is a possible race condition, what is the added benefit of doing a status check in this change?  Wouldn't it be better to keep the change simple and limit the communication with the pump to the minimum needed (in this case - ESC ESC ESC ESC) to ensure the problem doesn't occur?  Or am I missing something the status check will cover that is different that the ESC solution provides?

**Comment by scottleibrand** [comment]
If the bolus is already started you can’t cancel it. The ESC ESC ESC ESC is just in case the human is in the Bolus Wizard about to start one.

**Comment by bewest** [comment]
Fwiw, suspend causes bolus to cancel.

HTH,
-bewest

**Comment by scottleibrand** [comment]
Yeah, that’s what we recommend people do manually if they accidentally enter a too-large bolus. In this case we don’t want to cancel the bolus once it’s started, just defer setting the time until it completes.

**Comment by danamlewis** [comment]
Resolved via #1151, closing.
