### ISSUE TITLE
Nightscout does not recognise Bolus Wizard carbs from Medtronic 512 pump

### ISSUE THREAD

**Issue by Raeburn6111** [openaps/oref0#1033]
Not sure if I'm posting in right place but....
Initially posted this on Facebook through Looped!
At @danamlewis suggestion posted this in Gitter openaps/hardware dev
Someone was going to look into it but this was a couple of weeks ago and issue not resolved.
Since then I have been calculating bolus using bolus wizard, and then doing a carb correction through Nightscout.
Would prefer not to have to do this if possible.
Is anyone able to look into this further please?
(using Medtronic 512 with Edison board rig)
Thanks in advance

**Comment by rollerdecom** [comment]
This never worked for me with my 512 on Edison. So I usually just quickbolus, stay around 1/3 below my calculation and let oref0 basals do the rest. This is with Fiasp dosing before eating and wide basal ranges.

Of course, it's just a workaround, but relying on autosens works nicely for my rapidly changing sensitivity.

**Comment by cluckj** [comment]
This should be fixed when one does a new setup with a 0.7.0 branch for the x12. Can someone with an x12 please confirm?

**Comment by rollerdecom** [comment]
@cluckj: This totally worked! Thank you !!!
---
I was on dev, when switching to 0.7.0-dev. So this is not a newly flashed setup. But the switch worked without flashing vom scratch, which it didn't some weeks before. Also, as carbs never have worked before, this is not an 0.6 inherited fix.

**Comment by rollerdecom** [comment]
Maybe I was too quick. When using bolus wizard the 2nd time, the bolus vanished completely. It's still seen on the pump display, but it's not part of loop-calculation or nightscout.

First working bolus was 0.5, 2nd failing was 3.0U. Could the problem be time span related?

**Comment by cluckj** [comment]
Can you run `rm ~/myopenaps/monitor/pumphistory-24h-zoned.json` to force a full pump history refresh, and see if that makes the bolus show up in the loop calculation?

**Comment by rollerdecom** [comment]
I did that. But even after a refresh, there was no change. 

Then I found sth else, that might be relevant. In nightscout admin the first bolus expert was logged as future object in mdb and any basal change since then. The second bolus expert was just logged with the carbs (in future objects...). I delete them now.

**Comment by scottleibrand** [comment]
Please be very careful to note whether you’re seeing problems with refreshing pump history records on the rig, and having them show up in IOB etc., or if you’re seeing problems with those treatments being uploaded to NS. Those are very different things, and only the former matters for looping safely.

**Comment by rollerdecom** [comment]
I mentioned, because I was pretty sure about this specific incidence. 

Rig calculation and NS data were in sync. 2h zero temp, bolus wizard 30g/3U, but 20 min. with 10U basal later around 2.9 IOB on rig as on NS.

**Comment by rollerdecom** [comment]
P.S.: after deleting future treatments, all basals, boluses and carbs are gone since the first bolus expert some hours before (Nightscout), but IOB looks unchanged (OK).

**Comment by danamlewis** [comment]
is this still an issue with x12 pumps and 0.7.0-dev? Can someone clarify?

**Comment by cluckj** [comment]
This was resolved in https://github.com/ecc1/medtronic/commit/3cc940777ec9bfea456fe2f0432dbf9ba97fbe25

Should be okay to close this issue.
