### ISSUE TITLE
OpenAPS enacting temp basal with old bg data

### ISSUE THREAD

**Issue by eyim** [openaps/oref0#104]
[glucose.json.txt](https://github.com/openaps/oref0/files/243955/glucose.json.txt)
Attached is my glucose.json file.  This file resulted in openaps running a temp basal even well after the 15 old threshold.  I've had old data from hours ago that openaps still thinks is current data.

Obviously, this is a major concern as if his last bg was high or low it could cause a serious problem

**Comment by jasoncalabrese** [comment]
I think this is related to the old xdrip date string issue, I see `"dateString": "04/30/2016 20:56:43 PM"`, maybe we can detect that and fallback to using `date`.  Also you might want to process the file.  Need to figure out the exact json -e, but the idea would be to set `dateString = new Date(date).toISOString()`, but that might still need to be zoned.

**Comment by eyim** [comment]
Thanks for looking into this Jason.  Not sure if it is worth fixing it in oref0 since it seems like an edge case although a particularly dangerous one.  I'll look into fixing it on my end.

**Comment by jasoncalabrese** [comment]
I expect it to happen again, and since the correct data is there we should be able to make it work, but it might need to fixed in multiple places
