### ISSUE TITLE
Autotune: support AndroidAPS data format from NS

### ISSUE THREAD

**Issue by scottleibrand** [openaps/oref0#1047]
Currently autotune does not recognize AndroidAPS temp basal records or bolus records from NS.  Some examples are below.

I don't think there's enough information in the percent temp basal records to run autotune: we need some way to tell for sure what the neutral basal was at the time that each temp basal was recorded. I don't think that exists in the treatments collection, and I'm not sure how we'd infer it from profile switch records that might not even occur on the same day...

```
  {
    "_id": "5af5d81311c3561028ad2cb9",
    "eventType": "Temp Basal",
    "duration": 30,
    "percent": -100,
    "pumpId": "redacted",
    "created_at": "2018-05-11T17:50:49Z",
    "enteredBy": "openaps://AndroidAPS",
    "NSCLIENT_ID": "redacted",
    "carbs": null,
    "insulin": null
  },
  {
    "_id": "5af5d6fe11c3561028ad2cb5",
    "eventType": "Temp Basal",
    "created_at": "2018-05-11T17:45:53Z",
    "enteredBy": "openaps://AndroidAPS",
    "pumpId": "redacted",
    "NSCLIENT_ID": "redacted",
    "carbs": null,
    "insulin": null
  },
  {
    "_id": "5af5ca1111c3561028ad2c99",
    "eventType": "Bolus Wizard",
    "insulin": 0.95,
    "created_at": "2018-05-11T16:51:16Z",
    "date": 1526057476000,
    "isSMB": false,
    "pumpId": "redacted",
    "glucose": 7.5,
    "glucoseType": "Manual",
    "boluscalc": {
      "profile": "<"redacted">",
      "eventTime": "2018-05-11T16:50:51Z",
      "targetBGLow": 5.5,
      "targetBGHigh": 5.5,
      "isf": 10,
      "ic": 24,
      "iob": 0.30700000000000005,
      "bolusiobused": true,
      "basaliobused": true,
      "bg": 7.5,
      "insulinbg": 0.2,
      "insulinbgused": true,
      "bgdiff": 2,
      "insulincarbs": 1,
      "carbs": 24,
      "cob": 0,
      "insulincob": 0,
      "othercorrection": 0.2,
      "insulinsuperbolus": 0,
      "insulintrend": -0.124,
      "insulin": 0.9500000000000001
    },
    "NSCLIENT_ID": "redacted",
    "carbs": null
  },
  {
    "_id": "5af5ca3211c3561028ad2c9a",
    "eventType": "Meal Bolus",
    "carbs": 24,
    "created_at": "2018-05-11T16:51:06Z",
    "date": 1526057466000,
    "isSMB": false,
    "pumpId": "redacted",
    "NSCLIENT_ID": "redacted",
    "insulin": null
  },
  {
    "_id": "5af5c56211c3561028ad2c89",
    "eventType": "Temp Basal",
    "duration": 15,
    "percent": 30,
    "pumpId": "redacted",
    "created_at": "2018-05-11T16:30:52Z",
    "enteredBy": "openaps://AndroidAPS",
    "NSCLIENT_ID": "redacted",
    "carbs": null,
    "insulin": null
  },
  {
    "_id": "5af5c1c711c3561028ad2c80",
    "eventType": "Correction Bolus",
    "insulin": 0.1,
    "created_at": "2018-05-11T16:15:54Z",
    "date": 1526055354000,
    "isSMB": true,
    "pumpId": "redacted",
    "NSCLIENT_ID": "redacted",
    "carbs": null
  },
  {
    "_id": "5af5c1c711c3561028ad2c7f",
    "eventType": "Temp Basal",
    "duration": 30,
    "percent": -90,
    "pumpId": "redacted",
    "created_at": "2018-05-11T16:15:51Z",
    "enteredBy": "openaps://AndroidAPS",
    "NSCLIENT_ID": "redacted",
    "carbs": null,
    "insulin": null
  },
  {
    "_id": "5af5c0a311c3561028ad2c7a",
    "eventType": "Temp Basal",
    "duration": 15,
    "percent": 120,
    "pumpId": "redacted",
    "created_at": "2018-05-11T16:11:00Z",
    "enteredBy": "openaps://AndroidAPS",
    "NSCLIENT_ID": "redacted",
    "carbs": null,
    "insulin": null
  },
```

**Comment by MilosKozak** [comment]
when we run autotune inside NS, profile switch information will be visible and easy accessible

**Comment by scottleibrand** [comment]
Do you anticipate AndroidAPS running NS autotune every night and automatically downloading the results?  I am a bit hesitant to recommend SMB without regular autotune runs, so it seems like we need to automate it somehow.

**Comment by MilosKozak** [comment]
i expect we port autotune to AAPS as well. but it would be better to have it running in NS to be able compare results

**Comment by philipgo** [comment]
Our AndroidAPS entries look different and contain an absolute basal value (What causes the difference? @MilosKozak ). I think the only change necessary in order to make Autotune process AAPS entries would be to accept the term "absolute" in addition to "rate" in the [IOB calculation from temp basals](https://github.com/openaps/oref0/blob/66c610afa64bb249d215122a1732391c771ce7a1/lib/iob/index.js#L48)

AndroidAPS temp basal entry:
```
{ 
    "_id" : ObjectId("5a62aa948985f800113082a2"), 
    "eventType" : "Temp Basal", 
    "duration" : NumberInt(15), 
    "absolute" : 0.48400000000000004, 
    "created_at" : "2018-01-20T02:33:56Z", 
    "enteredBy" : "openaps://AndroidAPS", 
    "NSCLIENT_ID" : 12345678.0
}
``` 
OpenAPS temp basal entry
```
{ 
    "_id" : ObjectId("5b439d146d3c1ce2083cec12"), 
    "duration" : NumberInt(30), 
    "raw_duration" : {
        "_type" : "TempBasalDuration", 
        "_description" : "TempBasalDuration 2018-07-09T19:34:37 head[2], body[0] op[0x16]", 
        "timestamp" : "2018-07-09T19:34:37+02:00", 
        "_body" : "", 
        "_head" : "1601", 
        "duration (min)" : NumberInt(30), 
        "_date" : "65e2134912"
    }, 
    "timestamp" : "2018-07-09T19:34:37+02:00", 
    "absolute" : 0.35, 
    "rate" : 0.35, 
    "raw_rate" : {
        "_type" : "TempBasal", 
        "temp" : "absolute", 
        "_description" : "TempBasal 2018-07-09T19:34:37 head[2], body[1] op[0x33]", 
        "timestamp" : "2018-07-09T19:34:37+02:00", 
        "_body" : "00", 
        "_head" : "330e", 
        "rate" : 0.35, 
        "_date" : "65e2134912"
    }, 
    "eventType" : "Temp Basal", 
    "medtronic" : "mm://openaps/mm-format-ns-treatments/Temp Basal", 
    "created_at" : "2018-07-09T19:34:37+02:00", 
    "enteredBy" : "openaps://medtronic/722"
}
```

**Comment by scottleibrand** [comment]
Yeah, `absolute` records should be pretty straightforward to process: the bigger challenge is the pumps that report things in `percent` with no other information available (in the treatments, without separately parsing the profile) to figure out how much insulin was actually delivered.

**Comment by philipgo** [comment]
So it depends on the pump whether AAPS uploads 'percent' or 'absolute'? (We use a Combo pump) If that is the case, AAPS still always knows what absolute rate that corresponds to and it should be easy to let AAPS upload it?

**Comment by AdrianLxM** [comment]
If we could change the data structure we could upload the absolute value as well. Problem would be rates that start before a full hour and end afterwards. Those would only have the absolute value valid when the temp begins in case the basal profile changes at the full hour.

**Comment by AdrianLxM** [comment]
On the other hand: Autotune must know the current valid profile switch anyway. That would be one multiplication.

**Comment by sulkaharo** [comment]
Let's please please fix data formats to be unified and not add logic

**Comment by MarkMpn** [comment]
If AAPS converted percent temp basals to absolute before uploading to NS and it went over a basal change boundary, it's likely that AAPS would set a new temp basal on the first BG reading received after that hour, so the discrepancy should be minor. Not perfect, but should be a step forward?

Alternatively, could OAPS only set percentage temp basals up to the next basal change boundary to avoid any overlaps? This might be a useful change anyway - if you've got a high temp basal running and the base basal suddenly steps up on the next hour, you might end up getting significantly more insulin than OAPS had calculated.

**Comment by sulkaharo** [comment]
@MarkMpn OAPS only ever uses absolute basal rates, never percentages

**Comment by MarkMpn** [comment]
@sulkaharo For absolute temps, doesn't the same logic apply the other way around? If OAPS sets a high temp and it overlaps with a step down in the base basal rate, it would end up delivering more extra insulin than it had calculated?

**Comment by scottleibrand** [comment]
@AdrianLxM @sulkaharo do y'all know if this has been resolved in AndroidAPS or Nightscout, or if it's still an issue?

**Comment by philipgo** [comment]
IIRC this is what fixed the issue in dev: https://github.com/openaps/oref0/pull/1060
