### ISSUE TITLE
Kill go binaries before upgrading them

### ISSUE THREAD

**Issue by scottleibrand** [openaps/oref0#1049]
Downloading Go pump binaries from: https://github.com/ecc1/medtronic/releases/download/v2018.05.24/medtronic-386-spi.tar.xz
./
./openaps.jq
./cgmpage
./sniff
./historypage
./pumphistory
./listen
./mmtune
./fakemeter
./cgmhistory
./mdt
Installing Go pump binaries ...
‘/root/go/bin/cgmhistory’ -> ‘/usr/local/bin/cgmhistory’
‘/root/go/bin/cgmpage’ -> ‘/usr/local/bin/cgmpage’
‘/root/go/bin/fakemeter’ -> ‘/usr/local/bin/fakemeter’
‘/root/go/bin/historypage’ -> ‘/usr/local/bin/historypage’
‘/root/go/bin/listen’ -> ‘/usr/local/bin/listen’
‘/root/go/bin/mdt’ -> ‘/usr/local/bin/mdt’
‘/root/go/bin/mmtune’ -> ‘/usr/local/bin/mmtune’
‘/root/go/bin/openaps.jq’ -> ‘/usr/local/bin/openaps.jq’
‘/root/go/bin/pumphistory’ -> ‘/usr/local/bin/pumphistory’
cp: cannot create regular file ‘/usr/local/bin/pumphistory’: Text file busy
‘/root/go/bin/sniff’ -> ‘/usr/local/bin/sniff’
Couldn't copy go/bin

**Comment by danamlewis** [comment]
Fixed via https://github.com/openaps/oref0/pull/1134
