### ISSUE TITLE
No data in offline webpage 0.7.0-dev

### ISSUE THREAD

**Issue by tepidjuice** [openaps/oref0#1053]
Offline webpage does is not populated with data when using 0.7.0-dev and a non-standard install directory.

As a fix I've tried hardcoding all the file paths but this hasn't worked either. There is probably a requirement somewhere for the directory to be /root/myopenaps/

**Comment by tepidjuice** [comment]
It seems when pulled the latest branch a number of files in the www directory did not download. I've curled these and it is working as expected now. Closing issue.

**Comment by scottleibrand** [comment]
Which files were those? Are they not properly managed by git? Is the problem reproducible? If so, I’d like to figure out a fix.

**Comment by tepidjuice** [comment]
From memory it was: `www/setup-http.sh` and `www/regenerate-index.sh`. Also, the folder: `www/static/css/` was missing and everything in `www/static/js/` except: `bootstrap.min.js`.

**Comment by tepidjuice** [comment]
After updating, by running, `cd src/oref0 && git checkout dev && git pull && npm run global-install && cd && ./${myopenaps}/oref0-runagain.sh` It seems the files in `www/` that weren't installed last time have not been updated. Here's the output of `ls -al` in the `www/` directory:

`drwxr-xr-x 4 root root 4096 Jul 23 13:51 .`
`drwxr-xr-x 9 root root 4096 Jul 23 13:23 ..`
`-rw-r--r-- 1 root root 3864 Jul 23 13:23 app.py`
`-rw-r--r-- 1 root root 5375 Jul 23 13:51 app.pyc`
`-rw-r--r-- 1 root root 1177 Jul 16 14:01 regenerate-index.sh`
`-rw-r--r-- 1 root root  340 Jul 16 14:01 setup-http.sh`
`drwxr-xr-x 4 root root 4096 Jul 16 14:01 static`
`drwxr-xr-x 2 root root 4096 Jul 23 13:23 templates`

The 16th is when I manually downloaded the missing files.

**Comment by danamlewis** [comment]
probably related to #979 - let's keep web server discussion/resolutions in that thread.
