### ISSUE TITLE
alert messages not entirely visible on samsung galaxy s4 mini and s5 mini

### ISSUE THREAD

**Issue by wootmasterslick** [openaps/oref0#1056]
The alarm messages are not entirely visible. See attached picture. [https://files.gitter.im/MilosKozak/AndroidAPS/Fqf9/IMG_2156.jpeg](https://files.gitter.im/MilosKozak/AndroidAPS/Fqf9/IMG_2156.jpeg)
This possibly also occurs on other devices with smaller screen size.

**Comment by danamlewis** [comment]
Can you resubmit to the AndroidAPS repo? Thanks!

**Comment by wootmasterslick** [comment]
woops
