### ISSUE TITLE
nightscout treatment does not retrieve past BG value when programming tratment in the past

### ISSUE THREAD

**Issue by wootmasterslick** [openaps/oref0#1057]
When programming a treatment in the careportal. e.g. entering bolus and carbs that was done 3 hours before  it does not retrieve the BG value from that timepoint. The autofill BG remains the current BG readout. This confuses new users. Also as far as I could track this value does not affect the input and data in nightscout for these entries. Would help if the BG at that time was retrieved or the input removed if it is not relevant.

**Comment by danamlewis** [comment]
@wootmasterslick this should be logged in the cgm-remote-monitor repo for Nightscout - if you haven't had this resolved already, can you open a PR there so Nightscout devs can address it?
