### ISSUE TITLE
Support plugged-in G4 receiver w/g4-go in oref0-setup.sh

### ISSUE THREAD

**Issue by cluckj** [openaps/oref0#1062]
And deprecate g4-local/g4-upload...

**Comment by scottleibrand** [comment]
We use a plugged-in G4 w/ g4-go without issue. I don’t recall if that depends on anything in misc-stuff or not.

**Comment by cluckj** [comment]
I think the issue is with setting up G4 receivers without Share; this code in `oref0-setup.sh` doesn't let the setup proceed without specifying a Share serial number:
```
    if [[ ${CGM,,} =~ "g4-go" ]]; then
        prompt_and_validate BLE_SERIAL "If your G4 has Share, what is your G4 Share Serial Number? (i.e. SM12345678)" validate_g4share_serial
        BLE_SERIAL=$REPLY
        echo "$BLE_SERIAL? Got it."
        echo
    fi
```

**Comment by scottleibrand** [comment]
Ah, ok. You could probably make one up, but that is less than ideal.

**Comment by cluckj** [comment]
Issue was fixed upstream...
