### ISSUE TITLE
Issue with Bluetooth Switching under Dev since merge of 0.7.0-dev

### ISSUE THREAD

**Issue by tim2000s** [openaps/oref0#1066]
Updated a dev rig today to new dev following the update. Bluetooth switching no longer works with the Edison/EXB. 

When I re-entered the oref0-online cron entry from the previous set up into crontab, bluetooth connection worked fine when dropping wifi.

The difficulty is that with the new oref0-cron-xxx files, following through to where the bluetooth MAC address is stored is much more difficult so I've been unable to check whether there is an error in my set-up.

**Comment by ToreBj** [comment]
I just went through that and you need to put it in your preferences.json file.
"bt_mac": "64:A2:F9:35:09:2D"
It's done in: oref0-cron-every-minute.sh

BT_MAC="$(get_pref_string .bt_mac "")"

get_pref_string is in : oref0-bash-common-functions.sh

Yeah- harder to navigate now!

**Comment by ToreBj** [comment]
I guess you did like me, copied your old pref file after setup :)

**Comment by ToreBj** [comment]
I also saw that bluetoothd was running after startup:
 419 ?        Ss     0:00 /usr/lib/bluetooth/bluetoothd

This path is not used by the scripts? oref0-bluetoothup.sh is using:

# start bluetoothd if bluetoothd is not running
if ! ( ps -fC bluetoothd >/dev/null ) ; then
   sudo /usr/local/bin/bluetoothd &

I copied it to /usr/local/bin.

**Comment by danamlewis** [comment]
Closing; please reopen if still an issue with latest 0.7.0-dev
