### ISSUE TITLE
Autotune no longer updating settings/autotune.json in latest dev branch 

### ISSUE THREAD

**Issue by tim2000s** [openaps/oref0#1069]
I’ve been running this for three days. On no occasion has the autotune.json file been created from the newprofile file, even though autotune has run correctly. Comparing to older setups I’m not sure why as I’ve not found the difference.

**Comment by zgohr** [comment]
Does `autotune.json` exist and it's just not being tuned correctly, or does it not exist at all?

**Comment by tim2000s** [comment]
Further to this, autotune doesn’t seem to be running now. The last three days I’ve had to manually run it. 

I’ll probably start over with a fresh rig and see what happens.

**Comment by tim2000s** [comment]
updated dev to the most recent branch and not seeing Autotune running overnight at all now. I saw a similar issue with the online service, so wonder whether the new cron construct is causing a few issues.

**Comment by tim2000s** [comment]
I’ve added dev on a second rig and it is also not running Autotune overnight. I’ve had a look through the oref0-cron-nightly.sh file and the only thing I can suggest is that there’s something around the ENABLE function for Autotune not working correctly. 

If I add this to run directly in crontab it works as normal so it’s definitely something about the structure of the script causing the issue.

**Comment by danamlewis** [comment]
@tim2000s is this still an issue on latest dev?

**Comment by danamlewis** [comment]
Closing; please reopen if still an issue with latest 0.7.0-dev
