### ISSUE TITLE
xDripAPS not working with current Dev

### ISSUE THREAD

**Issue by tim2000s** [openaps/oref0#1072]
I cleaned the rig down (cleared out ~/src and removed myopenaps then reinstalled using dev with xDripAPS as data source). When offline, it doesn’t operate correctly within the loop, although the glucose data Is getting across to the platform correctly. Will have to dig further into the issue but I suspect it’s that xDripAPS isn’t being picked up correctly in setup.

**Comment by dramageek** [comment]
Let me know if I can help diagnose. Seeing the same problem here, which is why I started #1064 .

**Comment by tim2000s** [comment]
I’m closing this one as after a couple of reboots it’s now working, so we may need a slightly different issue for this.
