### ISSUE TITLE
TI stick is called dead when looping, even after calling oref0-reset-usb

### ISSUE THREAD

**Issue by inform880** [openaps/oref0#108]
It seems completely random when this happens, but I get it more frequently when rebooting or after turning my pi on after I shut it down, properly or improperly. It also happens randomly throughout the day. This is what it looks like after it goes dead, and then calling oref0-reset-usb:

```
pi@raspberrypi:~/myopenaps $ sudo oref0-reset-usb
Power-cycling USB to fix dead stick
pi@raspberrypi:~/myopenaps $ lsusb
Bus 001 Device 022: ID 1d50:8001 OpenMoko, Inc.
Bus 001 Device 021: ID 22a3:0047
Bus 001 Device 020: ID 0424:ec00 Standard Microsystems Corp. SMSC9512/9514 Fast Ethernet Adapter
Bus 001 Device 019: ID 0424:9514 Standard Microsystems Corp.
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

pi@raspberrypi:~/myopenaps $ ls -la /dev/mmeowlink
lrwxrwxrwx 1 root root 7 May  5 10:39 /dev/mmeowlink -> ttyACM1
```

As you can see it, it finds it just find! It's worth mentioning also, that I can physically see it doing the reset, as the dexcom says it's not charging for a few seconds when it happens. I can also call `openaps use pump mmtune`, which seems contrary to what you would think I'd be able to do. Next time it goes dead, I'll try more and add more information.

**Comment by jasoncalabrese** [comment]
What does your preflight look like?  Maybe some old carelink stuff still in there?

**Comment by inform880** [comment]
My preflight command:
```
pi@raspberrypi:~/myopenaps $ openaps alias show preflight
preflight ! bash -c "rm -f monitor/clock.json && openaps report invoke monitor/clock.json 2>/dev/null && grep -q T monitor/clock.json && echo PREFLIGHT OK || (mm-stick warmup || (sudo oref0-reset-usb && echo PREFLIGHT SLEEP && sleep 120); echo PREFLIGHT FAIL; exit 1)"
```

**Comment by scottleibrand** [comment]
You'll want to take the mm-stick stuff out of preflight for a TI stick.  Should looks something like this: https://github.com/scottleibrand/openaps-sh/blob/mmeowlink/setup.sh#L149

To reset the USB stick if needed, I do: `* * * * * killall -g --older-than 10m openaps && sudo reboot` on an Edison.  You could also do `* * * * * killall -g --older-than 10m openaps && sudo oref0-reset-usb` on a Pi.

**Comment by scottleibrand** [comment]
If those didn't do the trick, please reopen or ping us in gitter to troubleshoot further.
