### ISSUE TITLE
Couldn't verify smb_verify_status Error

### ISSUE THREAD

**Issue by aeminkoff** [openaps/oref0#1089]
running oref0 with a 512 pump and pi+ hat -- good radio communication verified - loop will send a temp rate that the pump accepts, then loop consistently stops at "checking pump status (suspend/bolusing) : (NOT VALID JSON: empty) Couldn't verify smb_verify_status
oref0 pump loop failed. 

on nightscout - openaps will go from enabled  to looping and then get kicked out when the loop fails. 
Any suggestions??
[pump-loop.log.log](https://github.com/openaps/oref0/files/2304014/pump-loop.log.log)

**Comment by danamlewis** [comment]
Closing; please reopen if still an issue with 0.7.0-dev
