### ISSUE TITLE
Warning: currenttemp rate != lastTemp rate when going from > 0 COB to 0 COB

### ISSUE THREAD

**Issue by zgohr** [openaps/oref0#1092]
Latest dev branch

With the setting `enableSMB_with_COB`, the loop after COB hits zero I seem to consistently get this error. It resolves itself on the next loop, but it seems the `currenttemp` comparison while SMB is _not_ enabled to the `lastTemp` when SMB _is_ enabled has an issue.

**Comment by scottleibrand** [comment]
I can’t think of any mechanism that would cause that. Those checks are just comparing inputs from the pump, and shouldn’t care what is recommended by determine-basal. Can you capture what the temp_basal.json and pumphistory.json say at the time?

**Comment by zgohr** [comment]
The next time I catch it happening I'll grab those files.
