### ISSUE TITLE
Use of autotune.json file overrides changed settings on pump and in preferences.json

### ISSUE THREAD

**Issue by tim2000s** [openaps/oref0#1093]
When Autotune creates its new profile from the previous run’s Autotune.json file, it ignores changes made in the pump which are propagated in profile.json or in the preferences.json files. 

This means that if you flip from multiple ISFs to one or if you switch insulin curve, Autotune doesn’t pick up the change without manual intervention. It means we should warn people who have changed to Fiasp to check what their Autotune settings are as they are probably tuning to the rapid-acting rather than ultra-rapid curve. 

To fix it we need to identify when the appropriate settings in profile.json don’t match autotune.json and adjust Autotune accordingly.

**Comment by scottleibrand** [comment]
I think the first step toward troubleshooting this is creating a simple process to reproduce it.  Do you know (or can you figure out) what the exact (minimal) steps are required to do so?

**Comment by jpcunningh** [comment]
@tim2000s, that was my first thought, but then I realized that OpenAPS already keeps the pump profile updated with everything except the autotune basals, so #1101 uses the data that's in the pump profile.

**Comment by danamlewis** [comment]
Closing as this appears to be resolved. Please comment in #1251  if this is still an issue (I have a comment there to see if this is resolved fully).
