### ISSUE TITLE
Cannot complete oref0-setup?

### ISSUE THREAD

**Issue by RaRalalala** [openaps/oref0#1105]
Hi there, looking for some help in the script setup, have ran it, completed the questions but I keep getting

Value error: No JSON object could be coded
Could not run nightscout autoconfiguration-device-crud

I'm not technical at all and I've no idea how to get past this. Any help welcome!

**Comment by scottleibrand** [comment]
https://gitter.im/nightscout/intend-to-bolus is the best place to go for setup help.
