### ISSUE TITLE
[Suggestion] Display confidence level alongside suggestions in Autotune report

### ISSUE THREAD

**Issue by MarkMpn** [openaps/oref0#1107]
It would be useful to have some indicator displayed against the output from the Autotune report to show whether a large or small amount of data was used to build the suggestion.

For example, a CR or ISF suggestion could be highlighted as low confidence if there are only one or two periods of deviations classed as CR or ISF, while an hourly basal suggestion could be low confidence if it was inferred by averaging the adjacent hours because that hour was covered by carb absorption etc.

**Comment by scottleibrand** [comment]
Autotune results are incrementally built up over many days or weeks, not based on individual days’ data. How would you propose to indicate confidence in a result built up over a long period of time?

**Comment by MarkMpn** [comment]
If you have the confidence for each element for a single day represented as 0 (low) or 1 (high), this could be averaged when it's run over multiple days, so you might end up with something like (not paying too much attention to the actual numbers):

Day 1
------

| Parameter | Current | Autotune | Confidence |
|------------|----------|------------|-------------|
| ISF             | 40         | 46.790     | 1 |
| CR           | 10.000     | 11.613     | 1 |
| Basal Profile |           |                 | |
| 00:00           | 1.150   | 1.112       | 1 |
| 12:00           | 2.234   | 2.234       | 0 |

Day 2
------

| Parameter | Current | Autotune | Confidence |
|------------|----------|------------|-------------|
| ISF             | 40         | 46.790     | 1 |
| CR           | 10.000     | 11.613     | 1 |
| Basal Profile |           |                 | |
| 00:00           | 1.150   | 1.150       | 0 |
| 12:00           | 2.234   | 2.245       | 1 |

Finish
------

| Parameter | Current | Autotune | Confidence |
|------------|----------|------------|-------------|
| ISF             | 40         | 46.790     | 1 |
| CR           | 10.000     | 11.613     | 1 |
| Basal Profile |           |                 | |
| 00:00           | 1.150   | 1.112       | 0.5 |
| 12:00           | 2.234   | 2.234       | 0.5 |

**Comment by scottleibrand** [comment]
I think you'd need to be more nuanced than that to get something useful, as the end result is a weighted average, where more recent days end up getting weighted more than older ones.  Also not sure how you'd weight your confidence in the ISF and CR numbers.  Also keep in mind that having run autotune over more days should make us more confident in the result, up to some sort of limit.

**Comment by MarkMpn** [comment]
Fair point. My main reason for suggesting it is to highlight periods where the basal rate has been averaged rather than updated based on the deviations. Maybe a simpler version would be a straightforward percentage of days for which each hour’s basal has been calculated vs averaged and not worry about the ISF and CR for now?

**Comment by scottleibrand** [comment]
Devil is in the details on this one.  If you think the result is worth the work, feel free to get started on a branch and we can figure it out.

**Comment by wootmasterslick** [comment]
I suggest using a confidence interval of 95% . This way your get a suggestion +/- a range. Statistically you have a >95% certainty that the true value is within the range. The 95% is scientifically the accepted value of being certain but you can experiment if this results in a too large range. This range is then based in the n of values taken into account and the variation between them. So the result is based on the reproducibility and size of the dataset. I think it would be a good idea to include this to keep people from the "shit in = shit out" problem you can have with autotune.

You can do a little experimenting with the =CONFIDENCE.T function in excel 
![image](https://user-images.githubusercontent.com/41203638/52167530-91c9cd80-271c-11e9-823e-ab492b8baf1f.png)

Here is also more info and the source of the formula
https://www.statisticshowto.datasciencecentral.com/probability-and-statistics/confidence-interval/

**Comment by danamlewis** [comment]
Addressed in https://github.com/openaps/oref0/pull/1133
