### ISSUE TITLE
max basal rates higher than 6.35 fail

### ISSUE THREAD

**Issue by tynbendad** [openaps/oref0#1127]
i searched gitter and apparently this is a longstanding known issue - but i didn't find an existing issue tracker for it?

7,357,357,357,357,357,357,357,358]},"COB":0,"IOB":-0.242,"reason":"COB: 0, Dev: 11, BGI: 0, ISF: 60, CR: 11.35, Target: 90, minPredBG 361, minGuardBG 344, IOBpredBG 367, UAMpredBG 358; Eventual BG 369 >= 90,  insulinReq 4.5; maxBolus 1. Microbolusing 1U. adj. req. rate: 10.9 to maxSafeBasal: 7.05, temp 1.3<7.05U/hr. ","units":1,"duration":30,"rate":7.05}
Temp refreshed: monitor/temp_basal.json: {"duration":8,"rate":1.3,"temp":"absolute"}
rm: cannot remove ‘enact/smb-enacted.json’: No such file or directory
ValueError: byte must be in range(0, 256)
grep: enact/smb-enacted.json: No such file or directory
ValueError: byte must be in range(0, 256)
cp: cannot stat ‘enact/smb-enacted.json’: No such file or directory
enact/smb-enacted.json: cat: enact/smb-enacted.json: No such file or directory
Temp refreshed: monitor/temp_basal.json: {"duration":8,"rate":1.3,"temp":"absolute"}
C

**Comment by tynbendad** [comment]
fyi the version i saw the error on is:
commit fa395b4b5fa02539ccd892a3d8fea62d4e3564e0
Author: Dana Lewis <dmlewis@ua.edu>
Date:   Sun Jun 17 18:13:38 2018 -0700

    0.6.2

**Comment by scottleibrand** [comment]
Have you tried 0.7.0 dev?

**Comment by tynbendad** [comment]
no, not yet, not quite sure when i'll get there... i've had a pi-hat setup that's been sitting idle for months.

**Comment by scottleibrand** [comment]
I believe this is not an issue in 0.7.0, but we can leave this open until someone confims. I don’t think we’ll spend any time fixing this in 0.6.x though.

**Comment by scottleibrand** [comment]
(If you need a workaround, just set your max basal to 6.35 U/hr, and enable SMB if needed.)

**Comment by telabu** [comment]
I'm running 0.7.0 and can confirm that I've had no problems with temp basals up to 12u/hr

**Comment by danamlewis** [comment]
Closing. thanks for the feedback @telabu.
