### ISSUE TITLE
cgm-loop.log: Not an openaps environment, run: openaps init in papertrail logs; similar in normal logs

### ISSUE THREAD

**Issue by mhaeberli** [openaps/oref0#1149]
**Describe the bug**

After installing dev branch on a freshly installed Edison, at least in the nightscout/G5 configuration, repeated error messages are seen in the logs, of the form:

(in papertrail, for example):
`cgm-loop.log: Not an openaps environment, run: openaps init`

Looping seems still to be proceeding normally.

**To Reproduce**
1. Flash a fresh Edison
2. Follow normal installation procedures, but hit ctrl-C at the point where it offers to finish installing 'master' oref0
3. Reboot Edison, set new password as requested
4. Install dev branch per instructions
5. Configure and run dev branch via standard oref0-setup interactive setup

6. Problem can be 'fixed' by adding:
`  "cgm_loop_path": "/root/myopenaps/",` as the first entry in preferences.json

**Expected behavior**
I would expect the above needed cgm_loop_path parameter in preferences.json to be set correctly, or the system otherwise to avoid reporting a (spurious) error.

**Smartphone (please complete the following information):**
Not Applicable, but iPhone 7 with latest production iOS

**Setup Information (please complete the following information):**
* Medtronic 723, v.2.4A firmware
* CGM type (e.g. Dexcom G6 via Dexcom Share and Nightscout)
* Edison/Explorer Board rig)
* oref0 dev latest commit hash - 7f3526e190c9455016c71f664de6e6bd1dce934a

**Additional context**
N/A

**Comment by mhaeberli** [comment]
PS props to @cluckj for guidance !

**Comment by cluckj** [comment]
Found the bug: oref0-setup.sh does not set cgm_loop_path for "G5" cgm type.

**Comment by jaylagorio** [comment]
Fix included in #1217

**Comment by danamlewis** [comment]
Resolved in https://github.com/openaps/oref0/pull/1211 as noted - thanks all.
