### ISSUE TITLE
openaps-install on dev does not work

### ISSUE THREAD

**Issue by cascer1** [openaps/oref0#1153]
**Describe the bug**
the openaps-install.sh script on the dev branch does not currently work. I've identified two issues, which might be related.

1. during setup, an error scrolls by about using the wrong node.js package. [schreenshot](https://i.eliens.co/1543175617553.png)
2. A while later, after the install script completes, you cannot run `npm run global-install` because npm is not installed.

**To Reproduce**
1. flash raspbian on your pi (I'm using the 2018-11-13 build)
2. run `curl -s https://raw.githubusercontent.com/openaps/oref0/dev/bin/openaps-install.sh > /tmp/openaps-install.sh && bash /tmp/openaps-install.sh dev`
3. observe the error

**Expected behavior**
`openaps-install.sh` should install all the required dependencies and then oref0 itself, after which the `oref0` command should be available.

**Comment by danamlewis** [comment]
Closing; resolved
