### ISSUE TITLE
determine-basal report not working if auto-sens.json report not available

### ISSUE THREAD

**Issue by johnmales** [openaps/oref0#117]
I have encountered an issue where inadequate blood glucose data to produce an auto-sens.json file is stopping determine-basal reporting from producing a report, and therefore stopping looping. 

It would appear to be more logical to continue to have determine-basal produce a report if auto-sens.json is missing or has no data, rather than stopping the report from proceeding at all.

**Comment by scottleibrand** [comment]
@bewest Can you fix this easily, or do we need to roll back your hard-failure changes so it doesn't break people's working loops?

**Comment by scottleibrand** [comment]
@johnmales can you test #120 (by checking out the fix-autosens-data-warning branch) and confirm this fixes your issue?

**Comment by scottleibrand** [comment]
Per https://github.com/openaps/oref0/pull/120#issuecomment-220828541 this should now be fixed.
