### ISSUE TITLE
Acronyms overused thought documentation

### ISSUE THREAD

**Issue by joeyede** [openaps/oref0#1173]
When writing technical documentation it is considered a best practice to avoid acronyms.  The Open Artificial Pancreas System (OpenAPS) documentation is littered with acronyms making it hard to understand especially for people who are just getting started who conversely are the ones who need the documentation the most.  Ideally all acronyms should be expanded.  At a minimum any term used on a page should be fully defined the first time it is used (like I did for OpenAPS above) 
Note: I would happy to help with this but honestly I am not always sure I know what they all mean.  
Recommended first step: Define a glossary

**Comment by danamlewis** [comment]
Thanks, @joeyede - would you take a look at the existing glossary, and maybe make a PR with some recommendations where to link to the glossary? https://openaps.readthedocs.io/en/latest/docs/Resources/glossary.html

Or, if you can identify the acronyms that are not defined where you saw them, we can define & add them.

**Comment by joeyede** [comment]
Happy to do both once we get back from our first vacation while looping.
The existing glossary is good but I guess not discoverable enough given I
looked and missed it...

**Comment by danamlewis** [comment]
Lots of acronyms removed and addressed after this posting, and subsequently since then. Closing, but please do open PRs to the documentation directly with any edits and suggestions and acronym clarification if needed!
