### ISSUE TITLE
Unexpected COB

### ISSUE THREAD

**Issue by dogakurtulus** [openaps/oref0#1183]
Unexpected COB

As I observed, a new amount of COB is added to the current COB that is active at night. But I don't do this addittion from the pump or the Nightscout careportal.  It is doing it itself. As a result, when the system is included in the calculation of active COB, it need to send more unnecessary insulin, which causes us to live low.
As you can see in the two photos below, the same day at 23:58 active COB is 5 and then  00:02 active COB will be 10. I don't do this addition

![cob 5](https://user-images.githubusercontent.com/39736481/51091424-92191d80-179b-11e9-8852-c673163e3e09.jpg)
![cob 10](https://user-images.githubusercontent.com/39736481/51091428-99402b80-179b-11e9-8e78-bbc7111f5c47.jpg)

l am waiting for your help on the subject

**Comment by Kdisimone** [comment]
https://www.facebook.com/groups/TheLoopedGroup/permalink/2010010709215585/

**Comment by dogakurtulus** [comment]
> https://www.facebook.com/groups/TheLoopedGroup/permalink/2010010709215585/

Thanks alot Kdisimone

**Comment by dogakurtulus** [comment]
l did try to change my CR times to solve that problem, l did dinner time CR and midnight CR is the same but didn't change anything. When the clock comes to 00:01, if COB still not decay or if the new is over, COB is increased again dramatically. After 00:01 my CR is 19 in the pump and also NS profile but at the NS Openaps pill shown is 16,21 as autotune CR value, so the system again calculate active COB as per autotune CR value

How can l fix that problem pls assist me.

![cr](https://user-images.githubusercontent.com/39736481/51307532-016b6780-1a51-11e9-96fc-25d63ab565ef.JPG)

![autotune cr](https://user-images.githubusercontent.com/39736481/51307537-04feee80-1a51-11e9-9ed9-5f2cdfdba2b1.JPG)

**Comment by scottleibrand** [comment]
Sorry for the slow response: we've been dealing with the fallout of Dana falling off a the side of a mountain in New Zealand.

Can you paste the full pump-loop.log output from one run just before midnight, and one run just after?  And the full cat-autotune output?

Thanks,
Scott

**Comment by danamlewis** [comment]
Closing due to logs/lack of activity in this thread + so we can keep the discussion over at the related issue: https://github.com/openaps/oref0/issues/977 (please target additional comments or logs with this issue there)
