### ISSUE TITLE
Autosens should decay older sensitivity quicker as it discards intervals due to COB

### ISSUE THREAD

**Issue by tynbendad** [openaps/oref0#1192]
**Describe the bug**

Autosens was holding sensitivity at ~0.6 even though it didn't really have any data for several hours due to COB... seems that it should decay the old sensitivity quicker when discarding data due to COB.

Starting oref0-autosens-loop at Sat Feb 2 19:48:02 MST 2019:
Calculating sensitivity using 8h of non-exluded data
Setting lastSiteChange to 2019-02-02T07:10:26.000Z using timestamp 2019-02-02T00:10:26-07:003h----------==4h====------=--5h=---=-------6h=-----=++----7h-----=++----8h=-=+--------9h---++-----10h=------------11h------------12h=--+---------13h-----+++++++14h=+++u(xxxxxxxxx15hxxxxxxxxxxxx16h=xxxxxxxxxxxx17hxxxxxxxxxxxx18h=xxxxxxxxxxxx19hxxxxxxxx ns negative (>50% = sensitivity)
RMS deviation: 4.96
Insulin sensitivity detected: ISF adjusted from 23.297 to 38
Calculating sensitivity using all non-exluded data (up to 24h)
Setting lastSiteChange to 2019-02-02T07:10:26.000Z using timestamp 2019-02-02T00:10:26-07:003h----------==4h====------=--5h=---=-------6h=-----=++----7h-----=++----8h=-=+--------9h---++-----10h=------------11h------------12h=--+---------13h-----+++++++14h=+++u(xxxxxxxxx15hxxxxxxxxxxxx16h=xxxxxxxxxxxx17hxxxxxxxxxxxx18h=xxxxxxxxxxxx19hxxxxxxxx ns negative (>50% = sensitivity)
RMS deviation: 4.17
Insulin sensitivity detected: ISF adjusted from 23.297 to 39
Using 24h autosens ratio of 0.59 (ISF 39)
Autosens refreshed: {"ratio":0.59}
Completed oref0-autons-loop at Sat Feb 2 19:48:15 MST 2019

**Expected behavior**
Sensitivity should have reverted to 1.0 quicker, instead it held steady at 0.6 through the whole time it was generating the x's.

**Setup Information (please complete the following information):**
* Pump type (e.g. Medtronic 722, v. 2.4A firmware)
723
* CGM type (e.g. Dexcom G4 via xDrip+)
dexcom g6
* Rig type (e.g. Edison/Explorer Board rig)
edison/explorer
* oref0 version (e.g. oref0 0.6.2 master, or 0.7.0-dev)
oref 0.6.2
**Additional context**

**Comment by tynbendad** [comment]
eventually i had to disable autosens in cron and manually overwrite sensitivity to 1.0 to get the stubborn high down.

**Comment by scottleibrand** [comment]
An easier workaround is to set a temp target to override autosens, if you have the appropriate preferences enabled. 

We do “pad” neutral deviations, but only one every 2h I believe. You could try increasing their frequency to one per hour. Alternatively, we’ve been considering porting the AndroidAPS weighted average sensitivity calculation method back over to OpenAPS, which would probably help.

**Comment by tynbendad** [comment]
>An easier workaround is to set a temp target to override autosens, if you have the appropriate preferences enabled.

i considered doing a temp target but wasn't sure if that would help - the docs just say this about "low_temptarget_lowers_sensitivity": Defaults to false. When set to true, can lower sensitivity for temptargets <= 99.

That sounds like it wouldn't have helped in this case, since sensitivity was 0.6 and needed to be higher, 1.0 (autosens had detected him sleeping in on the weekend which lowered sensitivity, and then eating all day after that caused the discards)... 

Or does "lower sensitivity" mean a higher number?  If so I can clarify in the docs and set that to true on our rigs & try it next time. Would it have been an immediate change to 1.0, or gradual?

I didn't want to change the safety multipliers to 1 since they also affect autotune. 

I considered rewind_resets_autosens but for me accessing the rig is easier than asking my kid for access to the pump (he doesn't even like me mentioning anything diabetes ;). 

>We do “pad” neutral deviations, but only one every 2h I believe. You could try increasing their frequency to one per hour. 

i guess this is somewhere in oref0/lib/determine-basal/autosens.js, but i don't see it, can you point me to it?

>we’ve been considering porting the AndroidAPS weighted average sensitivity calculation method back over to OpenAPS, which would probably help.

sounds like that would be great, provided it decays quicker over the excluded periods,..

**Comment by tynbendad** [comment]
oh, i see the math for low_temptarget_lowers_sensitivity (and the high temptarget one also flows to the same code), in oref0/lib/determine-basal/determine-basal.js:

`
    } else {
        var halfBasalTarget = 160; // when temptarget is 160 mg/dL, run 50% basal (120 = 75%; 140 = 60%)
        // 80 mg/dL with low_temptarget_lowers_sensitivity would give 1.5x basal, but is limited to autosens_max (1.2x by default)
    }
    if ( high_temptarget_raises_sensitivity && profile.temptargetSet && target_bg > normalTarget + 10
        || profile.low_temptarget_lowers_sensitivity && profile.temptargetSet && target_bg < normalTarget ) {
        // w/ target 100, temp target 110 = .89, 120 = 0.8, 140 = 0.67, 160 = .57, and 200 = .44
        // e.g.: Sensitivity ratio set to 0.8 based on temp target of 120; Adjusting basal from 1.65 to 1.35; ISF from 58.9 to 73.6
        //sensitivityRatio = 2/(2+(target_bg-normalTarget)/40);
        var c = halfBasalTarget - normalTarget;
        sensitivityRatio = c/(c+target_bg-normalTarget);
        // limit sensitivityRatio to profile.autosens_max (1.2x by default)
        sensitivityRatio = Math.min(sensitivityRatio, profile.autosens_max);
        sensitivityRatio = round(sensitivityRatio,2);
        process.stderr.write("Sensitivity ratio set to "+sensitivityRatio+" based on temp target of "+target_bg+"; ");
` 

our normal low target on pump is 95 (high is 140 if that matters here). so if i had set a temp target of 90, then:
c = 160 - 95 = 65;
sensitivityRatio = 65/(65+90-95) = 65 / 60 = 1.08;

that is indeed what i wanted, if i've done the math right... guess the docs confused me and i'll edit them to clarify if you agree w/my math.

**Comment by scottleibrand** [comment]
The high and low targets for autosens are relative to 100, not to your normal target. So setting a 90 would be slightly more aggressive than that. But you could set a 95 or 99 and it’d do something closer to 1.01, or 101 to get something like .99 sensitivityRatio. (Do the math from a 100 baseline to see exactly what it’d be.) It’s also worth noting that (IIRC) a target of exactly 100 does *not* reset sensitivityRatio to 1.

**Comment by tynbendad** [comment]
https://github.com/openaps/docs/pull/1413 for documentation... please review as it can be very confusing with the raising/lowering/inversions, also i may have done the math wrong as some of the comments in the .js were slightly different than my calcs.

in any case, as far as this issue goes i would still like to see if i can adjust autosens to decay more rapidly, as i like/trust autopilot a lot more than a human such as myself doing temp target setting.

**Comment by danamlewis** [comment]
Closing, as addressed here & in the docs PR.

**Comment by tynbendad** [comment]
@danamlewis has autosens been addressed to fix the original issue, or is there no hope for no-carb-entry with autosens?

**Comment by scottleibrand** [comment]
The original issue was about periods with COB. If there is still an issue with no-carb-entry meals that wouldn’t surprise me, but we should open a new issue and clearly describe that problem so we can troubleshoot it.

**Comment by tynbendad** [comment]
COB, or COB without a carb entry, I'm not sure if there's a difference to autosens. Had either been fixed?

**Comment by scottleibrand** [comment]
COB without a carb entry isn't possible. If you enter carbs, you'll get a notation in the autosens-loop.log of the carb entry, with parentheses around e(x)cluded deviations for the duration of the COB, up to the first negative deviation with COB=0, like this:

8h=--------30g(xxxx19hxxx72gxxxxxxxxx20h=xxxxxxxxxxxx21hxxxxx)-++--++22h=-----+------23h-------+++++0h=+-----------1h-----+--+---2h=---+----+---3h--+---++++++4h=++---------+5h-------+++++6h=+--------+-+7h-+---------+8h=++++++--+--+9h------+

If you rely on UAM, it will mark exclusions with u(xxxx), but that isn't quite as reliable.

As to the original request for faster-decaying sensitivity, if the temp target workaround isn't sufficient, you could port the AndroidAPS weighted average sensitivity calculation method back over to OpenAPS...

**Comment by tynbendad** [comment]
Ok, thanks for the explanation. Longer term I plan on moving to aaps anyway, so will keep using temp target sensitivity' instead of autosens for now.
