### ISSUE TITLE
640 uploader users may have an issue due to weird format timestamp

### ISSUE THREAD

**Issue by danamlewis** [openaps/oref0#1207]
2 users have reported having issues looping, due to their BG data constantly being set in the future, or similar issues. The common denominator was them both using a 640 pump to capture CGM data & upload it with the 600-series uploader. 

See issue in the 600-uploader repository to track this issue as it relates to using a 640 to upload BG data to NS & use OpenAPS with it. https://github.com/pazaan/600SeriesAndroidUploader/issues/241

**Comment by sulkaharo** [comment]
This sounds like a time zone issue?

**Comment by tuzoenduro** [comment]
datestring & timezone... The current 0.6.1 version of the 600SeriesAndroidUploader uses CET and openaps cannot interpret it correctly.

The new 0.7.0 version will revert to the same datestring format as openAPS and this corrects the issue. I'm currently running a 0.7.0 WIP and this is corrected...

**Comment by danamlewis** [comment]
Closing, as corrected in 0.7.0.
