### ISSUE TITLE
Carb decay extremelly slow

### ISSUE THREAD

**Issue by cascer1** [openaps/oref0#1209]
**Describe the bug**
The carb decay is exceptionally slow on my rig. I have tried configuring just one CR for the entire day (usually I have multiple), and avoiding using the bolus wizard for a while.

**To Reproduce**
1. Enter carbs
2. Observe exceptionally slow carb decay

**Expected behavior**
Carbs should decay according to the currently active carb ratio and BG changes

**Setup Information (please complete the following information):**
* Pump type: European Medtronic 554 2.6A
* CGM type: Dexcom G5 via xDrip+
* Rig type: Pi zero with explorer HAT
* oref0 version: 0.7.0-dev

**Logs**
* [pump-loop.log](https://gist.github.com/cascer1/46b1aae354b6db6c2c941a0b75a821d4) (Manually bolussed 11 units at 12:13, and then entered carbs in xDrip)

**Comment by scottleibrand** [comment]
Did you do a before and after comparison? What ratios and times did you use that didn’t / did have the problem? Do you have any data from the pump-loop.log showing which ratio it thought it was using?

**Comment by cascer1** [comment]
I actually don't think I've quite identified the source of the issue. Will test some more and then update this issue accordingly (including logs). Right now I think the only situation in which I don't get this issue is when I do not enter carbs in the bolus wizard on my pump *and* only have one carb ratio configured.

**Comment by cascer1** [comment]
@scottleibrand I have updated the issue with a more accurate description of the problem (unfortunately changes in bolus wizard usage or settings make no difference like I originally expected). I have also uploaded my [pump-loop.log](https://gist.github.com/cascer1/46b1aae354b6db6c2c941a0b75a821d4).

This log contains the information for my lunch, for which I bolussed 11 units at 12:13 and entered 55 carbs (using xDrip) at 12:14

**Comment by cascer1** [comment]
I'd like to add that I do not have a modified `min_5m_carbimpact` setting currently.

**Comment by scottleibrand** [comment]
Sorry for the delay in looking this over in more detail.

I don't see any slow absorption in the linked pump-loop.log.  It appears that absorption proceeded apace during the actual carb absorption, as indicated by high Carb Impact (often limited prospective to the 30 g/h maximum), and by the time CI dropped below min_5m_carbimpact, 85% of carbs had been absorbed and COB was down to 11g.  At that point, the UAMpredBGs were being weighted at 85%, vs. only 15% for COBpredBGs, so the remaining COB decay had very little impact on dosing decisions.

How have things been looking over the last couple months?

**Comment by cascer1** [comment]
Thanks for getting back to me. 

Unfortunately I'm still experiencing the same issue where a 40 gram carb entry will take 3 or sometimes even 4 hours to be fully absorbed. I'm up-to date with dev.

**Comment by cascer1** [comment]
I updated to dev on April 17th and have been running autotune from that branch since then. Just to be sure I did clear my old autotune data on the day that I updated. Autotune seems to recommend values very similar to what my endo and I figured out together.

**Comment by scottleibrand** [comment]
Ok. When you have 40g carbs that take 3h+ to fully absorb, how long do they take to decay down to <10g of COB? That’s what matters most for insulin dosing.

**Comment by cascer1** [comment]
I'll use my last lunch as example: 
at 12:16 I entered 43 carbs
at 13:59 12 cob remained

That works out to 29 carbs absorbed in about 1:40 -- or about 17 per hour if my math is correct.

**Comment by danamlewis** [comment]
@cascer1 is this still a point of frustration with latest 0.7.0?

**Comment by cascer1** [comment]
@danamlewis I have since switched to AndroidAPS so I cannot test this on 0.7.0 (I don't have a compatible pump anymore).

**Comment by danamlewis** [comment]
Ok, thanks for the update. Closing due to age/inability to test; if anyone stumbles on this one in the future, please open a new issue with pertinent details regarding tests with 0.7.0 or the latest dev version at the time. Thanks!
