### ISSUE TITLE
oref0-setup install fails on latest dev with errors running jq updating nightscout info

### ISSUE THREAD

**Issue by mhaeberli** [openaps/oref0#1219]
**Describe the bug**

**To Reproduce**
0. this happens on latest dev, for example hash: a2f37135dbc6492c750c0719ec0e6bae71648f07
1. using live dev branch from public github oref0
2. connect to Edison rig; service cron stop; killall -g oref0-pump-loop
3. run oref0-setup in interactive mode; re-enter all parameters.  We are using nightscout with a G5, shared secret authentication
4. fails with the below error.
5. this was NOT happening on January 6 2019 dev branch, hash 53e49fa4f70c3853d22f6156cbadc504f9f92330

---
**Expected behavior**
oref0-setup to run happily to completion

**Screenshots**
N/A

**Smartphone (please complete the following information):**
iPhone 7 but most likely not relevant

**Setup Information (please complete the following information):**
* Pump type Medtronic 723, v. 2.4A firmware
* CGM type Dexcom G6 via Dexcom Share
* Rig type Edison/Explorer Board
* oref0 version 0.7.0-dev

**Additional context**

**Comment by mhaeberli** [comment]
ran regressions by doing revert backwards in time from dev branch head (per @scottleibrand suggestion).  had to revert back to 5cb8f9227bf175da183794d70027adc372e46827 , then it seemed to work.  I would offer to run regression test on any fix offered, and also going forward, to be in the release regression loop for Edison Explorer...

**Comment by cluckj** [comment]
I think the issue is a missing `|` at the end of this line: https://github.com/openaps/oref0/blob/a2f37135dbc6492c750c0719ec0e6bae71648f07/bin/nightscout.sh#L340

**Comment by jpcunningh** [comment]
Good catch, @cluckj ! I have PR #1221 waiting for @scottleibrand.

**Comment by scottleibrand** [comment]
Merged. @mhaeberli can you please confirm this fixes your issue, and close if so?

**Comment by mhaeberli** [comment]
confirmed! regression succeeded! [memo to self - remember to check out dev if regressing dev...] ; master install failed on Edison / Explorer not finding yargs - but that's another story and for myself I see no need to put effort into that.
