### ISSUE TITLE
oref0-meal fails when order of arguments is wrong and/or carbhistory.json is empty

### ISSUE THREAD

**Issue by Spazholio** [openaps/oref0#122]
After upgrading the `advanced-meal-assist` branch to the latest and greatest, my `monitor/meal.json` is failing.  The line in my `meal.ini` file was `fields = pumphistory profile clock carbhistory glucose basal_profile` and that worked previously.  My `settings/carbhistory.json` file is empty because reasons.  Running the command manually, but with my previous order like so: `oref0-meal monitor/pumphistory.json settings/profile.json monitor/clock.json settings/carbhistory.json monitor/glucose.json settings/basal_profile.json` gives me `input data: [SyntaxError: Unexpected end of input]`.  However, if I make the order of arguments match the help prompt, then the report runs fine, both manually and from within my loop.

**Comment by scottleibrand** [comment]
https://github.com/openaps/oref0/commit/f217c66685b1c8b66cff87af337e1ef65e2b1996 fixes this for me.  Can you confirm, or have you already adjusted your config?

**Comment by scottleibrand** [comment]
Closing.  Please reopen if this doesn't fix.
