### ISSUE TITLE
Virtual pump for open-looping and interfacing with simulator (in silico testing)

### ISSUE THREAD

**Issue by lsandini** [openaps/oref0#1220]
Adding a virtual pump mode would give the possibility to use openaps for open-looping with any pump, without the necessity for pump comms. 

The virtual pump should be serving the same history data as a standard Paradigm pump, and the treatment decisions should suggested/enacted. A virtual pump would also be ideal for in silico testing of the oref0/oref1 algorithms with a physiological simulator, where the simulator would serve BG and CGM values, and the virtual pump would delivers insulin to the simulated patient.

"If I could do it, I would". But with no or very few coding skills, I hope this idea gathers interest.

**Comment by danamlewis** [comment]
I think the best bet is using the simple simulator code for this (https://github.com/openaps/oref0/compare/dev...simple-simulator) within the community for retrospective and individual prospective testing. (Also, I know there's a pending publication reviewing the use of oref(0/1) in silico using the Padova simulator, so this is also being addressed in the research world, too.)  For those who want a real-time virtual pump, I recommend trying AndroidAPS with a virtual pump.
