### ISSUE TITLE
COB wrong in loop and NS pill, after updating dev branch today

### ISSUE THREAD

**Issue by straykatz** [openaps/oref0#1226]
**Describe the bug**
1) After I updated dev branch today, the COB are wrongly used as zero, even though there were 60 g entered in the last 75 min.  

2) In addition, the fakemeter BG is re-uploaded to Nightscout as meter BG,

**To Reproduce**
Steps to reproduce the behavior: well - here is what I have: 
I am running a G6-Lookup setup, and after that was working today, I updated dev branch, which is when the issues started.

**Expected behavior**
COB are pulled from NS like before. Right now they are pulled, but ignored.

**Screenshots**
<img width="1274" alt="Screen Shot 2019-03-09 at 9 23 52 PM" src="https://user-images.githubusercontent.com/45725845/54081175-365ba400-42b5-11e9-8e11-76b6856b7de4.png">
<img width="1436" alt="Screen Shot 2019-03-09 at 9 17 00 PM" src="https://user-images.githubusercontent.com/45725845/54081179-3b205800-42b5-11e9-956f-5bd6e5a406ba.png">
<img width="1274" alt="Screen Shot 2019-03-09 at 9 23 52 PM" src="https://user-images.githubusercontent.com/45725845/54081183-3fe50c00-42b5-11e9-9904-dcaef083b078.png">
 
and a fresh NS shot - unchanged: 0 COB at 21:51

<img width="1440" alt="Screen Shot 2019-03-09 at 9 51 48 PM" src="https://user-images.githubusercontent.com/45725845/54081218-c4d02580-42b5-11e9-9603-6211a1d1d425.png">

**Smartphone (please complete the following information):**
N/A

**Setup Information (please complete the following information):**
* Pump type (Medtronic 522, v. 2.4A firmware
* CGM type (e.g. Dexcom G4 via xDrip+): Dexcom G6
* Rig type (Edison/Explorer Board rig)
* oref0 version (e.g. oref0 0.7.0-dev)
* Lookout-dev (latest - 3/9/2019)
**Additional context**

After setting up the rig to run the Dexcom G6 sensor with Lookout today, I just updated this rig to the newest oref0 - 0.7.0-dev branch - 6 new commits. It was working fine before the update.  The rig had just started running Lookout - I did not notice the 0 COB issue, and also, the fakemeter values being uploaded to NS as meter glucose BEFORE the oref0 update.

**Comment by straykatz** [comment]
Here's the other rig, once it had caught up ... it sees the COB. 

Main difference between the two is today's update of dev branch.
<img width="1440" alt="Screen Shot 2019-03-09 at 10 31 16 PM" src="https://user-images.githubusercontent.com/45725845/54081555-52624400-42bb-11e9-90cc-f594512d712e.png">

**Comment by scottleibrand** [comment]
there is info on why COB is zero a little further back in the pump-loop.log.
There are various error conditions that can cause that: we default to zero if there’s any anomaly, to avoid dosing off an erroneously high COB value.
