### ISSUE TITLE
1 minute glucose data not being processed by autotune

### ISSUE THREAD

**Issue by rob-andy** [openaps/oref0#1235]
**Describe the bug**
Autotune does not support glucose/sgv values that are recorded every minute.  If values occur more frequently than every 2 minutes, the current logic in categorizeBGDatums (lib/autotune-prep/categorize.js) tries to average each successive value with the previous value and does not split the data into buckets correctly.

**Expected behavior**
If values occur more frequently than the 2 minute deadband, all values that fall within that deadband should be averaged.  The start of the deadband should be the time of the first value placed into the bucket, not a continually moving window.

**Setup Information:**
* Libre sensor, using miaomiao reader
* Glimp on Android to connect to miaomiao
* oref0 latest dev

**Additional context**
Sample code of possible solution attached. I'd like to see clarification around what should the minimum bucket time size be and when should values be ignored (currently logic ignores two successive <39 values, but why?)  Additionally, if values are recorded every minute, this will be 1440 values a day, which is more then the default retrieval limit of 1000 used by ns-get.

[categorize.js_diff.txt](https://github.com/openaps/oref0/files/3002715/categorize.js_diff.txt)

**Comment by scottleibrand** [comment]
Unfortunately, oref0 (and autotune) were never designed or tested for the every-minute-CGM-data scenario.  We only had access to and designed/tested for multiple CGM receivers transmitting data every 5 minutes.  The code we put in to accommodate that could be extended to get the expected behavior you want, but it's going to require some development, probably by someone with access to every-minute Libre data.

In the meantime, do you have the ability to get your Libre reader to upload data to NS aggregated into every-5-minute data points instead of every-minute?

**Comment by rob-andy** [comment]
Well at this point in time, the only issue is the current bug I've highlighted.

I've created a branch with my proposed changes.  https://github.com/rob-andy/oref0/tree/glucose-categorize-improvements

Can I submit a pull request? Before I do, I'd still like to clarify the current two minute window? And the removal of two consecutive < 39 readings?

**Comment by sulkaharo** [comment]
Related: Nightscout codebase also has logic in place that assumes 5 minute intervals on CGM data. The main view does seem to work with 1 minute intervals, but the reporting completely breaks when 1 minute CGM interval is used.

**Comment by rob-andy** [comment]
That was next on my todo list.  Look into why nightscout report totals don't add up :+1:

**Comment by tim2000s** [comment]
The two consecutive <39 readings relate to Dexcom error representation.

**Comment by sulkaharo** [comment]
@rob-andy Created an issue https://github.com/nightscout/cgm-remote-monitor/issues/4496

Re: readings under 39 - we really need better way to communicate error data than magic BG values. Also, now the DIY CGM implementations seem to produce data that shows BG values that are lower than the officially supported ranges, which probably means the data is in some cases highly inaccurate. And we now have systems where the lower and upper bound for the range doesn't match the original Dexcom range, but we don't have a mechanism to actually know supported range.

**Comment by danamlewis** [comment]
Has anyone taken a look at this or related issues recently?
