### ISSUE TITLE
oref0 thinks Meal Assist is enabled despite there being no meal.json report

### ISSUE THREAD

**Issue by live4sw** [openaps/oref0#124]
Received this message when running loop:
`get-profile://text/shell/settings/profile.json Could not parse carbratio_data. Feature Meal Assist enabled but cannot find required carb_ratios.` I don't have a meal.json report, since I haven't done any Meal Assist setup yet.

Removing `remainder = []` from my settings/profile.json and enact/suggested.json report configurations fixed this. Perhaps it was feeding [] to oref0 when it was expecting a meal.json?

For reference:

Profile.json report output of: `{"error":{"errno":34,"code":"ENOENT","path":"[]","syscall":"open"},"msg":"Could not parse carbratio_data. Feature Meal Assist enabled but cannot find required carb_ratios.","file":"[]"}`

Profile.json report configuration of: `[report "settings/profile.json"]
use = shell
bg_targets = settings/bg_targets.json
settings = settings/settings.json
basal_profile = settings/basal_profile.json
reporter = text
json_default = True
max_iob = max_iob.json
device = get-profile
remainder = []
insulin_sensitivities = settings/insulin_sensitivities.json`

gather-profile alias of: `gather-profile = report invoke settings/settings.json settings/bg_targets.json settings/insulin_sensitivities.json settings/basal_profile.json settings/profile.json`

**Comment by scottleibrand** [comment]
Is this still an issue with AMA in oref0 dev?  If so, please reopen.
