### ISSUE TITLE
Two instances of the same rig, having different autotune values.

### ISSUE THREAD

**Issue by tzachi-dar** [openaps/oref0#1249]
It seems that two rigs that have the exact same myopenaps/preferences.json have very different autotune values (=> behaviors).

Here is autotune for both of them:
{
  "max_iob": 4,
  "max_daily_safety_multiplier": 3,
  "current_basal_safety_multiplier": 4,
  "autosens_max": 1.01,
  "autosens_min": 0.99,
  "rewind_resets_autosens": true,
  "adv_target_adjustments": false,
  "exercise_mode": false,
  "wide_bg_target_range": false,
  "sensitivity_raises_target": true,
  "unsuspend_if_no_temp": false,
  "enableSMB_with_COB": false,
  "enableSMB_with_temptarget": false,
  "enableUAM": false,
  "curve": "rapid-acting",
  "offline_hotspot": false,
  "nightscout_host": "https://snir-dev.herokuapp.com",
  "cgm": "xdrip",
  "enable": " autotune ",
  "ttyport": "/dev/spidev0.1",
  "myopenaps_path": "/root/myopenaps",
  "pump_serial": "523442",
  "radio_locale": "US",
  "xdrip_path": "/root/.xDripAPS",
  "bt_offline": "true"
}

Here is the result of the files myopenaps/autotune/profile.json
For one of them:
{
   "A52_risk_enable": false,
   "SMBInterval": 3,
   "adv_target_adjustments": false,
   "allowSMB_with_high_temptarget": false,
   "autosens_max": 1.01,
   "autosens_min": 0.99,
   "autotune_isf_adjustmentFraction": 1,
   "basalprofile": [
      {
         "i": 0,
         "minutes": 0,
         "rate": 0.694,
         "start": "00:00:00",
         "untuned": 2
      },
      {
         "i": 1,
         "minutes": 60,
         "rate": 0.707,
         "start": "01:00:00",
         "untuned": 1
      },
      {
         "i": 2,
         "minutes": 120,
         "rate": 0.48,
         "start": "02:00:00",
         "untuned": 3
      },
      {
         "i": 3,
         "minutes": 180,
         "rate": 0.48,
         "start": "03:00:00",
         "untuned": 2
      },
      {
         "i": 4,
         "minutes": 240,
         "rate": 0.454,
         "start": "04:00:00",
         "untuned": 1
      },
      {
         "i": 5,
         "minutes": 300,
         "rate": 0.451,
         "start": "05:00:00",
         "untuned": 1
      },
      {
         "i": 6,
         "minutes": 360,
         "rate": 0.404,
         "start": "06:00:00",
         "untuned": 2
      },
      {
         "i": 7,
         "minutes": 420,
         "rate": 0.404,
         "start": "07:00:00",
         "untuned": 2
      },
      {
         "i": 8,
         "minutes": 480,
         "rate": 0.404,
         "start": "08:00:00",
         "untuned": 2
      },
      {
         "i": 9,
         "minutes": 540,
         "rate": 0.4,
         "start": "09:00:00",
         "untuned": 1
      },
      {
         "i": 10,
         "minutes": 600,
         "rate": 0.359,
         "start": "10:00:00",
         "untuned": 1
      },
      {
         "i": 11,
         "minutes": 660,
         "rate": 0.354,
         "start": "11:00:00",
         "untuned": 2
      },
      {
         "i": 12,
         "minutes": 720,
         "rate": 0.354,
         "start": "12:00:00",
         "untuned": 2
      },
      {
         "i": 13,
         "minutes": 780,
         "rate": 0.354,
         "start": "13:00:00",
         "untuned": 2
      },
      {
         "i": 14,
         "minutes": 840,
         "rate": 0.364,
         "start": "14:00:00",
         "untuned": 2
      },
      {
         "i": 15,
         "minutes": 900,
         "rate": 0.482,
         "start": "15:00:00",
         "untuned": 3
      },
      {
         "i": 16,
         "minutes": 960,
         "rate": 0.487,
         "start": "16:00:00",
         "untuned": 2
      },
      {
         "i": 17,
         "minutes": 1020,
         "rate": 0.505,
         "start": "17:00:00",
         "untuned": 2
      },
      {
         "i": 18,
         "minutes": 1080,
         "rate": 0.505,
         "start": "18:00:00",
         "untuned": 2
      },
      {
         "i": 19,
         "minutes": 1140,
         "rate": 0.505,
         "start": "19:00:00",
         "untuned": 2
      },
      {
         "i": 20,
         "minutes": 1200,
         "rate": 0.607,
         "start": "20:00:00",
         "untuned": 3
      },
      {
         "i": 21,
         "minutes": 1260,
         "rate": 0.736,
         "start": "21:00:00",
         "untuned": 3
      },
      {
         "i": 22,
         "minutes": 1320,
         "rate": 0.736,
         "start": "22:00:00",
         "untuned": 3
      },
      {
         "i": 23,
         "minutes": 1380,
         "rate": 0.697,
         "start": "23:00:00",
         "untuned": 2
      }
   ],
   "bg_targets": {
      "first": 1,
      "targets": [
         {
            "high": 110,
            "i": 0,
            "low": 110,
            "max_bg": 110,
            "min_bg": 110,
            "offset": 0,
            "start": "00:00:00",
            "x": 0
         }
      ],
      "units": "mg/dL",
      "user_preferred_units": "mg/dL"
   },
   "bolus_increment": 0.1,
   "bolussnooze_dia_divisor": 2,
   "carb_ratio": 14.96,
   "carb_ratios": {
      "first": 1,
      "schedule": [
         {
            "i": 0,
            "offset": 0,
            "ratio": 15,
            "start": "00:00:00",
            "x": 0
         },
         {
            "i": 12,
            "offset": 360,
            "ratio": 8.5,
            "start": "06:00:00",
            "x": 1
         },
         {
            "i": 18,
            "offset": 540,
            "ratio": 9.2,
            "start": "09:00:00",
            "x": 2
         },
         {
            "i": 28,
            "offset": 840,
            "ratio": 13,
            "start": "14:00:00",
            "x": 3
         },
         {
            "i": 37,
            "offset": 1110,
            "ratio": 13,
            "start": "18:30:00",
            "x": 4
         }
      ],
      "units": "grams"
   },
   "carbsReqThreshold": 1,
   "csf": 5.94,
   "current_basal": 0.45,
   "current_basal_safety_multiplier": 4,
   "curve": "rapid-acting",
   "dia": 4,
   "enableSMB_after_carbs": false,
   "enableSMB_always": false,
   "enableSMB_with_COB": false,
   "enableSMB_with_temptarget": false,
   "enableUAM": false,
   "exercise_mode": false,
   "half_basal_exercise_target": 160,
   "high_temptarget_raises_sensitivity": false,
   "insulinPeakTime": 75,
   "isfProfile": {
      "first": 1,
      "sensitivities": [
         {
            "i": 0,
            "offset": 0,
            "sensitivity": 90.463,
            "start": "00:00:00",
            "x": 0
         },
         {
            "endOffset": 300,
            "i": 2,
            "offset": 60,
            "sensitivity": 120,
            "start": "01:00:00",
            "x": 1
         },
         {
            "i": 10,
            "offset": 300,
            "sensitivity": 80,
            "start": "05:00:00",
            "x": 2
         }
      ],
      "units": "mg/dL",
      "user_preferred_units": "mg/dL"
   },
   "low_temptarget_lowers_sensitivity": false,
   "maxCOB": 120,
   "maxSMBBasalMinutes": 30,
   "maxUAMSMBBasalMinutes": 30,
   "max_basal": 2,
   "max_bg": 110,
   "max_daily_basal": 0.775,
   "max_daily_safety_multiplier": 3,
   "max_iob": 4,
   "min_5m_carbimpact": 8,
   "min_bg": 110,
   "model": "754\n",
   "noisyCGMTargetMultiplier": 1.3,
   "offline_hotspot": false,
   "out_units": "mg/dL",
   "remainingCarbsCap": 90,
   "remainingCarbsFraction": 1,
   "resistance_lowers_target": false,
   "rewind_resets_autosens": true,
   "sens": 90.463,
   "sensitivity_raises_target": true,
   "suspend_zeros_iob": true,
   "unsuspend_if_no_temp": false,
   "useCustomPeakTime": false,
   "wide_bg_target_range": false
}

And for the other one

{
   "A52_risk_enable": false,
   "SMBInterval": 3,
   "adv_target_adjustments": false,
   "allowSMB_with_high_temptarget": false,
   "autosens_max": 1.2,
   "autosens_min": 0.7,
   "autotune_isf_adjustmentFraction": 1,
   "basalprofile": [
      {
         "i": 0,
         "minutes": 0,
         "rate": 0.694,
         "start": "00:00:00",
         "untuned": 3
      },
      {
         "i": 1,
         "minutes": 60,
         "rate": 0.707,
         "start": "01:00:00",
         "untuned": 2
      },
      {
         "i": 2,
         "minutes": 120,
         "rate": 0.48,
         "start": "02:00:00",
         "untuned": 2
      },
      {
         "i": 3,
         "minutes": 180,
         "rate": 0.48,
         "start": "03:00:00",
         "untuned": 3
      },
      {
         "i": 4,
         "minutes": 240,
         "rate": 0.48,
         "start": "04:00:00",
         "untuned": 3
      },
      {
         "i": 5,
         "minutes": 300,
         "rate": 0.452,
         "start": "05:00:00",
         "untuned": 2
      },
      {
         "i": 6,
         "minutes": 360,
         "rate": 0.404,
         "start": "06:00:00",
         "untuned": 2
      },
      {
         "i": 7,
         "minutes": 420,
         "rate": 0.404,
         "start": "07:00:00",
         "untuned": 3
      },
      {
         "i": 8,
         "minutes": 480,
         "rate": 0.404,
         "start": "08:00:00",
         "untuned": 2
      },
      {
         "i": 9,
         "minutes": 540,
         "rate": 0.404,
         "start": "09:00:00",
         "untuned": 2
      },
      {
         "i": 10,
         "minutes": 600,
         "rate": 0.364,
         "start": "10:00:00",
         "untuned": 2
      },
      {
         "i": 11,
         "minutes": 660,
         "rate": 0.354,
         "start": "11:00:00",
         "untuned": 3
      },
      {
         "i": 12,
         "minutes": 720,
         "rate": 0.354,
         "start": "12:00:00",
         "untuned": 3
      },
      {
         "i": 13,
         "minutes": 780,
         "rate": 0.354,
         "start": "13:00:00",
         "untuned": 3
      },
      {
         "i": 14,
         "minutes": 840,
         "rate": 0.354,
         "start": "14:00:00",
         "untuned": 3
      },
      {
         "i": 15,
         "minutes": 900,
         "rate": 0.516,
         "start": "15:00:00",
         "untuned": 3
      },
      {
         "i": 16,
         "minutes": 960,
         "rate": 0.508,
         "start": "16:00:00",
         "untuned": 3
      },
      {
         "i": 17,
         "minutes": 1020,
         "rate": 0.511,
         "start": "17:00:00",
         "untuned": 4
      },
      {
         "i": 18,
         "minutes": 1080,
         "rate": 0.511,
         "start": "18:00:00",
         "untuned": 4
      },
      {
         "i": 19,
         "minutes": 1140,
         "rate": 0.508,
         "start": "19:00:00",
         "untuned": 3
      },
      {
         "i": 20,
         "minutes": 1200,
         "rate": 0.587,
         "start": "20:00:00",
         "untuned": 3
      },
      {
         "i": 21,
         "minutes": 1260,
         "rate": 0.767,
         "start": "21:00:00",
         "untuned": 3
      },
      {
         "i": 22,
         "minutes": 1320,
         "rate": 0.762,
         "start": "22:00:00",
         "untuned": 3
      },
      {
         "i": 23,
         "minutes": 1380,
         "rate": 0.723,
         "start": "23:00:00",
         "untuned": 4
      }
   ],
   "bg_targets": {
      "first": 1,
      "targets": [
         {
            "high": 110,
            "i": 0,
            "low": 110,
            "max_bg": 110,
            "min_bg": 110,
            "offset": 0,
            "start": "00:00:00",
            "x": 0
         }
      ],
      "units": "mg/dL",
      "user_preferred_units": "mg/dL"
   },
   "bolus_increment": 0.1,
   "bolussnooze_dia_divisor": 2,
   "carb_ratio": 14.9,
   "carb_ratios": {
      "first": 1,
      "schedule": [
         {
            "i": 0,
            "offset": 0,
            "ratio": 15,
            "start": "00:00:00",
            "x": 0
         },
         {
            "i": 12,
            "offset": 360,
            "ratio": 8.5,
            "start": "06:00:00",
            "x": 1
         },
         {
            "i": 18,
            "offset": 540,
            "ratio": 9.2,
            "start": "09:00:00",
            "x": 2
         },
         {
            "i": 28,
            "offset": 840,
            "ratio": 13,
            "start": "14:00:00",
            "x": 3
         },
         {
            "i": 37,
            "offset": 1110,
            "ratio": 13,
            "start": "18:30:00",
            "x": 4
         }
      ],
      "units": "grams"
   },
   "carbsReqThreshold": 1,
   "csf": 6.06,
   "current_basal": 0.45,
   "current_basal_safety_multiplier": 4,
   "curve": "rapid-acting",
   "dia": 4,
   "enableSMB_after_carbs": false,
   "enableSMB_always": false,
   "enableSMB_with_COB": false,
   "enableSMB_with_temptarget": false,
   "enableUAM": true,
   "exercise_mode": false,
   "half_basal_exercise_target": 160,
   "high_temptarget_raises_sensitivity": false,
   "insulinPeakTime": 75,
   "isfProfile": {
      "first": 1,
      "sensitivities": [
         {
            "i": 0,
            "offset": 0,
            "sensitivity": 90.561,
            "start": "00:00:00",
            "x": 0
         },
         {
            "endOffset": 360,
            "i": 2,
            "offset": 60,
            "sensitivity": 170,
            "start": "01:00:00",
            "x": 1
         },
         {
            "i": 12,
            "offset": 360,
            "sensitivity": 115,
            "start": "06:00:00",
            "x": 2
         }
      ],
      "units": "mg/dL",
      "user_preferred_units": "mg/dL"
   },
   "low_temptarget_lowers_sensitivity": false,
   "maxCOB": 120,
   "maxSMBBasalMinutes": 30,
   "maxUAMSMBBasalMinutes": 30,
   "max_basal": 2,
   "max_bg": 110,
   "max_daily_basal": 0.775,
   "max_daily_safety_multiplier": 3,
   "max_iob": 3,
   "min_5m_carbimpact": 8,
   "min_bg": 110,
   "model": "754\n",
   "noisyCGMTargetMultiplier": 1.3,
   "offline_hotspot": false,
   "out_units": "mg/dL",
   "remainingCarbsCap": 90,
   "remainingCarbsFraction": 1,
   "resistance_lowers_target": false,
   "rewind_resets_autosens": true,
   "sens": 90.561,
   "sensitivity_raises_target": true,
   "suspend_zeros_iob": true,
   "unsuspend_if_no_temp": false,
   "useCustomPeakTime": false,
   "wide_bg_target_range": false
}

**Comment by tzachi-dar** [comment]
Please note that the second file seems to be missing a lot of the values that existed in preferences.json

For example on preference.json we have:
"max_iob": 4,
"autosens_max": 1.01,
"enableUAM": false,

On the first file we have:
"max_iob": 4,
"autosens_max": 1.01,
"enableUAM": false,

On the second file we have:
"max_iob": 3
"autosens_max": 1.2
"enableUAM": true,

It also seems that the second file did not take the values of insulin sensitivities correctly.

**Comment by tzachi-dar** [comment]
The file settings/autotune.json seems to be different on both machines. Although both were created on  Apr 28 04:05

The files  settings/insulin_sensitivities.json seems to be the same on both machines, and were created recently. 
The bg values in them seems to match my pump settings but the time of day not.
Content of file is:
cat settings/insulin_sensitivities.json
{
  "units": "mg/dL",
  "user_preferred_units": "mg/dL",
  "sensitivities": [
    {
      "i": 0,
      "x": 0,
      "sensitivity": 90,
      "offset": 0,
      "start": "00:00:00"
    },
    {
      "i": 2,
      "x": 1,
      "sensitivity": 120,
      "offset": 60,
      "start": "01:00:00"
    },
    {
      "i": 10,
      "x": 2,
      "sensitivity": 80,
      "offset": 300,
      "start": "05:00:00"
    }
  ],
  "first": 1

On py pump settings are:
00:00 90
01:00 120
21:00 80
So, I expect it to remain 120 until 21:00 while they seem to change on 05:00.

**Comment by tzachi-dar** [comment]
So, I guess I'm missing two pieces of the puzzle: The first and more important:
How does the ISF settings being copied from the pump? The error that I'm gettings seems very strange.
(that is values are being copied correctly, but time is not set correctly.)

The second issue is how should the date be copied from myopenaps/preferences.json to the file autotune/profile.json (or should it first go to settings/profile.json) (or is it actually coming from settings/pumpprofile.json ?)
It is already 03:00 am here, so quitting, but I think the key here is in the following code:

**Comment by tzachi-dar** [comment]
First issue seems resolved. Continuing to the second.

It seems that the following files are correct:
settings/pumpprofile.json 
autotune/profile.pump.json

**Comment by tzachi-dar** [comment]
settings/profile.json also seems correct.

**Comment by tzachi-dar** [comment]
Looking right now, it seems that autotune/profile.json is wrong I need to understand who is creating it.
So the coping in the line:
(oref0-autotune -d=$directory -n=$NIGHTSCOUT_HOST && cat $directory/autotune/profile.json | jq . | grep -q start && cp $directory/autotune/profile.json $directory/settings/autotune.json) 2>&1 | tee -a /var/log/openaps/autotune.log &

probably takes place, but it is already too late.

By the way, changed insulin sensitivities on the pump, insulin_sensitivities.json has changed correctly, but it still was not propagated. Will also have to look at it.

**Comment by tzachi-dar** [comment]
Here are my conclusions regarding the bug.
TLDR: I have noticed that ISF data is not being copied correctly from pump to code.
During the debug, I have noticed that other variables are also not being copied correctly.
The bug is in the function tuneAllTheThings More specicly in:
https://github.com/openaps/oref0/blob/86f601ea56210d7dc55babcff4a5a4e906fa9476/lib/autotune/index.js#L415

The code here starts from “autotuneOutput = previousAutotune;”
As a result variables that are on the struct will not be copied from the file profile.pump.json
Let’s look at a few variables that do not work as expected:
enableUAM
Max_iob
Actually all fields that are directly on the strurct.
ISF data, also copied from the previousAutotune and not from profile.pump.json.
That is we have:
var isfProfile = previousAutotune.isfProfile;
…
autotuneOutput.isfProfile = isfProfile;
Only the first variable in the code is used.
So, we always stay with the data that was read in the first day.

**Comment by tim2000s** [comment]
@tzachi-dar - on rig Autotune has always started a new tune from the previous output of Autotune rather than from the pump settings. That’s how it was designed to work, as an iterative, slow changing process. It uses the existing pump settings to provide a max deviation  check and restrict any changes from being more than the autosens max and min from those. 

What behaviour are you expecting from Autotune on rig?

**Comment by tzachi-dar** [comment]
Thanks for helping @tim2000s.
This bug started as one thing, and after debugging it, it is actually a different one.
I'll close this one and open a new one soon, to reflect the new findings.

As for autotune it became the suspect of this bug for two reasons.
1) This is where parameters are being copied.
2) As for insulin sensitivities. On the pump there can be more than one value depending on time. Autotune only works on the first value. (I assume that tuning all values is better but harder). So, if the user has changed other values on the pump they should be propagated by autotune. This is not happening today.

I'm closing this bug and opening a new bug to make it easier to follow now that (i think that) I understand the issue better.

**Comment by tzachi-dar** [comment]
Opened https://github.com/openaps/oref0/issues/1251 instead.
