### ISSUE TITLE
Non-sgv entries in monitor/glucose.json breaks settings/auto-sens.json report

### ISSUE THREAD

**Issue by Spazholio** [openaps/oref0#127]
As of today, when the `settings/auto-sens.json` report encounters an entry in `monitor/glucose.json` that doesn't have a "sgv" entry in it, it dies.  Creating a new report that lives alongside `monitor/glucose.json` and pointing `settings/auto-sens.json` at that seems to resolve the issue.

**Comment by scottleibrand** [comment]
@dpiessens reported what looks like the same issue, with the following error:
`avgDelta = avgDelta.toFixed(2); ^ TypeError: Object NaN has no method 'toFixed' at detectSensitivityandCarbAbsorption (/home/edison/src/oref0/lib/determine-basal/cob-autosens.js:50:29) at Object.<anonymous> (/home/edison/src/oref0/bin/oref0-detect-sensitivity.js:73:5) at Module._compile (module.js:456:26) at Object.Module._extensions..js (module.js:474:10) at Module.load (module.js:356:32) at Function.Module._load (module.js:312:12) at Function.Module.runMain (module.js:497:10) at startup (node.js:119:16) at node.js:906:3`

**Comment by bewest** [comment]
Ah, need to use something like this: `openaps use ns shell get entries/sgv.json count=288`.
This selects only sgv entries from Nightscout.  There are a few other ways, but this works well and is easy to type.

**Comment by scottleibrand** [comment]
Is this workaround sufficient, or do we need to update the oref0 code to handle a data source other than entries/sgv.json ?
