### ISSUE TITLE
Write a script to install mraa for pi dev branch in the event of needing to flash the radio chip with ccprog

### ISSUE THREAD

**Issue by tepidjuice** [openaps/oref0#1270]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tepidjuice** [comment]
Had a lot of issues trying to flash the radio chip of my pi as mraa wasn't installed by the dev branch. Adding a script to install mraa for dev would be handy.

Something like:

cd ~/src &&
wget https://github.com/intel-iot-devkit/mraa/archive/v1.7.0.tar.gz &&
tar -xvf v1.7.0.tar.gz && mv mraa-1.7.0/ mraa/ &&
apt-get install cmake &&
mkdir -p mraa/build && cd mraa/build && cmake .. -DBUILDSWIGNODE=OFF &&
make && make install && echo mraa installed. Please reboot before using. &&
bash -c "grep -q i386-linux-gnu /etc/ld.so.conf || echo /usr/local/lib/i386-linux-gnu/ >> /etc/ld.so.conf  && ldconfig"

**Comment by cluckj** [comment]
We removed it because the `dev` code doesn't use it, and it takes a long time to compile on the Pi Zero. 

I'm down with writing something up to have it install in some form; what do y'all think is best? Should we put it behind a `[y/N]` switch in interactive setup with a runagain flag (like we do with bluetooth tethering), install by default, or have a standalone install script for it?

**Comment by scottleibrand** [comment]
We probably still don't need to install it by default.  I'd be fine with either a standalone script or a non-default option in oref0-setup.  Wouldn't even need runagain, as it only has to be installed once...

**Comment by tepidjuice** [comment]
Personally I think a quick separate script would be best as it's only needed for ccprog. I'm also happy to try and write something although my bash scripting is a bit *very* terrible.

**Comment by scottleibrand** [comment]
Resolved via #1302
