### ISSUE TITLE
Upload additional information to NS for retrospective analysis 

### ISSUE THREAD

**Issue by danamlewis** [openaps/oref0#1276]
For retrospective analysis, it would be useful to track additional data elements, such as:

- Insulin curve
  - peak and end time, if being calculated 
- Preferences 

It would be useful to upload these on a regular (daily? weekly?) basis to track feature usage & changes over time.

**Comment by scottleibrand** [comment]
https://github.com/openaps/oref0/pull/1300

**Comment by danamlewis** [comment]
Closing as it's now in dev with the 0.7.0 release candidate
