### ISSUE TITLE
Add check to oref0-meal to make sure there's enough glucose history to match carb history

### ISSUE THREAD

**Issue by jasoncalabrese** [openaps/oref0#128]
After watching COB stay way to high for a long time I finally found the issue was caused by using my short glucose.json with 10 entries instead of the 24h glucose.  The result was that carbs older than 50 minutes were never getting decayed.

**Comment by scottleibrand** [comment]
Looks like that fixed it.  Can you please test to confirm?

**Comment by jasoncalabrese** [comment]
Looks good.

I saw both the "Could not parse input data" and "Optional feature meal assist disabled: not enough glucose data to calculate carb absorption" while upgrading one of my rigs.
