### ISSUE TITLE
RPI + USB TI Stick (legacy rig) - setup results in hard exit

### ISSUE THREAD

**Issue by rkresha** [openaps/oref0#1281]
**oref0-setup.sh fails to complete**
Using my typical non-interactive oref0-setup results with the following message
> Unsupported ttyport. Exiting.
This is the result of #1244 and the hard exit in it. My understanding is that mmeowlink is being deprecated in some fashion however, I'm currently relying on it for one of my rigs which is a RPI3 and a USB TI stick.

**To Reproduce**
`~/src/oref0/bin/oref0-setup.sh --max_iob=10 --max_daily_safety_multiplier=5 --current_basal_safety_multiplier=6 --dir=/home/pi/openaps --serial=XXXXXX --cgm=xdrip --ns-host=https://XXXXXX.herokuapp.com --api-secret=XXXXXX --tty=/dev/mmeowlink --enable=' autosens autotune meal ' --radio_locale='US' --npm_install=force`

`/dev/meeowlink is a softlink to the actual /dev/ port/interface`

**Expected behavior**
Would like this to be soft throw instead of exiting all the way out, but I'm un-aware of long term goals here so I figure it would be best to let @cluckj try to address it before I get my hand in the cookie jar (there is a joke here).

Thanks and please advise.

**Comment by cluckj** [comment]
It should completely barf in `dev` because the USB TI stick won't work with the Go-based pump communication library -- you can switch back to the `master` branch, or you can use jumpers to wire the TI stick to the SPI header of the Pi (I think you'll need to reflash the TI stick firmware too?).

**Comment by rkresha** [comment]
@cluckj @scottleibrand are there any talks of being able to continue to support the TI USB stick via the old non-go mmeowlink libraries or has that ship sailed?

**Comment by scottleibrand** [comment]
If you’d like to take over maintenance of an 0.6.x branch for that purpose, I would have no objection. Not sure if it still works with 0.6.3 master as is.

**Comment by cluckj** [comment]
Just to update on this for folks who are curious,

There is *no support* for USB-connected TI sticks in 0.7.0. If you want to keep using the hardware, you'll need to jumper the header to the Pi or Edison, and re-flash the cc111x chip:

There is support within `oref0-setup.sh` for the TI stick when it the headers are jumper-connected to the SPI ports on the Pi (or Edison).

There is *no support* in `oref0-setup.sh` for UART-wired TI sticks in `oref0-setup` at the moment, but you can manually configure the software.

**Comment by danamlewis** [comment]
Closing, see @cluckj note above or the release notes and docs regarding 0.7.0 and beyond for the TI options currently supported.
