### ISSUE TITLE
Help needed for my project(with openAPS)

### ISSUE THREAD

**Issue by gabriellm1** [openaps/oref0#1293]
Hey guys, my name is Gabriel and I'm a computer engineering student in São Paulo, Brazil. I'm currently enrolled in a project with my teacher where we will try to build a hardware in the loop system which will simulate BG-insulin dynamics. The ideia is that we could implement an open-source closed loop system such as openAPS or loop to this model to "validate " that with the hardware.

We just started the project and we are very excited with the idea. For me, as a type 1 person, is even more special.

The dynamic model I'm using right know is a MatLab script from John Hedengren. This is just a start project which I understood right away. I'm open for suggestions on other dynamic models.
https://www.mathworks.com/matlabcentral/fileexchange/48019-blood-glucose-regulation-in-a-type-i-diabetic-in-simulink?focused=3842674&tab=function

I would be very happy to know how you guys actually test the code when an important pull request is made. And with that if there is a way to force values without the need of a glucose monitor or a pump. This is important for me because I want to simulate those entries with my hardware. 

Thanks in advance for your attention.

**Comment by scottleibrand** [comment]
You might want to check out https://github.com/Perceptus/GlucoSym and/or https://github.com/openaps/oref0/tree/simple-simulator
