### ISSUE TITLE
Bolus via wizard not appearing in Nightscout

### ISSUE THREAD

**Issue by mddub** [openaps/oref0#130]
Here are the commits from two `iter_pump_hours 4` reports, one loop apart. The first commit adds a bolus wizard entry to history, the second adds the bolus itself to history (presumably the record was created after delivery finished?). Because the bolus has the same timestamp as the already-uploaded bolus wizard entry, it is excluded by `nightscout cull-latest-openaps-treatments`:

First commit: https://gist.github.com/mddub/f64b5ae8cacbaa1b67b308654450ec46
Second commit: https://gist.github.com/mddub/ec20634e5a579a7225655b715b2bf930

From my openaps.ini:

```
latest-ns-treatment-time = ! bash -c "nightscout latest-openaps-treatment $NIGHTSCOUT_HOST | json created_at"
format-latest-nightscout-treatments = ! bash -c "nightscout cull-latest-openaps-treatments monitor/pumphistory-zoned.json settings/model.json $(openaps latest-ns-treatment-time) > upload/latest-treatments.json"
upload-recent-treatments = ! bash -c "openaps format-latest-nightscout-treatments && test $(json -f upload/latest-treatments.json -a created_at eventType | wc -l ) -gt 0 && (ns-upload $NIGHTSCOUT_HOST $API_SECRET treatments.json upload/latest-treatments.json ) || echo \"No recent treatments to upload\""
upload = ! bash -c "openaps upload-recent-treatments 2>/dev/null >/dev/null && echo -n \"Uploaded; most recent treatment event @ \" && openaps latest-ns-treatment-time || echo \"Error; could not upload\""
```

I set these aliases up a long time ago according to the docs. Is there a newer way to upload treatments which prevents this issue?

(Running openaps 0.1.0, oref0 0.1.4, decocare 0.0.23)

**Comment by jasoncalabrese** [comment]
I've seen things like this when the history is read and uploaded before the bolus finishes.  The trick for fixing that is checking the `bolusing` status.

The hack I'm using for that is here: https://github.com/jasoncalabrese/indy-e1b/blob/master/openaps.ini#L3

**Comment by bewest** [comment]
Sounds like the read history commands (and possibly others?) should check the bolusing (optionally taking a `pump-status.json`?) and... maybe wait a bit before continuing?

**Comment by jasoncalabrese** [comment]
Not sure of it should wait or fail, but does make sense to have a read
history use that takes a status.

**Comment by mddub** [comment]
Thanks @jasoncalabrese, I like your `bolusing` workaround. Sounds like the right way to fix this is a change to history commands in `openaps`/`decocare`, so I'll close this.
