### ISSUE TITLE
Use reservoir data as alternative to pumphistory

### ISSUE THREAD

**Issue by scottleibrand** [openaps/oref0#132]
@loudnate's Loop app for iOS does an excellent job of calculating IOB and looping using only the pump reservoir information (refreshed every 5 minutes), without ever having to pull a full pumphistory.  While there are lots of things (like NS uploads) we still want pumphistory for, it would be good to be able to use reservoir data as an alternative when we're having trouble refreshing pumphistory (or want to do a quick enact without waiting to refresh it).  This would probably require building some sort of reservoirhistory.json file and using whatever portions of it are more recent than the most recent pumphistory.json

**Comment by loudnate** [comment]
While prototyping Loop last year, I added this feature to mmhistorytools.

The idea is you take reservoir data and you convert it to pseudo temp-basal records, then you normalize those against the basal profile, and the output is suitable for IOB calculation.

https://github.com/loudnate/openaps-mmhistorytools/blob/master/openapscontrib/mmhistorytools/historytools.py#L694

https://github.com/loudnate/openaps-mmhistorytools/blob/master/openapscontrib/mmhistorytools/__init__.py#L432

**Comment by scottleibrand** [comment]
Nice. Yet another reason we really need to get oref0 using mmhistorytools.

**Comment by scottleibrand** [comment]
I think this will eventually become part of https://github.com/openaps/oref0/issues/262 - not necessarily as an alternative to pumphistory, as I originally envisioned, but as a quick way to check whether pumphistory is out of date (because reservoir volume has dropped since the last pumphistory run) and needs refreshed.  Closing this out to work on it there.
