### ISSUE TITLE
Duplicate detection causes COB to be lost

### ISSUE THREAD

**Issue by daveewall** [openaps/oref0#134]
In /lib/meal/history.js, the following loop causes COB to disappear because the BolusWizard and the Bolus entry are in the pumphistory.js at exactly the same time, and it kills the BolusWizard entry, assuming it's a duplicate, but that's where the COB comes from:

            for (var j=0; j < mealInputs.length; j++) {
              var element = mealInputs[j];
              if (element.timestamp == current.timestamp) dupeFound = true;
          }

Commenting out this loop fixed the issue for me, but that's just a hack.

This is the meal.json setup:

openaps report add monitor/meal.json text meal shell monitor/pumphistory-zoned.json settings/profile.json monitor/clock-zoned.json monitor/glucoseclean.json settings/basal_profile.json

Not using a separate carb history file, because on Medtronic, it's in the pumphistory-zoned.json.

**Comment by sulkaharo** [comment]
I have a fix, testing.

**Comment by sulkaharo** [comment]
https://github.com/openaps/oref0/pull/135 should fix this. Which pump do you have? Ours seems to log a different timestamp for the bolus and the wizard event...

**Comment by daveewall** [comment]
I'm using a Medtronic 523.  Let me know if you need any sample files.

**Comment by sulkaharo** [comment]
Wanna pull the branch to your device? Alternatively - yes sample files would be cool.

**Comment by daveewall** [comment]
[aps.tar.gz](https://github.com/openaps/oref0/files/322481/aps.tar.gz)

Try this on for size.  It's my aps directory, sans .git.  The monitor/pumphistory-zoned.json has a BolusWizard and a Bolus object with timestamp 2016-06-19T12:59:36-04:00.

Sorry, don't have time to test it right now... figured this is quicker.

**Comment by sulkaharo** [comment]
https://github.com/openaps/oref0/pull/136 now has an unit test based on your sample data and better algorithm

**Comment by sulkaharo** [comment]
The PR was merged; can you update to latest AMA and check if the fix works for you? :)

**Comment by daveewall** [comment]
I just updated the system, and the code ran through fine, but since I don't have any COB, it's coming up zeroes.  I'll try to follow up later today.  If I forget, you can assume it worked.  :-)  If it doesn't, I'll make sure to follow up with more details for you.

Thanks for the fix, Sulka!

**Comment by sulkaharo** [comment]
Awesome! Wanna close the ticket? ;)

**Comment by daveewall** [comment]
Works well now, thanks!
