### ISSUE TITLE
Autotune integration in AndroidAPS

### ISSUE THREAD

**Issue by Philoul** [openaps/oref0#1376]
Hello,

I don't know if it's the right place to have this discussion (if not close it...)

I made an adaptation oref0-autotune as a plugin in AndroidAPS (see https://github.com/MilosKozak/AndroidAPS/pull/2669) but I have some gaps in results, and I was a little bit surprised with some parts of autotune algorythm...

I would appreciate to discuss with oref0-autotune developpers (@scottleibrand , may be others) to get lessons learned of oref0-autotune developments and have some help or advices how to test, check results...

Thank's

**Comment by scottleibrand** [comment]
https://gitter.im/openaps/autotune might be the best place to discuss.
