### ISSUE TITLE
0.7.0 Autotune: UAM always categorized as basal even if categorize-uam-as-basal setting is false

### ISSUE THREAD

**Issue by Philoul** [openaps/oref0#1383]
I made hundred tests to compare results with or without categorized-uam-as-basal setting
=> Tests done with AutotuneWeb and on a virtual machine on my computer (I use AndroidAPS)

UAM data are always categorized as basal whatever ```categorize-uam-as-basal``` setting (even in my worst days with several hours of uam data)

This is confirmed by a code analysis of categorized.js file lines 289-396
```
    if (opts.categorize_uam_as_basal) {
        console.error("--categorize-uam-as-basal=true set: categorizing all UAM data as basal.");
        basalGlucoseData = basalGlucoseData.concat(UAMGlucoseData);
    } else if (CSFLength > 12) {
        console.error("Found at least 1h of carb absorption: assuming all meals were announced, and categorizing UAM data as basal.");
        basalGlucoseData = basalGlucoseData.concat(UAMGlucoseData);
    } else {
        ...
    }
```

It's just quite impossible to have test line 392  ```else if (CSFLength > 12)``` false: if we have only one meal announced with 20 or 25g of carbs, we will have at least one hour of CSF data so even if we have several hours of UAM data, all uam data will always be categorized as basal...
=> I think code between lines 396 and 424 is never executed

I also made some tests replacing line 392 by  ```else if (UAMLength < 12)``` 
=> With this line if I have less than 1 hour of UAM data (assuming all meals were announced) UAM data is categorised as basal)
=> But if I have more than one hour of UAM data then UAM are categorized between ISF and basals according to lines between 396 and 424
I think with this modification Autotune works as expected (there are security warning in documentation if we use ```--categorize-uam-as-basal=true```...)

**Comment by scottleibrand** [comment]
Yes, this is on purpose. We originally had the behavior you expected, but too many people were seeing "problems with autotune failing to converge, and instead constantly trying to reduce basals until it hits safety limits, because too much data that would otherwise indicate basals are too low is being excluded as UAM", as described at in the PR where we added the code you found: 
https://github.com/openaps/oref0/pull/1195

**Comment by Philoul** [comment]
Sorry wrong manip
