### ISSUE TITLE
0.7.1 dev branch. The NS pill does not contain important diabetes values: COB, CR, ISF, Target

### ISSUE THREAD

**Issue by SeregaYakovlev** [openaps/oref0#1405]
In 0.7.0 master branch, I can see all elements of the NS pill:
_________________________________________________________________________________________________
**3m ago** **Temp Basal Started:** 0.00 for 60m, BG: 5.2, COB: 68, Dev: 2.3, BGI: -0.5, ISF: 2.7, CR: 8, Target: 6.0, minPredBG 6.8, minGuardBG 3.8, IOBpredBG 2.2, COBPredBG 17.1, UAMpredBG 3.0, minGuardBG 3.8<4.1, 16 add'l carbs req w/in 40m; EventualBG 8.6>= 6.0, insulinReq 0.15, maxBolus 1.5, setting 60m low temp of 0U/h., Microbolusing 1.5U, **SensitivityRatio:** 1, IOB: 3.29U, Basal IOB -2.00U, Bolus IOB 5.28U.
_________________________________________________________________________________________________

But in 0.7.1 dev branch I can see only:

________________________________________________________________________________________________
**3m ago** **Temp Basal Started:** 0.00 for 60m, BG: 5.2, minPredBG 6.8, minGuardBG 3.8, IOBpredBG 2.2, COBPredBG 17.1, UAMpredBG 3.0, minGuardBG 3.8<4.1, 16 add'l carbs req w/in 40m; EventualBG 8.6>= 6.0, insulinReq 0.15, setting 60m low temp of 0U/h., **SensitivityRatio:** 1, IOB: 3.29U, Basal IOB -2.00U, Bolus IOB 5.28U.
________________________________________________________________________________________________

**The important diabetes values are missing:** COB, Target, ISF, CR

**To Reproduce**
1. Install the **_dev_** branch of oref0;
2. Go to your nightscrout site.
2. Click on _'Openaps'_ pill.
4. See, that **the important diabetes values are missing**: COB, Target, ISF, CR.

**Expected behavior**
Ideally, I suggest to display the pill in such order as in _Additional Context Section_. But mostly I need the COB, Target, ISF, CR.

**Screenshots**
master branch NS pill:
![master-branch-NS-pill](https://user-images.githubusercontent.com/52125266/128252073-5889b5fa-d0da-4c3d-ae45-23cfa3a8d2e4.jpg)
dev branch NS pill:
![dev-branch-NS-pill](https://user-images.githubusercontent.com/52125266/128252094-fe0cb573-4a13-48e7-ba3a-45f8999d59b4.jpg)

**Smartphone:**
Xiaomi Redmi Note 5A.

**Setup Information:**
* Pump type: Medtronic 722, v. 2.4A firmware
* CGM type: MDT
* Rig type: Edison/Explorer Board rig
* oref0 version: 0.7.1-dev

**Additional context**
Ideally, I suggest to display the pill in this order:

_________________________________________________________________________________________________
**3m ago**: BG: 5.2, COB: 68, IOB: 3.29U, **carbsReq 16 within 40m;** Target: 6.0;
**SensitivityRatio:** 1, ISF: 2.7, CR: 8;
**Insulin info:** Dev: 2.3, BGI: -0.5, insulinReq 0.15.,  maxBolus 1.5, Microbolusing 1.5U, setting 60m low temp of 0U/h., Basal IOB -2.00U, Bolus IOB 5.28U, Temp Basal: 0.00 for 60m.
**PredBGs:** minPredBG 6.8, minGuardBG 3.8, IOBpredBG 2.2, COBPredBG 17.1, UAMpredBG 3.0, minGuardBG 3.8<4.1,  EventualBG 8.6 >= 6.0.
_________________________________________________________________________________________________

**Comment by mountrcg** [comment]
this is due to rT.reason not containing it anymore
https://github.com/openaps/oref0/blob/d8af80b1b347456cb24e53025aec780c53c01ae6/lib/determine-basal/determine-basal.js#L811
