### ISSUE TITLE
undefined variable dev5m in lib/autotune-prep/categorize.js dev branch

### ISSUE THREAD

**Issue by Zanfib** [openaps/oref0#1417]
I all,
I'm new to openaps and try to have an open loop running.
I've cloned the git dev branch of oref0 to use autotune on my linux desktop and faced an error with running autotune :

> /home/didier/Developpement/oref0/lib/autotune-prep/categorize.js:224                                                                                  
>         dev5m = delta-BGI;                                                                                                                            
>               ^                                                                                                                                       
>                                                                                                                                                       
> ReferenceError: dev5m is not defined                                                                                                                  
>     at categorizeBGDatums (/home/didier/Developpement/oref0/lib/autotune-prep/categorize.js:224:15)                          
>     at generate (/home/didier/Developpement/oref0/lib/autotune-prep/index.js:23:30)                                          
>     at Object.<anonymous> (/home/didier/Developpement/oref0/bin/oref0-autotune-prep.js:135:27)                        
>     at Module._compile (internal/modules/cjs/loader.js:999:30)                                                                                        
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)                                  
>     at Module.load (internal/modules/cjs/loader.js:863:32)                                                                                            
>     at Function.Module._load (internal/modules/cjs/loader.js:708:14)                                                                                  
>     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)                                                               
>     at internal/main/run_main_module.js:17:47

I've simply added 'var dev5m;' in the file lib/autotune-prep/categorize.js line 153 and it worked as expected.
Thanks !

**Comment by scottleibrand** [comment]
Thx. I opened #1417 to fix.
