### ISSUE TITLE
rT not completely converted for mmol/L units

### ISSUE THREAD

**Issue by mountrcg** [openaps/oref0#1439]
**Describe the bug**
Missing `convert_bg` function calls on rT assignments of BG variables

**To Reproduce**
just view rT with mmol/L as units specified in profile

**Expected behavior**
output in the units as specified by profile

**Additional context**
PR #1438 has been created, however for the `rT.predBGs` I havent found a solution as `convert_bg(value,profile)` does not work on something like` rT.predBGs.COB = COBpredBGs`

**Comment by mountrcg** [comment]
I cannot seem to the pull request to the issue, it's mentioned above

**Comment by scottleibrand** [comment]
You can like the PR like #1438.

**Comment by mountrcg** [comment]
fixed
