### ISSUE TITLE
Tick format

### ISSUE THREAD

**Issue by mountrcg** [openaps/oref0#1441]
Is there a reason why Tick being positive is a String as in +5, wheres if it is negative it' a number. Makes it troublesome in some clients.

**Comment by scottleibrand** [comment]
We didn’t coerce it beyond just adding the + for display, so that’s what it defaults to. A PR to make them both strings would be fine, or you could switch those clients to use delta (always a number) for things they don’t want as strings.

**Comment by mountrcg** [comment]
Thanks a lot Scott, that helps. So I will adjust on my side, no PR necessary.
