### ISSUE TITLE
Bolus snoozes zeroTemp functionality still active?

### ISSUE THREAD

**Issue by mountrcg** [openaps/oref0#1447]
@scottleibrand  Is the functionality that is configured with `bolussnooze_dia_divisor`not used anymore? The preference ist still there but I don't see it used?

**Comment by scottleibrand** [comment]
No, that was removed in https://github.com/openaps/oref0/pull/685

There is still one uncommented line defining the preference, but it's not used anywhere. If you'd like to do a PR to remove it (and maybe the commented-out code in oref0-setup) for clarity, please go ahead.

**Comment by mountrcg** [comment]
:-) the citation of the last remaining thing in #685 "The only remaining need for it might be if anyone is not entering carbs (either via NS or the pump), is manually bolusing for food, and then is expecting bolus snooze to cover until UAM kicks in. If that turns out to be a significant fraction of the OpenAPS user base (which I doubt) we can revisit how best to support that use case." is exactly what I do.
I don't enter carbs anymore and let UAM do it's thing. But for carb heavy meals I do pre-bolus.

**Comment by scottleibrand** [comment]
Heh. I guess one person speaking up in 5.5 years qualifies as a small fraction of the user base. :-) 

Is it significantly easier to pre-bolus for carb-heavy meals than to enter carbs (even a really rough estimate) and let SMB get to work?

**Comment by mountrcg** [comment]
I agree 100%, but things are changing now with people moving away from tracking carbs using oref.

I do not bother about counting carbs (I always sm to get it wrong when I have to guesstimate) anymore, but just take a  keep on the low side with the pre-bolus - I find the algo with UAM more reliable, than with my wrong carbs

**Comment by mountrcg** [comment]
and btw I am the second, there is one person in #685, but you could say that was before you started counting the 5.5 yrs :-)
