### ISSUE TITLE
It hangs out at Starting Kernel.....

### ISSUE THREAD

**Issue by Drainer2002** [openaps/oref0#1450]
My rig was completely working fine for years already. today morning, I rebooted the rig and the light in-between the port turned on for couple of minutes and then turned off.  every time I rebooted it , it did the same thing. I connected the rig to my computer and it hangs at starting kernel.....

Please help

`**********
PSH KERNEL VERSION: b0182929
                WR: 20104000
**********

SCU IPC: 0x800000d0  0xfffce92c

PSH miaHOB version: TNG.B0.VVBD.0000000c

microkernel built 10:14:01 Jan 13 2015

*** PSH loader ***
PCM page cache size = 192 KB
Cache Constraint = 0 Pages
Arming IPC driver ..
Adding page store pool ..
PagestoreAddr(IMR Start Address) = 0x04899000
pageStoreSize(IMR Size)          = 0x00080000

* Ready to receive application *

U-Boot 2014.04 (Feb 09 2015 - 15:40:31)

       Watchdog enabled
DRAM:  980.6 MiB
MMC:   tangier_sdhci: 0
In:    serial
Out:   serial
Err:   serial
Hit any key to stop autoboot:  0
Target:blank
Partitioning already done...
Flashing already done...
GADGET DRIVER: usb_dnl_dfu
reading vmlinuz
4841888 bytes read in 155 ms (29.8 MiB/s)
Valid Boot Flag
Setup Size = 0x00003c00
Magic signature found
Using boot protocol version 2.0c
Linux kernel version 3.10.98-jubilinux-edison (robin@robin-i7) #13 SMP PREEMPT Fri Jun 23 02:24:12 EDT 2017
Building boot_params at 0x00090000
Loading bzImage at address 00100000 (4826528 bytes)
Magic signature found
Kernel command line: "rootwait root=PARTUUID=012b3303-34ac-284d-99b4-34e03a2335f4 rootfstype=ext4 console=ttyMFD2 earlyprintk=ttyMFD2,keep loglevel=4 g_multi.ethernet_config=rndis systemd.unit=multi-user.target hardware_id=00 g_multi.iSerialNumber=7beb42dc3a904d201d984157e4c3e600 g_multi.dev_addr=02:00:86:c3:e6:00"

Starting kernel ...`

**Comment by Drainer2002** [comment]
`arget:blank
Partitioning already done...
Flashing already done...
GADGET DRIVER: usb_dnl_dfu
reading vmlinuz
4841888 bytes read in 159 ms (29 MiB/s)
Valid Boot Flag
Setup Size = 0x00003c00
Magic signature found
Using boot protocol version 2.0c
Linux kernel version 3.10.98-jubilinux-edison (robin@robin-i7) #13 SMP PREEMPT Fri Jun 23 02:24:12 EDT 2017
Building boot_params at 0x00090000
Loading bzImage at address 00100000 (4826528 bytes)
Magic signature found
Kernel command line: "rootwait root=PARTUUID=012b3303-34ac-284d-99b4-34e03a2335f4 rootfstype=ext4 console=ttyMFD2 earlyprintk=ttyMFD2,keep loglevel=4 g_multi.ethernet_config=rndis systemd.unit=multi-user.target hardware_id=00 g_multi.iSerialNumber=7beb42dc3a904d201d984157e4c3e600 g_multi.dev_addr=02:00:86:c3:e6:00"

Starting kernel ...`

**Comment by scottleibrand** [comment]
The most likely cause for this kind of failure is Edison SSD degradation. You’ll probably need to reflash the rig, most likely multiple times until it manages to mark all the bad sectors and use other ones. And/or you can buy a fresh Edison off eBay and flash that.

**Comment by Drainer2002** [comment]
the thing is I am living in Russia currently, so it was okay to have it transported to me but now.... its hard.

How can I start reflashing,  when I can't enter on it ?
like what happened ?

**Comment by Drainer2002** [comment]
can I get your discord, to be able to contact bait easier,  please?

**Comment by scottleibrand** [comment]
You should be able to reimage your current hardware by following the instructions at https://openaps.readthedocs.io/en/latest/docs/Resources/Edison-Flashing/all-computers-flash.html

**Comment by Drainer2002** [comment]
Could be outdated or highly loaded nightscout? Because when I checked the disk, it was 91% full.

**Comment by scottleibrand** [comment]
If the kernel won’t even boot, it wouldn’t have anything to do with Nightscout.

**Comment by Drainer2002** [comment]
It does reboot, when it hangs at starting kernel.....
