### ISSUE TITLE
Incorrect "Setting temp basal of 1.15U/hr" in reason

### ISSUE THREAD

**Issue by scottleibrand** [openaps/oref0#166]
{"temp":"absolute","bg":122,"tick":"+6","eventualBG":142,"snoozeBG":127,"predBGs":{"IOB":[122,125,127,129,130,130,130,129,127,125,123,120,117,114,110,106,103,99,96,92,89,86,83,80,78,75,73,72,70,69,68,67,66,65,64],"aCOB":[122,132,141,150,158,166,172,179,185,190,195,199,204,207,211,214,217,220,222,225,227,229,231,234,236,238,241,243,246,248,250,253,255,257,259,261,263],"COB":[122,125,128,130,132,134,135,135,136,136,136,135,135,134,133,133,132,131,130,129,128,128,127,127,127,128,128,129,130,131,132,134,135,137,138,140,142]},"COB":56,"IOB":0.991,"reason":"COB: 56, Dev: 7, BGI: 0.23, ISF: 41.2, Target: 101; Eventual BG 142 >= 100, 30m@1.850 = 0.925 > req 0.6310679611650485+0.1U. Setting temp basal of 1.15U/hr","duration":30,"rate":2.4}

**Comment by cjo20** [comment]
```
rT.reason += currenttemp.duration + "m@" + (currenttemp.rate - basal).toFixed(3) + " = " + insulinScheduled.toFixed(3) + " > req " + insulinReq + "+0.1U. Setting temp basal of " + **basal** + "U/hr";
return tempBasalFunctions.setTempBasal(rate, 30, profile, rT, **currenttemp**);
```
Looks like a copy/paste error

**Comment by scottleibrand** [comment]
No, the first argument to setTempBasal is what actually gets set, so it's rate, not currenttemp.

**Comment by scottleibrand** [comment]
Fix pushed to dev.
