### ISSUE TITLE
Avoid low-temping right after carbs with AMA

### ISSUE THREAD

**Issue by scottleibrand** [openaps/oref0#171]
@jasoncalabrese reports that oref0 with AMA often zero-temps ~30m after a meal.

One potential improvement to the AMA algorithm to help with this would be to adjust the assumptions for future minimum carb absorption.  Currently, if observed carb impact (CI) is less than 3mg/dL/5m, and fewer than half of the meal carbs have absorbed, we assume that the remaining COB will absorb at 3mg/dL/5m.  It might work better for this and related scenarios if we instead assume a higher minimum CI when COB is first entered (maybe 5mg/dL/5m), and then reduce that linearly to zero as COB decays from 100% to 50% of entered meal carbs.  We still don't want to assume any CI once half of carbs have decayed, to avoid going low from miscounting carbs or from other activities preventing them from impacting BG.

**Comment by jasoncalabrese** [comment]
As an example of what I'm trying to avoid

<img width="1336" alt="screenshot 2016-07-17 16 00 14" src="https://cloud.githubusercontent.com/assets/751143/16903709/5709ec9e-4c3a-11e6-8ce8-c0716ba9fda1.png">

**Comment by jasoncalabrese** [comment]
I'm testing with the old slower bolus snooze to see if that prevents the post meal low temping

**Comment by scottleibrand** [comment]
@jasoncalabrese do you think this is resolved now with the slower bolus snooze etc.?

**Comment by jasoncalabrese** [comment]
Yes, the slower bolus snooze was the solution for us
