### ISSUE TITLE
Conditionals in reports?

### ISSUE THREAD

**Issue by Spazholio** [openaps/oref0#173]
This isn't an issue, but more of a feature request.  I'd love it (and I hope others would too) if there was some way to determine certain things (ie: conditionals, a simple if/then/else) within the openaps reports themselves, rather than having to do some bash-level copying/comparing to accomplish certain things.  For example, I would like to have my rig set up to both use a connected CGM as well as NS for data.  If one set of data is available, then don't bother looking for the other - no need for me to pull data from a remote site if I've got it locally via my CGM.  I know we can invoke bash within the 'openaps.ini' file, but that's not really the most elegant way of doing it - especially for beginners.  I don't think that such functionality exists already, but if so, I'd love to take advantage of it.

**Comment by scottleibrand** [comment]
@Spazholio want to checkout out @sulkaharo's new oref0-crun tool in https://github.com/openaps/oref0/pull/205 and see if that does what you want?  If not, please reopen.
