### ISSUE TITLE
Auto resume when suspended for too long

### ISSUE THREAD

**Issue by jasoncalabrese** [openaps/oref0#175]
A common way to more accurately track IOB when disconnected from the pump while swimming, showering, etc is to temp to 0 and then suspend to "lock in the temp"

One of the risks with doing this is you may forget to resume.  To lower that risk we could auto-resume the pump after 30mins or until any 0 temp expires.

Related to this is correctly calculating IOB when pump was suspended without needing to also set a 0 temp.

**Comment by scottleibrand** [comment]
Per https://gitter.im/nightscout/intend-to-bolus?at=57ed497a34a8d5681ccae705, one way we might be able to auto-resume more safely would be to wait until all running temps have expired, it's been 30m+ (configurable), *and* a high-temp is required.  This would avoid the (slight) possibility that we resume basal and then are unable to set a low-temp if needed, and would more generally avoid overriding users' decisions to temp to zero and suspend to shut off delivery for whatever reason.

**Comment by scottleibrand** [comment]
Does anyone feel that this is a feature we really need?  If so, any volunteers to help code (or at least test) it?

**Comment by scottleibrand** [comment]
Closing for lack of interest.  Please reopen if that changes.

**Comment by esteward** [comment]
i have encountered this issue once before and forgot to resume my pump. I would be willing to test it. you do not want me going anywhere near the code.

**Comment by scottleibrand** [comment]
This (https://github.com/openaps/oref0/issues/496) has now been merged to dev: you can `git pull` the latest oref0 dev and add `"unsuspend_if_no_temp": true` to your preferences.json to enable it.  Once enabled, you should keep / make a habit of temping to zero and suspending your pump before your shower, and unsuspending when you reconnect the pump. If you forget to unsuspend it will do so automatically after the zero temp expires.

We should also add these instructions to the OpenAPS docs before we close this issue.

**Comment by danamlewis** [comment]
https://github.com/openaps/docs/pull/907 <-- issue can be closed, this docs PR is created and waiting for the next dev to master release.
