### ISSUE TITLE
Fix AMA oscillation

### ISSUE THREAD

**Issue by scottleibrand** [openaps/oref0#176]
When BG is projected to be just below the low end of the target range with COB, oref0 sets a zero temp, and then after pumphistory refresh sees that predictedBG is now within range and sets the current basal as temp. This continues ad nauseum until BG rises or falls enough that PredBGs are consistent no matter whether a temp is running or not. 

Should adjust the low temp logic to only low temp slightly when eventualBG is only slightly below target range. Maybe also figure out a way to back out the currently running temp from PredBGs.

**Comment by cjo20** [comment]
A possible solution would be to change the logic so that it only changes the temp basal rate (or cancels it) if the current temp basal would result in the eventualBG being outside of the target range.

**Comment by scottleibrand** [comment]
Just pushed a branch that attempts to address this.  Have been running it offline for a few days, and am now pushing it to a couple rigs for testing.  Fixed the one existing unit test affected, and added one more, but not sure how to properly test AMA stuff without bringing in full real-world scenarios.  The oscillation is fairly rare, so planning to just wait for the situation to occur and make sure it does better than before.

**Comment by scottleibrand** [comment]
This is (mostly) fixed in https://github.com/openaps/oref0/pull/200 now.
