### ISSUE TITLE
Enable oref0 to handle existing date format

### ISSUE THREAD

**Issue by mariano42** [openaps/oref0#180]
In dev branch invoking enact/suggested.json returns an error due to missing date fields in the json.  

> Error: date field not found : cannot calculate avgdelta
> Error: date field not found : cannot calculate twodelta
> Could not parse input data: [ReferenceError: twoavg is not defined]

Glitter Response from @scottleibrand
>" your data doesn't have a date field, which some of my new code in dev expects. there is a workaround that involves using the json tool to add a date field to your glucose data, or you can go back to master for now. either way, we should also open an issue to make oref0 handle your date format."

Example glucose.json payload:
[
{
"trend_arrow": "FLAT",
"system_time": "2016-07-27T07:12:57",
"display_time": "2016-07-27T07:18:51",
"glucose": 108
},
{
"trend_arrow": "FLAT",
"system_time": "2016-07-27T07:07:57",
"display_time": "2016-07-27T07:13:51",
"glucose": 109
}
]

**Comment by scottleibrand** [comment]
Do you have a glucose-zoned.json or similar?  It should have a timezone at the end of the display_time etc.

**Comment by cjo20** [comment]
https://github.com/openaps/oref0/pull/168 Might help?

**Comment by mariano42** [comment]
{
"trend_arrow":"FLAT",
"display_time":"2016-07-26T22:23:52-05:00",
"direction" : "Flat",
"system_time":"2016-07-26T05:17:57",
"sgv";120,
"dateString": 2016-07-26T22:23:52-05:00",
"device":"openaps://cgmdex",
"unfiltered": 173600,
"rssi" : 192,
"date" : 1469589832000.0,
"filtered": 181728,
"type" : "sgv",
"glucose" : 120
}

**Comment by scottleibrand** [comment]
So that one does have a valid date field. Which input file are you passing to oref0?

**Comment by scottleibrand** [comment]
@cjo20 Quite possibly.  Merged #168 to dev.  @mariano42 can you pull the latest dev branch of oref0 and try again?

**Comment by scottleibrand** [comment]
Closing this.  Please reopen if #168 didn't fix it.
