### ISSUE TITLE
determine_basal is asking for low temp even if low temp is already running

### ISSUE THREAD

**Issue by MilosKozak** [openaps/oref0#185]
https://github.com/openaps/oref0/blob/dev/lib/determine-basal/determine-basal.js#L301

**Comment by scottleibrand** [comment]
Yes, that is as designed. If BG is low and not rising fast enough, we extend the zero temp.

**Comment by MilosKozak** [comment]
Hmm. It's not good for open loop mode. will think about it

**Comment by scottleibrand** [comment]
I believe the setTempBasal function declines to set a new zero temp until the current one has less than 20m left to run. Are the open loop recommendations bypassing that?

**Comment by MilosKozak** [comment]
i have to decide what to do on android. from my point of view it's wasteful. it needs another connection to pump and especialy for DanaR i'd cancel it and set again.  if low temp expires it's set again by next loop

**Comment by scottleibrand** [comment]
The main reason for extending the zero temp is that you don't know if there will be a next loop, so it's safer to extend the zero temp to a full 30 minutes in case you loose connectivity (or BG data, or anything else).

**Comment by MilosKozak** [comment]
and in open loop asking user to set low temp again while low temp is running is stupid

**Comment by MilosKozak** [comment]
yeah understand the reason but not sure what to prefer

**Comment by scottleibrand** [comment]
I suspect that making the decision whether to extend a function of remaining temp basal duration is a good approach here too. 20 minutes may be too long, but 5 minutes left is probably cutting it too close.

**Comment by cjo20** [comment]
In an open loop, it might be a bit of a pain to have to set more basal rates, but it gives you a better approximation of what oref0 will actually end up doing. Why is the extra pump connection a problem?

**Comment by MilosKozak** [comment]
battery

**Comment by cjo20** [comment]
I don't know about other pumps, but the "Set basal to X" command doesn't involve a lot of communication in medtronic pumps, compared to (say) getting 28 hours of pump history. The pump RF has to be active for longer than the typical loop duration anyway to ensure that things don't cut off early anyway.

**Comment by MilosKozak** [comment]
it's different with DanaR (BT 2.0). I keep every connection as short as possible (and # of connections) to save battery

**Comment by scottleibrand** [comment]
Closing.  Please reopen or open a new issue if there's anything that needs to be done here.
