### ISSUE TITLE
suspend should cancel bolus[wizard][carbs]

### ISSUE THREAD

**Issue by bewest** [openaps/oref0#187]
![image](https://cloud.githubusercontent.com/assets/394179/17543696/497519aa-5e87-11e6-9abb-652579ecaa06.png)

I canceled a bolus (while offline) and redid it, and the carbs register twice.

![image](https://cloud.githubusercontent.com/assets/394179/17543721/8004a076-5e87-11e6-8c6b-34dd2adba1a5.png)

Some note taking... suspend affects bolus, and basal both.

**Comment by scottleibrand** [comment]
@bewest @jasoncalabrese any suggestions on what we should do here?

**Comment by scottleibrand** [comment]
Sounds like this is related to #387
