### ISSUE TITLE
add 'alias edit' ?

### ISSUE THREAD

**Issue by tghoward** [openaps/oref0#23]
Related to a recent discussion on gitter, one way to minimize my editing the openaps.ini file would be to provide a way to tweak current entries. For example, currently I can:
`openaps alias show myalias`
but if I want to tweak it I need to type (or copy paste) the entire string in again with 
`openaps alias add myalias "long string here"`
Perhaps the addition of an `openaps edit myalias` where the string is echo-ed (with 'add'?) on to the command line and the use simply can make a few tweaks, then hit enter?  Can this be universal for reports as well?

**Comment by scottleibrand** [comment]
If this is still of interest, we'll need to open a new issue against https://github.com/openaps/openaps/issues
