### ISSUE TITLE
NS Uploads fail depending upon URL structure

### ISSUE THREAD

**Issue by sjolundjohn** [openaps/oref0#242]
Issue: Inconsistent behaviour of Nightscout upload when you have a trailing '/' in the NS URL in cron or shell.

Suggestion: Automate script to remove '/' if it is added during setup.

IE:
EDIT: https://NSHOST.herokuapp.com/

to

https://NSHOST.herokuapp.com

Background:
I noted that if there is a trailing / in the NS URL (which is very common as it comes this way when you copy/paste from a browser) it can have erratic behaviour on how uploads work.

For example, after using setup script, the "NS-loop" alias (which contains "openaps upload") would not upload treatements/status. However, if I only ran "openaps upload" it worked fine.

I confirmed NIGHTSCOUT_HOST and API_SECRET were the same as cron, with the exception of the trailing slash.

**Comment by scottleibrand** [comment]
Fixed via https://github.com/openaps/oref0/issues/264
