### ISSUE TITLE
feature: cgm-loop.py, integrated with oref0-setup.sh

### ISSUE THREAD

**Issue by PieterGit** [openaps/oref0#243]
I'm working on a cgm-loop python script for a Dexcom G4 connect by USB.

Features I'm thinking of:
- can be started at boot, and runs as a loop for getting the cgm/egv values from the dexcom by usb
- efficient getting the records from the dexcom (caching previous records and merging them in python)
- resource efficient, would like to be able to run this on a pi zero
- perhaps even adding timezones instead of doing that in openaps
- to be integrated with oref0-setup.sh
- will try to get the new evg record as soon as possible. i'll try to sync the pace the sensor uploads the new record to the receiver and get it by usb a few seconds later
- loosely based on https://github.com/openaps/docs/wiki/CGM-Loop-with-openxshareble-scratchpad principles

I'm closing https://github.com/openaps/oref0/issues/218 because it turned out that 218 is not a bug, but a not implemented feature.

**Comment by PieterGit** [comment]
initial version available on https://github.com/PieterGit/oref0/commit/e0d250250f619d4fb67a26ff2c25dde54a9df3ba

implements 1,2 and 3 of the featurelist

**Comment by PieterGit** [comment]
i created a newer version of a python script to get cgm readings from dexcom
see branch https://github.com/PieterGit/oref0/tree/dexusb-cgm-loop2
file: https://github.com/PieterGit/oref0/blob/dexusb-cgm-loop2/bin/oref0-dexusb-cgm-loop.py

**Comment by scottleibrand** [comment]
@PieterGit I'm wondering if it would be best to incorporate this into the cgm-loop framework used for openxshareble in the code I just merge to dev.  Would you like to take the first pass at that, or should we PR your latest branch over to a new branch in the openaps/oref0 repo so we can collaborate there?

**Comment by PieterGit** [comment]
please merge my code to dev. i have tried to sent a pull request but i ended op in a merge hell. I'll refork later. i added basic pebble support as well to the dexusb stuff and working on only getting cgm data once every 5 minutes, exactly when the new cgm value is expected.

**Comment by PieterGit** [comment]
Closing this issue. Most of these features have been implemented with https://github.com/openaps/oref0/pull/282 and https://github.com/openaps/oref0/pull/305
