### ISSUE TITLE
ISF set over 250 (or 255) causes loop to fail 

### ISSUE THREAD

**Issue by ryanchen26** [openaps/oref0#245]
After setting the ISF for midnight to a value of 300 all the APS units in the house failed to loop. Here is what the pump-loop.log looks like when this happens: 

`Starting` pump-loop at Wed Oct 12 19:23:15 PDT 2016:
Listening: .No comms detected
Old settings refreshed
glucose.json newer than temp_basal.json
Temp refreshed
{"carbs":0,"mealCOB":0,"reason":"carb_ratio undefined out of bounds"}
Optional feature Auto Sensitivity enabled.  Could not find specified auto-sens: settings/autosens.json
[SyntaxError: Unexpected end of input]
[]
{"delta":-8,"glucose":137,"short_avgdelta":-6.78,"long_avgdelta":-4.02}
{"duration":0,"rate":0.75,"temp":"absolute"}
Error: could not get current basal rate`

I guess the code needs to check for ISF values over the threshold and assign it to the maximum allowed in order to prevent unexpected loop failure.  By changing the midnight ISF to 250 the aps rigs are looping fine now. 

Scott has indicated that the problem probably lies with decocare.

**Comment by moomoobloo** [comment]
This should be fixed in the latest decocare release:
https://github.com/openaps/decocare/issues/5
