### ISSUE TITLE
oref0-setup skipped mmeowlink?

### ISSUE THREAD

**Issue by tghoward** [openaps/oref0#252]
I don't know bash enough to parse line 198
if openaps vendor add --path . mmeowlink.vendors.mmeowlink 2>&1 | grep "No module"; then

But I'm pretty sure it didn't install mmeowlink for me on a clean run of the script.  Probably want to keep our eyes on this.

**Comment by scottleibrand** [comment]
Maybe try:
```
openaps vendor add --path . mmeowlink.vendors.mmeowlink
openaps vendor add --path . mmeowlink.vendors.mmeowlink 2>&1 | grep "No module" && echo install mmeowlink || echo mmeowlink not needed
```
and paste your results?

**Comment by tghoward** [comment]
Well ... I already installed it manually. So I'm not sure doing anything now would be relevant. But I'll check.

**Comment by tghoward** [comment]
Yes, it sees it just fine now. 
```
# openaps vendor add --path . mmeowlink.vendors.mmeowlink
added mmeowlink.vendors.mmeowlink://
```

**Comment by tghoward** [comment]
The only way to test would be with a fresh run of the script with nothing already installed.

**Comment by scottleibrand** [comment]
So if you have openaps installed but mmeowlink not, it should report "No module", and then go ahead and try to install mmoewlink.  I believe I tested it on a fresh install and it worked, so not sure what state your install was in when you ran it the first time.  Generally with bash it is pretty easy to try basic commands, and then pipe the results of those commands as input to other commands, or use && to run something else if the command returns true, or use || to run something else if it runs false.  Same thing with the `if some-command; then something-else; fi` syntax.  So it's best to break down the problem by running the individual commands if you think something is wrong with a bash script like this.  And you can obviously jump into Gitter to get help if you're not sure what you're seeing.

**Comment by tghoward** [comment]
Ok, thanks. I'll keep my eyes on it with the next install.
