### ISSUE TITLE
Hanging issue with Checking oref0 installation (cat $(which oref0-dex-is-fresh))

### ISSUE THREAD

**Issue by PieterGit** [openaps/oref0#254]
After starting `$~/src/oref0/bin/oref0-setup.sh `  I get a hanging terminal.

```
...
Already up-to-date.
Checking oref0 installation
```

Current code:
```
echo Checking oref0 installation
( cat $(which oref0-dex-is-fresh) | grep mins && grep -q oref0_glucose_since `which nightscout` && oref0-get-profile --exportDefaults 2>/dev/null >/dev/null ) || (echo Installing latest oref0 dev && cd $HOME/src/oref0/ && npm run global-install)
```

it turns out I don't have `oref0-dex-fresh` installed, so `which oref0-dex-fresh` returns emtpy, and therfore ` cat $(which oref0-dex-is-fresh)` hangs indefintely.

**Comment by PieterGit** [comment]
i found a workaround:
```
cd $HOME/src/oref0/ && sudo npm run global-install
````

Note that I needed to add `sudo`  in order to fix permissions errors.

**Comment by PieterGit** [comment]
wouldn't using a `oref0 version` or `oref --version` (showing the `package.json` version number) be a cleaner way of checking the oref0 version?

**Comment by scottleibrand** [comment]
Yes. That would also require doing a new release of oref0, which we're probably due for now. 

In the mean time, want to test https://github.com/openaps/oref0/pull/250 ?

**Comment by PieterGit** [comment]
i can't test anymore, because i installed my workaround.

**Comment by scottleibrand** [comment]
Yeah, that's why I haven't merged it yet. Got any suggestions for a check that would work?

**Comment by scottleibrand** [comment]
@PieterGit Care to test the fix in https://github.com/openaps/oref0/commit/240e244a5928d7e3bd4b104e87026537ff7e9785 and LMK if that works for you?
