### ISSUE TITLE
With medtronic CGM, setup script causes double-wakeup

### ISSUE THREAD

**Issue by oskarpearson** [openaps/oref0#268]
Hi

I've done some experimentation with the new setup script and the Medtronic CGM. It's looking pretty good! I did have to do some minor changes, but still have to coordinate them into useful patches. I must admit I wasn't actually following the documentation instructions either - and found some of the things that I had problems with were already resolved if I just followed the instructions ;) I'll do a slow walkthrough in the next few weeks and sort things out.

One thing that I noticed that might be an issue and probably could do with resolving: because we are adding two devices (pump.ini and cgm.ini) at https://github.com/openaps/oref0/blob/master/bin/oref0-setup.sh#L334-L345 the 'last wake time' that's automatically updated in the pump.ini is not shared with the time in cgm.ini

This means that Decocare will wake the pump device, and then a few moments later when the cgm device is used, it'll re-transmit all the wake-up signals to the pump. Since the wake process can take around 30 seconds on a pi zero, this slows down the loop a bunch.

The quickest solution would be to change references to the cgm device to refer to the pump device, but only if you're using Medtronic. This does lead to inconsistency between Medtronic CGMs and the Dexcom though :(

The other alternatives I can think of:

- It's been on my mind for a while to change the Mmeowlink code to do a quick 'probe' to see if the device is already awake. I think that this reasonably easy. The problem is that this would only fix things for people using mmeowlink. If someone is using a Carelink then they would still encounter the slowdown.
- We could possibly change the decocare code to do the probe-and-check-if-awake step, rather than just doing it in mmeowlink.
- We could change the ini files so that they can refer to the last-wake-time being stored in a 3rd party file (last-wake.ini?). Both cgm.ini and pump.ini would then refer to that filename.

**Comment by scottleibrand** [comment]
I've wanted that probe-and-check feature for quite awhile, because we often see that the pump is already awake from talking to another rig, or from an mmtune run, but decocare/mmeowlink wake it anyway. So I think that is the best general solution. 

Anything I can do to help make it happen?

**Comment by oskarpearson** [comment]
Makes sense - I think it's the most general improvement too.

I'll see if I can get it sorted. Don't think it'll be too big a change to mmeowlink to make it work. I'll try do it there rather than requiring changes to Decocare.

**Comment by Bender1061** [comment]
could this potentially be the issue, with causing a lock up of communications. When a Edison/TI Stick rig's LIPO battery dies. I've had this happen a couple times, where the only way I could get the Pump to start communicating again with the rig was to re-seat the battery on the pump. No amount of restarting/cycle power or changing to a different rig would start the communicating till I re-seated the battery on the pump.   
I've only had this happen a few times, so just wondering if this could be related somehow.

**Comment by scottleibrand** [comment]
I don't think that would be related. This is just a slight inefficiency, where OpenAPS spams the wake up sequence unnecessarily and the pump responds with a "yeah, yeah, I'm awake".

**Comment by scottleibrand** [comment]
I believe this is now fixed with the latest mmeowlink release?

**Comment by oskarpearson** [comment]
Correct - the new mmeowlink checks to see if the pump responds to a 'getmodel' message first. Only if it's unresponsive will it perform the time-consuming wakup process.
