### ISSUE TITLE
Low glucose suspend based on raw CGM data

### ISSUE THREAD

**Issue by scottleibrand** [openaps/oref0#269]
The https://github.com/openaps/oref0/tree/oref0-setup now has the ability to loop based on raw Dexcom CGM data, for example during the 2-hour (re)start period, or when the receiver is showing `???`.  In order to do so safely, it has a maximum threshold, above which raw data will not be used.  In order to maximize safety, @danamlewis and I propose to set the maximum threshold rather low by default, to 120 mg/dL.  That way, if sensor glucose values is low, oref0 will set a low temp if needed, and if SGVs are near target, it will set low or slightly high temps normally, but if SGVs are high, it will not high-temp much until the Dexcom starts reporting trustworthy data again.

Thoughts?

**Comment by jasoncalabrese** [comment]
I've been using it with a higher target, so 120 send safe.  Only issue (I think it's still open), that a high temp could be started, but if above 120 it wouldn't be cancelled.  High temps should be cancelled when data is old or missing.

**Comment by tekrulik** [comment]
120 seems safe to me as well. I like Jason's idea too. I love the idea of being able to loop based on raw - we had a ??? episode in the middle of the night last night and I would have loved for APS to low temp (which it would have based on the raw numbers). Thanks!

**Comment by scottleibrand** [comment]
@jasoncalabrese did you mean "120 sounds safe"?  You wrote "send".

The issue for canceling high-temps on old BG data is https://github.com/openaps/oref0/issues/70, which is still open because it was actually two issues.  We already fixed the issue of canceling high-temps when CGM is calibrating or in ??? state, which I believe would cover this situation.  The remaining question there is whether we need to also cancel high-temps if the data is just too old, but I don't think that's relevant for this issue...

**Comment by jasoncalabrese** [comment]
Yeah, typos, I edited it

**Comment by tim2000s** [comment]
You could also take a leaf out of the Medtronic book of algorithms and have a time limit on low suspend to avoid too long a period low if the data is unreliable?

**Comment by scottleibrand** [comment]
This is now in dev and ready for release soon.  Closing.
