### ISSUE TITLE
When using oref0-setup with MDT cgm, recent-missing-entries doesn't work as expected

### ISSUE THREAD

**Issue by tmecklem** [openaps/oref0#285]
oref0-setup produces two aliases, `prep-pumphistory-entries` and `upload-pumphistory-entries`, that prepare and upload pump history events to Nightscout's entries collection. These pump history events are incorrectly included by the recent-missing-entries report when identifying gaps in Nightscout's entries collection of sensor data.

Since pump history events are also separately uploaded to the treatments collection, these aliases should be removed to prevent uploading to the entries collection.

**Comment by tmecklem** [comment]
I am working this issue here: https://github.com/tmecklem/oref0/tree/remove-ns-upload-pumphistory-entries

**Comment by scottleibrand** [comment]
Thanks for taking this on. It should help with https://github.com/openaps/oref0/issues/274 too.

**Comment by scottleibrand** [comment]
@tmecklem where did you end up with this?  If this got deprioritized, is https://github.com/tmecklem/oref0/tree/remove-ns-upload-pumphistory-entries something someone else could/should pick up and try to run with?

**Comment by tmecklem** [comment]
I think this is handled by #287 and #288. I forgot to update the issue. Sorry!
