### ISSUE TITLE
Better low glucose suspend threshold formula

### ISSUE THREAD

**Issue by scottleibrand** [openaps/oref0#29]
Per discussion with @cjo20 and @eyim, we should use a more intelligent formula at 
https://github.com/openaps/oref0/blob/master/bin/oref0-determine-basal.js#L166
to ensure that threshold drops more slowly than min_bg, and is never less than about 70mg/dL.
Something like https://files.gitter.im/nightscout/intend-to-bolus/gqge/blob maybe.

Note that https://github.com/openaps/oref0/blob/master/lib/profile/targets.js#L29 already ensures that min_bg can't be lower than 90.

**Comment by cjo20** [comment]
That formula in my graph simplifies to `0.2 x min_bg + 56`

**Comment by scottleibrand** [comment]
Fixed with https://github.com/openaps/oref0/commit/e4ac7193b7e6e2d10a521f55bc2a876218cca550
