### ISSUE TITLE
Documentation on classes and data structures?

### ISSUE THREAD

**Issue by ijustlovemath** [openaps/oref0#295]
I'm trying to port OpenAPS's basal/bolus algorithm to another language for use in a glucose simulator. Short of following all of the function calls and tracing out which variables get filled with what data, are there any documents available that describe these things in detail? I'm looking for something akin to a header file from C, which lays out every "struct", its members, and the function declarations that need to be implemented.

I'm not using any of the format conversions (eg Medtronic -> oref0, Medtronic -> Nightscout), and am only looking to port the dosing algorithm you have. If this documentation is not available, that's okay as well.

Thanks!

**Comment by danamlewis** [comment]
@ijustlovemath OpenAPS doesn't use any boluses, so is just recommending basal adjustments. I would read the reference design first (https://openaps.org/reference-design/), which may help with viewing the raw code about the basic pieces (determine-basal.js is key). This may also be a helpful writeup to read: http://openaps.readthedocs.io/en/latest/docs/walkthrough/phase-3/Understand-determine-basal.html

**Comment by ijustlovemath** [comment]
Thanks, I've read the reference design a few times. That second page is extraordinarily helpful. So for a bolus, would you usually just play it by ear according to how many carbs you are about to intake? I'm assuming it's more qualitative rather than there being some sort of formula with which you calculate your bolus rate.

**Comment by danamlewis** [comment]
@ijustlovemath it's a hybrid closed loop, so you do your normal bolus calculation (i.e. with a 1:10 carb ratio and 40 carbs, you would do a 4u bolus for that meal). OpenAPS will read the bolus in and act accordingly with the additional 4u IOB, but it's not going to recommend boluses as an output; OpenAPS only enacts temporary basal rates.

**Comment by ijustlovemath** [comment]
Got it. Sounds good. Thanks, Dana! I'll reopen if I have further questions.

**Comment by danamlewis** [comment]
@ijustlovemath sounds good, also feel free to ping us on Gitter (https://gitter.im/nightscout/intend-to-bolus) if there's anything you're trying to puzzle out from the code that's not clear. 👍
