### ISSUE TITLE
Remove need for environement variables such as NIGHTSCOUT_HOST and API_SECRET and use ns device

### ISSUE THREAD

**Issue by PieterGit** [openaps/oref0#299]
@scottleibrand suggested to remove the environment variables for nightscout and only use the ns device.

Stuff to do:
- integrate ns device in oref0-setup.sh (done)
- remove environment variables uses in oref0-setup.sh 
- remove direct calls to `curl` (e.g. meals-and-carbs) and use `ns` device
- make sure there is only one place for nightscout host and api secret. That would be ( `ns.ini`). Currently it's in the crontab and in the ~/.bash_profile 
 remove nightscout host and api scret in ~/.profile (work in progress)
- ...

**Comment by vincepf** [comment]
I'm not sure if I understand this properly, but in the current setup script here:
```bash
# configure ns
if [[ ! -z "$NIGHTSCOUT_HOST" && ! -z "$API_SECRET" ]]; then
    echo "Removing any existing ns device: "
    killall -g openaps 2>/dev/null; openaps device remove ns 2>/dev/null
    echo "Running nightscout autoconfigure-device-crud $NIGHTSCOUT_HOST $API_SECRET"
    nightscout autoconfigure-device-crud $NIGHTSCOUT_HOST $API_SECRET || die "Could not run nightscout autoconfigure-device-crud"
fi
```
doesn't the autoconfigure-device-crud set up use nightscout.sh, which here:
```bash
autoconfigure-device-crud)
  NIGHTSCOUT_HOST=$1
  PLAIN_NS_SECRET=$2
  API_SECRET=$($self hash-api-secret $2)
  case $1 in
    help|-h|--help)
      setup_help
      exit 0
      ;;
  esac
  # openaps device add ns-get host
  test -z "$NIGHTSCOUT_HOST" && setup_help && exit 1;
  test -z "$API_SECRET" && setup_help && exit 1;
  openaps device add ns process --require "oper" nightscout ns "NIGHTSCOUT_HOST" "API_SECRET"
  openaps device show ns --json | json \
    | json -e "this.extra.args = this.extra.args.replace(' NIGHTSCOUT_HOST ', ' $NIGHTSCOUT_HOST ')" \
    | json -e "this.extra.args = this.extra.args.replace(' API_SECRET', ' $API_SECRET')" \
    | openaps import
  ;;
```

sets up the `ns` device itself as simply a process to use `nightscout.sh`?

**Comment by scottleibrand** [comment]
That is correct. We want to keep nightscout.sh and the ns device, and make the ns-* devices, and bare curl scripts, use it.
