### ISSUE TITLE
Fake openaps reports break auditing of loop via git

### ISSUE THREAD

**Issue by moomoobloo** [openaps/oref0#318]
The loop generated by oref0-setup creates a few files that look like openaps reports but are not actual openaps reports:

- monitor/glucose.json (file is copied from other report files via `cp`)
- monitor/carbhistory.json (output of `curl` redirected to file)
- settings/temptargets.json (output of `curl` redirected to file)

Since these files are not openaps reports, they are not tracked in git, which breaks the ability to debug and audit the loop using git. They should be converted to proper openaps reports.

**Comment by scottleibrand** [comment]
PRs welcome. The curl commands should probably be replaced with calls to the `ns` device. Replacing the `cp` aliases probably would require a new device, either using `copy-fresher` or a new script.

**Comment by scottleibrand** [comment]
Looks like the command to use for the carbhistory.json report would be `openaps use ns shell get treatments find[carbs][\$exists]=true`

**Comment by scottleibrand** [comment]
And `openaps use ns shell get treatments "find[created_at][\$gte]=`date -d \"6 hours ago\" -Iminutes`&find[eventType][\$regex]=Target"` seems to do the trick for settings/temptargets.json
