### ISSUE TITLE
use JS logging library with support for verbosity levels

### ISSUE THREAD

**Issue by moomoobloo** [openaps/oref0#320]
There are many helpful logging and debugging statements throughout the code base which are commented out. Enabling these requires editing the source code and installing from source, which is not always feasible or easy when debugging an already deployed loop. 

This could be better handled by a logging library with support for verbosity levels, which ideally could be set with an environment variable. 

I'm not too familiar with what's available, but this one could be a good option:
https://github.com/visionmedia/debug

**Comment by scottleibrand** [comment]
We'd need a volunteer for this.  I know @sulkaharo @jasoncalabrese and others have expressed interest in doing something better with Papertrail logging (which this would support), but not sure if they have any more interest than I do in actually doing all the plumbing work to make it happen.

**Comment by jasoncalabrese** [comment]
We don't need a js logging library for papertrail, just need to use syslog.  I've used winston before, the main thing it would give us is the ability to customize logging at runtime with env vars or config file.

I've also use bayon, before but it's output is json and I think it only makes sense if you're using logstash

**Comment by scottleibrand** [comment]
Any volunteers to work on this?

**Comment by scottleibrand** [comment]
Closing for lack of interest.  Please reopen if you'd like to work on it.
