### ISSUE TITLE
Autotune: support running on OS X

### ISSUE THREAD

**Issue by scottleibrand** [openaps/oref0#327]
Currently, some of the commands (particularly the `date` syntax) autotune uses are Linux-specific.  We should update it to run on OS X as well.

**Comment by CrushingT1D** [comment]
I can take this one.

**Comment by elnjensen** [comment]
I can take a look at some of this as well. What is likely to be needed to even get going with running to see what breaks?  Install `node.js` presumably and of course git. Anything else obvious for prerequisites that wouldn't be on a Mac?   I'll give it a go and start taking notes, but chime in if you have thoughts.

**Comment by scottleibrand** [comment]
I believe the code side of this was resolved by https://github.com/openaps/oref0/pull/384.  Next step is probably to have some folks do testing, and then update the autotune docs to reflect this method (including https://github.com/openaps/oref0/pull/380#issue-205451776).

**Comment by sulkaharo** [comment]
What's the expected symptoms of failing? I'm running autotune on OS X and haven't noticed any issues

**Comment by danamlewis** [comment]
This was completed a while back and the docs were updated - closing.
