### ISSUE TITLE
Autotune: weekday vs. weekend profiles

### ISSUE THREAD

**Issue by danamlewis** [openaps/oref0#340]
Idea: Maintain different day of week profiles and tune them separately, for people who have markedly different schedules (i.e. every Tuesday is X; or for school days vs non school days). 

Future idea - could do some ML around adjusting for time of day, too. 

But to start, probably assess by day of weeks, or weekday/weekend (by allowing people to input which days go into Bucket A or Bucket B) and tune those days separately.

**Comment by scottleibrand** [comment]
Something like https://github.com/openaps/oref0/blob/autotune-dayofweek/bin/oref0-autotune-dayofweek.sh should do the trick.  Anyone want to test and debug it?  I haven't even tried to run it yet.  :)

**Comment by danamlewis** [comment]
So per @scottleibrand, that looks like it tunes Day 7 (say, Sunday), then on Monday becomes Day 1, etc. etc. and tunes each of those. So ideally, you'd get tuned overall in general before turning on day-of-week autotune...

**Comment by scottleibrand** [comment]
And the way the (very simple) script works, since the day of week files won't exist at first, it will do a full week of regular daily autotuning once you turn it on before switching to day-of-week autotuning.

**Comment by scottleibrand** [comment]
To test this, you'd just need to edit your crontab and replace `( oref0-autotune -d=/home/edison/myopenaps -n=http://diyps.net:2929 && cat /home/edison/myopenaps/autotune/profile.json | json | grep -q start && cp /home/edison/myopenaps/autotune/profile.json /home/edison/myopenaps/settings/autotune.json)` with `~/src/oref0/bin/autotune-dayofweek.sh`

**Comment by scottleibrand** [comment]
To test this, you'd just need to edit your crontab and replace
```
( oref0-autotune -d=/home/root/myopenaps -n=http://yournightscouturl && cat /home/root/myopenaps/autotune/profile.json | json | grep -q start && cp /home/root/myopenaps/autotune/profile.json /home/root/myopenaps/settings/autotune.json)
```
with `~/src/oref0/bin/autotune-dayofweek.sh`

**Comment by scottleibrand** [comment]
If anyone is interested in testing this for further development, please let us know.  Otherwise I may go ahead and close this until/unless someone is interested.

**Comment by drpmorris** [comment]
I'm willing to have a go and see what happens. Might need some pointers on how to actually debug it. I do have a technical background but so far I've just been copy pasting things from the autotune instructions page into the terminal in linux without really understanding what I'm doing!

**Comment by drpmorris** [comment]
Having had a look at the .sh file you mention above, it looks like you need to run it daily to start to build up the profiles. Would it be possible to do two things:
1. add an input argument into the existing script file to take a date on which to run autotune, and then within the script run autotune with that given start date but set the end date as the next day (i.e. start date + 1 day).
2. write a 2nd "wrapper" script which given a global tart date in the past loops over calls to the modified dayofweek.sh incrementing its input start date from the global one right up to (e.g.) yesterday? 

I might try to have a crack at doing that, but I have 0 experience writing bash scripts so it might take me some time. IF anyone looking at this can do it in 5 minutes... I'd be interested to see how its done!

Thanks

**Comment by jodivers** [comment]
Is this still current? Unless Dev 6.0 renders this unnecessary, I would like this distinction.
Maybe my partner and I could get involved.

**Comment by scottleibrand** [comment]
No one has done any work on this since February.  If you'd like to take a stab at it, we'd be happy to point you in the right directions and help when you get stuck.

**Comment by jodivers** [comment]
If I understand correctly, we would run oref0-autotune-dayofweek.sh instead of oref0-autotune.sh and report back on results of the suggested adjustements?

And to do so, the line in the crontab would be:
~/src/oref0/bin/oref0-autotune-dayofweek.sh -d=/home/root/myopenaps -n=http://yournightscouturl

Would that be correct?

**Comment by scottleibrand** [comment]
Without actually trying it to be sure, that sounds about right.

**Comment by jodivers** [comment]
Ok, we will get to it next time Etienne and I can get together, sometime this week.

**Comment by TypeWon** [comment]
If this is still active, I'd be willing to try to help. I'm super new, using Loop, and have very little in the way of technical skills, but if pointed in the right direction, I'm a quick learner and thorough researcher and eager to assist. I have a 7 year old daughter (diagnosed at 3) with a variable schedule. 

Also, perhaps of interest for research on other projects, a son in the process of developing Type1. He has 4 of 5 autoantibodies already at work with a diagnosis expected within 2 years. Would be interesting to see what's happening at this stage.

**Comment by danamlewis** [comment]
There is a day of week option in 0.7.0 now, so closing this issue.
