### ISSUE TITLE
Autotune: Support MDI 

### ISSUE THREAD

**Issue by danamlewis** [openaps/oref0#341]
Several people have asked about autotune for MDI. 

Autotune was originally designed for pump/CGM users...but perhaps could be useful for MDI as well? We need to explore further.

A few known issues to tackle:

- Autotune currently pulls pump profile - so we would need to create a simulated basal profile to mimic the pump profile
- Autotune, because used with pumps, only deals with short term acting insulin. We would need to first calculate that activity curves of various long-acting insulin (there are multiple) or figure out how to approximate as short-acting insulin and convert results again at the end.

(If you're interested in this, please note your interest in helping below, and we can use this issue to track the work/discussion around making it happen).

**Comment by scottleibrand** [comment]
If we set aside the task of properly titrating long-acting basal insulin (which is fairly straightforward to do based on morning fasting BG using a simple iterative titration algorithm), autotune might be able to run on MDI users' data and generate useful estimates of ISF and CSF/CR.  If anyone who is using MDI with Nightscout and entering all of their boluses and carbs wants to give it a try, we can see how well it works for that.

**Comment by aellis13** [comment]
I am on MDI and log all my boluses and carbs to Nightscout. I manufactured a pump profile (basically levemir / (time between doses) becasue I was too lazy to do anything more detailed ). I ran it and the recommend ISF and CSF/CR were identical to the ones in my profile. The basal rate changes match what I would expect.

**Comment by scottleibrand** [comment]
Precisely identical, or just close? How many days of data did you run it on?

**Comment by aellis13** [comment]
I ran 1 month and 1 week. Here is sample running from Jan 1, 2017. They are identical

Parameter      | Current  | Autotune 
-------------------------------------
ISF            | 36.000   | 36.000   
CSF            | n/a      | 7.200    
Carb Ratio     | 5.000    | 5.000

**Comment by scottleibrand** [comment]
Ok, that means it didn't find any insulin or carb treatments in your NS. Perhaps the format is different than it expects? Want to get into Gitter and PM me your NS URL so I can take a look?

**Comment by scottleibrand** [comment]
@aellis13: It looks like the xdrip data source requires some changes to oref0 to support properly.  I just pushed a new branch with the changes necessary to let me run autotune on your data on my machine.  Can you please re-run your oref0 install using the autotune-mdi branch instead of the dev branch and give it another try?  Please hit us up on https://gitter.im/nightscout/intend-to-bolus for interactive troubleshooting if you hit any snags.

**Comment by DunePlodder** [comment]
I am MDI with Humalog & Levemir. I use the Nightscout CarePortal. Please let me know how I can help.

**Comment by danamlewis** [comment]
@DunePlodder great! we actually have a few MDI'ers successfully testing now - follow Phase C instructions (https://github.com/openaps/docs/blob/master/docs/docs/walkthrough/phase-4/autotune.md#phase-c-wip-running-autotune-more-easily-as-an-average-user) , but in steps 2-C and 2D use `autotune-mdi` where it says `dev` in those lines. Let us know in Gitter if you need live help, but also post here if it ends up working well for you.

**Comment by danamlewis** [comment]
Ask: for anyone running with MDI, we also need general feedback about whether it's useful to run it with your basals divided by hours...with the basal tuning feedback it's giving, does it give something that is useful to how you migh translate that back into adjusting your basals? Please give input into what you did, how you did it, etc.

**Comment by danamlewis** [comment]
Feedback for MDI'ers can now also be input into the Google form for general autotune feedback: https://docs.google.com/forms/d/e/1FAIpQLSclFZ6IZipWH1BGhHyRzQcnSQ4T2sUXI6-ea2FrN_4Bas-DJw/viewform?c=0&w=1

**Comment by scottleibrand** [comment]
Closing this for now.  If anyone wants to help work on any enhancements, please feel free to reopen, open a new more specific issue, or even open a pull request.
