### ISSUE TITLE
Autotune: check system locales

### ISSUE THREAD

**Issue by SandraK82** [openaps/oref0#342]
I ran into trouble on a german preinstalled server:
The server was configured to use german locale, thus printing 1.0 as 1,0 
Resulting in Output like:
/usr/local/bin/oref0-autotune-recommends-report: line 110: printf: 1.4: invalid number
or:
Parameter      | Current  | Autotune 
-------------------------------------
ISF            | 30,000   | 0,000    
CSF            | n/a      | 0,000    
Carb Ratio     | 3,000    | 0,000    
Basal Profile  |          |          
  00:00        | 1,000    | 1,000

**Comment by sulkaharo** [comment]
Side note: using US locale in all my Openaps related devices to avoid this, Finnish number formatting also differs from US and breaks things. Haven't recently tested what breaks with non-US formatting.

**Comment by SandraK82** [comment]
@sulkaharo good idea! Just wasn`t expecting that error and took my some time to reconfigure system since the setup was somewhat strange for ubuntu on this one...

**Comment by scottleibrand** [comment]
Added a note to the docs to address this: https://github.com/openaps/docs/commit/6975dae64a305cba0026f94b081f5d4e9c200b8c

**Comment by scottleibrand** [comment]
If anyone would like to take on the task of updating oref0-autotune.sh to check locales and error out if they're incorrect, PRs welcome.

**Comment by LynneRB** [comment]
Maybe this is the wrong place to put this, but possibly add the tz part for the "average user" section.  Some reports would not work because my timezone was off. I am using Google VM, average user.

**Comment by scottleibrand** [comment]
@LynneRB would you mind putting in a PR with the changes you'd suggest?

**Comment by LynneRB** [comment]
Sure.

**Comment by scottleibrand** [comment]
If anyone is interested in fixing this in oref0-setup, please speak up.  Otherwise I'll probably go ahead and close this, since we noted it in the docs already.

**Comment by PieterGit** [comment]
Fixed with https://github.com/openaps/oref0/pull/563
Set LC_NUMERIC=en_US.UTF-8 in oref0-autotune-recommends-report.sh
