### ISSUE TITLE
Autotune: carb Ratio limit

### ISSUE THREAD

**Issue by SandraK82** [openaps/oref0#343]
oref0-autotune-prep.js limits carb ratio hard to >= 3.0 on line 54.
Mmaybe this should be made configurable, as I ran into trouble as my base carb ratio is currently 3.0 and autotune suggested 2.741 for one day from my dataset.
Worked around it by setting Limit to >=2, an optional cmdline flag would be helpfull

**Comment by scottleibrand** [comment]
Just relaxed that to 2.0 in https://github.com/openaps/oref0/commit/7c4538627ad4307c27c2db44def54818419a66aa

The original check was for looping based off of pump data (where anything less than 3 was impossible): I don't think there's any reason to be as stringent for autotuning.
