### ISSUE TITLE
autotune time display doesn't mention timezone

### ISSUE THREAD

**Issue by tynbendad** [openaps/oref0#345]
there's no mention in the autotune output (or input) about what timezone the basal times are reported in.  i had assumed it was local time according to my nightscout setup, but on looking at the results i think its more likely to be GTC?  if so that should at least be mentioned. better would be to have something in profile.json that sets the timezone, so that the times match what are set on the loop...

**Comment by scottleibrand** [comment]
I believe it's actually local time on the box you're running autotune.  Can you try setting the VM's timezone to match your pump with `sudo dpkg-reconfigure tzdata` and see if that corrects it?  If so, we could just add a note to the docs to have people change their VM timezone to match their rig before running autotune...

**Comment by scottleibrand** [comment]
Added a note to the docs to address this: https://github.com/openaps/docs/commit/6975dae64a305cba0026f94b081f5d4e9c200b8c

**Comment by tynbendad** [comment]
yes, that command does fix it on google cloud vm.  i also tried ubuntu virtualbox and it didn't need it, already had the correct local time, and the results matched after fixing the timezone on google cloud.
