### ISSUE TITLE
Autotune profile entries

### ISSUE THREAD

**Issue by LynneRB** [openaps/oref0#346]
It is possible to leave out minutes. For example:
{
  "min_5m_carbimpact": 3,
  "dia":  your_dia,
  "basalprofile": [
    {
      "i": 0,
      "start": "00:00:00",
      "rate": your_basal
    },
    {
      "i": 1,
      "start": "00:30:00",
      "rate": your_basal
    },
    {
      "i": 2,
      "start": "21:00:00",
      "rate": your_basal
    }
  ],
  "isfProfile": {
    "sensitivities": [
      {
        "i": 0,
        "start": "00:00:00",
        "sensitivity": your_isf,
        "offset": 0,
        "x": 0,
        "endOffset": 1440
      }
    ]
},
"carb_ratio":  your_ic_ratio,
"autosens_max": 1.2,
"autosens_min": 0.7
}

Not sure if it is listed correctly from me here, it cut off my paste.

**Comment by danamlewis** [comment]
(Resolved)
