### ISSUE TITLE
Improve realibility of ww pump / oref0-subg-ww-radio-parameters.sh (especially with TI USB)

### ISSUE THREAD

**Issue by PieterGit** [openaps/oref0#354]
The current `oref0-subg-ww-radio-parameters.sh` script assumes several things that are wrong.
E.g. if `/dev/spidev5.1` exists (e.g. on an Edison board), it assumes the pump can be reached there.
Improvement: use `port` as specified in `pump.ini`

The `oref0-subg-ww-radio-parameters.sh`  script also assumes that the serial port exists. I've seen case in which (for some mysterious reason) the `/dev/mmeowlink` (udev symlink) was gone.  The script now calls `oref0-reset-usb` if it cannot find a working character device on the port after a minute.

**Comment by PieterGit** [comment]
@ceben80

To give it a try use:
```
cd ~/src
mv oref0 oref0.default
git clone https://github.com/PieterGit/oref0.git
cd oref0
git checkout devww
sudo npm install -g .
```

and remove `oref0` directory in future, and use `mv oref0.default oref0` once this fix has been merged

**Comment by PieterGit** [comment]
@ceben80 ,  @scottleibrand  , @oskarpearson 

Is still have some issues with the serial connection and the TI-stick

dmesg lists
```
[ 1113.667683] usb 1-1.2: Product: subg_rfspy
[ 1113.667695] usb 1-1.2: Manufacturer: Nightscout
[ 1113.667707] usb 1-1.2: SerialNumber: 000002
[ 1113.670394] cdc_acm 1-1.2:1.0: ttyACM0: USB ACM device
[ 1276.906168] cdc_acm 1-1.2:1.0: failed to set dtr/rts
[ 1285.126119] cdc_acm 1-1.2:1.0: failed to set dtr/rts
[ 1293.264857] cdc_acm 1-1.2:1.0: failed to set dtr/rts
[ 1293.523367] cdc_acm 1-1.2:1.0: failed to set dtr/rts
[ 1293.569368] usb 1-1.2: USB disconnect, device number 8
[ 1293.804862] usb 1-1.2: new full-speed USB device number 9 using dwc_otg
[ 1293.884847] usb 1-1.2: device descriptor read/64, error -71
[ 1294.074896] usb 1-1.2: device descriptor read/64, error -71
[ 1294.264890] usb 1-1.2: new full-speed USB device number 10 using dwc_otg
[ 1294.344944] usb 1-1.2: device descriptor read/64, error -71
[ 1294.534898] usb 1-1.2: device descriptor read/64, error -71
[ 1294.724911] usb 1-1.2: new full-speed USB device number 11 using dwc_otg
[ 1295.144875] usb 1-1.2: device not accepting address 11, error -71
[ 1295.224880] usb 1-1.2: new full-speed USB device number 12 using dwc_otg
[ 1295.644908] usb 1-1.2: device not accepting address 12, error -71
[ 1295.645054] usb 1-1-port2: unable to enumerate USB device
```

and the pump-log lists: 
```
Your TI device is located at /dev/mmeowlink
+ cd /home/pi/src/subg_rfspy/tools
+ ./reset.py /dev/mmeowlink
retry 0
retry 1 4f
RileyLink OK
retry 2 4f4b
Version: subg_rfspy 0.8
OK
+ sleep 2
```
Another part of the pump log
```
+ echo Your TI device is located at /dev/mmeowlink
Your TI device is located at /dev/mmeowlink
+ cd /home/pi/src/subg_rfspy/tools
+ ./reset.py /dev/mmeowlink
RileyLink OK
Version: subg_rfspy 0.8
OK
+ sleep 2
Starting pump-loop at Sun 29 Jan 00:02:17 CET 2017:
Traceback (most recent call last):
  File "/usr/local/bin/mmeowlink-any-pump-comms.py", line 15, in <module>
    app.run(None)
  File "/usr/local/lib/python2.7/dist-packages/decocare/helpers/cli.py", line 113, in run
    self.prelude(args)
  File "/home/pi/src/mmeowlink/mmeowlink/cli/any_pump_comms_app.py", line 28, in prelude
    super(AnyPumpCommsApp, self).prelude(args)
  File "/home/pi/src/mmeowlink/mmeowlink/cli/base_mmeowlink_app.py", line 26, in prelude
    self.link = link = LinkBuilder().build(args.radio_type, port)
  File "/home/pi/src/mmeowlink/mmeowlink/link_builder.py", line 16, in build
    return SubgRfspyLink(port)
  File "/home/pi/src/mmeowlink/mmeowlink/vendors/subg_rfspy_link.py", line 55, in __init__
    self.open()
  File "/home/pi/src/mmeowlink/mmeowlink/vendors/serial_interface.py", line 32, in open
    self.check_setup()
  File "/home/pi/src/mmeowlink/mmeowlink/vendors/subg_rfspy_link.py", line 72, in check_setup
    self.serial_rf_spy.sync()
  File "/home/pi/src/mmeowlink/mmeowlink/vendors/serial_rf_spy.py", line 121, in sync
    raise CommsException("Could not get subg_rfspy state or version. Have you got the right port/device and radio_type?")
mmeowlink.exceptions.CommsException: Could not get subg_rfspy state or version. Have you got the right port/device and radio_type?
subg-ww-radio-parameters:running /usr/local/bin/oref0-subg-ww-radio-parameters for max 30 seconds
+ echo 'Searching for pump device: '
Searching for pump device:
+ loop=0
++ oref0-get-pump-device
+ SERIAL_PORT=/dev/mmeowlink
+ echo

+ echo Your TI device is located at /dev/mmeowlink
Your TI device is located at /dev/mmeowlink
+ cd /home/pi/src/subg_rfspy/tools
+ ./reset.py /dev/mmeowlink
RileyLink OK
Version: subg_rfspy 0.8
OK
+ sleep 2
```

It seems to hang on this line `./change_setting.py $SERIAL_PORT 0x06 0x00          # CHANNR `

Any suggestions?

**Comment by PieterGit** [comment]
I also tried to set `export RFSPY_RTSCTS=0` and upgraded to https://github.com/ps2/subg_rfspy/tree/dev but nothing seems to work. Then I plugged the TI-USB stick in my rig that uses most of the master/official releases (from quite a while back). That works without problems.
I'll dig into it later, but help is appreciated.

**Comment by ceben80** [comment]
@PieterGit I don't use the TI, I'm running either with ERF or the Explorer Board, should I test with this environment?

**Comment by PieterGit** [comment]
@oskarpearson thanks a lot for helping me out. I'm using TI USB. I'll try to increase the wait or remove the reset. I currently cannot test because the pump and rig are not here

@ceben80 : this patch also creates a `oref0-get-pump-device` that will get the pump device from the users `pump.ini`. That's a lot better than current implementation of `oref0-find-ti`. 

@oskarpearson and @ceben80 can you review this loop https://github.com/openaps/oref0/pull/357/files#diff-95a0fa728e5a707dacbfc72eb5eb7f50R26 . The `oref0-reset-usb` only possibly fixes things if the TI-stick is connected to USB.  Is it possible to make a serial/usb reset command that will work for all the ERF/SRF/TI USB/etc. for WW pump users?

**Comment by PieterGit** [comment]
Removed the reset for now. See if that makes the rig stable. Will follow up later

**Comment by PieterGit** [comment]
Without reset.py was stable for whole afternoon, which makes me believe that the reset.py on a TI USB was the culprit.

I'm now trying with first a oref0-reset-usb if it fails after a minute, and if it still fails after the second minute a reset.py

```
# We'l try to find the TI device
# If it does not exist we will use oref0-reset usb first minute (12*5 seconds) to get it back up
# If it does not exist after two minutes we'll issue a reset.py
# If it fails after 150 seconds it will exit with error status code
loop=0
until SERIAL_PORT=`oref0-get-pump-device`; do
   if  [[ "$loop" -gt "11" ]]; then
      sudo oref0-reset-usb
      # wait a bit more to let everything settle back
      sleep 10
   fi
   if [[ "$loop" -gt "23" ]]; then
      # Reset to defaults
      ./reset.py $SERIAL_PORT
      sleep 10
   fi
   if [[ "$loop" -gt "30" ]]; then
      # exit the script with an error status
      exit 1
   fi
   sleep 5
   ((loop=loop+1))
done
```

I think I'll use the oref0-reset-usb when you use a TI USB. If you're using a spidev use `reset_spi_serial.py`
and otherwise use the `reset.py`. Is that a good direction?

@oskarpearson What's the difference between `reset.py` and  the `reset_spi_serial.py`

**Comment by PieterGit** [comment]
@cjo20 thanks for your review in the pull request https://github.com/openaps/oref0/pull/357#issuecomment-275882969

I don't like to use the serial device as a parameter, because then the mmtune alias needs to use that 'hardcoded' path instead of getting it from the `pump.ini` settings file. I don't like duplicating (volatile) data, when the correct source is the `port` in `pump.ini`. Adding the logic to a script outside of `subg-ww-radio-parameter` is possible but I think it's beneficial to only have one script for WW pump users.

I improved the subg-ww-radio-parameter script to also work on edison boards and non-usb connections.

I currently added a TI_USB environement variable to `oref0-subg-ww-radio-parameters.sh` to know whether `oref0-reset-usb` might be usefull. 
This is simalar to the `export RFSPY_RTSCTS=0` line. 
Question: doest the  only applies to ERF or also to TI USB or other TI-connections? 
Without ` RFSPY_RTSCTS=0` I see on a TI USB:
```
+ echo Your TI device is located at /dev/mmeowlink
Your TI device is located at /dev/mmeowlink
+ cd /home/pi/src/subg_rfspy/tools
+ sleep 2
+ ./change_setting.py /dev/mmeowlink 0x06 0x00
retry 1 38 (Do you need to run 'export RFSPY_RTSCTS=0' first?)
RileyLink OK
retry 2 4f4b (Do you need to run 'export RFSPY_RTSCTS=0' first?)
Version: subg_rfspy 0.8
Traceback (most recent call last):
  File "./change_setting.py", line 22, in <module>
    if ord(resp) == 1:
TypeError: ord() expected a character, but string of length 14 found
```

@ceben80 (or others with a WW pump): could you give it a test and tell me if it's good enough to merge to dev

**Comment by cjo20** [comment]
@PieterGit My comment on the pull request describes a way of using your script to determine the device path using your script and then passing it to `subg-ww-radio-parameters`  on the command line.

**Comment by PieterGit** [comment]
Updated the scripts quite a bit. Please test with WW-pump (and with/without TI USB).

**Comment by ceben80** [comment]
@PieterGit just re-flashed an edision (due to my bt tethering trial yesterday which didn't work reliable) and setup new with your 'devww' descripted above, will give feedback I've got issues...

**Comment by ceben80** [comment]
@PieterGit I got this message "No such file or directory"

Starting pump-loop at Wed Feb 1 16:51:05 CET 2017:
subg-ww-radio-parameters:bash: /usr/local/bin/oref0-subg-ww-radio-parameters-timeout: No such file or directory
mmtune: pump://JSON/mmtune/monitor/mmtune.json
reporting monitor/mmtune.json
"868.534", 5, -72  Listening: ............

**Comment by PieterGit** [comment]
@ceben80 you used oref0-setup.sh I guess with the new setup.  Somehow the patching of `openaps.ini` does not seem to work. I'll dig into it later tonight.  Replace `/usr/local/bin/oref0-subg-ww-radio-parameters-timeout` with `oref0-subg-ww-radio-parameters.py --resetusb` if you have a TI USB. Or replace it with `oref0-subg-ww-radio-parameters.py` otherwise.

**Comment by PieterGit** [comment]
@ceben80 could you retest? What setup do you use?

**Comment by ceben80** [comment]
@PieterGit yesterday I completely re-install (flash) my Breakout Eddie and run the oref0-setup

**Comment by ceben80** [comment]
@PieterGit maybe anything wrong I did, now again your above instructions

```
cd ~/src
mv oref0 oref0.default
git clone https://github.com/PieterGit/oref0.git
cd oref0
git checkout devww
sudo npm install -g .
```
...but got the same

```
Starting pump-loop at Thu Feb 2 07:26:46 CET 2017:
subg-ww-radio-parameters:bash: /usr/local/bin/oref0-subg-ww-radio-parameters-timeout: No such file or dire                   ctory
mmtune: pump://JSON/mmtune/monitor/mmtune.json
reporting monitor/mmtune.json
"868.486", 2, -95  Listening: .
```

**Comment by ceben80** [comment]
I have tested running `openaps mmtune`

```
edison@eddie:~/myopenaps$ openaps mmtune
subg-ww-radio-parameters:2017-02-06 19:41:05,066 DEBUG Parsing ./pump.ini
2017-02-06 19:41:05,075 DEBUG Serial device (port) for pump is: /dev/ttyMFD1
2017-02-06 19:41:05,076 DEBUG env RFSPY_RTSCTS=0
2017-02-06 19:41:05,077 DEBUG excuting ['oref0-subg-ww-radio-parameters', '/dev/ttyMFD1', '--resetpy']
+ echo

+ echo The CC111x is located at /dev/ttyMFD1
The CC111x is located at /dev/ttyMFD1
+ cd /home/edison/src/subg_rfspy/tools
+ case "$2" in
+ ./reset.py /dev/ttyMFD1
RileyLink OK
Version: subg_rfspy 0.8
OK
+ sleep 2
+ exit 0
2017-02-06 19:41:07,272 DEBUG script exited with 0
2017-02-06 19:41:07,273 DEBUG sleeping for 30 seconds
2017-02-06 19:41:37,305 DEBUG excuting ['oref0-subg-ww-radio-parameters', '/dev/ttyMFD1']
+ echo

+ echo The CC111x is located at /dev/ttyMFD1
The CC111x is located at /dev/ttyMFD1
+ cd /home/edison/src/subg_rfspy/tools
+ case "$2" in
+ ./change_setting.py /dev/ttyMFD1 0x06 0x00
RileyLink OK
Version: subg_rfspy 0.8
SUCCESS
+ sleep 0.5
.
.
.
```
looks good to me

**Comment by PieterGit** [comment]
@scottleibrand can you merge this to dev? I will try to find out if there are other ways besides oref0-reset-usb for TI USB stick, but this branch:
- checks out ps2 version subg_rfspy if it's not there
- reads the pump devices from pump.ini instead of vague logic

I think this will make WW pump work on master with oref0-setup.sh

Thanks to @ceben80 for helping me out with testing on an Explorer board with ERF

**Comment by PieterGit** [comment]
Please don't do discussion in this issue, but use the pull request. It's not a good idea to have an issue and a pull request. Discussion is at the pull request: https://github.com/openaps/oref0/pull/357
