### ISSUE TITLE
Implement mmtune speedup in oref0-setup loop

### ISSUE THREAD

**Issue by cjo20** [openaps/oref0#360]
Should be a simple change. Currently have this working locally in a non-`oref0-setup` loop using:

`cp mmtune.json mmtune_old.json; openaps use pump mmtune > mmtune.json`. It'll look for `mmtune_old.json` in the root of the openaps directory.

**Comment by scottleibrand** [comment]
This was implemented in https://github.com/openaps/oref0/commit/9eaf97d1
