### ISSUE TITLE
MDT CGM interfering with Temp Basal collection

### ISSUE THREAD

**Issue by tim2000s** [openaps/oref0#364]
When looping, "use pump read_temp_basal" fails following a "use CGM iter_glucose_hours 24.0". This happens consistently, until an mature runs, following which the loop runs successfully.

pump-loop.log output:

```
Starting pump-loop at Sun Jan 29 15:13:14 GMT 2017:
Radio ok, Listening: .No pump comms detected from other rigs
cgm://JSON/iter_glucose_hours/monitor/cgm-mm-glucosedirty.json
tz://JSON/rezone/monitor/glucose.json
reporting monitor/glucose.json
Profile less than 60m old
glucose.json newer than temp_basal.json
Temp refreshError, retrying
``` 

When run consecutively manually, they seem to function with no problems.

**Comment by cjo20** [comment]
It's worth looking in `/var/log/syslog` to see if it says why it failed
