### ISSUE TITLE
Autotune: Automatically handle pumpprofile.json/autotune.json creation

### ISSUE THREAD

**Issue by jessiepusateri** [openaps/oref0#373]
In the Phase C setup, the following steps:

- E. Create a pumpprofile.json that is the same as your profile.json. On the command line run: cp profile.json pumpprofile.json
- F. Create a third file from the command line by running: cp profile.json autotune.json

should be handled in the bash script. If the files are not present, it should prompt you "The following files are missing: pumpprofile.json, autotune.json. Would you like to them to be created from the profile.json file? (Y/N)".

Yes will automatically do the copying/creation for you.

**Comment by danamlewis** [comment]
(Just for reference, if anyone wants to jump in on this, the additions will be similar to the type of thing I just added to oref0-setup.sh recently, see: https://github.com/openaps/oref0/pull/382/files - happy to help if someone wants to kickstart this)

**Comment by danamlewis** [comment]
I believe this is resolved via https://github.com/openaps/oref0/pull/392, so closing this as an issue.
