### ISSUE TITLE
COB Decay Issues

### ISSUE THREAD

**Issue by JELCRAWFORD** [openaps/oref0#390]
COB decay problems - see images and related treatment info:

![jan 4th - cob issues 1](https://cloud.githubusercontent.com/assets/24684595/22681474/a95c132e-ecca-11e6-8302-2061827b8dd8.PNG)
![image 1 - jan 4th](https://cloud.githubusercontent.com/assets/24684595/22681479/abf21c82-ecca-11e6-8b2d-059760860544.png)
![image 2 - jan 4th](https://cloud.githubusercontent.com/assets/24684595/22681483/b6446a5a-ecca-11e6-878d-d076b0634228.png)

2nd data set:
![jan 3rd cob issues](https://cloud.githubusercontent.com/assets/24684595/22681486/c59f66da-ecca-11e6-8714-fe391124d731.PNG)
![treatments jan 3](https://cloud.githubusercontent.com/assets/24684595/22681489/c81c8a78-ecca-11e6-9bcf-36d17aec1db0.png)

**Comment by JELCRAWFORD** [comment]
We have ongoing discrepancies with COB display seeming to have much higher COB than should be onboard.  This does not seem to be related to double entries.

**Comment by scottleibrand** [comment]
Had a troubleshooting session with @JELCRAWFORD and @jmcrawford, and it looks like they're seeing this due to mis-sorted treatments.  Opened https://github.com/openaps/oref0/pull/404 to address that, and set them up to run it to test and see if it fixes the issue.

**Comment by JELCRAWFORD** [comment]
HI Scott - I think this is working fine - we have had only 1 incident that we saw an increase from zero  to 20 carbs around 11pm at night - we have not noticed it any other than that, and meal cob seems to be consistently accurate.

**Comment by scottleibrand** [comment]
Thanks. Merged #404
