### ISSUE TITLE
autotune does not use api-secret when needed

### ISSUE THREAD

**Issue by beached** [openaps/oref0#397]
I have a nightscout setup that is in default deny mode and needs an api-secret to view data.  I cannot see how or any references to it in the autotune code when calling curl to retrieve data.  I am not sure the approach, but seems this may be tangentially related to #299

**Comment by gregtcm** [comment]
This showed up for me with this error:
```
src/oref0/lib/autotune-prep/categorize.js:21
        var glucoseData = opts.glucose.map(function prepGlucose (obj) {
                                       ^

TypeError: opts.glucose.map is not a function
    at categorizeBGDatums (/home/gnu/src/oref0/lib/autotune-prep/categorize.js:21:40)
```

**Comment by PieterGit** [comment]
This is fixed with https://github.com/openaps/oref0/pull/563
Autotune now accepts: 
- no authentication (readable Nightscout)
- hashed API_SECRET. API_SECRET must be set as environment variable to the autotune script.
- token based authentication, API_SECRET starts with `token=hash`

**Comment by lgruen** [comment]
Maybe my version of curl (7.54.0) on Mac OS is weird, but I had to change the `ns-get` script from
`CURL_AUTH='-H "api-secret: ${API_SECRET}"'`
to
`CURL_AUTH="-H api-secret:${API_SECRET}"`
for this to work. As mentioned in the previous comment, `API_SECRET` needs to be set to the _hashed_ API_SECRET, which can be generated using
`nightscout hash-api-secret $UNHASHED_API_SECRET`

**Comment by mountrcg** [comment]
In oref0-autotune.sh I have tried to set environment variable API_SECRET using the hash or the token:
```
API_SECRET=32ea1df04----------------e84f2750
API_SECRET=token=autotune-5f--------a8
```
both don't work on a Nightscout site with `AUTH_DEFAULT_ROLES` set to `denied`. Any ideas how to get it to work on a Mac?

**Comment by mountrcg** [comment]
found solution. had to specify it in osx environment variables
`export API_SECRET=token=autotune-5f--------a8`
