### ISSUE TITLE
BT tethering and looping stops

### ISSUE THREAD

**Issue by Kdisimone** [openaps/oref0#406]
I *think* the issue starts when the rig comes off her school wifi and onto her iPhone via BT tether.  Rig stops looping.  Won't restart looping unless a manual reboot is performed.  Tonight I manage to pull this off the rig after it had been stalled for about 4 or 5 hours while she was at track.  Rig was connected to her hotspot, on her body the whole time while at track.  The rig did not come off hotspot for our home wifi when she got home, and was not looping.  I was able to pull this off the pump log

![img_3473](https://cloud.githubusercontent.com/assets/12402160/23005879/81e6c650-f3b3-11e6-91b3-296e7963549d.PNG)

Then I rebooted the rig and just before the pump started rolling again...i copied this off...

```
Starting pump-loop at Wed Feb 15 15:52:15 PST 2017:
Traceback (most recent call last):
  File "/usr/local/bin/mmeowlink-any-pump-comms.py", line 15, in <module>
    app.run(None)
  File "/usr/local/lib/python2.7/dist-packages/decocare/helpers/cli.py", line 113, in run
    self.prelude(args)
  File "/usr/local/lib/python2.7/dist-packages/mmeowlink/cli/any_pump_comms_app.py", line 28, in prelude
    super(AnyPumpCommsApp, self).prelude(args)
  File "/usr/local/lib/python2.7/dist-packages/mmeowlink/cli/base_mmeowlink_app.py", line 26, in prelude
    self.link = link = LinkBuilder().build(args.radio_type, port)
  File "/usr/local/lib/python2.7/dist-packages/mmeowlink/link_builder.py", line 16, in build
    return SubgRfspyLink(port)
  File "/usr/local/lib/python2.7/dist-packages/mmeowlink/vendors/subg_rfspy_link.py", line 55, in __init__
    self.open()
  File "/usr/local/lib/python2.7/dist-packages/mmeowlink/vendors/serial_interface.py", line 23, in open
    raise AlreadyInUseException("%s already in use" % self.device)
mmeowlink.vendors.serial_interface.AlreadyInUseException: /dev/spidev5.1 already in use
Starting pump-loop at Wed Feb 15 16:20:16 PST 2017:
Traceback (most recent call last):
  File "/usr/local/bin/mmeowlink-any-pump-comms.py", line 15, in <module>
    app.run(None)
  File "/usr/local/lib/python2.7/dist-packages/decocare/helpers/cli.py", line 113, in run
    self.prelude(args)
  File "/usr/local/lib/python2.7/dist-packages/mmeowlink/cli/any_pump_comms_app.py", line 28, in prelude
    super(AnyPumpCommsApp, self).prelude(args)
  File "/usr/local/lib/python2.7/dist-packages/mmeowlink/cli/base_mmeowlink_app.py", line 26, in prelude
    self.link = link = LinkBuilder().build(args.radio_type, port)
  File "/usr/local/lib/python2.7/dist-packages/mmeowlink/link_builder.py", line 16, in build
    return SubgRfspyLink(port)
  File "/usr/local/lib/python2.7/dist-packages/mmeowlink/vendors/subg_rfspy_link.py", line 55, in __init__
    self.open()
  File "/usr/local/lib/python2.7/dist-packages/mmeowlink/vendors/serial_interface.py", line 23, in open
    raise AlreadyInUseException("%s already in use" % self.device)
mmeowlink.vendors.serial_interface.AlreadyInUseException: /dev/spidev5.1 already in use
```

**Comment by Kdisimone** [comment]
Hoping for maybe a cron fix so that if this error happens, something resets or reboots automatically rather than hanging.

**Comment by theunnaturallog** [comment]
![before](https://cloud.githubusercontent.com/assets/24258275/23007847/438bfd64-f3d9-11e6-9fcf-e2c72bda7821.png)
![after](https://cloud.githubusercontent.com/assets/24258275/23007849/498b712c-f3d9-11e6-813a-c27933e27a54.png)

**Comment by theunnaturallog** [comment]
First picture shows when it initially disconnects, second picture shows that it stopped trying to connect until I got home and manually rebooted.

**Comment by ceben80** [comment]
Today before 3 hours my rig was bt hanging, same errors as posted above.
Only a `reboot`did solve this issue

my Wifi is completetly switch off in `/etc/networks/interfaces`
I want to use bt only!

```
root@eddie-eb:~# tail -n 300 /var/log/openaps/network.log | grep "getting bnep0

Error, connecting BT to D0:87:E2:1D:4E:57, getting bnep0 IP
Error, connecting BT to D0:87:E2:1D:4E:57, getting bnep0 IP
Error, connecting BT to D0:87:E2:1D:4E:57, getting bnep0 IP
Error, connecting BT to D0:87:E2:1D:4E:57, getting bnep0 IP
Error, connecting BT to D0:87:E2:1D:4E:57, getting bnep0 IP
Error, connecting BT to D0:87:E2:1D:4E:57, getting bnep0 IP
```

**Comment by ceben80** [comment]
suggestion for cron line

```
* * * * * if (tail -n 50 /var/log/openaps/network.log | grep "Error, connecting BT to"); then reboot; fi
```

**Comment by scottleibrand** [comment]
No, don't use that cron line, or you'll reboot continuously whenever your Internet drops. That error is perfectly normal to see once or twice as the rig transitions between networks. Sounds like you want some sort of count of the number of times it shows up in the logs.

**Comment by ceben80** [comment]
Okay, but how to fix, my rig was hanging today for 3 hours, didn't come back, only rebooting solves the issue?

**Comment by scottleibrand** [comment]
I would do something like a ` | grep -c Error` count piped through a > 10 comparison or something like that.

**Comment by ceben80** [comment]
that'll be a good idea, will try it later, thx Scott

**Comment by jbwittmer** [comment]
I'm seeing the same issue intermittently when the rig switches between Wifi and BT and back.  But not each time.  The switch between Wifi and BT and back to Wifi executes reliably.    At times (but not all the time) we end up with a `mmeowlink.vendors.serial_interface.AlreadyInUseException: /dev/spidev5.1 already in use` error.  I haven't been able to figure out why it happens sometimes but not all the time.  Would love to hear if someone comes up with a solution.  It won't happen for days at a time, and it happened twice today.  Irritating.

**Comment by scottleibrand** [comment]
Can y'all please test out https://github.com/openaps/oref0/pull/411 and see if it is a suitable workaround?

We might also want to try adjusting oref0-online to not fully restart networking every time it loses wifi, and see if that reduces the prevalence of this problem...

**Comment by ecc1** [comment]
Just noting that with these lines in /etc/network/interfaces:

allow-hotplug bnep0
iface bnep0 inet dhcp

the rig will automatically get an IP address from the phone after bt-pan succeeds.  I think this is more reliable than explicit calls to dhclient in the oref0-online.sh script.

**Comment by ecc1** [comment]
Another possible problem is at line 50 in oref0-online.sh.  If you bring up bnep0 when there's already a default route via the wlan0 interface, you won't get a route via bnep0 (because you can only have one default route and dhclient won't replace it AFAICT).  So you'd have to get rid of the wlan0 route first (either by bringing down the wlan0 interface or with an explicit route flush command), and then redo the DHCP for bnep0 so it picks up that default route.

**Comment by danamlewis** [comment]
Has this been resolved by the recent changes to oref0-online in dev; or is this still an ongoing issue?

**Comment by AllyCat09** [comment]
I believe it has been resolved.  We still get periodic slow BT connections, but I am fairly certain that is unrelated to openaps at this point.

**Comment by danamlewis** [comment]
Ok. Given all the work done in oref0-online that resolves much of this, closing the issue. if there are more specifics, please open a new issue to address any specifics that need to continue to be worked on.
