### ISSUE TITLE
IOB for bolus not showing

### ISSUE THREAD

**Issue by Kdisimone** [openaps/oref0#410]
Twice now in the last four days, it appears that a meal bolus has incorrectly been read or categorized as an unbolused event when uploaded to NS.  Current situation:  22g meal.  entered into pump through bolus wizard and 2.75 units given.  NS only showing 22g, no bolus.

Based on the IOB pill and OpenAPS pill, it appears as though they have registered the bolus.

![110__0_](https://cloud.githubusercontent.com/assets/12402160/23183139/e222fa22-f82f-11e6-8f97-22a6345afd85.jpg)

![110__0_](https://cloud.githubusercontent.com/assets/12402160/23183102/bee3dc48-f82f-11e6-98f4-5446a433892f.jpg)

**Comment by sulkaharo** [comment]
There is a known issue with the pump history sync to openaps that can cause this to happen. We don't have a fix yet but as you say openaps does calculate IOB correctly so this is just a display issue (although annoying at it).

**Comment by Kdisimone** [comment]
thanks...guess i'll put in a PR for the docs to make that known
