### ISSUE TITLE
lib/oref0-setup/edisonbattery.json overrides ns-loop in lib/oref0-setup/mdt-cgm.json 

### ISSUE THREAD

**Issue by tmecklem** [openaps/oref0#412]
The template for the edison battery https://github.com/openaps/oref0/blob/4b01147136573aa94765a9b2cdeb1b5785f276c0/lib/oref0-setup/edisonbattery.json#L20 overrides mdt-cgm https://github.com/openaps/oref0/blob/4b01147136573aa94765a9b2cdeb1b5785f276c0/lib/oref0-setup/mdt-cgm.json#L66 and causes `get-ns-bg` to be called even though it shouldn't for MDT cgm (since it's unlikely that a MDT cgm use will have uploaded cgm to Nightscout another way than through the openaps device - see #287). This can cause problems in identifying the gaps for entry uploads to NS.

I'm not sure if there's an easy fix for this since we want the edison battery behavior but not the `get-ns-bg`

**Comment by scottleibrand** [comment]
Could we place the battery-status call in the appropriate place in the mdt-cgm.json, and then make the offending edisonbattery.json get imported before the mdt-cgm.json so the latter overrides?

**Comment by Bender1061** [comment]
if we could find a way, to get rid of it ans speed up the uploads would be nice. because it would be nice if it uploaded the CGM to nightscout faster than never being faster than 7 mins old, and normally 10 mins old.

**Comment by tmecklem** [comment]
@Bender1061 what I've observed is that there's a delay in the history record being written and I don't think the cgm value is available until several minutes after the cgm record timestamp. I think it may just be a matter of trying to use a history table for something no one anticipated. Do you often see newer history readings on your openaps rig than in nightscout?

**Comment by cjo20** [comment]
CGM readings don't reach the pump on 5 minute boundaries.  It can often be 7 minutes since the last CGM timestamp before the next reading appears. Consistently having CGM data < 7 minutes old would be somewhere between difficult and impossible.

**Comment by Bender1061** [comment]
@tmecklem yes I do, at least in monitor/glucose but the ns/glucose does not update near as fast. I think if we made the ns/glucose part of the reformating of the cgm data, would help on that part at least a little

**Comment by scottleibrand** [comment]
Did this get resolved?
