### ISSUE TITLE
bucketed_data may be incorrect

### ISSUE THREAD

**Issue by MilosKozak** [openaps/oref0#415]
if is descending then this https://github.com/openaps/oref0/blob/master/lib/determine-basal/cob-autosens.js#L57 is probably wrong . it should be - 5 here. at least it was wrong on my port to java
and i had to add this https://github.com/MilosKozak/AndroidAPS/blob/dev/app/src/main/java/info/nightscout/androidaps/plugins/OpenAPSAMA/Autosens.java#L66-L70 to make it filling gaps properly
maybe it's a worth to print bucketed_data to console somewhere

Scott Leibrand @scottleibrand 18:56
hmm, let me confirm that we're not reversing the order from what's in glucose.json
there is a //console.error(bucketed_data); already
line 81 in cob-autosens.js

Scott Leibrand @scottleibrand 19:15
hmm, I was thinking you could uncomment the debug line in AAPS
k
I wonder if you could apply a sort function rather than changing line 57?

Milos Kozak @MilosKozak 19:18
array is sorted correctly, that's why i'm telling you ... maybe there is the same bug in oref0

Scott Leibrand @scottleibrand 19:18
what were the symptoms before you changed it?

Milos Kozak @MilosKozak 19:19
it was leading to unsorted array and 1 missing value
not sure about impact to algorithm
but only when filling gaps

**Comment by scottleibrand** [comment]
Fixed in https://github.com/openaps/oref0/pull/703.
