### ISSUE TITLE
Ignore bolus wizard carb entry without a bolus

### ISSUE THREAD

**Issue by scottleibrand** [openaps/oref0#419]
Per https://github.com/openaps/oref0/issues/387, many people are seeing double carb entries as a result of canceling the bolus wizard after entering carbs, taking too long to complete the bolus wizard, or similar. This presents a safety issue with AMA, as it may high temp too aggressively if COB is too high. In order to operate safely in all situations, oref0 should ignore any carbs entered without a corresponding bolus. This will require that any carb treatments entered on the pump be accompanied by at least a minimum-sized bolus (0.025U or 0.1U depending on the pump) to be considered by AMA. Carb-only treatments could still be entered via the NS API.

**Comment by scottleibrand** [comment]
It looks like this would probably be best done in https://github.com/openaps/oref0/blob/dev/lib/bolus.js once we get our heads around that code...

**Comment by scottleibrand** [comment]
PR open for testing: https://github.com/openaps/oref0/pull/512

**Comment by jrw35** [comment]
Hi. I posted this on Facebook the other day:

> I ended up with OpenAPS reporting double the COB I was expecting after breakfast today.
> 
> It turned out that there were two entries in Nightscout, one on top of the other. They duplicated the carbs but only one entry had insulin. I’ve corrected this now but thought this was worth sharing.
> 
> It looks like this is caused by using the pump’s bolus wizard and then going back (with ESC) before administering the insulin to check the numbers, then going forwards again to deliver the bolus. I do that sometimes.
> 
> I’d always assumed that the carbs were logged by the pump when it gets to the end of the wizard and delivers the bolus, but it looks like it records them earlier than that. It’s hard to spot because the two entries are at exactly the same time; the only indication of a problem is that reported COB in the OpenAPS pill is exactly double what it should be.

...and had a reply pointing me at this thread here.

I made a copy of all the logs at the time it happened, and looking at carbhistory.json I can see the duplicate carb entry, once with:

> "insulin": null,
> "eventType": "Carb Correction"

...and then again a few seconds later with:

> "insulin": 4,
> "eventType": "Meal Bolus"

Does this sound like the same issue that you were working on above? Thanks.
