### ISSUE TITLE
Run `openaps first-upload` automatically

### ISSUE THREAD

**Issue by scottleibrand** [openaps/oref0#434]
After troubleshooting on https://github.com/openaps/oref0/issues/433 with @francesc0-cgm, it has become apparent that we need to figure out a way to have oref0 bootstrap CGM uploads automatically.  Currently this requires running `openaps first-upload` as a workaround when first uploading CGM data to a Nightscout instance without any other recent data (because the nightscout/recent-missing-entries.json report fails).  We should either have `openaps first-upload` run periodically (hacky workaround), have it run only when the nightscout/recent-missing-entries.json report fails, or fix the `ns` device to properly handle the no-recent-data case.

**Comment by jaylagorio** [comment]
How can I help with this one? Or is it old enough to have already been solved but not closed out?

**Comment by scottleibrand** [comment]
If you have a MDT CGM, we need someone who can set up a new NS site and figure out how to make oref0 upload CGM data when the "check for gaps" fails because there is no recent data, preferably without just uploading things without checking (which can cause dupes).

**Comment by jaylagorio** [comment]
Crap, I don't have MDT CGM. Sorry!

**Comment by danamlewis** [comment]
Unclear if this is a current issue in the 0.7.0-dev era; please reopen if this is still a concern for MDT cgm users.
