### ISSUE TITLE
Adjust targets when high

### ISSUE THREAD

**Issue by scottleibrand** [openaps/oref0#440]
When BGs are running persistently high, we often recommend setting a low temp target (such as with an Eating Soon preset) to instruct oref0 to correct more aggressively.  This works well, but requires manual intervention.  It should be possible to automate this behavior, with less risk of overcorrection than with manually triggered Eating Soon modes, and *far* less hypo risk than with manual correction boluses.

To do so, we would want to ensure that oref0 high-temps more aggressively only if all the conditions are met:

 - current BG is elevated
 - eventualBG is above 80
 - naiveEventualBG (excluding deviations) is above 80

We also want aggressiveness to ramp up gradually as BG rises from target (i.e. 100), and reach its maximal level of aggressiveness above about 140.  

A simple algorithm for implementing these requirements would be:

```
    if (bg > target_bg) {
        // with target=100, as BG rises from 100 to 130, adjustedTarget drops from 100 to 85
        adjustedTargetBG = Math.max(85,(bg - target_bg)/2);
        // if either eventualBG or naiveEventualBG is below adjustedTarget, don’t use it
        if (eventualBG > adjustedTargetBG && naiveEventualBG > adjustedTargetBG) {
            console.error("Adjusting target_bg from",target_bg,"to",adjustedTargetBG);
            target_bg = adjustedTarget;
        }
    }
```

This would result in oref0 high-temping more quickly/aggressively as BG rises above target and there isn’t enough IOB yet to bring BG down to adjustedTarget.  As soon as the BG rise slows/reverses enough to get (naive)eventualBG down below adjustedTarget, then oref0 switches the adjustedTarget off, resulting in a zero temp to get eventualBG back up to target, which will generally happen before BG drops back down to target.  As a result, high BG should drop roughly 50% faster, but as it starts to do so, the resulting zero temps will result in a smooth landing right around target.

If the OpenAPS rig loses communication with the pump while a high-temp toward adjustedTarget is running, then over the course of DIA hours BG may drop as low as 80 if communication is not restored.  This seems like a low and acceptable risk in exchange for preventing and mitigating high BG, and seems like a safe way to lower average BG and A1c.

**Comment by JELCRAWFORD** [comment]
Sounds like a great enhancement.

**Comment by JELCRAWFORD** [comment]
Willinng to test when ready. Already use eating soon (or exercising soon for rapid drops) in the manner described.

**Comment by danamlewis** [comment]
I have been testing this via https://github.com/openaps/oref0/pull/441/ for several days, and with the additional adjustments @scottleibrand and I have made to the behavior so far on the go, I am happy with this to date. 

I changed the name for it in preferences.json to be adv_target_adjustments to indicate that this is an advanced feature that should only be turned on after people have an understanding of how baseline oref0 works before using this to further adjust targets.

That all being said, I think this could use additional testers now.

**Comment by JELCRAWFORD** [comment]
I don't see any big concerns with code from my perspective.  Better safety profile than when we put eating soon on and risk forget to turn it off, and better than our short duration (10 minutes) button that we then have to remember to keep turning on as we assess what is happening as it requires high vigilance while at work and such.  Mike can also probably answer - anything special about install on the separate branch?

**Comment by tomasboudr** [comment]
@danamlewis I am going to test this too assuming its in the latest dev.

**Comment by tomasboudr** [comment]
PS. I want to say for the 1000th time that this project is awesome. I randomly complained into the twitter void about sports watching related stress giving me 300s that wouldn;t come down and @scottleibrand  immediately came thru with a solution. Yall are amazing!

**Comment by danamlewis** [comment]
thx @tomasboudr - please comment in https://github.com/openaps/oref0/pull/441 with any feedback after you run it and/or a thumbs up if it works ok for you and good to merge to dev.

**Comment by scottleibrand** [comment]
This is now in dev via https://github.com/openaps/oref0/pull/441
