### ISSUE TITLE
Carb decay on sensor restart problem

### ISSUE THREAD

**Issue by tatigger** [openaps/oref0#444]
I entered carbs and insulin prior to sensor restart because bg was low, so carbs entered several times within about 20 minutes.  Then had to restart the sensor.  When sensor came back 2 hours later, the carbs from the carb corrections 2+ hours earlier were still in OpenAPS with a duration 10.5 hours.  Please see the snippet below.  Dana and I expected it to correct itself within a short period of time, it did not.  I shut down that Edison (Thing2) and switched to my 2nd rig, (Thing1).  

Additional details:
1. I updated Thing2s oref0 while sensor restarting
2.  I did not update preferences.json to my current settings (forgot to)
3.  Shut down Thing2 for some of the time that sensor was restarting.
4.  Ran for 2+ more hours without resolution, switched to backup rig.

1. I updated Thing2s oref0 while sensor restarting:

###root@thing2:~# bash ~/tedi2loop/oref0-runagain.sh
Setting up oref0 in /root/tedi2loop for pump XXXXXX with G4 CGM, 
NS host https://whispering-spire-16091.herokuapp.com, TTY /dev/spidev5.1, advanced features  autosens  meal 
# To run again with these same options, use:
oref0-setup --dir=/root/tedi2loop --serial=XXXXXXX --cgm=G4 --ns-host=https://whispering-spire-16091.herokuapp.com --api-secret=iXXXXXXXXXXX --tty=/dev/spidev5.1 --enable=' autosens  meal ' --radio_locale='US'

Continue? y/[N] y
Checking /root/tedi2loop: /root/tedi2loop already exists
/root/src/oref0/ already exists; pulling latest
remote: Counting objects: 1017, done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 1017 (delta 644), reused 634 (delta 634), pack-reused 360
Receiving objects: 100% (1017/1017), 167.94 KiB | 0 bytes/s, done.
Resolving deltas: 100% (691/691), completed with 55 local objects.
From git://github.com/openaps/oref0
 * [new branch]      adj-target-when-high -> origin/adj-target-when-high
   0208319..9016828  dev        -> origin/dev
   494a8c7..a3d7451  floating-carbs -> origin/floating-carbs
Already up-to-date.
Checking oref0 installation
* master
└── oref0@0.4.1 
Checking mmeowlink installation
Version: 0.11.0
{
	"max_iob": 0,
	"max_daily_safety_multiplier": 3,
	"current_basal_safety_multiplier": 4,
	"autosens_max": 1.2,
	"autosens_min": 0.7,
	"autosens_adjust_targets": true,
	"override_high_target_with_low": false,
	"skip_neutral_temps": false,
	"bolussnooze_dia_divisor": 2,
	"min_5m_carbimpact": 3,
	"carbratio_adjustmentratio": 1
}
Removing any existing ns device: 
removed process://ns/nightscout/ns https://whispering-spire-16091.herokuapp.com XXXXXXXXXXXXXXXXXXXXX
Running nightscout autoconfigure-device-crud https://whispering-spire-16091.herokuapp.com intsmnicpwiob
added process://ns/nightscout/ns NIGHTSCOUT_HOST API_SECRET
process://ns/nightscout/ns https://whispering-spire-16091.herokuapp.com XXXXXXXXXXXXXXXXXXXXXX
importing vendor file
openapscontrib.timezones://
mmeowlink.vendors.mmeowlink://
importing device file
dexcom://cgm
process://ns-glucose/bash -c "curl -m 30 -s $NIGHTSCOUT_HOST/api/v1/entries/sgv.json?count=1000 | json -e \"this.glucose = this.sgv\""/
process://oref0/oref0/
process://iob/oref0/calculate-iob
process://meal/oref0/meal
process://get-profile/oref0/get-profile
process://detect-sensitivity/oref0/detect-sensitivity
process://determine-basal/oref0/determine-basal
process://pebble/oref0/pebble
timezones://tz
medtronic://pump
units://units
process://xdrip/bash -c "curl -s http://localhost:5000/api/v1/entries?count=288 | json -e \"this.glucose = this.sgv\""/
importing report file
cgm://JSON/iter_glucose_hours/monitor/cgm-glucose.json
cgm://JSON/oref0_glucose/raw-cgm/raw-entries.json
ns://JSON/shell/cgm/ns-glucose.json
pump://JSON/mmtune/monitor/mmtune.json
pump://JSON/model/settings/model.json
pump://JSON/read_clock/monitor/clock.json
tz://JSON/rezone/cgm/cgm-glucose.json
tz://JSON/clock/monitor/clock-zoned.json
pump://JSON/read_temp_basal/monitor/temp_basal.json
pump://JSON/reservoir/monitor/reservoir.json
pump://JSON/read_battery_status/monitor/battery.json
pump://JSON/status/monitor/status.json
pump://JSON/iter_pump_hours/monitor/pumphistory.json
pump://JSON/iter_pump_hours/settings/pumphistory-24h.json
tz://JSON/rezone/monitor/pumphistory-zoned.json
tz://JSON/rezone/settings/pumphistory-24h-zoned.json
iob://text/shell/monitor/iob.json
meal://text/shell/monitor/meal.json
detect-sensitivity://text/shell/settings/autosens.json
units://JSON/bg_targets/settings/bg_targets.json
units://JSON/insulin_sensitivities/settings/insulin_sensitivities.json
pump://JSON/read_carb_ratios/settings/carb_ratios.json
pump://JSON/read_selected_basal_profile/settings/basal_profile.json
pump://JSON/read_settings/settings/settings.json
get-profile://text/shell/settings/profile.json
determine-basal://text/shell/enact/suggested.json
pump://JSON/set_temp_basal/enact/enacted.json
pebble://text/shell/upload/pebble.json
pump://JSON/read_bg_targets/settings/bg_targets_raw.json
pump://JSON/read_insulin_sensitivities/settings/insulin_sensitivities_raw.json
xdrip://text/shell/xdrip/glucose.json
importing alias file
invoke report invoke
mmtune ! bash -c "reset_spi_serial.py 2>/dev/null; find monitor/ -size +5c | grep -q mmtune && cp monitor/mmtune.json mmtune_old.json; echo {} > monitor/mmtune.json; echo -n \"mmtune: \" && openaps report invoke monitor/mmtune.json; grep -v setFreq monitor/mmtune.json | grep -A2 $(json -a setFreq -f monitor/mmtune.json) | while read line; do echo -n \"$line \"; done"
wait-for-silence report invoke monitor/temp_basal.json
wait-for-long-silence report invoke monitor/temp_basal.json
monitor-cgm report invoke raw-cgm/raw-entries.json cgm/cgm-glucose.json
get-ns-glucose report invoke cgm/ns-glucose.json
monitor-pump report invoke monitor/clock.json monitor/temp_basal.json monitor/pumphistory.json monitor/pumphistory-zoned.json monitor/clock-zoned.json monitor/iob.json monitor/meal.json monitor/reservoir.json monitor/battery.json monitor/status.json
ns-temptargets ! bash -c "curl -m 30 -s \"$NIGHTSCOUT_HOST/api/v1/treatments.json?find\[created_at\]\[\$gte\]=$(date -d \"6 hours ago\" -Iminutes -u)&find\[eventType\]\[\$regex\]=Target\" > settings/temptargets.json; openaps report invoke settings/profile.json 2>/dev/null >/dev/null; exit 0 "
ns-meal-carbs ! bash -c "curl -m 30 -s \"$NIGHTSCOUT_HOST/api/v1/treatments.json?find\[carbs\]\[\$exists\]=true\" > monitor/carbhistory.json; oref0-meal monitor/pumphistory-zoned.json settings/profile.json monitor/clock-zoned.json monitor/carbhistory.json monitor/glucose.json settings/basal_profile.json > monitor/meal.json.new; grep -q COB monitor/meal.json.new && mv monitor/meal.json.new monitor/meal.json; exit 0"
get-settings report invoke settings/model.json settings/bg_targets_raw.json settings/bg_targets.json settings/insulin_sensitivities_raw.json settings/insulin_sensitivities.json settings/basal_profile.json settings/settings.json settings/carb_ratios.json settings/profile.json
bg-fresh-check ! bash -c "cat cgm/glucose.json | json -c \"minAgo=(new Date()-new Date(this.dateString))/60/1000; return minAgo < 6 && minAgo > 0 && this.glucose > 38\" | grep -q glucose"
get-bg ! bash -c "openaps monitor-cgm 2>&1 | tail -1 && grep -q glucose cgm/cgm-glucose.json && cp -pu cgm/cgm-glucose.json cgm/glucose.json; cp -pu cgm/glucose.json monitor/glucose.json"
get-ns-bg ! bash -c "openaps get-ns-glucose && cat cgm/ns-glucose.json | json -c \"minAgo=(new Date()-new Date(this.dateString))/60/1000; return minAgo < 10 && minAgo > -5 && this.glucose > 38\" | grep -q glucose && cp -pu cgm/ns-glucose.json cgm/glucose.json; cp -pu cgm/glucose.json monitor/glucose.json"
gather ! bash -c "openaps report invoke monitor/status.json 2>/dev/null >/dev/null && echo -n Ref && test $(cat monitor/status.json | json bolusing) == false && echo -n resh && ( openaps monitor-pump || openaps monitor-pump ) 2>/dev/null >/dev/null && echo ed pumphistory || (echo; exit 1) 2>/dev/null"
autosens ! bash -c "date; (find settings/ -newer settings/autosens.json | grep -q pumphistory-24h-zoned.json || find settings/ -size -5c | grep -q autosens.json || ! find settings/ | grep -q autosens || ! find settings/autosens.json) && openaps invoke settings/autosens.json"
refresh-old-pumphistory ! bash -c "find monitor/ -mmin -15 -size +100c | grep -q pumphistory-zoned || ( echo -n \"Old pumphistory: \" && openaps gather && openaps enact ) "
refresh-old-pumphistory-24h ! bash -c "find settings/ -mmin -120 -size +100c | grep -q pumphistory-24h-zoned || (echo -n Old pumphistory-24h refresh && openaps report invoke settings/pumphistory-24h.json settings/pumphistory-24h-zoned.json 2>/dev/null >/dev/null && echo ed)"
refresh-temp-and-enact ! bash -c "if( (find monitor/ -newer monitor/temp_basal.json | grep -q glucose.json && echo glucose.json newer than temp_basal.json ) || (! find monitor/ -mmin -5 -size +5c | grep -q temp_basal && echo temp_basal.json more than 5m old)); then (echo -n Temp refresh && openaps report invoke monitor/temp_basal.json monitor/clock.json monitor/clock-zoned.json monitor/iob.json 2>/dev/null >/dev/null && echo ed && if(cat monitor/temp_basal.json | json -c \"this.duration < 27\" | grep -q duration); then openaps enact; else echo Temp duration 27m or more; fi); else echo temp_basal.json less than 5m old; fi"
refresh-pumphistory-and-enact ! bash -c "if ((find monitor/ -newer monitor/pumphistory-zoned.json | grep -q glucose.json && echo -n glucose.json newer than pumphistory) || (find enact/ -newer monitor/pumphistory-zoned.json | grep -q enacted.json && echo -n enacted.json newer than pumphistory) || (! find monitor/ -mmin -5 | grep -q pumphistory-zoned && echo -n pumphistory more than 5m old) ); then (echo -n \": \" && openaps gather && openaps enact ); else echo Pumphistory less than 5m old; fi "
refresh-old-profile ! bash -c "find settings/ -mmin -60 -size +5c | grep -q settings/profile.json && echo Profile less than 60m old || (echo -n Old settings refresh && openaps get-settings 2>/dev/null >/dev/null && echo ed )"
refresh-profile ! bash -c "find settings/ -mmin -10 -size +5c | grep -q settings.json && echo Settings less than 10m old || (echo -n Settings refresh && openaps get-settings 2>/dev/null >/dev/null && echo ed)"
refresh-pumphistory-24h ! bash -c "find settings/ -mmin -20 -size +100c | grep -q pumphistory-24h-zoned && echo Pumphistory-24 less than 20m old || (echo -n pumphistory-24h refresh && openaps report invoke settings/pumphistory-24h.json settings/pumphistory-24h-zoned.json 2>/dev/null >/dev/null && echo ed)"
merge-pumphistory-long ! bash -c "jq -s \".[0] + .[1]|unique|sort_by(.timestamp)|reverse\" settings/pumphistory-long.json monitor/pumphistory-zoned.json settings/pumphistory-24h-zoned.json > pumphistory-long.json.new && mv pumphistory-long.json.new settings/pumphistory-long.json"
enact ! bash -c "rm enact/suggested.json; openaps invoke enact/suggested.json && if (cat enact/suggested.json && grep -q duration enact/suggested.json); then ( rm enact/enacted.json; openaps invoke enact/enacted.json ; grep -q duration enact/enacted.json || openaps invoke enact/enacted.json ) 2>&1 | egrep -v \"^  |subg_rfspy|handler\"; fi; grep incorrectly enact/suggested.json && oref0-set-system-clock 2>/dev/null; cat enact/enacted.json | json -0"
ns-loop ! bash -c "echo Starting ns-loop at $(date): && openaps get-ns-bg; openaps ns-temptargets && echo -n Refreshed temptargets && openaps ns-meal-carbs && echo \" and meal-carbs\" && openaps upload"
pump-loop ! bash -c "sleep $[ ( $RANDOM / 2048 ) ]s; until(echo Starting pump-loop at $(date): && openaps wait-for-silence && openaps refresh-old-pumphistory && openaps refresh-old-pumphistory-24h && openaps refresh-old-profile && openaps refresh-temp-and-enact && openaps refresh-pumphistory-and-enact && openaps refresh-profile && openaps refresh-pumphistory-24h && echo Completed pump-loop at $(date) && echo); do echo Error, retrying && [[ $RANDOM > 25000 ]] && openaps wait-for-long-silence && openaps mmtune; sleep 5; done"
pebble ! bash -c "grep -q iob monitor/iob.json && grep -q absolute enact/suggested.json && openaps report invoke upload/pebble.json"
latest-ns-treatment-time ! bash -c "nightscout latest-openaps-treatment $NIGHTSCOUT_HOST | json created_at"
format-latest-nightscout-treatments ! bash -c "nightscout cull-latest-openaps-treatments monitor/pumphistory-zoned.json settings/model.json $(openaps latest-ns-treatment-time) > upload/latest-treatments.json"
upload-recent-treatments ! bash -c "openaps format-latest-nightscout-treatments && test $(json -f upload/latest-treatments.json -a created_at eventType | wc -l ) -gt 0 && (ns-upload $NIGHTSCOUT_HOST $API_SECRET treatments.json upload/latest-treatments.json ) || echo \"No recent treatments to upload\""
format-ns-status ! bash -c "ns-status monitor/clock-zoned.json monitor/iob.json enact/suggested.json enact/enacted.json monitor/battery.json monitor/reservoir.json monitor/status.json > upload/ns-status.json"
upload-ns-status ! bash -c "grep -q iob monitor/iob.json && find enact/ -mmin -5 -size +5c | grep -q suggested.json && openaps format-ns-status && grep -q iob upload/ns-status.json && ns-upload $NIGHTSCOUT_HOST $API_SECRET devicestatus.json upload/ns-status.json"
upload ! bash -c "echo -n Upload && ( openaps upload-ns-status; openaps upload-pumphistory-entries; openaps upload-recent-treatments ) 2>/dev/null >/dev/null && echo ed"
monitor-xdrip report invoke xdrip/glucose.json
Checking for BT Mac, BT Peb or Shareble
Checking spi_serial installation
Checking mraa installation
Checking openaps dev installation
openaps 0.2.0-dev
Removing any existing pump device:
removed medtronic://pump
added mmeowlink://pump
added wait-for-silence ! bash -c "(mmeowlink-any-pump-comms.py --port /dev/spidev5.1 --wait-for 1 | grep -q comms && echo -n Radio ok, || openaps mmtune) && echo -n \" Listening: \"; for i in $(seq 1 100); do echo -n .; mmeowlink-any-pump-comms.py --port /dev/spidev5.1 --wait-for 30 2>/dev/null | egrep -v subg | egrep No && break; done"
added wait-for-long-silence ! bash -c "echo -n \"Listening: \"; for i in $(seq 1 200); do echo -n .; mmeowlink-any-pump-comms.py --port /dev/spidev5.1 --wait-for 45 2>/dev/null | egrep -v subg | egrep No && break; done"
edison:x:1002:100::/home/edison:/bin/bash
Checking if EdisonVoltage is already installed
EdisonVoltage already installed
importing edisonbattery file
format-ns-status ! bash -c "ns-status monitor/clock-zoned.json monitor/iob.json enact/suggested.json enact/enacted.json monitor/battery.json monitor/reservoir.json monitor/status.json --uploader monitor/edison-battery.json > upload/ns-status.json"
battery-status ! bash -c "sudo ~/src/EdisonVoltage/voltage json batteryVoltage battery > monitor/edison-battery.json"
ns-loop ! bash -c "echo Starting ns-loop at $(date): && openaps get-ns-bg; openaps ns-temptargets && echo -n Refreshed temptargets && openaps ns-meal-carbs && echo \" and meal-carbs\" && openaps battery-status; cat monitor/edison-battery.json; echo; openaps upload"
Checking for BT Pebble Mac
Running: openaps report add enact/suggested.json text determine-basal shell monitor/iob.json monitor/temp_basal.json monitor/glucose.json settings/profile.json settings/autosens.json monitor/meal.json
added determine-basal://text/shell/enact/suggested.json
Add NIGHTSCOUT_HOST and API_SECRET to /root/.profile

Resetting spi_serial
Attempting to communicate with pump:
openaps: no process found
mmtune: pump://JSON/mmtune/monitor/mmtune.json
reporting monitor/mmtune.json
"916.588", 5, -54 
Schedule openaps in cron? y/[N] y
Saving existing crontab to /root/crontab.txt:

NIGHTSCOUT_HOST=https://whispering-spire-16091.herokuapp.com
API_SECRET=XXXXXXXXXXXXXXXXXXXXXXX
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
* * * * * ps aux | grep -v grep | grep -q "oref0-online " || oref0-online  >> /var/log/openaps/network.log
* * * * * sudo wpa_cli scan
* * * * * killall -g --older-than 15m openaps
* * * * * cd /root/tedi2loop && oref0-reset-git
* * * * * cd /root/tedi2loop && oref0-truncate-git-history
* * * * * cd /root/tedi2loop && ps aux | grep -v grep | grep -q 'openaps get-bg' || ( date; openaps get-bg ; cat cgm/glucose.json | json -a sgv dateString | head -1 ) | tee -a /var/log/openaps/cgm-loop.log
* * * * * cd /root/tedi2loop && ps aux | grep -v grep | grep -q 'openaps ns-loop' || openaps ns-loop | tee -a /var/log/openaps/ns-loop.log
* * * * * cd /root/tedi2loop && ps aux | grep -v grep | grep -q 'openaps autosens' || openaps autosens | tee -a /var/log/openaps/autosens-loop.log
@reboot reset_spi_serial.py
* * * * * oref0-radio-reboot
* * * * * cd /root/tedi2loop && ( ps aux | grep -v grep | grep -q 'openaps pump-loop' || openaps pump-loop ) 2>&1 | tee -a /var/log/openaps/pump-loop.log
@reboot cd /root/tedi2loop && oref0-delete-future-entries
Would you like to remove your existing crontab first? y/[N] n
NIGHTSCOUT_HOST=https://whispering-spire-16091.herokuapp.com
API_SECRET=XXXXXXXXXXXXXXXXXXXXXXXXX
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
* * * * * ps aux | grep -v grep | grep -q "oref0-online " || oref0-online  >> /var/log/openaps/network.log
* * * * * sudo wpa_cli scan
* * * * * killall -g --older-than 15m openaps
* * * * * cd /root/tedi2loop && oref0-reset-git
* * * * * cd /root/tedi2loop && oref0-truncate-git-history
* * * * * cd /root/tedi2loop && ps aux | grep -v grep | grep -q 'openaps get-bg' || ( date; openaps get-bg ; cat cgm/glucose.json | json -a sgv dateString | head -1 ) | tee -a /var/log/openaps/cgm-loop.log
* * * * * cd /root/tedi2loop && ps aux | grep -v grep | grep -q 'openaps ns-loop' || openaps ns-loop | tee -a /var/log/openaps/ns-loop.log
* * * * * cd /root/tedi2loop && ps aux | grep -v grep | grep -q 'openaps autosens' || openaps autosens | tee -a /var/log/openaps/autosens-loop.log
@reboot reset_spi_serial.py
* * * * * oref0-radio-reboot
* * * * * cd /root/tedi2loop && ( ps aux | grep -v grep | grep -q 'openaps pump-loop' || openaps pump-loop ) 2>&1 | tee -a /var/log/openaps/pump-loop.log
@reboot cd /root/tedi2loop && oref0-delete-future-entries
root@thing2:~# l

2.  I did not update preferences.json to my current settings (forgot to)

3.  Shut down Thing2 for some of the time that sensor was restarting.

_Starting pump-loop at Sun Apr 16 12:45:03 MST 2017:
Radio ok, Listening: .No pump comms detected from other rigs
Profile less than 60m old
glucose.json newer than temp_basal.json
Temp refreshed
{"carbs":40,"boluses":2.2,"mealCOB":37}
{"ratio":1.11}
{"iob":0.044,"activity":0.0044,"bolussnooze":0,"basaliob":0.033,"netbasalinsulin":0.65,"hightempinsulin":0.65,"time":"2017-04-16T19:45:28.000Z"}
{"delta":-2,"glucose":100,"short_avgdelta":-2,"long_avgdelta":-2.22}
{"duration":18,"rate":0.4,"temp":"absolute"}
Adjusting basal from 0.35 to 0.4
Adjusting target_bg from 110 to 105
Adjusting sens from 74 to 66.7
Carb Impact: 3 mg/dL per 5m; CI Duration: 10.5 hours
Accel. Carb Impact: 10 mg/dL per 5m; ACI Duration: 3.2 hours_

**Comment by scottleibrand** [comment]
One known issue that no one has worked on much, which I think might be causing these symptoms, is to figure out how to decay carbs properly when CGM data is missing. Since @danamlewis and I always make sure to have CGM data (even during sensor swaps, thanks to G4 raw) that isn't a scenario I've had much "opportunity" to experience, so it hasn't been a priority for me to fix. 

I think simply interpolating straight-line CGM data for any gaps would do the trick, if someone wants to take that on.

**Comment by tynbendad** [comment]
we use a g5 without xdrip so i'm interested in looking - pasting a tip from Scott:
Scott Leibrand @scottleibrand 12:25
@tynbendad once you're up and running, look through the code for other places I've done interpolation. Maybe just grep -ri interpolat bin* lib* or similar.

**Comment by Kdisimone** [comment]
Alright...I'd have to learn a lot of code but maybe this will be the motivation. Third time in 2 weeks anna has eaten right before a period of extended missing cgm data. Lol...kids.

**Comment by tatigger** [comment]
I don't know why, but I am ALWAYS hungry when I have to start the sensor!  

Terri - Sent from my iPhone

**Comment by danamlewis** [comment]
@tatigger @tynbendad and anyone else with the carbs-while-no-CGM-data problem - we've got a potential fix per https://github.com/openaps/oref0/pull/518 that needs some other thumbs up before we can stick it in dev!

**Comment by danamlewis** [comment]
This is currently fixed in latest dev and will be in the next release to master.
