### ISSUE TITLE
Reset autosens on site change

### ISSUE THREAD

**Issue by scottleibrand** [openaps/oref0#447]
Pump sites are one of the main causes of insulin resistance dealt with by autosens.  When a site that's not working very well gets changed, we often see a very rapid reduction in resistance, to the point where autosens cannot really keep up by using the last 24h of data to calculate sensitivity/resistance.

The simplest solution I can think of to this problem would be to provide a preferences-configurable option to have autosens ignore all BG data prior to the last pump rewind event.  This would have a couple of useful effects:

 - If the old site was causing resistance, then autosens would return to neutral sensitivity ratio upon site change, and after 6 hours, would shift to whatever sensitivity was detected since then.
 - If the old site was fine and autosens was previously detecting sensitivity, autosens returning to neutral sensitivity ratio upon site change would help with the effect we often see, where insulin given through a brand new site takes a little extra time to get started.  

Undesirable side effects might be:

 - If the PWD is running extremely sensitive, enough to outweigh the new-site effect, we might not want to return to neutral sensitivity for 6 hours before (presumably) going back to using the detected sensitivity.
 - If the PWD is running resistant for some reason unrelated to their pump site (maybe steroids or something), then returning to neutral sensitivity for 6h may be suboptimal.

We could try to implement more complicated solutions, like checking the last-6h data against the last-24h, and using whichever one is showing more sensitivity.  That would have its own issues, though: it would take a few hours to adjust to a new site, and might not be able to effectively head off lows in the mean time.

Thoughts?  Does anyone have any better ideas than simply providing a preferences-configurable option to have autosens ignore all BG data prior to the last pump rewind event (and/or manually entered pump site change events)?

**Comment by scottleibrand** [comment]
While coding and testing this, I realized that instead of simply cutting off autosens completely and returning a neutral sensitivity ratio for 6h after lastSiteChange, we could instead pad some additional zero deviations to the data autosens is using to calculate it.  That means that autosens will always return ratio: 1 for the first hour after the site change, and thereafter it will gradually be more and more able to return a ratio indicating sensitivity or resistance if the data very clearly shows such.  After 6h, we'll only be padding 30m worth of data, so sensitivity will be calculated fairly normally, and by 12h we will completely stop padding.

**Comment by scottleibrand** [comment]
Merged to dev: closing.

**Comment by rsilvers129** [comment]
How are people liking or not liking how this works out?

**Comment by scottleibrand** [comment]
It seems to work better than before.
