### ISSUE TITLE
Pushover integration - for insulin needed notifications and/or carbs needed notifications

### ISSUE THREAD

**Issue by danamlewis** [openaps/oref0#453]
An idea for how to create a bolus recommendation upon request, while taking into account netIOB and providing a safe recommendation that's cognizant of looping activity (even in the scenario that someone has SMB enabled):

- Use ThisButton on Pebble, similar to temp target command. Press the button, and it will:
- Use Pushover to notify you of insulinReq (which is the insulin OpenAPS thinks is required to bring you to target; or in future an estimate of how much to bolus for carbs to get minCOBpredBG down to target)
- After each SMB, it will continue to send a new pushover alert of the updated insulinReq, until insulinReq a) hits zero or b) sees a manual bolus given
- Maybe should also send a pushover confirmation of the manual bolus, to guard against distracted behaviors?

**Comment by danamlewis** [comment]
More thoughts on this topic:

- Should be a more simple (at first) Pushover integration that alerts when carbs have been entered and there is SMB activity ongoing. if a person decides they want to manually bolus, they can; otherwise SMB will have at it. (This will also help with distractedness, i.e. someone enters carbs but forgets to bolus) Info provided can be similar to what's displayed in OpenAPS pill in NS/logs, i.e. insulinReq is 3.4 and attempting SMB of .5.

- We can also use this same feature add to provide some alerts if BG is going to be low and even low temping won't prevent it from reaching back up to a normal level - i.e. "do xx carbs to bring bg up to YY level"

**Logistics notes related to designing this:**
Pay for pushover
include pushover API in oref0-setup in some way
It will send http posts as pushover message from rig when online
Creates equivalent of event like a temp target (new treatment item) to go into the NS API (doesn't need to be added into CarePortal)
If new treatment exists and is more recent than manual bolus, then cascade alerts for insulinReq when calculated including note about SMB attempt
Could also do it from carb entry via ifttt/NS til a bolus comes in

**Comment by PieterGit** [comment]
I like the xdrip plus notation of "Expected low in XX min" (possible even with the minimum value of all of the expected cgm values).

I think notifications should be configurable, e.g. pushover and/or pebble notify (e.g. `openaps use pbbl notify "Expected low" "in XX minutes (min=YY)"` )

**Comment by scottleibrand** [comment]
Initial implementation in https://github.com/openaps/oref0/pull/458

**Comment by danamlewis** [comment]
Implemented and documented via http://openaps.readthedocs.io/en/latest/docs/walkthrough/phase-4/oref1-features.html#pushover-smb-and-openaps, so closing the issue.
