### ISSUE TITLE
Clarify Pump time vs rig time error

### ISSUE THREAD

**Issue by dmdfreak** [openaps/oref0#459]
The error that displays when the pump and rig clocks are too far out of sync is hard to understand what the problem actually is or that it is an error. 

Also add a suggestion to run oref0-set-device-clocks to fix the error.

**Comment by scottleibrand** [comment]
https://github.com/openaps/oref0/pull/458 implements an automatic run of oref0-set-device-clocks when pump time is more than 1m off rig time.
