### ISSUE TITLE
SMB, UAM, and other oref1 related issues while testing PR #424

### ISSUE THREAD

**Issue by danamlewis** [openaps/oref0#461]
If you're running into issues with turning on or testing SMB, UAM, and other oref1, let's use this thread so we don't clutter the PR (https://github.com/openaps/oref0/pull/424).

**Comment by ericfeibelman** [comment]
I can't get SMB to run on any of my rigs. I'm using a 722 with enlite sensors and edison/explorer board. I can get openaps to work fine without --enable='  microbolus  '. As soon as runagain with microbolus, I get a repeat of the following on both rigs (my date/time are accurate on both the rig and the pump):

Radio ok. Listening: .No pump comms detected from other rigs
Listening for 30s silence before mmtuning: .No pump comms detected from other rigs
mmtune: "916.516", 5, -41 Sleeping 6;

Starting supermicrobolus pump-loop at Mon May 8 19:53:44 EDT 2017 with 26 second wait_for_silence:
Waiting up to 4 minutes for new BG: ........................Radio ok. Listening: .No pump comms detected from other rigs
Preflight OK. Old pumphistory, waiting for 26 seconds of silence: Radio ok. Listening: .No pump comms detected from other rigs
Refreshed pumphistory
Profile less than 60m old. pump_loop_completed less than 5m ago. Refreshed pumphistory
pumphistory.json: ^[[32m"TempBasalDuration 2017-05-08T19:27:01 head[2], body[0] op[0x16]"^[[0m
Checking pump clock: "2017-05-08T20:00:04-04:00" is within 1m of current time: Mon May  8 20:00:20 EDT 2017
and that pumphistory is less than 1m old.  Temp refreshed
{"carbs":0,"boluses":3.7,"mealCOB":0,"currentDeviation":null,"maxDeviation":0,"minDeviationSlope":0}
BG data is too old (it's probably this), or clock set incorrectly.  The last BG data was read at Sun May 07 2017 07:47:00 GMT-0400 (EDT) but your system time currently is Mon May 08 2017 20:00:43 GMT-0400 (EDT)
Checking deliverAt: null is within 1m of current time: Mon May  8 20:00:44 EDT 2017
date: invalid date ‘null’
Error, retrying
Sleeping 6;

**Comment by mgranberryto** [comment]
Combining autotune and `carbratio_adjustmentratio` in `preferences.json` leads to doubly-applied adjustments.

**Comment by scottleibrand** [comment]
I believe that behavior is unchanged from master.  Have you seen otherwise?  If not, it'd probably be best to open a new issue to track that, so we don't lose it amongst all the changes in dev.  (It might also warrant a patch release to master...)

**Comment by ericfeibelman** [comment]
After redoing everything from scratch on my dev, it worked beautifully while microbolus was not enabled, once again I enabled microbolus and redid runagain.sh and date errors again 

Starting supermicrobolus pump-loop at Thu May 11 07:23:02 EDT 2017 with 17 second wait_for_silence:
Waiting up to 4 minutes for new BG: jq: error: null and number cannot be divided
date: invalid date ‘@’
.jq: error: null and number cannot be divided
date: invalid date ‘@’
.jq: error: null and number cannot be divided
date: invalid date ‘@’

**Comment by lukas-ondriga** [comment]
I had the same problem as @ericfeibelman.
date: invalid date ‘@’
I use Enlite sensors. The glucose.json does not contain field 'date', but it contains 'display_time' instead.
My temporary fix is this replacement inside oref0-pump-loop:
-  touch -d "$(date -R -d @$(jq .[0].date/1000 monitor/glucose.json))" monitor/glucose.json
+ touch -d "$(date -R -d $(jq -r .[0].display_time monitor/glucose.json))" monitor/glucose.json

It works for me, but I do not know how other glucose.json files look like. If they all have 'display_time', I can create the PR, if not, we will need to add 'date' into the glucose.json.

**Comment by scottleibrand** [comment]
That should be fixed in https://github.com/openaps/oref0/pull/478 - if you or someone can test that for us, we should be able to merge it to dev more quickly.

**Comment by Bender1061** [comment]
would there be a way to enable SMB without having it turn off my basal after a meal? I'm finding that because I'm very insulin insensitive that by blood sugar is raising far higher because I'm not getting my basal for that time after I give myself a large basal. I like the fact of the smb should be helping keep up with my sensitivity issue, but it's mostly trying to play catch up so it's not really helping me.

**Comment by danamlewis** [comment]
@Bender1061 that goes against the safety design of not being able to prevent a low if that ends up becoming too much insulin because of change in activity, digestion, etc. later on. Any thoughts on ways to accomplish both, as an improvement to how SMB is currently?

**Comment by danamlewis** [comment]
for those sharing input, would be helpful to know more details about what you have turned on in preferences (what SMB triggers, if UAM is on, etc.) plus how confident you are in your basals, ISF, carb ratio, and DIA.

**Comment by Bender1061** [comment]
I know it's a safety feature but it would be nice to test so that it does not do the suspend. as for a better solution, I do not have that yet. Issue is due to my insulin insensitivity, Which most people hopefully are not fighting that as much as I do.

**Comment by Bender1061** [comment]
![image](https://cloud.githubusercontent.com/assets/18385876/26472922/6edafea8-4176-11e7-8233-5d941f560439.png)

**Comment by Bender1061** [comment]
a good example is of today, I know from past experiance, Cause Breakfast was a smores poptart. that it would have gone up to at worst 180, but even though it gave me the extra almost unit, but with my basal rates at such a large amount, that did not make up for the amount that I lost after breakfast. and cause that goes into lunch, I'm well finally starting to come back down to normal. and I'm about to have dinner

**Comment by davidkeddydb** [comment]
Dana, Scott: here is where I guess I am struggling.  I understand why it zero temps and the safety, but is sort of seems counter to how Oref0 use to work.  You would take a bolus, bolus snooze would kick in for most of it and your regular basal for the most part would run in the background.  In fact, the whole safety of OpenAPS back then was worst case, you fall back to the pump settings.  I am finding that the Zero temp is just too long and I would be better served to just let my current basals run.  Now on the other hand with the new SMB it maybe makes more sense to up the carb bolus amounts.  I definitely wouldn't want to do that and then the pump doesn't zero out as OpenAps doesn't function for some reason.  I think having an adjustment of the predicted IOBpredbg maybe not in preferences but people changing it in the code makes more sense.

**Comment by scottleibrand** [comment]
@davidkeddydb: do you use papertrail?  I just reviewed your NS, and it looks like the carbs may not be getting fully included in the COBpredBGs (or perhaps the CR or ISF is off).  I'd like to review the full determine-basal debug output in your pump-loop.log, so if you could either PM me access to your papertrail, or upload a copy of your pump-loop.log somewhere I can review that, I'd love to dig in deeper.  @Bender1061, same to you, if you'd like to PM me your NS URL and/or access to your pump-loop.log.

**Comment by davidkeddydb** [comment]
@scottleibrand Will pm you the pump-loop log.  I haven't set up papertrail.  Mistake not to, maybe?  Today all was right as rain at least in the am and SMB was fantastic.

**Comment by scottleibrand** [comment]
Thanks. If you have a good way to ssh to your rig and are comfortable with less and scp, then papertrail is basically just a pretty GUI. It is useful for remote caregivers who want to be able to watch logs and can't ssh in, though.

**Comment by rsilvers129** [comment]
I can't turn on dev with microbolus without getting stuck in the same loop that ericfeibelman posted 18 days ago.

**Comment by davidkeddydb** [comment]
@scottleibrand So I am not certain what to supply you with from my loop logs, but today was another where I wish that bolus snoooze worked more as it did before and not zero temp as long.  I have an old rig with an older version of master that I don't would have zero temped out the same way.
![screenshot 2017-05-30 13 19 55](https://cloud.githubusercontent.com/assets/10411709/26595873/c4c3407e-453a-11e7-8fdd-199c7135e89e.png)

**Comment by Bender1061** [comment]
@rsilvers129 you could try out https://github.com/openaps/oref0/pull/478 that fixed the issue for @ericfeibelman and we could always use more people to test it before @scottleibrand pushes it to dev.

**Comment by Bender1061** [comment]
I'm starting to think that maybe the basal rate going back to normal rate while this is running might be a better idea. or do we need some kind of preference for insulin sensitivity? cause I'm thinking it just a matter of some people need that zero temp or they would go low. some people that zero temp does more damage than good, and maybe they would be better off at least leaving the normal basal rate. and then there are some people  that might not be better off using SMB or have the SMB running and maybe needing a higher temp basal. Something I need to try doing is seeing what happens if I eat some pizza, cause that is the kind of food, that if I do take all the Bolus for, I will drop right away before I start rising. In that case the zero temp might make more sense. 
Right now I just at 90 g of carbs and it automatically set me a zero temp for 240 mins, when I actually have a slight trend up of my BG levels, if it was trending down, it would make more sense.

**Comment by davidkeddydb** [comment]
@Bender1061 I am with you.  The old function of bolus snooze without the zero temping worked better for me.  I have to look at the code so I can give some valid suggestions of how the old Bolus Snooze works vs the current SMB and zero temping.

**Comment by Bender1061** [comment]
Yeah I need to really go into that java script. I'm thinking I need to make a flowchart so I can wrap my head around it. Cause there is a whole lot in there.

**Comment by scottleibrand** [comment]
I think the YDMV here may not be just about the D varying, but that everyone has learned such markedly different bolusing behaviors that work for them in the absence of an APS.  We could take at least three fundamentally different approaches:  We could give people lots of knobs to tune the system to work more like they've learned to do things.  We could make the system work a certain way, and retrain all the users to do what it expects.  Or we could try to make the system flexible enough that it can handle whatever the user does, and however their body responds, and dose accordingly.  I'm trying to move away from the first approach to the last one, but that is probably the most difficult from an algorithm design perspective.

**Comment by davidkeddydb** [comment]
You were crazy enough to attempt UAM, my money is on you and the OpenAPS community.  We will all have to tweak the code some likely to get it to work for our given bolusing behavior.  My Doc is also a T1 and is in awe of the way the bar keeps getting raised of what OpenAPS can do/handle.

**Comment by ericfeibelman** [comment]
I am testing the remainingCarbsFraction set to 1 now and will re-enable SMB.

**Comment by dougtakeuti** [comment]
I hope this is the right place to post this. I've been running the dev
branch in one rig for a week, with just oref0 features enabled. The only
apparent issue is the higher number of radio problems. Yesterday I did a
fresh install with SMB enabled. It worked beautifully for about 12 hours. I
was very excited with SMB helping us minimize the breakfast spike, which
has been one important issue since diagnosis.  However, this morning, right
after the luch bolus, the pump clock was set back to 2005. The reservoir
level was set to zero when in fact there were 40 units left and the basal
profile, which was originally Profile B, was set to the Standard profile.
The MDT sensor had been lost.  The pump seemed to have stopped altogether.
I had to reset it, rewind and decided to change battery. I switched back to
the oref0 rig. It still does not supply BG data to the loop. I saved the
pump-loop log around that time, hoping it helps figure out possible bugs.
Would it help if I posted it anywhere?

2017-05-30 23:28 GMT-03:00 David <notifications@github.com>:

**Comment by scottleibrand** [comment]
@dougtakeuti Did you use the Bolus Wizard for the lunch bolus?  Did the pump give you an error and reset just as you were doing the bolus?  If so, then you'll probably want to set "enableSMB_with_temptarget": false and make sure that oref1 is not trying to administer an SMB based on a previous meal's COB or bolus when you are trying to use the Bolus Wizard.  There is a known issue (originally discovered by Loop users) where administering a bolus remotely (with SMB or Loop) while the Bolus Wizard screen is open will cause the pump to crash and reset, so you'll want to avoid that situation if you can.  One other approach is to stop using the Bolus Wizard and just use the easy bolus button to deliver boluses, and NS/IFTTT to enter carbs.

**Comment by ericfeibelman** [comment]
I got the following error - not sure if it is related to this branch. I have my own script to synchronize the pump and rig clocks so I'll do that now ....

Checking pump clock: "2017-05-31T15:30:17-04:00" is within 1m of current time: Wed May 31 15:31:21 EDT 2017
Pump clock is more than 1m off: attempting to reset it
Waiting for ntpd to synchronize... OK!
sudo: ntpdate: command not found
Setting pump and CGM time to Wed May 31 15:31:22 EDT 2017
{
  "raw": [
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0
  ],
  "requested": {
    "old": "2017-05-31T15:31:23",
    "params": [
      15,
      31,
      25,
      7,
      225,
      5,
      31
    ],
    "clock": "2017-05-31T15:31:25.448087"
  },
  "timestamp": "2017-05-31T15:31:27.060280",
  "clock": "2017-05-31T15:31:26"
}usage: openaps-use cgm [-h] USAGE ...
openaps-use cgm: error: argument USAGE: invalid choice: 'UpdateTime' (choose from 'bolus', 'config', 'filter_glucose_date', 'filter_isig_date', 'iter_glucose', 'iter_glucose_hours', 'iter_pump', 'iter_pump_hours', 'mmtune', 'model', 'mytest', 'press_keys', 'read_basal_profile_A', 'read_basal_profile_B', 'read_basal_profile_std', 'read_battery_status', 'read_bg_targets', 'read_carb_ratios', 'read_clock', 'read_current_glucose_pages', 'read_current_history_pages', 'read_glucose_data', 'read_history_data', 'read_insulin_sensitivies', 'read_insulin_sensitivities', 'read_selected_basal_profile', 'read_settings', 'read_status', 'read_temp_basal', 'reservoir', 'resume_pump', 'set_clock', 'set_temp_basal', 'settings', 'status', 'suspend_pump', 'test_oref0_compat_menu')
Error, retrying
Sleeping 4;

**Comment by scottleibrand** [comment]
That output is ugly, but it looks like it successfully set your pump clock automatically.  The error was from attempting to set the clock on a `cgm` device that doesn't exist, which shouldn't matter, as setting the pump clock should get the two devices into sync should do the trick.

However, it looks like your pump clock may have only been about 2 seconds off, which would mean there's something funky with your (MDT CGM?) setup that causes it to spend more than a minute doing something else in between pulling the pump clock.json and checking it against the rig time.  If this is a recurring problem, we may need to adjust the order of operations so it refreshes the clock.json right before checking it.

**Comment by ericfeibelman** [comment]
Thanks Scott - it only happened once. Now it is looping without error and quickly.

**Comment by ericfeibelman** [comment]
Getting a new error now - one I didn't get on dev ....

Checking deliverAt: 2017-05-31T19:58:27.629Z is within 1m of current time: Wed May 31 15:58:28 EDT 2017
and that smb-suggested.json is less than 1m old
enact/smb-suggested.json: {"insulinReq":-1.07,"bg":174,"reservoir":"78.2","temp":"absolute","snoozeBG":53,"rate":0,"predBGs":{"COB":[174,170,165,161,157,153,149,145,141,138,134,132,129,126,124,122,119,117,115,113,111,109,107,106,104,102,101,100,99,98,97,96,96,96,95,95,96,96,96,97,98],"aCOB":[174,177,180,182,184,185,186,186,185,185,184,182,180,178,175,172,168,164,160,157,153,150,146,143,139,136,133,130,127,125,122,120,118,116,114,112,111,109,108,107,106,105],"UAM":[174,168,162,156,150,144,139,133,128,123,118,113,109,104,100,96,93,89,85,81,78,74,71,67,64,61,58,55,52,49,47,45,42,40,39],"IOB":[174,168,162,156,150,144,139,133,128,123,118,113,109,104,100,96,93,89,85,81,78,74,71,67,64,61,58,55,52,49,47,45,42,40,39]},"minPredBG":53,"IOB":3.232,"reason":"COB: 22, Dev: 2, BGI: -5.85, ISF: 44, Target: 100, minPredBG 53, IOBpredBG 39, COBpredBG 98, UAMpredBG 39;  insulinReq -1.07; setting 120m zero temp. ","COB":22,"eventualBG":98,"duration":120,"tick":-6,"deliverAt":"2017-05-31T19:58:27.629Z"}
Temp refreshIndexError: bytearray index out of range
IndexError: bytearray index out of range
grep: enact/smb-enacted.json: No such file or directory

**Comment by scottleibrand** [comment]
`IndexError: bytearray index out of range` is usually just flaky pump comms.  If it persists, you can drill down into the report being run, but it will probably self-resolve.

**Comment by ericfeibelman** [comment]
yep, reboot resolved it.

**Comment by dougtakeuti** [comment]
Yes, Julia used the bolus Wizard at School. Thanks for the info. I need to
think of a solution that makes her life easier. Using bolus Wizard is
something she's used to and is simple enough. Do you mean that disabling
"enableSMB_with_temptarget" will minimize this problem but not necessarily
eliminate It?

**Comment by scottleibrand** [comment]
Correct.  Disabling enableSMB_with_temptarget will eliminate one common source of SMBs at Bolus Wizard entry time, but if she's stacking meals such that the SMBs from a previous meal are still going when she does her next meal's Bolus Wizard, it won't necessarily prevent it.  One way to be sure it's safe to use the Bolus Wizard is to make sure that it's been less than 3 minutes since the last bolus.  If not, you can do a small Easy Bolus first, and that will force SMB to wait 3m before doing another one, during which time it'd be safe to do a Bolus Wizard...

**Comment by ericfeibelman** [comment]
This branch is looping. However, it isn't updating the NS BG's. I think it has to do with the time issue. This was not a problem on the dev branch.

The following command doesn't force the update either:
alias f='cd ~/myopenaps && openaps first-upload'

I may need to switch back to dev.

**Comment by Bender1061** [comment]
@ericfeibelman you are substituting your openaps directory in place of "myopenaps" right? well unless you are actually using "myopenaps" that is :-)

**Comment by davidkeddydb** [comment]
@scottleibrand I am going to attempt changing my carb ratios given the SMB and temping to Zero that happens post bolus. My only concern with doing this is if OpenAPS goes off line, the basal insulin and giving more insulin at meal time will be too much.  Here was today, post prandial breakfast and lunch both higher than I would likely.
![screenshot 2017-05-31 20 57 46](https://cloud.githubusercontent.com/assets/10411709/26660156/07c74a1e-4644-11e7-9e0f-0a8cb9c30956.png)
![screenshot 2017-05-31 20 58 17](https://cloud.githubusercontent.com/assets/10411709/26660157/07c94f94-4644-11e7-9ffc-575d0a098067.png)

**Comment by ericfeibelman** [comment]
yep, my directory is myopenaps.

**Comment by ericfeibelman** [comment]
Here's my afternoon running on this branch. Wednesday night is milkshake night so it is pushing the limits ...
![image](https://cloud.githubusercontent.com/assets/26698840/26660375/ae3a9b2a-4645-11e7-9c86-1490d7b07a09.png)

I like how it picked up SMB faster than it did before after dinner.

**Comment by ericfeibelman** [comment]
SMB working like I want it to. Yeah!
![image](https://cloud.githubusercontent.com/assets/26698840/26685182/51da961a-46b7-11e7-9fee-3fadb470950b.png)

**Comment by Bender1061** [comment]
OK so after a few more days of testing. 
When Running SMB it is super important at least for me to NOT bolus for my food. Or at least not bolus much. I guess further testing on my part and yes a lot of retraining myself, will be required. Such as watching my trend before I decided if I need to bolus for a meal or what part of it.

but what I'm really getting out of this is. Maybe if someone runs the bolus wizard and takes the full amount of bolus suggested that it would disable SMB. Cause that is what was hurting me, it will Zed temp far too long. 
I do understand why you do not want to use the bolus wizard while using SMB, Had that happen a few days ago. 
But well habits are hard to change.

**Comment by rsilvers129** [comment]
David - I wonder about changing carb ratio. OpenAPS will use the auto-tune version of the carb ratio. I am not sure it would honor what you put in the pump for carb ratio.

Bender - so you announce carbs and let SMB handle the entire meal? I could try that, but I just don't see how it would work well unless it was like a salad or something.

**Comment by Bender1061** [comment]
@rsilvers129  I'm a heavy carb eater (I love my bread) what I also did was increase carbratio_adjustmentratio to 1.4 (which I think is a little aggressive) so I'm still playing. and that made a huge difference. So if it's a super carb heavy meal, I give myself a few units instead of the 10 or so I would normally have done, it might zero temp for a little bit, but then when SMB starts kicking in it actually does what I'm wanting. if it's less than a 50 carb meal I don't bolus at all. But yes I do announce all my carbs. 
I'm on a steroid, so I don't ever expect to have perfect BG after a meal, but it's not going up near as high as it was.

**Comment by rsilvers129** [comment]
Is it valid to use carbratio_adjustmentratio greater than 1 and still announce all carbs? I thought it was for when carbs were being under-announced by the inverse ratio?

So you are announcing 100% of the carbs, setting carbratio_adjustmentratio to 1.4, and taking some smaller amount of insulin?

Why can't one announce 100% of carbs, not touch carbratio_adjustmentratio, and take a smaller amount of insulin?

Scott - is what Bender is doing one way to go that may be good for a lot of people?

**Comment by Bender1061** [comment]
oh please don't use what I'm exactly using! Sorry I should have clarified that. I imagine most people can use the default 1 and not need to do that. I'm kind of a special case.

**Comment by rsilvers129** [comment]
I am not suggesting other people use. 1.4. Even you said you may not want to use 1.4.

I asm asking if it is a valid concept to use more than 1.0 in this context.

**Comment by davidkeddydb** [comment]
I don't believe you can as Scott has a hard code that will not allow it to go greater than 1.

**Comment by Bender1061** [comment]
And I have not double checked that. So you could be right

**Comment by rsilvers129** [comment]
Would autotune think that you had 1.4x as many carbs and mess up the calculations?

**Comment by rsilvers129** [comment]
I am turning off SMB. Seven hours after my 107 gram carb meal, I am at 244. With the previous non-SMB, it was able to handle my 177 gram carb test.

**Comment by tim2000s** [comment]
How did you dose for your carb heavy meal? Did you repeat the test on AMA or only do it once? How did it get entered into NS/oref1? What does your NS trace look like? What is your DIA? That's almost the opposite of what most have seen so it would be good to understand why.

**Comment by rsilvers129** [comment]
Active Insulin Time is set to 4 in the pump. With AMA, I didn't repeat my very large carb test, but it was such an extreme test that it seemed like a sure thing it could handle anything normal. 

My dinner with SMB was 107 grams of carb in the form of 460 grams (uncooked) fresh ravioli, with 10 grams of olive oil, and 22 grams of four-cheese. I was at 130 BG and going down with a a small amount of IOB. My bolus wizard said I would need 14 units for 107 gram carb. I reduced the amount to 10 units, and let it dose, leaving 4 units for SMB. Very soon SMB issued 0.4 units. It was doing ok for a while, and was periodically giving me 0.4 units, but by 7 hours later, I was at 242. It was just not dosing enough to ride the wave and balance the carbs being digested. Now, maybe I should have given the full bolus, and then also let SMB handle the tail.

Or I think it would work for me if there was a knob I could turn that would make it SMB more. So is that making carbratio_adjustmentratio be more than 1.0? I am not sure, but I am afraid of side effects of having it think I am eating more carb than I am. I think that may have unintended consequences for autotune. A simple aggressiveness setting, or a carb digestion rate setting, may be what I am looking for.

With oref0 I could work with the multipliers, but with SMB it seems to be overriding those because SMB is active, but then it doesn't have its own multipliers, as far as I know, unless that is what carbratio_adjustmentratio is. But I don't think so, since carbratio_adjustmentratio was also in oref0.

**Comment by tim2000s** [comment]
Posting your Nightscout view of the period would be helpful. Also, what settings do you have enabled in preferences.json?

**Comment by rsilvers129** [comment]
Image:
https://s12.postimg.org/4fxn2s36l/IMG_6430.png
[img]https://s12.postimg.org/4fxn2s36l/IMG_6430.png[/img]

{
	"max_iob": 12,
	"max_daily_safety_multiplier": 3,
	"current_basal_safety_multiplier": 4,
	"autosens_max": 1.2,
	"autosens_min": 0.6,
	"rewind_resets_autosens": false,
	"autosens_adjust_targets": true,
	"adv_target_adjustments": false,
	"maxCOB": 120,
	"override_high_target_with_low": false,
	"skip_neutral_temps": false,
	"bolussnooze_dia_divisor": 2,
	"min_5m_carbimpact": 5,
	"carbratio_adjustmentratio": 1,
	"autotune_isf_adjustmentFraction": 0.5,
	"remainingCarbsCap": 90,
	"enableUAM": true,
	"enableSMB_with_bolus": false,
	"enableSMB_with_COB": false,`
	"enableSMB_with_temptarget": false
}

**Comment by davidkeddydb** [comment]
I have had to change my carb ratios at all meals from 1:9; 1:6; 1:10 more aggressive to 1:8, 1:5, 1:9 because of the zero temp after bolus but it does seem to work pretty well.  I also increased by DIA from 3 out to 5.  With just bolus snooze, ama and autosens the previous ratios and DIA worked well. I have UAM and also SMB set to true

**Comment by scottleibrand** [comment]
@rsilvers129 you have all the SMB options disabled.

**Comment by rsilvers129** [comment]
Oh sorry, I copied that now. I disabled SMB last night. They were all enabled until last night.

**Comment by scottleibrand** [comment]
One important caveat for SMB: it relies on uninterrupted CGM data. If your CGM goes out, you'll need to take over manually and do whatever is most appropriate: cancel the zero temp, bolus manually, or whatever. If you're running sensors past end of life, you might want to consider replacing them sooner if you start getting gaps. 

I'm also testing some bolus snooze behavior for SMB, and will report back when we're ready for more testers.

**Comment by rsilvers129** [comment]
I was napping at that point. I didn't know it went out. But yes, I can see that had it not went out, it would have probably given additional doses. Still, it let me get to almost 240 before CGM went out.

**Comment by tim2000s** [comment]
Your first CGM gap is pretty soon after the meal and that would also have had an impact. We just can't tell how much.

**Comment by rsilvers129** [comment]
This is what happens when carbratio_adjustmentratio is set to 1.25:

https://s22.postimg.org/lr3ltnb41/1.25carbratio.png

**Comment by rsilvers129** [comment]
Just had the null date issue on a friend's rig after putting microbolus on the line. Spent a few hours trying to fix radio complaints and null date issues. The fix ended up being removing microbolus. But no SMB of course. without it.

**Comment by danamlewis** [comment]
Closing, since oref1-features are merged into dev.
