### ISSUE TITLE
Combining carbratio_adjustmentratio and autotune leads to incorrect results

### ISSUE THREAD

**Issue by mgranberry** [openaps/oref0#464]
Combining autotune and carbratio_adjustmentratio in preferences.json leads to doubly-applied adjustments.

The value set by autotune should be multiplied by the reciprocal of carbratio_adjustmentratio before being written out.

**Comment by rsilvers129** [comment]
I am interested in following this. I have found that setting carbratio_adjustmentratio to a higher than 1.0 value gives less insulin, and a lower than 1.0 gives more insulin. I am not sure how that effects autotune, but hopefully not in a way that will mess things up. If it does, the docs should be changed to say to not use carbratio_adjustmentratio and possibly disable it in the code.

**Comment by scottleibrand** [comment]
Is there anyone actually using carbratio_adjustmentratio the way it was originally intended?  If not, I agree we might want to remove it as a recommended option in the docs...

**Comment by scottleibrand** [comment]
@danamlewis @Kdisimone what do you think about removing carbratio_adjustmentratio from the docs?

**Comment by danamlewis** [comment]
having Hilary test this now.

* breakfast ratio is 9. autotune is using overnight of 15 and tuning that to 12.996. w/ fiasp, she wants the pump to have 50%, so she's changing breakfast ratio to 18 to make bolusing easier.
* having her change overnight to 18, and running autotune manually to check how the 18 gets tuned.
* then will set carbratio_adjustment ratio to 1.1, and run it again, to confirm how much it tunes further and the impact on autotune. 

That'll give us an idea for fixing/adjusting and what else we might want to do with this (keep it and fix it, or phase it out in lieu of another solution).

**Comment by scottleibrand** [comment]
This was solved by removing carbratio_adjustmentratio entirely per https://github.com/openaps/oref0/pull/798
