### ISSUE TITLE
Run Autotune nightly as a safety factor for oref1

### ISSUE THREAD

**Issue by Kdisimone** [openaps/oref0#468]
Despite all the docs and pleas for people to do their testing before starting looping, people may still be jumping in without vetting their ISFs and basals.  To help add a layer of safety, it may be a good idea to have autotune run nightly even if the user doesn't choose to enable autotune during setup.

The idea is that autotune could produce a nightly autotuned-profile that the user could access via an easy alias like `cat-autotune` (which exists in the dev branch now`.  Reducing the administrative steps to get an autotune run may help get new users on the right track if they have some tuning problems, and add to the safety of the system.

I don't know what ways are possible or preferred...but maybe one option is to no longer have autotune as an optional advanced feature during setup.  Instead it runs all the time, but there is a preference setting that says something like "use-autotune.profile=true/false"? 

personally, i'd love to have autotune run nightly and then have an optional way of accessing the data even if I don't want it "enabled" as my profile for the day.

thanks!

**Comment by tim2000s** [comment]
I think that it might be better for autotune to be run before the SMB/UAM preferences can be changed, and if there isn't enough data to do so, leave it set as oref0 with the required warnings about why oref1 is not available, i.e. Each pump loop check for Autotune and if not there revert to default preference settings of false. 

Just trying to think of ways to stop oref1 use when users haven't done the prerequisites manually or automatically.

**Comment by moomoobloo** [comment]
Is autotune considered a prerequisite for oref1 features? Did not see anything about that in the testing instructions: https://github.com/openaps/oref0/pull/424#issuecomment-298807656.

**Comment by scottleibrand** [comment]
Autotune itself is not (yet), but "having well-tuned basals and ratios" is (see the original SMB issue). I agree we can't really force people to use the autotune profile, as it may be suboptimal for them, but I like the idea of requiring it to be run (manually or automatically) before SMB can be turned on...

**Comment by hilarykoch** [comment]
Would requiring it to be run before SMB be required then every time someone does an update or reruns the script? For folks who have well tuned basals, or have been looping for a while, I would think it would be a hassle. I kind of like the initial suggestions Katie proposed. I think for newer users, having it enabled automatically, a ways to access a report (even if not enabled) and then an option of true/false would be idea.

**Comment by danamlewis** [comment]
Proposed solution is to check for the presence of the autotune directory folder, which means someone has enabled autotune as part of their loop, or already run it manually. See https://github.com/openaps/oref0/pull/491 for testing.

**Comment by scottleibrand** [comment]
#491 has been merged, so this is now completed.
