### ISSUE TITLE
oref0-setup.sh failed to install jq when upgrading to dev with SMB causing loop to fail

### ISSUE THREAD

**Issue by jbwittmer** [openaps/oref0#469]
Using oref0-setup.sh with the latest dev branch to update an older Edison-rig with soldered TI stick and Intel Breakout board.  Rig had never had autotune installed.  SMB was selected (using -microbolus flag) but UAM was not used.  Running oref0-pump-loop from command line revealed errors relating to jq not installed.  After installing jq manually worked properly.

**Comment by tim2000s** [comment]
How did you pull the dev branch on to the rig?

**Comment by jbwittmer** [comment]
Don't remember exactly the seqence but I think:  Git checkout dev.  Git pull.  Sudo npm run global-install

**Comment by scottleibrand** [comment]
I think that should fix it.  Please reopen if not.
