### ISSUE TITLE
Potential minor enhancements to the IOB curve calculation to increase flexibility

### ISSUE THREAD

**Issue by jeremybarnum** [openaps/oref0#474]
The current IOB curve calculation has hardcoded coefficients derived from a basic intuitive concept of the insulin activity rising from zero to a peak amount at a peak time, and then decreasing back to zero between the peak time and the DIA.  As implemented, the curve can be "stretched" or "squeezed" by changing the DIA, but the relationship between the peak time and the DIA is not configurable.  Since it's possible to calculate the area under the curve analytically, it's possible to expose the peak time to the user, and therefore have more control over the curve shape.  This could be useful as faster insulins become available.  In addition, the current curve seems to have (this may be wrong) some slightly unnatural behavior around the peak time, and the analytical implementation might help to smooth it out. The enclosed spreadsheet lays out all these points.
[OpenAPS_IOB_curve_analysis.xlsx](https://github.com/openaps/oref0/files/1015876/OpenAPS_IOB_curve_analysis.xlsx)

**Comment by AdrianLxM** [comment]
Hi, just to add some information:

@warstar2187 also added a 4 point curve (0, 2 setup points, dia). In AndroidAPS you can already choose between them:
Original:
![screenshot_2017-05-20-15-21-45](https://cloud.githubusercontent.com/assets/9692866/26276096/d3b4bd50-3d70-11e7-9b4c-5a0d32f0b9ce.png)
Prolonged (the new one):
![screenshot_2017-05-20-15-22-21](https://cloud.githubusercontent.com/assets/9692866/26276100/e5f56870-3d70-11e7-9392-d7a0b87c63f4.png)

Fiasp users report this curve to work better for them.

**Comment by jeremybarnum** [comment]
Thanks for that info - I was playing with something similar also in order to try to match published fiasp curves as it does seem like it's hard to match the fiasp curve with a "three point" curve.  Was waiting for feedback and more data to post it - glad to see it's already done!

**Comment by scottleibrand** [comment]
I think we're going to take the https://github.com/openaps/oref0/issues/544 approach to this.  Any reason to do the three-point-curve approach as well?

**Comment by jeremybarnum** [comment]
No reason I can think of.
