### ISSUE TITLE
"Auto" set maxIOB for safety

### ISSUE THREAD

**Issue by danamlewis** [openaps/oref0#475]
From the early days of OpenAPS, we designed around making sure that no one would turn on a rig without knowing what they're doing and inadvertently cause themselves harm. This included setting maxIOB to 0, meaning the rig would essentially be in predictive low glucose suspension mode (and only high temp until maxIOB returned to zero). 

However, there are two scenarios where this may be inadvertently causing worse outcomes:

- New users will mistakenly not set maxIOB, wonder why BG is high and the rig isn't doing anything to help them.
- Previous users, when running oref0-setup.sh, will forget to re-change maxIOB and go for several hours until they discover it's not high temping as expected based on settings from pre-runagain.

**Proposal:**
Upon initial setup and runagain, set maxIOB to be "auto", unless a value is otherwise specified (as usual) in preferences.json. The manually set value would override auto mode. "Auto" maxIOB would be equal to 1 hour of the current basal rate at any given time. (i.e. Basal of 0.3U/hr: maxIOB would be 0.3U. Basal of 1.2U/hr: maxIOB would be 1.2U.)

**Comment by tepidjuice** [comment]
This is an excellent idea. I'd even have a 'preserve settings' option which would keep all settings in preferences.json provided they are compatible with the update.

**Comment by mgranberry** [comment]
I don't like it.  I think a reminder to verify that max_iob is set correctly at the end of `oref0-setup.sh` would be more appropriate, although I have definitely been bitten by the second bullet point before.  It feels like I would be less likely to notice in incorrect setting this way.  At the very least I'd like to see the fact that `max_iob` is being automatically determined in`devicestatus.json`'s `reason` string for a little extra visibility.

**Comment by scottleibrand** [comment]
Should we make max_iob a required field during oref0-setup?

**Comment by mgranberry** [comment]
I'd prefer that.  At least it would be explicit.

**Comment by tomasboudr** [comment]
@scottleibrand @mgranberry - all the seconds possible on having it be in the setup script.

**Comment by danamlewis** [comment]
I'd be fine now having it asked & answered in setup script, too.

**Comment by scottleibrand** [comment]
Ok, I think I'd be fine with that, too.  Maybe we can add some verbiage suggesting people start with max IOB equal to their normal basal or something like that, to discourage people from putting in a really high value that basically disables it...

**Comment by danamlewis** [comment]
@scottleibrand let's fold it in with the other de-advancing-features branch oref0-setup.sh to test them all together (vs the original separate branch we were intending)

**Comment by danamlewis** [comment]
This is ready alongside some other oref0-setup.sh changes that are awaiting some 👍's before merging to dev: https://github.com/openaps/oref0/pull/486

**Comment by tomasboudr** [comment]
trying it... does this branch include oref1 stuff as well?

**Comment by scottleibrand** [comment]
Yes, this branch is based off of dev, so you can enable oref1 features the same way you would there.

**Comment by tomasboudr** [comment]
should the script have asked me for maxIOB? 
I got a 0 value

**Comment by danamlewis** [comment]
@tomasboudr see https://github.com/openaps/oref0/pull/486#issuecomment-305347753

**Comment by tomasboudr** [comment]
I used the de-advanced-features branch.. was that correct?

**Comment by danamlewis** [comment]
ha. nope. see this PR (https://github.com/openaps/oref0/pull/486) - it's the auto-maxIOB branch that I ended up doing all the work on. waiting to pull a few things from de-advancifying features branch in before deleting that. sorry for confusion!

**Comment by tomasboudr** [comment]
Got it. Tested and it worked +1!

**Comment by danamlewis** [comment]
Implemented in dev with https://github.com/openaps/oref0/pull/486. Closing as an issue.
