### ISSUE TITLE
Too many NewTimeSet with oref1

### ISSUE THREAD

**Issue by PieterGit** [openaps/oref0#477]
@scottleibrand 

Will debug into it later, but here is the screenshot. The rig will update the time quite a number of times...

![image](https://cloud.githubusercontent.com/assets/6500826/26329363/34f9fd46-3f47-11e7-9ec8-3c5d105b9508.png)

**Comment by danamlewis** [comment]
@pietergit this is the first time I've seen it reported - not happened on my pump.

**Comment by scottleibrand** [comment]
Would need to see pump-loop.log to see what the mismatch is that's causing it to reset the time, and figure out why the newly reset time is still mismatched.

**Comment by PieterGit** [comment]
```
pumphistory.json: "NewTimeSet 2017-05-22T13:12:21 head[2], body[0] op[0x18]"
Checking pump clock: "2017-05-22T13:13:55+02:00" is within 1m of current time: Mon May 22 13:16:28 CEST 2017
Pump clock is more than 1m off: attempting to reset it
Waiting for ntpd to synchronize... OK!
sudo: ntpdate: command not found
Setting pump and CGM time to Mon May 22 13:16:29 CEST 2017
{
  "raw": [
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
 ...
  "requested": {
    "old": "2017-05-22T13:16:35",
    "params": [
      13,
      16,
      36,
      7,
      225,
      5,
      22
    ],
    "clock": "2017-05-22T13:16:36.864395"
  },
  "timestamp": "2017-05-22T13:16:38.109350",
  "clock": "2017-05-22T13:16:36"
}{
  "requested": {
    "clock": "2017-05-22T13:16:47.108351",
    "offset": -21486.891649
  },
  "enacted_at": "2017-05-22T13:16:47.243382",
  "result": {
    "ACK": true
  },
  "offset": -21486.0,
  "clock": "2017-05-22T13:16:47.108351"
}Error, retrying
Waiting for 30s silence before mmtuning
Radio ok. Listening: .No pump comms detected from other rigs
+ echo

+ echo The CC111x is located at /dev/spidev5.1
```

Two guesses:
- ntpdate was missing (and is not installed by default). Fixed that
- I see `Error, retrying` after the change time set (but it looks like the time is set on the pump)

**Comment by scottleibrand** [comment]
It looks like the pump clock was off by 2.5 minutes, and that run successfully set the pump clock correctly.  After that you shouldn't see any more mismatches I'd think.  Are you still getting them?  Or do you have logs from a previous instance to compare?

**Comment by PieterGit** [comment]
I saved the log and will dig into it later. Too late for now.

**Comment by Bender1061** [comment]
I see that same issue, and it seems to come in spurts, this afternoon between 1 and 4 PM, it happened 22 times.but since then it has not happed again and it did not do it all night. The Rig was also right beside me in my cargo pants pocket all day so it's not like it was away from it at any time.

**Comment by PieterGit** [comment]
@scottleibrand 
debugging it, maybe this is a clue:
```
# cat monitor/status.json
{
  "status": "normal",
  "bolusing": false,
  "suspended": false
}
```
I disabled line 70 and 71 in oref0-pump-loop.sh. I don't see why it's reporting an error and calling maybe_mmtune again:

```
 if grep -q '"suspended": true' monitor/status.json; then
            echo -n "Pump suspended; "
            smb_verify_status
        #else
        #    echo Error, retrying && maybe_mmtune
```

**Comment by PieterGit** [comment]
Didn't see this error for quite some time... But today it occured again with my branch which is quite on similar to the current dev branch. 13 NewTimeSets within 2 hours.
![image](https://user-images.githubusercontent.com/6500826/27518889-062e6e12-59ea-11e7-9674-fadb5b3f0d08.png)

**Comment by ceben80** [comment]
same issue running on my pi zero rig

![image](https://user-images.githubusercontent.com/12679825/27518915-8b153606-59ea-11e7-9775-160028f7076a.png)

**Comment by scottleibrand** [comment]
From the grey circles, and the logs I've seen, the oref0-set-device-clocks script seems to be successfully setting the pump clock, but for some reason is either setting it with a slightly-too-old time, or the subsequent time check is comparing a slightly-too-old clock reading to the rig time.  This is likely a race condition exacerbated by having a rig with a slow CPU.  We'll need to determine a couple of things:

- Is the pump time being set correctly to within a few seconds of rig time?  Or is it more than 30 seconds off?
- How much time is there between the pump clock reading (of clock.json or clock-zoned.json) and the comparison against rig time in oref0-pump-loop?

**Comment by ceben80** [comment]
I will try with my 522 today in the evening to see whether it's low cpu related or not due to the fact Pieter was running into this issue with an edison

**Comment by ceben80** [comment]
Now I've been running my pi zero rig with a 522, no issue so far, seems probably a 754 issue, not related to a slow CPU


![image](https://user-images.githubusercontent.com/12679825/27554193-ea255cb6-5aad-11e7-99f6-85a5734f5cd7.png)

```
Starting supermicrobolus pump-loop at Mon 26 Jun 20:10:07 CEST 2017 with 2 second wait_for_silence:
Waiting up to 4 minutes for new BG: glucose.json newer than pump_loop_completed
Radio ok. Listening: .No pump comms detected from other rigs
Preflight OK. Profile less than 60m old. glucose.json newer than pump_loop_completed.
Temp refreshed
Warning: Autotune has not been run. All microboluses will be disabled until you manually run autotune or add it to run nightl                             y in your loop.
{"carbs":0,"boluses":0,"mealCOB":0,"currentDeviation":0.51,"maxDeviation":9.84,"minDeviationSlope":-1.206}
{"iob":0.871,"activity":0.0038,"bolussnooze":0,"basaliob":0.871,"netbasalinsulin":0.9,"hightempinsulin":1.3,"microBolusInsuli                             n":0,"microBolusIOB":0,"time":"2017-06-26T18:10:44.000Z","lastBolusTime":0}
{"delta":-0.5,"glucose":121.5,"short_avgdelta":-0.17,"long_avgdelta":2.17}
{"duration":27,"rate":0.8,"temp":"absolute"}
Basal unchanged: 0.8; target_bg unchanged: 95; sens unchanged: 35
Carb Impact: 0.2 mg/dL per 5m; CI Duration: 0 hours; remaining 4h+ CI: 0 mg/dL per 5m
Accel. Carb Impact: 10 mg/dL per 5m; ACI Duration: 0 hours
UAM Impact: 0.5 mg/dL per 5m; UAM Duration: 0 hours
minPredBG: 91 minIOBPredBG: 91 avgPredBG: 91 COB: 0 carbs: 0
BG projected to remain above 95 for 110 minutes
bgUndershoot: 3 zeroTempDuration: 110 zeroTempEffect: 51 carbsReq: -12
Checking deliverAt: 2017-06-26T18:11:34.027Z is within 1m of current time: Mon 26 Jun 20:11:35 CEST 2017
and that smb-suggested.json is less than 1m old
enact/smb-suggested.json: {"insulinReq":0,"bg":121.5,"reservoir":"49.4","temp":"absolute","snoozeBG":92,"rate":0.45,"predBGs"                             :{"IOB":[122,121,120,120,119,117,116,114,113,111,109,108,106,104,103,102,100,99,98,97,96,95,94,94,93,92,92,92,92,92,91]},"min                             PredBG":999,"IOB":0.871,"reason":"COB: 0, Dev: 1, BGI: -0.66, ISF: 35, Target: 95, minPredBG 91, IOBpredBG 91; Eventual BG 92                              < 95, setting 0.45U/hr. ","COB":0,"eventualBG":92,"duration":30,"tick":0,"deliverAt":"2017-06-26T18:11:34.027Z"}
Temp refreshed: monitor/temp_basal.json: {"duration":26,"rate":0.8,"temp":"absolute"}
enact/smb-enacted.json: {"insulinReq":0,"bg":121.5,"reservoir":"49.4","temp":"absolute","snoozeBG":92,"recieved":true,"predBG                             s":{"IOB":[122,121,120,120,119,117,116,114,113,111,109,108,106,104,103,102,100,99,98,97,96,95,94,94,93,92,92,92,92,92,91]},"m                             inPredBG":999,"deliverAt":"2017-06-26T18:11:34.027Z","duration":30,"rate":0.45,"COB":0,"eventualBG":92,"timestamp":"2017-06-2                             6T20:11:50.043846","reason":"COB: 0, Dev: 1, BGI: -0.66, ISF: 35, Target: 95, minPredBG 91, IOBpredBG 91; Eventual BG 92 < 95                             , setting 0.45U/hr. ","tick":0,"IOB":0.871}
Temp refreshed: monitor/temp_basal.json: {"duration":30,"rate":0.45,"temp":"absolute"}
Refreshed pumphistory
pumphistory.json: "TempBasalDuration 2017-06-26T20:11:42 head[2], body[0] op[0x16]"
Checking pump clock: "2017-06-26T20:12:30+02:00" is within 1m of current time: Mon 26 Jun 20:13:15 CEST 2017
and that pumphistory is less than 1m old.  Temp refreshed
Warning: Autotune has not been run. All microboluses will be disabled until you manually run autotune or add it to run nightl                             y in your loop.
{"carbs":0,"boluses":0,"mealCOB":0,"currentDeviation":0.51,"maxDeviation":9.84,"minDeviationSlope":-1.1}
{"iob":0.859,"activity":0.0042,"bolussnooze":0,"basaliob":0.859,"netbasalinsulin":0.9,"hightempinsulin":1.3,"microBolusInsuli                             n":0,"microBolusIOB":0,"time":"2017-06-26T18:13:21.000Z","lastBolusTime":0}
{"delta":-0.5,"glucose":121.5,"short_avgdelta":-0.17,"long_avgdelta":2.17}
{"duration":29,"rate":0.45,"temp":"absolute"}
Basal unchanged: 0.8; target_bg unchanged: 95; sens unchanged: 35
Carb Impact: 0.2 mg/dL per 5m; CI Duration: 0 hours; remaining 4h+ CI: 0 mg/dL per 5m
Accel. Carb Impact: 10 mg/dL per 5m; ACI Duration: 0 hours
UAM Impact: 0.6 mg/dL per 5m; UAM Duration: 0 hours
minPredBG: 92 minIOBPredBG: 92 avgPredBG: 92 COB: 0 carbs: 0
BG projected to remain above 95 for 110 minutes
bgUndershoot: 3 zeroTempDuration: 110 zeroTempEffect: 51 carbsReq: -12
Checking deliverAt: 2017-06-26T18:13:51.584Z is within 1m of current time: Mon 26 Jun 20:13:53 CEST 2017
and that smb-suggested.json is less than 1m old
enact/smb-suggested.json: {"insulinReq":0,"bg":121.5,"reservoir":"49.3","temp":"absolute","snoozeBG":92,"predBGs":{"IOB":[122                             ,121,120,119,118,117,116,114,112,111,109,107,105,104,103,101,100,99,98,97,96,95,94,94,93,93,92]},"minPredBG":999,"IOB":0.859,                             "reason":"COB: 0, Dev: 1, BGI: -0.73, ISF: 35, Target: 95, minPredBG 92, IOBpredBG 92; Eventual BG 92 < 95, Snooze BG 92, tem                             p 0.45 ~< req 0.5U/hr. ","COB":0,"eventualBG":92,"tick":0,"deliverAt":"2017-06-26T18:13:51.584Z"}
No smb_enact needed. Temp refreshed: monitor/temp_basal.json: {"duration":28,"rate":0.45,"temp":"absolute"}
No bolus needed (yet). Settings less than 10m old
Edison battery level not found. Pumphistory-24 < 20m old
Completed supermicrobolus pump-loop at Mon 26 Jun 20:14:17 CEST 2017:

```

**Comment by scottleibrand** [comment]
Could also be related to what time setting the pump starts out with. If it's slightly ahead of rig time, it may never get into this time set loop in the first place.

**Comment by tim2000s** [comment]
Just to add in on this, I've never seen this issue running a 722 pump, so I suspect the linkage to an x54 may be on to something.

**Comment by PieterGit** [comment]
@Bender1061 Can you also confirm that you have a x54 pump? Then we can link this issue to x54 pumps.
I have the issue with a 754ww pump, with an Edison/Explorer board, so I also doubt it's a CPU issue.

**Comment by PieterGit** [comment]
Idea: Can it be that the `openaps use $CGM UpdateTime --to now` `oref0-set-device-clocks` causes the pump loop to stall (because the cgm is busy reading the CGM value). I disabled the CGM time sync to see if that fixes the problem.

**Comment by scottleibrand** [comment]
It would probably be a good idea, regardless of whether it's contributing to this problem, to do an `lsusb` check to see if there's a connected CGM receiver (if oref0 is configured for one) before trying to set the CGM time.  (We would need to be careful not to do the `lsusb` check if the rig is configured for `openxshareble` though.)  Anyone want to take that on?  Might also be good to prettify the pump-loop.log output when oref0-set-device-clocks runs, too...

**Comment by PieterGit** [comment]
ok, i'll first want to understand what's going wrong, but improving the pump logging is a good idea.
let's keep some verbose logging in the mean time.

**Comment by ceben80** [comment]
`openaps use $CGM UpdateTime --to now` doesn't work

```
root@pi-zero:~/myopenaps# openaps use $CGM UpdateTime --to now
usage: openaps-use [-h] [--format {text,json,base,stdout}] [--output OUTPUT]
                   [--version]
                   device ...
openaps-use: error: argument device: invalid choice: 'UpdateTime' (choose from u'cgm', u'detect-sensitivity', u'determine-basal', u'get-profile', u'iob', u'meal', u'ns', u'ns-glucose', u'oref0', u'pebble', u'pump', u'tz', u'units', u'xdrip')
```
SetTime was set but not every minute....(pi zero w/ 522)

![image](https://user-images.githubusercontent.com/12679825/27580413-c38dc674-5b2a-11e7-90c6-33f8b5ea1dd5.png)

Here the log w/ debug

```
Checking pump clock: "2017-06-27T11:15:58+02:00" is within 1m of current time: Tue 27 Jun 11:17:09 CEST 2017
Pump clock is more than 1m off: attempting to reset it
DEBUG1: Tue 27 Jun 11:17:10 CEST 2017 11:17:10 up 16:43, 6 users, load average: 7.41, 5.35, 4.79
Pump time "2017-06-27T11:17:25"

-rw-r--r-- 1 root root 27 Jun 27 11:16 monitor/clock-zoned.json
"2017-06-27T11:15:58+02:00"
Waiting for ntpd to synchronize... OK!
Setting pump and CGM time to Tue 27 Jun 11:17:32 CEST 2017
{
  "raw": [
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0
  ],
  "requested": {
    "old": "2017-06-27T11:17:42",
    "params": [
      11,
      17,
      43,
      7,
      225,
      6,
      27
    ],
    "clock": "2017-06-27T11:17:43.458950"
  },
  "timestamp": "2017-06-27T11:17:44.395563",
  "clock": "2017-06-27T11:17:44"
}Traceback (most recent call last):
  File "/usr/local/bin/openaps-use", line 63, in <module>
    app( )
  File "/usr/local/lib/python2.7/dist-packages/openaps/cli/__init__.py", line 51, in __call__
    self.run(self.args)
  File "/usr/local/bin/openaps-use", line 57, in run
    output = app(args, self)
  File "/usr/local/lib/python2.7/dist-packages/openaps/uses/__init__.py", line 92, in __call__
    return self.method.selected(args)(args, app)
  File "/usr/local/lib/python2.7/dist-packages/openaps/uses/__init__.py", line 31, in __call__
    return self.method(args, app)
  File "/usr/local/lib/python2.7/dist-packages/openaps/uses/use.py", line 45, in __call__
    output = self.main(args, app)
  File "/usr/local/lib/python2.7/dist-packages/openaps/vendors/dexcom.py", line 130, in main
    program = self.get_program(args)
  File "/usr/local/lib/python2.7/dist-packages/openaps/vendors/dexcom.py", line 124, in get_program
    current_utc = self.dexcom.ReadSystemTime( )
AttributeError: 'NoneType' object has no attribute 'ReadSystemTime'
DEBUG2:
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
DEBUG3:
root      2803  2755  0 11:10 ?        00:00:00 /bin/sh -c cd /root/myopenaps && ( ps aux | grep -v grep | grep bash | grep -q 'bin/oref0-pump-loop' || oref0-pump                        -loop --microbolus ) 2>&1 | tee -a /var/log/openaps/pump-loop.log
root      2819  2803  0 11:10 ?        00:00:00 /bin/bash /usr/local/bin/oref0-pump-loop --microbolus
root      2820  2803  0 11:10 ?        00:00:00 tee -a /var/log/openaps/pump-loop.log
root      2997  2899  0 11:10 ?        00:00:00 bash -c date; (find settings/ -newer settings/autosens.json | grep -q pumphistory-24h-zoned.json || find settings/                         -size -5c | grep -q autosens.json || ! find settings/ | grep -q autosens || ! find settings/autosens.json) && openaps invoke settings/autosens.json
root      3043  3013 28 11:10 ?        00:02:07 node /usr/local/bin/oref0-detect-sensitivity monitor/glucose.json settings/pumphistory-24h-zoned.json settings/ins                        ulin_sensitivities.json settings/basal_profile.json settings/profile.json
root      3387  2819  0 11:11 ?        00:00:00 /bin/bash /usr/local/bin/oref0-pump-loop --microbolus
root      4460  3387  0 11:15 ?        00:00:00 /bin/bash /usr/local/bin/oref0-pump-loop --microbolus
root      4997  1906  0 11:16 pts/3    00:00:00 tail -F /var/log/openaps/pump-loop.log
root      5382  5291  1 11:17 ?        00:00:00 grep pump
DEBUG4:
Pump time "2017-06-27T11:18:18"

DEBUG5:  Tue 27 Jun 11:18:24 CEST 2017 11:18:24 up 16:45, 6 users, load average: 5.23, 5.05, 4.72
Error, retrying
Sleeping 5;

Starting supermicrobolus pump-loop at Tue 27 Jun 11:18:30 CEST 2017 with 3 second wait_for_silence:
Waiting up to 4 minutes for new BG: glucose.json newer than pump_loop_completed
```

**Comment by ceben80** [comment]
Now changed back to 754, same behaviour as 522, but the Q is why does this issue occur on a 754 w/ edison?

![image](https://user-images.githubusercontent.com/12679825/27595642-8a95467a-5b5d-11e7-8da9-1338c647c314.png)

**Comment by PieterGit** [comment]
On an Edison I don't experience it that much. Only once in about a week or so.
I noticed your CPU is quite busy (uptime `load average: 7.41, 5.35, 4.79` which shows CPU-load from 
last minute/5 minutes/15 minutes.). That should be around equal to the number of CPU cores (1 core on a Pi Zero, 2 cores on an Edison).
I noticed that under severe load pump communication seems to be able to fail.

The command `openaps use cgm UpdateTime --to now` (notice if you want to run it from the command line you must use expand
`$CGM` to the name of your `cgm`) only works if you use a Dexcom attached to USB. You can comment that line out if you use xdrip.

I can't figure out why you have 3 SMB-pump loops running (2819, 3387, 4460), maybe that is a cause of the high CPU usage and the pump errors.
But I can't figure out why there are three `/bin/bash /usr/local/bin/oref0-pump-loop --microbolus` running

Can you change `oref0-set-device-clocks` to:
```
esac

echo "DEBUG1:" `date` `uptime`
echo "Pump time"  `openaps use pump read_clock`
echo
echo `date` `uptime`
ls -al $CLOCK
cat $CLOCK
echo

checkNTP() { ntp-wait -n 1 -v || ( sudo /etc/init.d/ntp restart && ntp-wait -n 1 -v ) }

if checkNTP; then
    sudo ntpdate -s -b time.nist.gov
    echo Setting pump and CGM time to $(date)
    openaps use $PUMP set_clock --to now
    echo "DEBUG2:" `date`
    lsusb
    echo "DEBUG3:"
    ps -ef | grep pump
    #openaps use $CGM UpdateTime --to now
fi
echo "DEBUG4:" `date` `uptime`
echo Pump time `openaps use pump read_clock`
echo
echo "DEBUG5: " `date` `uptime`
```

**Comment by ceben80** [comment]
@PieterGit I have changed the above and made some overclocking stuff for the zero ;)
`arm_freq=1000 and force_turbo=1` in `/boot/config.txt`
will post when I have new logs....1st impression, runs more faster ;)

**Comment by ceben80** [comment]
running the pi zero with overclocking parameter doesn't show "NetSetTime" anymore (60 min w/o NewSetTime), using top, max. cpu load was 55%

![image](https://user-images.githubusercontent.com/12679825/27646047-f4d421a8-5c27-11e7-8d77-b0959c0c3cc2.png)

![image](https://user-images.githubusercontent.com/12679825/27645991-df06e572-5c27-11e7-9cd5-38b96e1ff00b.png)

![image](https://user-images.githubusercontent.com/12679825/27645941-c51839f4-5c27-11e7-8cfe-db8633804536.png)

**Comment by ceben80** [comment]
yeah 🎉 🌟 🎊 , 2 hours w/o NewTimeSet

![image](https://user-images.githubusercontent.com/12679825/27648497-0eadef94-5c2f-11e7-833a-b9649fe71e6c.png)

**Comment by scottleibrand** [comment]
Could someone also test the https://github.com/openaps/oref0/pull/509 fix against a rig that still experiences the issue?

**Comment by scottleibrand** [comment]
Per @ceben80's testing, it looks like https://github.com/openaps/oref0/pull/509 should address this, at least on the Pi Zero.  If anyone else has another rig experiencing the issue, please try this fix:

```
cd ~/src/oref0
git fetch
git checkout clock-after-history
git pull
```

No oref0-setup or other install should be needed if you're already running oref1.

**Comment by PieterGit** [comment]
I manually added the line to my Edison rig. I think this is a good solution. I can only say that it works after about two weeks no (or only one) timeset). I will monitor.
