### ISSUE TITLE
Expected Delta fails to low temp when BG is falling but not as fast as expected

### ISSUE THREAD

**Issue by audiefile** [openaps/oref0#48]
For example, here a low temp basal was ended because Avg Delta > Expected Delta, even though Eventual BG was much lower than min set. 
![screenshot_2015-12-16-23-06-55 2](https://cloud.githubusercontent.com/assets/8140689/11861703/b3d05bc6-a450-11e5-9024-a8ed07ddfcba.jpg)

**Comment by jasoncalabrese** [comment]
Think we can close this since #47 was merged
