### ISSUE TITLE
Some oref1 users have null/0 CSF reported; bonks autotune report despite valid calculations

### ISSUE THREAD

**Issue by danamlewis** [openaps/oref0#480]
2+ oref1 users are seeing autotune reports that don't show the tuned results, because somehow CSF is getting translated as 0. It complains about  https://github.com/openaps/oref0/blob/master/bin/oref0-autotune-recommends-report.sh#L72 by erroring "/usr/local/bin/oref0-autotune-recommends-report: line 72: printf: null: invalid number" in the logs

```
Autotune pump profile recommendations:
---------------------------------------------------------
Recommendations Log File: /root/johnopenaps/autotune/autotune_recommendations.log

/usr/local/bin/oref0-autotune-recommends-report: line 72: printf: null: invalid number
Parameter      | Current  | Autotune 
-------------------------------------
ISF            | 30.000   | 30.000   
CSF            | n/a      | 0.000    
Carb Ratio     | 10.000   | 10.000   
  00:00        | 1.750    | 1.750    
  03:30        | 1.650    | 1.650    
  06:00        | 1.650    | 1.650    
  08:30        | 1.650    | 1.650    
  11:30        | 2.000    | 2.000    
  13:00        | 2.150    | 2.150    
  15:30        | 1.900    | 1.900    
  19:00        | 3.000    | 3.000    
  22:00        | 3.000    | 3.000
```

but actually does do the calculations, shown in the logs above that, i.e.:
```
  { i: 21, start: '21:00:00', rate: 3, minutes: 1260 },
  { i: 22, start: '22:00:00', rate: 3, minutes: 1320 },
  { i: 23, start: '23:00:00', rate: 3, minutes: 1380 } ]
p50deviation: -1.59 p50BGI -2.8600000000000003 p50ratios: 1.682 Old ISF: 30 fullNewISF: 50.46 adjustedISF: 40.230000000000004 newISF: 31.023
totalMealCarbs: 58 totalDeviations: 481.73999999999984 fullNewCSF: 8.31 newCSF: 3.531
```

**Comment by danamlewis** [comment]
The short-term fix if you notice your CSF being 0 is to do a manual run of autotune, and consider whether you want to manually adjust your underlying pump values. This doesn't harm loop performance, but just renders autotune ineffective as it's keeping the pump-set values.

**Comment by ceben80** [comment]
@danamlewis here is my 'autotune_recommendations.log' from last night, no deviations

```
root@eddie-eb:~/myopenaps/autotune# cat autotune_recommendations.log
Parameter      | Current  | Autotune
-------------------------------------
ISF            | 35.000   | 30.000
CSF            | n/a      | 0.000
Carb Ratio     | 9.000    | 9.000
Basal Profile  |          |
  00:00        | 1.200    | 1.200
  00:30        |          |
  01:00        | 1.100    | 1.100
  01:30        |          |
  02:00        | 1.100    | 1.100
  02:30        |          |
  03:00        | 1.100    | 1.100
  03:30        |          |
  04:00        | 1.300    | 1.300
  04:30        |          |
  05:00        | 1.300    | 1.300
  05:30        |          |
  06:00        | 1.500    | 1.500
  06:30        |          |
  07:00        | 1.500    | 1.500
  07:30        |          |
  08:00        | 1.500    | 1.500
  08:30        |          |
  09:00        | 1.200    | 1.200
  09:30        |          |
  10:00        | 1.200    | 1.200
  10:30        |          |
  11:00        | 1.200    | 1.200
  11:30        |          |
  12:00        | 0.800    | 0.800
  12:30        |          |
  13:00        | 0.800    | 0.800
  13:30        |          |
  14:00        | 0.800    | 0.800
  14:30        |          |
  15:00        | 0.800    | 0.800
  15:30        |          |
  16:00        | 0.800    | 0.800
  16:30        |          |
  17:00        | 0.800    | 0.800
  17:30        |          |
  18:00        | 0.800    | 0.800
  18:30        |          |
  19:00        | 0.800    | 0.800
  19:30        |          |
  20:00        | 0.800    | 0.800
  20:30        |          |
  21:00        | 0.800    | 0.800
  21:30        |          |
  22:00        | 0.800    | 0.800
  22:30        |          |
  23:00        | 0.800    | 0.800
  23:30        |          |
```
The corresponding files:

```
root@eddie-eb:~/myopenaps/autotune# ls -tl
total 5256
-rw-r--r-- 1 root root  34406 May 25 00:08 autotune.2017-05-25-000505.log
-rw-r--r-- 1 root root   2052 May 25 00:08 autotune_recommendations.log
-rw-r--r-- 1 root root   2917 May 25 00:08 newprofile.1.2017-05-24.json
-rw-r--r-- 1 root root  92136 May 25 00:08 autotune.1.2017-05-24.json
-rw-r--r-- 1 root root   2876 May 25 00:05 profile.1.2017-05-24.json
-rw-r--r-- 1 root root 197392 May 25 00:05 ns-entries.2017-05-24.json
-rw-r--r-- 1 root root 182537 May 25 00:05 ns-treatments.json
-rw-r--r-- 1 root root   2876 May 25 00:05 profile.json
-rw-r--r-- 1 root root   2880 May 25 00:05 profile.pump.json
```
and in ` /var/log/openaps/autotune.log` same as above

`/usr/local/bin/oref0-autotune-recommends-report: line 72: printf: null: invalid number`

for me no problem at all regards with autotune, my basal is tuned well, but FYI

**Comment by tim2000s** [comment]
How have those who have installed oref1 and are seeing this issue done it? Both of my rigs Running oref1 I've archived the myopenaps directory before reinstalling using setup and had no issues. What did those seeing issues do toninstall oref1?

**Comment by ceben80** [comment]
my rig here I have completely re-flashed with the new jubi, afterwards orf1 install on a blank box a few weeks ago.....

**Comment by davidkeddydb** [comment]
I enabled autotune by going into oref0-runagain.sh and enabling it and then rerunning set up.  I have not done autotune from initial set up install to see if issue still happens then but I will. Here is my autotune file:
root@dke5:~/dke5/autotune# cat autotune_recommendations.log
Parameter      | Current  | Autotune 
-------------------------------------
ISF            | 65.000   | 65.000   
CSF            | n/a      | 0.000    
Carb Ratio     | 11.000   | 11.000   
Basal Profile  |          |          
  00:00        | 1.000    | 1.000    
  00:30        |          |          
  01:00        |          |          
  01:30        |          |          
  02:00        |          |          
  02:30        |          |          
  03:00        | 1.000    | 1.000    
  03:30        |          |          
  04:00        |          |          
  04:30        |          |          
  05:00        |          |          
  05:30        |          |          
  06:00        |          |          
  06:30        |          |          
  07:00        |          |          
  07:30        |          |          
  08:00        |          |          
  08:30        | 0.600    | 0.600    
  09:00        |          |          
  09:30        |          |          
  10:00        |          |          
  10:30        |          |          
  11:00        |          |          
  11:30        |          |          
  12:00        |          |          
  12:30        |          |          
  13:00        | 1.600    | 1.600    
  13:30        |          |          
  14:00        |          |          
  14:30        |          |          
  15:00        | 1.300    | 1.300    
  15:30        |          |          
  16:00        |          |          
  16:30        |          |          
  17:00        |          |          
  17:30        |          |          
  18:00        |          |          
  18:30        |          |          
  19:00        |          |          
  19:30        |          |          
  20:00        | 1.100    | 1.100    
  20:30        |          |          
  21:00        |          |          
  21:30        |          |          
  22:00        |          |          
  22:30        |          |          
  23:00        |          |          
  23:30        |          |

**Comment by zjedr** [comment]
I am getting this issue as well, it is a fresh install on a new edison, about a week old. Has only had dev installed and have run oref0-setup multiple times, currently enabling 'meal microbolus autotune'

**Comment by hilarykoch** [comment]
I'm having this issue as well. I had run oref1 a week ago for a few days and when I ran autotune last weekend, I noticed the 0 for csf. I switched to a rig running oref0 for the wee, and while my son's basals are fairly well tuned, autotune on oref0 was making slight suggestions during the week. I did a fresh install and started running oref1 again last night. My autotune report shows null for csf and suggests no changes for basals. So I'm looking at this report and thinking not only is it not accurate, I'm assuming it means basals were not tweaked (again even if slightly). Thinking longterm, it would of course negate the benefits of using autotune. 
<img width="648" alt="screen shot 2017-05-28 at 9 37 13 am" src="https://cloud.githubusercontent.com/assets/11912289/26529238/6c5deb16-438a-11e7-8f6f-c69c3c68a96a.png">

**Comment by hilarykoch** [comment]
This is an autotune from our rig running oref0, you can see it has made some adjustments. 
<img width="607" alt="screen shot 2017-05-28 at 10 00 57 am" src="https://cloud.githubusercontent.com/assets/11912289/26529369/c65bb146-438c-11e7-8760-858fbc1db03b.png">

**Comment by zjedr** [comment]
The master version of oref0-autotune.sh:207 copies the new profile back over profile.json to be picked up by next iteration of the loop, I can't see where this is done in dev.
Adding the copy line onto my rig seems to have fixed the issue.

**Comment by hilarykoch** [comment]
Any chance you could PR a fix for this? We're using the remainingCarbsFraction branch, and I'd love to be able to have this working again. :)

**Comment by danamlewis** [comment]
@ceben80 @davidkeddydb can one or both of you try https://github.com/openaps/oref0/pull/484#issuecomment-304707629, and if that fixes it, please comment on the PR so we can merge it in to dev?

**Comment by davidkeddydb** [comment]
Dana,

Not sure if I respond back by email if you get it or not, but here it goes.

I should be able to try the prescribed fix on my rig at home later this evening.  Will update once complete.


David Eddy
President
NEFCO Fire Investigations
www.nefco.net
(800) 675-8500

Submit an assignment<http://extranet.nefco.net/client.php>

**Comment by danamlewis** [comment]
Resolved via https://github.com/openaps/oref0/pull/484, so closing.
