### ISSUE TITLE
Radio error when updating preferences in oref1

### ISSUE THREAD

**Issue by hilarykoch** [openaps/oref0#482]
I had a weird error appear when I was updating my preferences in json. I had to exit json, go back in, and the same error appeared. I rebooted the rig, went back into preferences, and it happened again. I was able to update my preferences and everything appears to be working, but I'm not sure why this error appeared. 
<img width="747" alt="radio error" src="https://cloud.githubusercontent.com/assets/11912289/26524710/47421ce2-430a-11e7-9362-32c28542a11f.png">

**Comment by dramageek** [comment]
Hmm. Does the time change, or is it always 2017-05-27 11:54? Were you running a reinstall at that time?
Guessing here: the reboot broadcast announcement was sent as you were running the install, and it got written into the file? I can't think of any way that opening the file could make the radio-reboot run.

**Comment by Kdisimone** [comment]
Had you just rerun a loop install?  

That message will show up about three times after a loop reinstall, if you don't remove the crontab before reinstalling.  But, i've found it is best just to wait it out.  exit the editor, wait until the message passes about three times, and then you'll usually see a "canceled reboot" message.  Then you know the message is done interfering with your view and can finish the edits

**Comment by danamlewis** [comment]
@Kdisimone I just attempted to fix radio reboot during install via https://github.com/openaps/oref0/commit/ac794512333eaa60503660e90a3f202018ebdd32. (So it's part of the PR with autotune check if you want to kill two birds with one stone on testing: https://github.com/openaps/oref0/pull/491)

**Comment by scottleibrand** [comment]
Fixed in dev.  Closing.
