### ISSUE TITLE
Calculate oref0 carbsReq if eventualBG < min_bg

### ISSUE THREAD

**Issue by PieterGit** [openaps/oref0#483]
As discussed with @danamlewis  on  https://gitter.im/nightscout/intend-to-bolus?at=592b2fbffcbbe1891c5385e2

Current https://github.com/openaps/oref0/blob/dev/lib/determine-basal/determine-basal.js calculates carbsReq for the situation `BG undershoot, minus effect of 30m zero temp, converted to grams, minus COB`

But if a BG prediction will expect a hypo within X minutes it would also be good to warn the user intervention is required to prevent a hypo (i.e. eat more carbs or do less physical activity).

This is currently a TODO in the code https://github.com/openaps/oref0/blob/dev/lib/determine-basal/determine-basal.js#L567

I would think something like this is needed:

Set `hypoExpected` to number of minutes that a hypo is expected in either the UAM, COB, aCOB or IOB BG array. E.g. 
```
 "predBGs": {
    "UAM": [  100,  90,  80, ... ] ,
     "IOB": [ 90, 80, 70, ...],
 } 
```
will return `hypoExpected=10` minutes (because second value of IOB  is `<= 80` and each position represent 5 minutes).

Do an estimate of the `carbsReq` in this case.
Is that something like the difference between the `target_bg` and the minimal expected prediction BG, e.g.
`var carbsReq= (target_bg -  minPredBG ) / csf - meal_data.mealCOB`

@scottleibrand @danamlewis : can you help me with this one. I'll try to PR it.

**Comment by scottleibrand** [comment]
I think we're now doing this in dev.  @PieterGit can you test it out, and let us know if anything is missing?
