### ISSUE TITLE
0.2.0-dev max_iob .5 gets error

### ISSUE THREAD

**Issue by kenkotch** [openaps/oref0#495]
pulled a fresh dev and in setup input 4.5 as max_iob
setup was successful but max_iob didnt work. 
error message (with some extra):
└── oref0@0.5.0-dev  -> /root/src/oref0
Checking mmeowlink installation
Version: 0.11.0
/root/src/oref0/bin/oref0-setup.sh: line 489: [[: 4.5: syntax error: invalid arithmetic operator (error token is ".5")
/root/src/oref0/bin/oref0-setup.sh: line 493: [[: 4.5: syntax error: invalid arithmetic operator (error token is ".5")
{
	"max_iob": 0,
...

If it is relevant, I setup w/ bluetooth, enabled autosens, autotune and ama. also put in my pushover tokens

**Comment by scottleibrand** [comment]
Yes, that it a known limitation of trying to do floating point arithmetic in bash.  As a workaround, you can set the max_iob to 4 or 5, and then adjust your max_iob to 4.5 in preferences.json after finishing oref0-setup.  If anyone cares to rework oref0-setup to support fractional max_iob's (or to instruct the user to enter a whole number), PRs are welcome.

**Comment by kenkotch** [comment]
Dana wasn't sure. Thanks for clarifying. I'm /trying/ to learn floats in bash and how to push it to its limit

**Comment by scottleibrand** [comment]
Closing this for now.  Feel free to reopen if you decide to attempt a fix.
