### ISSUE TITLE
"ValueError: Invalid GPIO pin specified" error after script install

### ISSUE THREAD

**Issue by jbwittmer** [openaps/oref0#500]
Multiple users reporting error "ValueError: Invalid GPIO pin specified" in pump-loop log after new flash and install of openaps using both Jubilinux 0.1.0 and 0.1.1 on both master and dev branches.

**Comment by Stavrosnco** [comment]
In case it helps, it seems possible this issue has arisen in the past week as I flashed an edison and had it running fine on the dev branch on 6/15 and then flashed on today and got this error.

**Comment by jbwittmer** [comment]
I built two rigs on either 6/17 or 6/18 -  and they both worked - so something changed even more recently than 6/15.

**Comment by Stavrosnco** [comment]
A temporary and ugly work around can be achieved by the following:
Navigate to a directory you can make a new directory in without getting it mixed up with your openAPS directory. I just put mine in /home/test
`
git clone https://github.com/intel-iot-devkit/mraa.git
cd mraa/
git reset --hard e0052acfa7ab441b5417a0fbd010ce77b285a4d8
mkdir build
cd build
cmake -DBUILDSWIGNODE=OFF ..
make
sudo make install
reboot
`

**Comment by jbwittmer** [comment]
This temporary fix seems to have worked for me as well

**Comment by jbwittmer** [comment]
https://github.com/openaps/oref0/pull/501

Above is my attempt at changing oref0-setup.sh to pull the  e0052acfa7ab441b5417a0fbd010ce77b285a4d8 branch instead of master branch.  Haven't been able to test yet.

**Comment by PieterGit** [comment]
@KDisimone @jbwittmer : you probably can best use the latest mraa release, https://github.com/intel-iot-devkit/mraa/releases/tag/v1.7.0 instead of a specific commit.

Did one of you create an issue at https://github.com/intel-iot-devkit/mraa/ because one of their latests commits broke openaps?

**Comment by jburke41** [comment]
This may be a very dumb questions--I am unsure how to make a new directory in order to fix this error

**Comment by PieterGit** [comment]
@scottleibrand asked me to create a fix. I added another pull request. I tested the git commands, but don't have a spare Explorer rig available.

**Comment by PieterGit** [comment]
I created an issue upstream: https://github.com/intel-iot-devkit/mraa/issues/771

@kdisimone @jbwittmer or @Stavrosnco. Can you check your `/var/log` files (e.g. `/var/log/messages`, `/var/log/daemon.log`  to see if there messages from the MRAA libraries that may be of help to the MRAA developers and post them in the upstream issue.

That way we can change openaps dev branch back to master once the MRAA issue is fixed.

**Comment by Stavrosnco** [comment]
I was able to test this fix on the master branch and can happily report I have a rig looping successfully again!
