### ISSUE TITLE
openaps failed just after local midnight - suspect autotune may have broken something

### ISSUE THREAD

**Issue by mhaeberli** [openaps/oref0#506]
This issue is being created to track an item mentioned on gitter a few days ago - a diagnostic .zip file has already been sent to @scottleibrand .  openaps had been configured here with autotune / autosens - the problem was eventually solved by re-running oref0-runagain with autotune and autosens off.  iob.json kept on coming back empty, which contributed to the failure to loop.

**Comment by scottleibrand** [comment]
Zip file was corrupt.  We can reopen if you get a non-corrupted version you can send me.
