### ISSUE TITLE
Unable to initialize libusb: -99 errors with Dexcom

### ISSUE THREAD

**Issue by PieterGit** [openaps/oref0#527]
Dexcom G4 connected to USB OTG to a new Explorerboard and powered with a Zendure powerbank.
When I charge the Zendure the power on the USB UART is very shortly unavailable.
It doesn't reboot because I have a LIPO attached to the Explorerboard.
But it will upset the USB-subsystem, causing the Dexcom to stop being able to get CGM data and to stop the pumploop after 10 minutes.

```
root@edison# lsusb
unable to initialize libusb: -99
```
Workaround I have is to add a crontab entry
```
*/15 * * * * /usr/bin/lsusb || shutdown -r now "lsusb error"
```

I think it might be related to the combination of Dexcom G4  and Linux Kernel.
```
root@edison# openaps use cgm GetFirmwareHeader
{
  "DexBootVersion": "6",
  "RFVersion": "1.0.0.28",
  "ApiVersion": "2.3.0.0",
  "ProductName": "Dexcom G4 Receiver",
  "SoftwareNumber": "SW10324",
  "TestApiVersion": "2.4.0.0",
  "SchemaVersion": "1",
  "PortVersion": "4.6.4.60",
  "FirmwareVersion": "2.0.1.216",
  "ProductId": "G4Receiver"
}
root@edison# uname -a
Linux lou78 3.10.98-poky-edison #5 SMP PREEMPT Tue Apr 4 22:42:44 EDT 2017 i686 GNU/Linux
```

Questions:
1. Does anybody else also experience this behaviour?
2. What kernel (`uname -r`) and Dexcom version do they use (`openaps use cgm GetFirmwareHeader`)?
3. Should create a PR for this? I see three types of implementation in oref0-setup.sh
- Default for `CGM=G4-upload` 
- Optional: As a question/command line item
- Integrate it with the cgm-loop after 10 minutes of no CGM

**Comment by PieterGit** [comment]
@jbwittmer: since you have the same type of receiver? Can you tell me if you also experience this problem?

**Comment by scottleibrand** [comment]
Another workaround is to get a power bank that supports pass through charging, like the Tecknet one. 

Would still be worthwhile trying to reboot if both NS and USB are unavailable. Wouldn't want to always reboot on lsusb -99, though, as that would mean constant reboots when the Dexcom receiver is unplugged.

**Comment by PieterGit** [comment]
Zendure supports passthrough, but seems to be interrupted very shortly that breaks the Edisons USB-system with the old kernel. I didn't realize the lsusb -99 already appear after unplugging, so I'll go vfor option three. Should I make it configurable, or just log into cgm-loop.log and reboot the rig just like we do for the spidev pump communication failures.

**Comment by scottleibrand** [comment]
Yeah, lsusb always shows -99 when nothing is plugged in.

I'm not sure what behavior we want if someone configures g4-upload, doesn't have a G4 receiver plugged in, and goes offline.  Do we want it to reboot every 15m?  Ideally not.  Maybe only reboot if  BG is old, but uptime is longer than oldest BG time?

**Comment by jbwittmer** [comment]
I am not sure.  I have not had any luck trying to use Explorer/Edison in offline mode but haven't ever been in a position to troubleshoot why.  We just got back from Glacier NP (and were offline for an entire week) and just used the old Raspberry Pi rig for night time looping (which was bulletproof) after the Edison rigs quit looping.  I didn't have the right equipment to log in and troubleshoot why.   I'll see if I can reproduce

**Comment by jyaw** [comment]
I just started using my Edison rig for offline in the last week and used my zendure after the other battery died... Seems like I may have had the same experience you did. I had to reboot a couple times but haven't looked back thru the logs. Will see if I can look at it tonight. If you find a good solution, please share!

**Comment by PieterGit** [comment]
Fix was much easier than I thought. I created https://github.com/openaps/oref0/pull/528
@scottleibrand please review
@jbwittmer and @jyaw can you give it a test to see if it works for you as well
I tested it and I think it won't harm users that don't use the Dexcom G4 connected to USB OTG port.

**Comment by PieterGit** [comment]
Found some issues, see https://github.com/openaps/oref0/pull/528 for details.

**Comment by danamlewis** [comment]
Seems resolved elsewhere? Closing, please reopen if still an issue not tackled by 0.6.1 or the 0.7.0 work.
