### ISSUE TITLE
Treatments upload to NS not reliable with MDT

### ISSUE THREAD

**Issue by betluis** [openaps/oref0#538]
Treatments upload to NS not reliable with MDT

temp basals and boluses get uploaded to mlab/Nightsout intermittently. Certain events seem to activate these uploads then stops for hours or days. Recently tried token based uploading to NS as this PR also included some other upload fixes but did not fix it.

This issue has been also been identified by Jorge Aguilar.

**Comment by JELCRAWFORD** [comment]
Can you describe more specifically what you are seeing?  We noted difficulties with COB reporting today, with rapid decay, then no reporting of cob, then finally no reporting of COB or Bolus.  Fell back to oref0 rig with reporting of COB back. Visualization in NS still off tho. Had noted in previous few days on oref0 (just implemented dev on Sat) that we were getting NS entries/visualization from bolus wizard that would show carbs but no insulin. Is this anything like what you have been seeing?

**Comment by sulkaharo** [comment]
Which pump models and which operating system are you using to run the loop? Where are you hosting Nightscout? The only issue I know that would cause this is something creating an event in the Nightscout database that's in the future (pump event parsing failing and a future event being uploaded?) in respect to the events being decoded from the pump, the which in turn causes the uploads to stop until openaps has newer events that those in Nightscout database. This can also happen if the time zone configurations aren't applied correctly in all locations, so it might be worth checking if the openaps rig is running in the right time zone and Nightscout's zone matches this.

**Comment by betluis** [comment]
@JELCRAWFORD , @sulkaharo , thanks for your questions...
this is an issue I have had since day one back in 2016. The issue as I can see is particularly with the treatment data, i.e. bolus and temp basals not continuously updated to NS/mlab. In practice, the issue  lies in the fact that I can't see the continuous render of temp basals or boluses information in NS. It may work for a few hours and then disappear for days where the render shows only the pre-configured basal rate and no bolus information at all. I have not paid enough attention to COB to say if this data gets uploaded normally or not...

I am assuming this has to do with MDT sensor algorithms but not 100% sure about this...

Pump: 722, have tried at least 4 pumps (all 722) no change
NS host: Heroku. I was previously in Azure, same thing
Timezone: I can't see an issue with time zone, Glucose data get's perfectly displayed and in the correct timing.

@scottleibrand just recommended to update to the very latest dev version, which I will do tonight (our current version is a few weeks old) I will let you know.

**Comment by betluis** [comment]
Tried with brand new master release. No improvement unfortunately

**Comment by sulkaharo** [comment]
I know the data model of both OpenAPS and Nightscout quite well and I'm pretty sure the CGM being used cannot affect the treatment uploads (the code _and_ data storages are different). I'll read through the code that determines when to upload again in case I can figure out new potential breaking points.

**Comment by PieterGit** [comment]
I don't know if it's related, but maybe. I just tried to upgrade to node v6.11.1 and had a problem uploading cgm upload-first. After upgrading all the packages in package.json, the problem disappeared. So maybe it's not a MDT/oref0 problem, but a nodejs dependency problem.

**Comment by scottleibrand** [comment]
If you'd like to test out that hypothesis, it might be worth re-flashing the rig and reinstalling using either https://raw.githubusercontent.com/openaps/docs/dev/scripts/openaps-bootstrap.sh (for node 0.10) or https://raw.githubusercontent.com/openaps/docs/nodejs-6/scripts/openaps-bootstrap.sh (for node 6.11) and see whether the problem persists with either/both.

**Comment by betluis** [comment]
Yesterday I updated the rigs to Master 5.2 and erased all data in Mlab.. also ran openaps first upload... and ran the "fixed dabase" command in mlab... I did this because I got the memory full in mlab.... One of these actions or a combination of them fixed the issue... for the first time after almost a year, we can see a consistent basal render in nightscout as well as other treatments information. I would like to propose an update to the documentation but I really have no clue what the problem was and what fixed it... but as far as I can see, looks like we can close this issue... thanks for your support...
