### ISSUE TITLE
Disable git by default in oref0-setup

### ISSUE THREAD

**Issue by scottleibrand** [openaps/oref0#539]
Per https://github.com/openaps/openaps/issues/118 it is now possible (with some as-yet-untested code) to disable git in openaps.  We should do so by default in oref0-setup to cut down on git repository errors, but allow people to pass a flag to keep it enabled if they prefer.

**Comment by scottleibrand** [comment]
PR opened: https://github.com/openaps/oref0/pull/549

**Comment by danamlewis** [comment]
Resolved and into dev via https://github.com/openaps/oref0/pull/699, so closing.
