### ISSUE TITLE
oref0-online requires bnep0

### ISSUE THREAD

**Issue by PieterGit** [openaps/oref0#543]
@scottleibrand One issue so far...

On a fresh rpi3 rig (without using bluetooth) and 0.5.0-dev  oref0-online has an error:
```
$ oref0-online
Starting oref0-online.
At Thu 13 Jul 01:16:00 CEST 2017 my local IP is: Device "bnep0" does not exist.
```

oref0-online should also work without bnep0 device

**Comment by scottleibrand** [comment]
What would you like oref0-online to do in the absence of Bluetooth tethering?

And what is the rest of the output after that line?  As best I can tell from the script, you're just seeing the results of the second local-IP check (`ip -4 -o addr show dev bnep0 | awk '{split($4,a,"/");print a[1]}'`) erroring out.  It should still proceed to check its public IP, and if that fails, it should try cycling networking and getting new wlan0 IP.

**Comment by PieterGit** [comment]
I was on wired ethernet instead of Wifi and I think it didn't return a local IP.  I'm on WiFi now and it returns a local ip. 

```
Starting oref0-online.
At Thu 13 Jul 01:50:27 CEST 2017 my local IP is: 1.2.3.4
Device "bnep0" does not exist.
```
The spurious Device error can be surpressed by `ip -4 -o addr show dev bnep0  2> /dev/null`

**Comment by scottleibrand** [comment]
If the rest of the script works fine when you're on wifi, I think the stderr output from those commands is probably more useful to have than not.

**Comment by PieterGit** [comment]
Found a more serious issue with the script on rpi. It failed, when I don't think my WiFi was down.

```
Starting oref0-online.
At Thu 13 Jul 02:04:02 CEST 2017 my local IP is:
At Thu 13 Jul 02:04:02 CEST 2017, my wifi network name is , and my public IP is:
At Thu 13 Jul 02:04:02 CEST 2017, my wifi network name is , and my public IP is:

At Thu 13 Jul 02:04:02 CEST 2017, my wifi network name is , and my public IP is:
Error, cycling networking
Stopping networking (via systemctl): networking.service.
Starting networking (via systemctl): networking.service.
and getting new wlan0 IP
```

Will investigate further

**Comment by scottleibrand** [comment]
Looks like your wifi was down to me. iwgetid and the public IP check were both failing.
