### ISSUE TITLE
Bug w/ NS Uploading and Ubilinux on Wheezy

### ISSUE THREAD

**Issue by TC2013** [openaps/oref0#55]
This first treatment entry is NOT picked up by the OpenAPS minutes ago pill, but the second entry below it is...  Ben pointed out that non-working entry is missing " "duration": 30," at Line 5
{
    "_id": {
        "$oid": "569d4d4c2bb7e86eaf13996f"
    },
    "raw_duration": {
        "_type": "TempBasalDuration",
        "_description": "TempBasalDuration 2016-01-18T14:36:40 head[2], body[0] op[0x16]",
        "timestamp": "2016-01-18T14:36:40-06:00",
        "_body": "",
        "_head": "1600",
        "duration (min)": 0,
        "_date": "28640e5210"
    },
    "timestamp": "2016-01-18T14:36:40-06:00",
    "absolute": 0,
    "rate": 0,
    "raw_rate": {
        "_type": "TempBasal",
        "temp": "absolute",
        "_description": "TempBasal 2016-01-18T14:36:40 head[2], body[1] op[0x33]",
        "timestamp": "2016-01-18T14:36:40-06:00",
        "_body": "00",
        "_head": "3300",
        "rate": 0,
        "_date": "28640e5210"
    },
    "eventType": "Temp Basal",
    "medtronic": "mm://openaps/mm-format-ns-treatments/Temp Basal",
    "created_at": "2016-01-18T14:36:40-06:00",
    "enteredBy": "openaps://medtronic/722"
}
Working entry:
{
    "_id": {
        "$oid": "569d1e562bb7e86eaf139930"
    },
    "duration": 30,
    "raw_duration": {
        "_type": "TempBasalDuration",
        "_description": "TempBasalDuration 2016-01-18T11:16:55 head[2], body[0] op[0x16]",
        "timestamp": "2016-01-18T11:16:55-06:00",
        "_body": "",
        "_head": "1601",
        "duration (min)": 30,
        "_date": "37500b5210"
    },
    "timestamp": "2016-01-18T11:16:55-06:00",
    "absolute": 4.65,
    "rate": 4.65,
    "raw_rate": {
        "_type": "TempBasal",
        "temp": "absolute",
        "_description": "TempBasal 2016-01-18T11:16:55 head[2], body[1] op[0x33]",
        "timestamp": "2016-01-18T11:16:55-06:00",
        "_body": "00",
        "_head": "33ba",
        "rate": 4.65,
        "_date": "37500b5210"
    },
    "eventType": "Temp Basal",
    "medtronic": "mm://openaps/mm-format-ns-treatments/Temp Basal",
    "created_at": "2016-01-18T11:16:55-06:00",
    "enteredBy": "openaps://medtronic/722"
}

**Comment by bewest** [comment]
Actually, based on the data, I think it should be `duration: 0`, but looking at the code, the eventType shouldn't show up like that unless `duration` exists.

**Comment by TC2013** [comment]
This error was user cased.  I run my loop through cron, but I overlapped tasks.  Somehow the data was "misaligned" causing the observed error.  Solution: kill off processes >5min and better timing of loop.
