### ISSUE TITLE
IOB drops to zero two hours after bolus

### ISSUE THREAD

**Issue by jmcrawford** [openaps/oref0#554]
Have observed IOB is dropped to zero 2 hours after bolus,  Any remaining COB will cause OpenAPS to predict a BG rise, triggering a high-temp response.

Starting pump-loop at Wed Jul 19 08:56:03 MDT 2017:
Waiting up to 4 minutes for new BG: .............glucose.json newer than pump_loop_completed
Radio ok. Listening: .No pump comms detected from other rigs
Profile less than 60m old. glucose.json newer than temp_basal.json. Temp refreshed
{"carbs":46,"boluses":3.5,"mealCOB":8,"currentDeviation":12.56,"maxDeviation":16.98,"minDeviationSlope":-3.34}
{"iob":1.05,"activity":0.0227,"bolussnooze":0,"basaliob":-0.322,"netbasalinsulin":-0.4,"hightempinsulin":0.05,"microBolusInsulin":0,"microBolusIOB":0,"time":
"2017-07-19T14:59:04.000Z","lastBolusTime":1500469032000}
{"delta":-2,"glucose":159,"short_avgdelta":-0.47,"long_avgdelta":2.64}
{"duration":21,"rate":0.65,"temp":"absolute"}
Autosens adjusting basal from 0.375 to 0.325; Temp Target set, not adjusting with autosens; sens from 99 to 115.1 (autosens ratio 0.86)
min_bg unchanged: 80; target_bg unchanged: 80; max_bg unchanged: 80
Carb Impact: 11.1 mg/dL per 5m; CI Duration: 1.1 hours; remaining 4h+ CI: 0 mg/dL per 5m
Accel. Carb Impact: 10 mg/dL per 5m; ACI Duration: 1.2 hours
UAM Impact: 12.6 mg/dL per 5m; UAM Duration: 0.3 hours
minPredBG: 82 minIOBPredBG: 77 minCOBPredBG: 82 avgPredBG: 86 COB: 8 carbs: 46
BG projected to remain above 80 for 240 minutes
bgUndershoot: -24 zeroTempDuration: 240 zeroTempEffect: 172 carbsReq: -30
determine-basal://text/shell/enact/suggested.json
reporting enact/suggested.json
{"temp":"absolute","bg":159,"tick":-2,"eventualBG":104,"snoozeBG":104,"insulinReq":0.02,"reservoir":null,"deliverAt":"2017-07-19T14:59:18.408Z","minPredBG":82,"predBGs":{"IOB":[159,156,153,150,146,142,138,133,129,124,118,113,107,101,97,92,89,86,83,81,79,78,78,77,78,79,80,80,81,81,82,82,83,83,83,84],"aCOB":[159,155,151,148,144,140,136,132,128,124,119,115,111,106,102,97,94,90,88,86,84,83,82,82,83,84,84,85,86,86,87,87,88,88,88,89],"COB":[159,156,153,150,146,143,139,135,131,126,121,116,111,106,101,97,93,90,87,85,84,82,82,82,82,83,84,85,85,86,86,87,87,87,88,88,88,88,88,88,89]},"COB":8,"IOB":1.05,"reason":"COB: 8, Dev: 66, BGI: -13.06, ISF: 6.4, Target: 4.4, minPredBG 4.6, IOBpredBG 4.7, COBpredBG 4.9; Eventual BG 5.8 >= 4.4, 21m@0.65 > 2 * insulinReq. Setting temp basal of 0.375U/hr. ","duration":30,"rate":0.375}
enact/enacted.json: {"insulinReq":0.02,"bg":159,"reservoir":null,"temp":"absolute","snoozeBG":104,"rate":0.375,"predBGs":{"COB":[159,156,153,150,146,143,139,135,131,126,121,116,111,106,101,97,93,90,87,85,84,82,82,82,82,83,84,85,85,86,86,87,87,87,88,88,88,88,88,88,89],"aCOB":[159,155,151,148,144,140,136,132,128,124,119,115,111,106,102,97,94,90,88,86,84,83,82,82,83,84,84,85,86,86,87,87,88,88,88,89],"IOB":[159,156,153,150,146,142,138,133,129,124,118,113,107,101,97,92,89,86,83,81,79,78,78,77,78,79,80,80,81,81,82,82,83,83,83,84]},"minPredBG":82,"IOB":1.05,"reason":"COB: 8, Dev: 66, BGI: -13.06, ISF: 6.4, Target: 4.4, minPredBG 4.6, IOBpredBG 4.7, COBpredBG 4.9; Eventual BG 5.8 >= 4.4, 21m@0.65 > 2 * insulinReq. Setting temp basal of 0.375U/hr. ","COB":8,"eventualBG":104,"recieved":true,"duration":30,"tick":-2,"timestamp":"2017-07-19T08:59:23.158259","deliverAt":"2017-07-19T14:59:18.408Z"}
glucose.json newer than pumphistory. : RefreshRemoved duplicate bolus/carb entries:1
ed pumphistory
{"carbs":46,"boluses":3.5,"mealCOB":8,"currentDeviation":12.56,"maxDeviation":16.98,"minDeviationSlope":-1.886}
{"iob":-0.103,"activity":-0.0015,"bolussnooze":0,"basaliob":-0.103,"netbasalinsulin":-0.15,"hightempinsulin":0.25,"microBolusInsulin":0.2,"microBolusIOB":0.2,"time":"2017-07-19T14:59:27.000Z","lastBolusTime":1500476169000}
{"delta":-2,"glucose":159,"short_avgdelta":-0.47,"long_avgdelta":2.64}
{"duration":30,"rate":0.375,"temp":"absolute"}
Autosens adjusting basal from 0.375 to 0.325; Temp Target set, not adjusting with autosens; sens from 99 to 115.1 (autosens ratio 0.86)
min_bg unchanged: 80; target_bg unchanged: 80; max_bg unchanged: 80
Carb Impact: -2.9 mg/dL per 5m; CI Duration: 0 hours; remaining 4h+ CI: 1.5 mg/dL per 5m
Accel. Carb Impact: 10 mg/dL per 5m; ACI Duration: 1.2 hours
UAM Impact: -1.3 mg/dL per 5m; UAM Duration: 0 hours
minPredBG: 173 minIOBPredBG: 156 minCOBPredBG: 173 avgPredBG: 188 COB: 8 carbs: 46
BG projected to remain above 80 for 240 minutes
bgUndershoot: -137 zeroTempDuration: 240 zeroTempEffect: 172 carbsReq: -43
determine-basal://text/shell/enact/suggested.json
reporting enact/suggested.json
{"temp":"absolute","bg":159,"tick":-2,"eventualBG":217,"snoozeBG":173,"insulinReq":0.16,"reservoir":null,"deliverAt":"2017-07-19T15:00:14.701Z","minPredBG":173,"predBGs":{"IOB":[159,157,156,154,153,153,152,152,152,153,153,154,155,156,157,157,158,158,159,159,159,159,159,160,160,160,160,160,159,159,159,159,159,159,158,158,158,158,157],"aCOB":[159,166,174,180,186,192,197,202,207,211,214,217,220,221,222,223,224,224,225,225,225,225,225,225,225,225,225,225,225,225,225,225,225,225,224,224,224,224,223],"COB":[159,159,159,159,159,160,161,162,164,166,168,170,173,175,177,179,182,184,185,187,189,190,192,193,195,196,198,199,201,202,204,205,206,207,209,210,211,212,214,215,216,217]},"COB":8,"IOB":-0.103,"reason":"COB: 8, Dev: -8, BGI: 0.86, ISF: 6.4, Target: 4.4, minPredBG 9.6, IOBpredBG 8.7, COBpredBG 12.1; Eventual BG 12.1 >= 4.4, temp 0.375<0.65U/hr. ","duration":30,"rate":0.65}
enact/enacted.json: {"insulinReq":0.16,"bg":159,"reservoir":null,"temp":"absolute","snoozeBG":173,"rate":0.65,"predBGs":{"COB":[159,159,159,159,159,160,161,162,164,166,168,170,173,175,177,179,182,184,185,187,189,190,192,193,195,196,198,199,201,202,204,205,206,207,209,210,211,212,214,215,216,217],"aCOB":[159,166,174,180,186,192,197,202,207,211,214,217,220,221,222,223,224,224,225,225,225,225,225,225,225,225,225,225,225,225,225,225,225,225,224,224,224,224,223],"IOB":[159,157,156,154,153,153,152,152,152,153,153,154,155,156,157,157,158,158,159,159,159,159,159,160,160,160,160,160,159,159,159,159,159,159,158,158,158,158,157]},"minPredBG":173,"IOB":-0.103,"reason":"COB: 8, Dev: -8, BGI: 0.86, ISF: 6.4, Target: 4.4, minPredBG 9.6, IOBpredBG 8.7, COBpredBG 12.1; Eventual BG 12.1 >= 4.4, temp 0.375<0.65U/hr. ","COB":8,"eventualBG":217,"recieved":true,"duration":30,"tick":-2,"timestamp":"2017-07-19T09:00:19.438250","deliverAt":"2017-07-19T15:00:14.701Z"}
Settings refreshed
Edison on battery: 81%. Pumphistory-24 < 90m old
Completed pump-loop at Wed Jul 19 09:00:34 MDT 2017

Starting pump-loop at Wed Jul 19 09:01:01 MDT 2017:
Waiting up to 4 minutes for new BG: .............glucose.json newer than pump_loop_completed
Radio ok. Listening: .No pump comms detected from other rigs
Profile less than 60m old. glucose.json newer than temp_basal.json. Temp refreshed
Temp duration 27m or more
glucose.json newer than pumphistory. : RefreshRemoved duplicate bolus/carb entries:1
ed pumphistory
{"carbs":46,"boluses":3.7,"mealCOB":4,"currentDeviation":8.4,"maxDeviation":16.98,"minDeviationSlope":-2.595}
{"iob":-0.095,"activity":-0.0015,"bolussnooze":0,"basaliob":-0.095,"netbasalinsulin":-0.15,"hightempinsulin":0.25,"microBolusInsulin":0.2,"microBolusIOB":0.199,"time":"2017-07-19T15:04:16.000Z","lastBolusTime":1500476169000}
{"delta":-6,"glucose":153,"short_avgdelta":-4,"long_avgdelta":1.15}
{"duration":27,"rate":0.65,"temp":"absolute"}
Autosens adjusting basal from 0.375 to 0.325; Temp Target set, not adjusting with autosens; sens from 99 to 115.1 (autosens ratio 0.86)
min_bg unchanged: 80; target_bg unchanged: 80; max_bg unchanged: 80
Carb Impact: -6.9 mg/dL per 5m; CI Duration: 0 hours; remaining 4h+ CI: 0.7 mg/dL per 5m
Accel. Carb Impact: 10 mg/dL per 5m; ACI Duration: 0.5 hours
UAM Impact: -4.9 mg/dL per 5m; UAM Duration: 0 hours
minPredBG: 135 minIOBPredBG: 128 minCOBPredBG: 135 avgPredBG: 142 COB: 4 carbs: 46
BG projected to remain above 80 for 240 minutes
bgUndershoot: -82 zeroTempDuration: 240 zeroTempEffect: 177 carbsReq: -36
determine-basal://text/shell/enact/suggested.json
reporting enact/suggested.json
{"temp":"absolute","bg":153,"tick":-6,"eventualBG":156,"snoozeBG":135,"insulinReq":0,"reservoir":null,"deliverAt":"2017-07-19T15:04:55.795Z","minPredBG":999,"predBGs":{"IOB":[153,148,143,139,135,132,129,128,126,126,126,126,127,128,129,129,130,130,130,131,131,131,131,131,131,131,131,131,131,130,130,130,130,130,130,129,129,129,128],"aCOB":[153,156,158,159,160,159,158,156,154,154,154,154,155,156,157,157,158,158,158,159,159,159,159,159,159,159,159,159,159,159,158,158,158,158,158,157,157,157,156],"COB":[153,148,144,141,138,135,134,132,132,132,132,134,135,137,138,139,141,142,143,144,144,145,146,147,147,148,149,149,150,150,151,151,152,152,153,153,154,154,154,155,155,156]},"COB":4,"IOB":-0.095,"reason":"COB: 4, Dev: -29, BGI: 0.86, ISF: 6.4, Target: 4.4, minPredBG 7.5, IOBpredBG 7.1, COBpredBG 8.7; Eventual BG 8.7 > 4.4 but Min. Delta -6.00 < Exp. Delta -1.3; setting current basal of 0.325 as temp. ","duration":30,"rate":0.325}
enact/enacted.json: {"insulinReq":0,"bg":153,"reservoir":null,"temp":"absolute","snoozeBG":135,"rate":0.325,"predBGs":{"COB":[153,148,144,141,138,135,134,132,132,132,132,134,135,137,138,139,141,142,143,144,144,145,146,147,147,148,149,149,150,150,151,151,152,152,153,153,154,154,154,155,155,156],"aCOB":[153,156,158,159,160,159,158,156,154,154,154,154,155,156,157,157,158,158,158,159,159,159,159,159,159,159,159,159,159,159,158,158,158,158,158,157,157,157,156],"IOB":[153,148,143,139,135,132,129,128,126,126,126,126,127,128,129,129,130,130,130,131,131,131,131,131,131,131,131,131,131,130,130,130,130,130,130,129,129,129,128]},"minPredBG":999,"IOB":-0.095,"reason":"COB: 4, Dev: -29, BGI: 0.86, ISF: 6.4, Target: 4.4, minPredBG 7.5, IOBpredBG 7.1, COBpredBG 8.7; Eventual BG 8.7 > 4.4 but Min. Delta -6.00 < Exp. Delta -1.3; setting current basal of 0.325 as temp. ","COB":4,"eventualBG":156,"recieved":true,"duration":30,"tick":-6,"timestamp":"2017-07-19T09:05:00.626296","deliverAt":"2017-07-19T15:04:55.795Z"}
Settings less than 10m old
Edison on battery: 81%. Pumphistory-24 < 90m old
Completed pump-loop at Wed Jul 19 09:05:01 MDT 2017

**Comment by jmcrawford** [comment]
If oref0-calculate-iob.js is basing its' calculations based on monitor/pumphistory-zoned.json which is only the last 2 hours of activity, wouldn't this be the expected behaviour?  In which case, we'd need to use pumphistory-24h-zoned.json to be sure to capture enough history to be accurate, or increase the timespan included in pumphistory-zoned.json.

**Comment by scottleibrand** [comment]
BTW, if you're using `less` to view the pump-loop.log, you can use `less -R` to properly render the color codes.  It might be worth editing your comment above and re-pasting it that way...

**Comment by scottleibrand** [comment]
If oref0-calculate-iob.js is basing its' calculations based on monitor/pumphistory-zoned.json, that is our problem.  It should be using pumphistory-merged.json.  

And, sure enough, it looks like I forgot to update that.  I wonder why no one noticed this before it got released.  PR open: #555

**Comment by jmcrawford** [comment]
less -R - nice

**Comment by scottleibrand** [comment]
This is fixed in https://github.com/openaps/oref0/releases/tag/v0.5.2 - thanks to @jmcrawford @jelcrawford and @francesc0-cgm for identifying the issue.
