### ISSUE TITLE
Ignore old autotune.json

### ISSUE THREAD

**Issue by thebookins** [openaps/oref0#571]
OpenAPS was behaving weirdly for the last week or so (immediate zero temping after breakfast bolus for example). Turns out the cause was an `autotune.json` file in `settings` from when we ran autotune over a month ago. (We have the autotune line in crontab commented out as our son has different carb ratios throughout the day and autotune can't yet cope with this.)

`oref0-get-profile.js` copies the basalprofile, isf and first element of the carb ratio array from `autotune.json` if it exists, overriding what's read from the pump.

Would it be worth adding a test for the age of `autotune.json` before it's used to generate `profile.json`? (It it's over 24 hrs old we could safely assume that autotune didn't run last night.)

Alternatively, maybe a PR to the docs to describe how best to disable autotune and not get stuck with old data?

**Comment by danamlewis** [comment]
I believe we have this now in 0.7.0. as an automated check for the profile; and docs discuss how to disable now.
