### ISSUE TITLE
Error checking a bad (single night) autotune run and falling back to a known good profile

### ISSUE THREAD

**Issue by danamlewis** [openaps/oref0#572]
Occasionally, people's autotune's will end up with a wonky file, with an error message something like "unexpected end of iob". Manual fix is to delete that night's single autotune file. 

I'd like to add an automatic check so that if the autotune file creates this, that file is ignored and it instead falls back to the previous day's autotune profile or the pump profile.

**Comment by danamlewis** [comment]
The error message is: 

Could not parse input data: [SyntaxError: /root/myopenaps/monitor/iob.json: Unexpected end of input]

**Comment by danamlewis** [comment]
IF: Could not parse input data: [SyntaxError: /root/myopenaps/monitor/iob.json: Unexpected end of input]
   THEN: run yesterday's autotune
   IF: failure or same error
      THEN: run based on pump profile instead of autotune file AND try to report in pump-loop log/pill output as a heads up.

**Comment by danamlewis** [comment]
Should tackle https://github.com/openaps/oref0/issues/571 in the same PR (checking age of autotune)

**Comment by johnmales** [comment]
Just having this same issue with newly installed rig from dev branch, issue continues if autotune.json is deleted.

**Comment by scottleibrand** [comment]
Has it pulled all the settings from the pump yet to build the profile.json?

**Comment by johnmales** [comment]
Yes, running for around 10 hours, profile.json looks complete.

**Comment by johnmales** [comment]
My issue resolved with full reinstall from scratch.

**Comment by danamlewis** [comment]
Closing; any related problems in 0.7.0-dev era, please reopen as a new issue.
