### ISSUE TITLE
 Autotune is not being limited by Autosens min and max as expected

### ISSUE THREAD

**Issue by GreatEscape** [openaps/oref0#580]
I had switched Autosens min and max to 1 and 1 believing this would effectively turn off both Autosens and Autotune.  

I noticed that in the OpenAPS pill on Nightscout, the ISF being reported did not match what I knew to be configured in the pump.

I removed both autosens and autotune from the rerun script and installed again. The ISF was reported correctly and now matched the pump.

I added autosens back to the install script and re-installed. The ISF reported still matched the pump. 

I changed autosens min/max to 1 and 1. The ISF reported still matched the pump.

Next I added autotune back to the install script and re-installed.

I switch autosens min/max back to 1.  Now the ISF displayed in the pill, no longer matched what was configured on the pump.

I expected OpenAPS to obey the ISF settings on the pump because Autosens min/max were set to 1.  However, adjusted ISF values were used.

**Comment by PieterGit** [comment]
@GreatEscape : I think I found a piece of the puzzle. The autotune takes the 
`"autosens_max"` and `"autosens_min"` from another file than `preferences.json`, e.g.
`./settings/pumpprofile.json` or `./settings/profile.json`

A workaround is to stop the pump loop (`/etc/init.d/cron stop`) and after it has stopped run `openaps get-settings`. That will refresh the profiles.

@scottleibrand is there a reason why the preferences are merged with the profile? 

I would expect autotune to only use `preferences.json` and I would not expect the preferences inside the profile json files.

**Comment by scottleibrand** [comment]
If you’d like to re-do all the files to take yet another input (preferences.json), that would be doable. I used profile because it’s already there. The profile should be updated frequently, so that should work fine. If it’s not refreshing that’s a different issue we should investigate.

**Comment by danamlewis** [comment]
I believe this was resolved in 0.6.x-land. Now that we're on to 0.7.0, closing this, but please re-open and make notes with regards to re-occurrences if they're still existing as issues on 0.7.0. Thanks!
