### ISSUE TITLE
BS reading in future 

### ISSUE THREAD

**Issue by Telefingers** [openaps/oref0#581]
Loop reads pump data in terms of knowing my active insulin, pump battery, etc. but it can't read the blood sugar data that I am seeing on my pump.  It appears the time on readings is 4:08 on loop app but on pump and iPhone they match.

![img_5155](https://user-images.githubusercontent.com/20625222/28950208-92a9dafa-7887-11e7-8fb7-61118329f96b.PNG)
![img_5156](https://user-images.githubusercontent.com/20625222/28950209-92f0e3d2-7887-11e7-8d41-3aae81c3cd77.PNG)
![img_5157](https://user-images.githubusercontent.com/20625222/28950211-92f1fa88-7887-11e7-9ea1-13040f902b47.PNG)
![img_5158](https://user-images.githubusercontent.com/20625222/28950210-92f1b5a0-7887-11e7-9f5e-e15be811b7c9.PNG)

**Comment by dramageek** [comment]
This is the wrong project. I did check, and you posted the issue in LoopKit as well.

Looks like you found the cause?
@scottleibrand Should be good to close/delete?
