### ISSUE TITLE
COB not decayed at all after rig just comes into pump range

### ISSUE THREAD

**Issue by tynbendad** [openaps/oref0#583]
one of my rigs just got in range of the pump and calculated COB way wrong (didn't decay it at all) and started over-SMB'ing... i shut it off and did a temp target and avoided a low, but how do i figure out what went wrong - what data do we need from the rig? (it is still off - i can turn it back on and stop the cron and copy files off...)
![20545641_1756270704387591_4764884335561713432_o](https://user-images.githubusercontent.com/20666529/28977090-e0e21522-78fd-11e7-8fca-1ec91770390f.jpg)

**Comment by tynbendad** [comment]
just to be sure, I re-installed oref0 0.5.2 (from scratch, and also setup from scratch - i.e., removed old src/oref0 and myopenaps dirs) on this rig and as soon as the loop started again it did a similar errant SMB microbolus based on an undecayed COB (total of all carbs consumed 3-5 hours prior).  this time we were in a better BG and the microbolus was smaller so i let it go.  the next loop had the correct COB (0).  so it appears this only affects the first successful loop (either after install or after pump comes into range from being out of range for a long time).

**Comment by tim2000s** [comment]
I've seen the "lack of data" affecting oref1 in this way too, although slightly different circumstances. I had intermittent phone signal and 45 mins of no SGV readings resulted in a data gap followed by a repetition of the COB that had been present before before the signal dropped. 

There was an SMB on that calculation, but the COB were decayed within 3 SGV readings. 

Mine occurred from data entered into NS. @Tynbendad was yours from NS or the pump bolus wizard?

**Comment by tynbendad** [comment]
All our carbs are entered via pump bolus wizard.

**Comment by tim2000s** [comment]
Mine were from Nightscout. It suggests that when there isn't a a gap in data collection, the first time that the carbs are pulled after the gap, it uses the full extent of carb history and rather than interpolating a decay based on time and the carb absorption rate in preferences.json it uses the full value. It then decays them based on time administered and a few glucose readings, getting back to where it should be between 15 mins and an hour after repelling the data. 

I think this is the same issue as when I've been seeing the zombie carbs, as it nearly always occurs when I get home after work, and the home rigs pick up the pump for the first time since I left that morning, then use the carb data from nightscout undecayed.

**Comment by tim2000s** [comment]
Sorry - that should be "when there is a gap in data collection"

**Comment by tynbendad** [comment]
i see this... mealCOB was 0 on other rigs {"carbs":68,"boluses":0,"mealCOB":68,"currentDeviation":null,"maxDeviation":0,"minDeviationSlope":0}
here is around same time on other rig:
{"carbs":68,"boluses":10,"mealCOB":0,"currentDeviation":6.2,"maxDeviation":6.64,"minDeviationSlope":-0.26}
note the "null" on bad rig

i only find currentDeviation in a few places in oref0 source... autosense mainly - going to try to turn that off on the bedroom rig (where i've been seeing this a lot).

**Comment by scottleibrand** [comment]
#589 may help with this

the Deviation stuff is used by UAM in this case, not autosens.  It looks like certain scenarios result in insufficient data to calculate it properly, so for now the safest thing to do is just set mealCOB=0 when that happens.

**Comment by scottleibrand** [comment]
Please re-test with the latest dev branch and close this issue if fixed or update it if not.

**Comment by tynbendad** [comment]
i've been testing with this on dev branch on all my rigs and things are going ok, although i haven't specifically seen the issue, its likely happened & been dealt with properly without my noticing. 
am closing issue - thanks!
