### ISSUE TITLE
Temp targets not being enacted in timezone UTC+10

### ISSUE THREAD

**Issue by LilDucky** [openaps/oref0#584]
Temp targets not being enacted in timezone UTC+10.

openaps use ns shell temp_targets -6hours
running query with -11 hours only selects the current temp target

Changed to -24hours and 60 minute temporary target stretches into the future in NS
changed to -11hours and all seems to be working correctly in NS and rig recognises targets

https://gitter.im/nightscout/intend-to-bolus?at=59890fbe1c8697534a991b94 refers

**Comment by scottleibrand** [comment]
I think this has now been resolved.  Please reopen if you still see any issues in 0.6.0-dev.
