### ISSUE TITLE
User definable ISF's

### ISSUE THREAD

**Issue by tepidjuice** [openaps/oref0#588]
As per the discussion on gitter. I'd like to be able to give oref0 user-defined ISF's the use cases would be: 

- exercise, or lack of it, 
- illness
- large amounts of very slow acting food. 

For example say I plan to do medium intensity aerobic exercise then I'd like to be able to tell oref0 that my ISF will, e.g. double for one hour, in two hours time. It then calculates the amount of insulin I'd need to keep my bgl in range given this doubling. 

My preferred implementation would be a user inputted list:

`ISF_scale_factor, start_time, duration, time_to_return`

1. `ISF_scale_factor` -- the amount by which your `ISF` is increased so `new_ISF = basal_ISF * ISF_scale_factor`
2. `start_time` -- the time at which your `ISF` will change from `basal_ISF` to `user_ISF`
3. `duration` -- the length of time your `ISF` will be at `user_ISF`
4. `time_to_return` -- the length of time after `start_time+duration` that it takes your `ISF` to return to `basal_ISF` e.g. `ISF` would linearly return to `basal_ISF` over `time_to_return`. I think this would be most helpful for dealing with the after effects of exercise.

When initialised the algorithm would:
1. calculate the basal rate required to keep your bgl in range with the new ISF.
2. find the temp basal required to have the IOB at start time be the IOB you'd have if your basal rate was as in (1)
3. Do it's standard maths but with the new basal rate throughout the duration of the exercise
4. Periodically redo the above throughout the `time_to_return` period. For example this ramp or decay of ISF back to its basal value would happen over 8-24 hours for exercise.
5. Autosens would keep running but be ` +- autosens_ratio * new_ISF`.

Ideally (ignoring food and a slight raise/drop in bgl before the ISF actually changed) this would allow the bgl to be kept exactly on target rather than running higher or lower for exercise/laziness.

Also I think it means we would address the actual need for temp_targets during exercise.

Here's the back of the envelope calculations I propose:

Say you have a basal rate `x` u /hr (e.g. 1) which holds your basal bgl at `y` mmol\L (e.g. 5) with and ISF of `z` mmol\L\u (e.g. 3) then `xz = E` mmol\L\hr (i.e. 3) is your Endogenous Glucose Production (EGP), which we assume is constant. 

If your ISF changes to `z'` (e.g. 4)  then a basal rate of `x' = E/z'` (i.e. 3/4) should hold the bgl at `y` mmol/L (i.e. 5) during exercise. Without exercise you can expect a bgl raise of `E - x' z` (i.e. 3 - 3/4*3 = 2.25) per hour from the 'uncounted' EGP.

Also temp-targets and ISF might be equivalent enough to do this with temp_targets:

Thus if you're ISF would change to `z'` (e.g. 4) in 1 hour then a temp_target of `y + E - x'z` (i.e. 7.25) starting in 1 hour would calculate the same IOB.

**Comment by scottleibrand** [comment]
As an interim step toward meeting this need with a minimum of complexity, we could create an option in preferences.json to temporarily override the autosens ratio. For example, if you set an activity mode temp target of 1.4x your normal target, it would set the autosens ratio to 1/1.4=0.7, so it'd assume a neutral basal of 0.7 instead of 1 U/h and an ISF of 70 instead of 50. When the temp target ended, it would simply go back to the autosens-calculated ratio. 

If this option were enabled and an activity mode were set ~1h prior to exercise, this should help avoid the need for lots of carbs to keep BG up. Similarly, if the temp target remains active after exercise, it might allow autosens some time to catch up to the post-exercise sensitivity.

**Comment by scottleibrand** [comment]
I've created a working (but not yet real-world tested) version of this interim solution: https://github.com/openaps/oref0/compare/no-basal-v-bolus...exercise-mode

For now it also includes some other stuff I'm testing (removal of bolus snooze), but if anyone is interested in testing this, we can rebase the branch off of dev and open a PR once someone has reviewed the diff and is comfortable with the code changes and the general approach.

**Comment by scottleibrand** [comment]
Exercise Mode has now been merged to 0.6.0-dev.  I think that captures most of what you're trying to accomplish here.  Please give it a try and let us know if you think it still needs any enhancement.  (Also note https://github.com/openaps/oref0/pull/705 has some other enhancements around doing the same for autosen, but hasn't been merged yet.)
