### ISSUE TITLE
Remove coveralls

### ISSUE THREAD

**Issue by scottleibrand** [openaps/oref0#610]
We need to remove coveralls from running automatically on PRs so we can more clearly see when unit tests are actually failing, rather than always getting false alarms about code coverage.  Does anyone know who set up coveralls and would be able to reconfigure/remove it?

**Comment by scottleibrand** [comment]
@jasoncalabrese @cjo20 @sulkaharo

**Comment by sulkaharo** [comment]
I haven’t seen too many false alerts for code coverage? Most of the PRs _do_ make the code coverage worse, so the constant alarms are more about the team not having a culture that values including unit tests? Anyway, i’ll check if there’s a threshold setting that would stop the messages about changes that cause tiny % changes, which should cover almost all the false positives (I got one from a commit that reduced the number of lines in code that was covered).

**Comment by scottleibrand** [comment]
Thanks.  Yes, I agree the root cause is that #WeAreNotWaitingForUnitTests.  ;-)  Agreed that ignoring tiny % changes would probably do the trick, and allow us to actually get the full benefit of the unit tests we do have.

**Comment by sulkaharo** [comment]
The threshold for failing is now set to 1% decrease in coverage. Thinking I need to PR in some unit tests that fail (but shouldn't). ;)
