### ISSUE TITLE
COB and Meal bolus info not always being correctly uploaded

### ISSUE THREAD

**Issue by JELCRAWFORD** [openaps/oref0#611]
We are seeing double cob issues again, registered in both NightScout as well as Openaps.  It seems this is happening in conjunction with an error with how the bolus wizard info comes into the system.  We are seeing some entries with bolus wizard come into the system as either meal bolus or carb correction - this is with a single BW entry for a meal that included both BG data and carb data and for which insulin was given. Sometimes both entries are made (see NS treatment log below). Most recently this resulted in a double carb entry of 63 carbs (both NS and Openaps) and the outcome was that the rig did not low temp or zero temp because it believed there were carbs to cover the insulin, which there was not. This resulted in a need to manually zero temp and suspend.

See below for a screen shot of NS as well as treatment info showing the double entry.  We can provide additional logging info as requested.

![img_1188](https://user-images.githubusercontent.com/24684595/29281906-f60707c2-80dd-11e7-8bff-0a3efa271ebe.PNG)
![img_1189](https://user-images.githubusercontent.com/24684595/29281909-f95569be-80dd-11e7-99f6-927b00916bf6.PNG)

**Comment by JELCRAWFORD** [comment]
sorry, wrong nightscout treatment instance grabbed.  See correct one below
![screen shot 2017-08-14 at 10 50 12 am](https://user-images.githubusercontent.com/24684595/29282019-78fffa94-80de-11e7-8363-7a3e50d12253.png)

**Comment by scottleibrand** [comment]
To fix issues like this, I think we'll need you to drill down to the point where you can reproduce the issue from the command line (running the upload manually) so we can add debugging, find the problem, and test a fix.

**Comment by JELCRAWFORD** [comment]
Had another instance last evening whereby COB was no longer being updated in Openaps.  Also had questionable behaviour of ISF - For unknown reasons (mild illness/infection??) we had a long very high climb of BG with limited/no response to correction.  Eventually, after pump site change, insulin change, 2nd pump site change due to occlusion error, we did manual needle correction.  Though we were at a BG of 25.1 (451) before we could get BG to drop, ISF never changed from a value of 6.1.  So, in the end, we simply re-installed dev.  So far today, system seems to be functioning as expected again.  I will close this issue for now.
