### ISSUE TITLE
problems downgrading from oref0 0.6.0-dev to 0.5.x

### ISSUE THREAD

**Issue by CaptainBalou** [openaps/oref0#616]
I tried 0.6.0-dev yesterday and heard that this is not ready for testing yet. I switched back to dev and re-ran oref0-runagain. During running the script I see the following:

```
Continue? y/[N] y
Checking /root/myopenaps: Traceback (most recent call last):
  File "/usr/local/bin/openaps", line 170, in <module>
    app( )
  File "/usr/local/lib/python2.7/dist-packages/openaps/cli/__init__.py", line 51, in __call__
    self.run(self.args)
  File "/usr/local/bin/openaps", line 155, in run
    builtins.dispatch(args, self)
  File "/usr/local/lib/python2.7/dist-packages/openaps/builtins.py", line 44, in dispatch
    command(args)
  File "/usr/local/lib/python2.7/dist-packages/openaps/init.py", line 6, in init
    if args.args[1] == '--nogit':
IndexError: list index out of range
Can't init /root/myopenaps
Is it normally possible to go back to dev without following some specialities?
```
I was wondering if I have to follow some special rules to switch back to dev. So I asked and got answer from Scott:

Scott Leibrand @scottleibrand Aug. 16 21:50
you may have found a backwards-compatibility bug with the new openaps that supports the --nogitflag
you might need to uninstall the dev version of the openaps toolkit and re-install

Scott Leibrand @scottleibrand Aug. 16 21:52
or maybe just checking out the master branch of openaps and installing that would be sufficient
try cd ~/src/openaps && git branch first

Marco @CaptainBalou Aug. 16 21:53
$HOME/src/openaps is non existent.

Scott Leibrand @scottleibrand Aug. 16 21:54
openaps --version

Marco @CaptainBalou Aug. 16 21:55
openaps 0.2.1-dev

Scott Leibrand @scottleibrand Aug. 16 21:55
not sure how you accomplished that, but ok.
cd ~/src && git clone https://github.com/openaps/openaps.git

Marco @CaptainBalou Aug. 16 21:56
cloning...
done.

Scott Leibrand @scottleibrand Aug. 16 21:56
then cd ~/src/openaps && git checkout master && sudo python setup.py develop

Marco @CaptainBalou Aug. 16 21:57
done.

Scott Leibrand @scottleibrand Aug. 16 21:57
oh, I remember what we did to allow you to install 0.2.1-dev without cloning the repo
anyway, try oref0-setup now

Marco @CaptainBalou Aug. 16 21:59
Is running flawlessly now.

I am opening this bug because Scott said we should try to have some reminder to dig further into this.

**Comment by scottleibrand** [comment]
I suspect this is a problem with openaps 0.2.1-dev such that it fails if args.args[1] is undefined.  We probably just need a null check there.

**Comment by scottleibrand** [comment]
Unless anyone volunteers to fix this in the `openaps` Python code, it will probably be left as a backwards-incompatibility and will require fixing manually if anyone really wants to go back to a version of oref0 that uses git.

**Comment by humalogwolfgang** [comment]
Hello,
my name ist Wolfgang from Germany. I´m new in the group and I tried to built my system with an edison-board. But I get everytime the following notice:

Continue? y/[N] y
Checking /root/myopenaps: /root/myopenaps already exists
Cloning oref0: Cloning into 'oref0'...
fatal: unable to connect to github.com:
github.com: Name or service not known

Couldn't clone oref0

root@welle:~# 

I have entered all the above commands.
Can you help me?

**Comment by scottleibrand** [comment]
https://gitter.im/nightscout/intend-to-bolus is the best place to go for
troubleshooting like this.  There are folks there from all around the world
to help at all hours.

In this particular case your problem is that your rig doesn't have Internet
connectivity.  I'd start by checking your wifi config.

-Scott

**Comment by humalogwolfgang** [comment]
Hallo,
Thank  you for the tip . With your tip I found the mistake.
The system  works!!!

**Comment by scottleibrand** [comment]
Closing now that 0.6.0 has been released.
