### ISSUE TITLE
No pump mmtune on SMB error for four consecutive failing pump loop runs

### ISSUE THREAD

**Issue by PieterGit** [openaps/oref0#630]
@ecc1 @scottleibrand Follow up to https://github.com/openaps/oref0/pull/591#issuecomment-326703920 in a separate issue.

See screenshot of the pump loop:

![image](https://user-images.githubusercontent.com/6500826/29999135-8a2063ea-903d-11e7-9064-8e68dceccc81.png)

I changed the `RANDOM` to `$RANDOM` in `maybe_mmtune` about 23:57, causing the mmtune to run (in two consecutive runs) and fixing the rig-pump communication.

The odds of running mmtune after 4 unsuccusful pump runs should be  (25% ^ 4)  = 0,391 %, so 1 out of 256 tries. I suspect it's a bug in the maybe_mmtune logic.

**Comment by PieterGit** [comment]
Issue with 0.5.3-dev

**Comment by scottleibrand** [comment]
No, it's only supposed to mmtune 25% of the time. Your calculation is the odds of not tuning with 75% odds. The odds of not tuning after 4 runs with 25% odds each time are (1-0.25)^4, or 32%

I've already raised the maybe_mmtune probability to 30% in 0.6.0-dev. Maybe we should add some sort of check on the last mmtune timestamp and always mmtune if it's been more than 15m since the last one?

**Comment by scottleibrand** [comment]
Opened https://github.com/openaps/oref0/pull/631 to do that.  If you'd like that merged to 0.5.3 before release, please test and comment.

**Comment by PieterGit** [comment]
I just switched to a 0.6.0-dev checkout on a different rig. I think your patch will improve it, but I think the mmtune logic can be improved. That won't make it in time for 0.5.3, so I'll propose new things (and a new issue / PR) when I worked some thing out.

**Comment by jaylagorio** [comment]
So is this in 0.6.0? I think I've noticed that after rebooting the rig it tries to loop three times and then does an mmtune on the fourth time through. I've done more than the usual number of reboots the past couple days and this has been pretty consistent. Successful loop before a reboot, and this right after reboot:

```
Starting supermicrobolus pump-loop at Fri Sep 22 21:56:02 EDT 2017 with 5 second wait_for_silence:   
Waiting up to 4 minutes for new BG: .glucose.json newer than pump_loop_completed                     
Radio ok. Listening: .No pump comms detected from other rigs                                         
Preflight mmeowlink.exceptions.CommsException: No acknowledgement from pump on wakeup. Is it out of r
ange or is the battery too low?                                                                      
fail. Preflight mmeowlink.exceptions.CommsException: No acknowledgement from pump on wakeup. Is it ou
t of range or is the battery too low?                                                                
fail. SMB pump-loop failed. Unsuccessful supermicrobolus pump-loop at Fri Sep 22 21:58:13 EDT 2017   
                                                                                                     
Starting supermicrobolus pump-loop at Fri Sep 22 21:59:02 EDT 2017 with 22 second wait_for_silence:  
Waiting up to 4 minutes for new BG: glucose.json newer than pump_loop_completed                      
Radio ok. Listening: .No pump comms detected from other rigs                                         
Preflight mmeowlink.exceptions.CommsException: No acknowledgement from pump on wakeup. Is it out of r
ange or is the battery too low?                                                                      
fail. Preflight mmeowlink.exceptions.CommsException: No acknowledgement from pump on wakeup. Is it ou
t of range or is the battery too low?                                                                
fail. SMB pump-loop failed. Unsuccessful supermicrobolus pump-loop at Fri Sep 22 22:01:20 EDT 2017   
                                                                                                     
Starting supermicrobolus pump-loop at Fri Sep 22 22:02:02 EDT 2017 with 6 second wait_for_silence:   
Waiting up to 4 minutes for new BG: glucose.json newer than pump_loop_completed                      
Radio ok. Listening: .No pump comms detected from other rigs                                         
Preflight mmeowlink.exceptions.CommsException: No acknowledgement from pump on wakeup. Is it out of r
ange or is the battery too low?                                                                      
fail. Preflight mmeowlink.exceptions.CommsException: No acknowledgement from pump on wakeup. Is it ou
t of range or is the battery too low?                                                                
fail. SMB pump-loop failed. Unsuccessful supermicrobolus pump-loop at Fri Sep 22 22:04:07 EDT 2017   
                                                                                                     
Starting supermicrobolus pump-loop at Fri Sep 22 22:05:02 EDT 2017 with 28 second wait_for_silence:  
Waiting up to 4 minutes for new BG: glucose.json newer than pump_loop_completed                      
Radio ok. Listening: .No pump comms detected from other rigs                                         
Preflight mmeowlink.exceptions.CommsException: No acknowledgement from pump on wakeup. Is it out of r
ange or is the battery too low?                                                                      
fail. Preflight mmeowlink.exceptions.CommsException: No acknowledgement from pump on wakeup. Is it ou
t of range or is the battery too low?                                                                
fail. SMB pump-loop failed. pump_loop_completed more than 15m old; waiting for 40s silence before mmt
uning                                                                                                
Radio ok. Listening: .No pump comms detected from other rigs                                         

Listening for 40s silence before mmtuning: .No pump comms detected from other rigs                   
mmtune: "916.636", 5, -77 waiting for 34 second silence before continuing                            
Radio ok. Listening: .No pump comms detected from other rigs                                         
Done waiting for rigs with better signal.                                                            
Unsuccessful supermicrobolus pump-loop at Fri Sep 22 22:09:54 EDT 2017                               
```

**Comment by scottleibrand** [comment]
The logic in dev is to randomly mmtune on 25% of failures, but then always mmtune on failure if it's been 15m since the last completed loop (by that rig). That seems to work well for us, so I'm happy to close this if no objections.

**Comment by jaylagorio** [comment]
Is there no way to detect a possible reboot and immediately mmtune? Maybe mmtune at least once immediately if `uptime` is less than 10 minutes?

**Comment by scottleibrand** [comment]
You could add a cron line that removes pump_loop_completed @reboot and it would mmtune on first failure...

**Comment by jaylagorio** [comment]
Cool! I'll try it out for a few reboot cycles, then I'll add a PR for this line to the part of the setup script that sets up the crontab:
```
(crontab -l; crontab -l | grep -q "mv pump_loop_complete pump_loop_complete.old" || echo "@reboot cd $directory/monitor/ && rm pump_loop_complete.old && mv pump_loop_complete pump_loop_complete.old")  | crontab -
```

**Comment by scottleibrand** [comment]
Probably no need for the .old stuff: you can safely just rm the file without keeping an old copy.  You can also reference the absolute path to avoid the need for `cd`.  And finally, it's `completed`, past tense. So:

`(crontab -l; crontab -l | grep -q "rm $directory/monitor/pump_loop_completed" || echo "@reboot rm $directory/monitor/pump_loop_completed")  | crontab -

**Comment by jaylagorio** [comment]
I'm sure I would have caught the tense in testing, but everything else is cool - I didn't know if it was a file anyone would be interested in saving but if you don't think so then just blasting it is fine with me. I'll test and PR a little later, thanks!

**Comment by jaylagorio** [comment]
https://github.com/openaps/oref0/pull/666 submitted!

**Comment by scottleibrand** [comment]
Perfect, thanks. Closing this, but please reopen (or do a new issue) if you see anything else.
