### ISSUE TITLE
False Not Enacted in Nightscout with Dev 0.6.0-dev

### ISSUE THREAD

**Issue by ELUTE** [openaps/oref0#637]
Nightscout reporting not enacted but rig is working. Only started when updated to 0.6.0-dev
![screen shot 2017-09-04 at 4 23 33 pm](https://user-images.githubusercontent.com/7684327/30037926-a165cc10-918d-11e7-9d61-96f8bbdf2827.png)

**Comment by scottleibrand** [comment]
What does the pump-loop.log run look like?

**Comment by ELUTE** [comment]
![screen shot 2017-09-04 at 4 43 49 pm](https://user-images.githubusercontent.com/7684327/30038231-4e125f12-9190-11e7-87fa-3e2895f92c44.png)

**Comment by drnoname82** [comment]
We experience the same error on the 0.6.0-dev and cob-aware-autosens branches. Nightscout works fine with all other branches. Boluses and basal rates are uploaded without any issues.

[pump-loop.log.txt](https://github.com/openaps/oref0/files/1275484/pump-loop.log.txt)

**Comment by drnoname82** [comment]
I think I may have found a possible cause. In the mlab devicestatus entries the word "received" is spelt differently in the enacted-section. 
0.5.3:  "recieved": true,
0.6.0:  "received": true,

**Comment by scottleibrand** [comment]
There is a dependency on a new version of openaps that fixes the spelling. Did you reinstall and re-run oref0-setup? I believe it will upgrade `openaps` for you.

**Comment by drnoname82** [comment]
I reflashed the rig to jubilinux 0.2.0, installed the current master, switched to 0.6.0-dev and did npm run global-install and then re-ran oref0-setup. 0.5.3-entries containing the wrong spelling "recieved" work fine. Could the correct spelling "received" be the problem because Nightscout does not parse it?

**Comment by PieterGit** [comment]
Can also confirm this bug, on a jubilinux 0.1.1 with 0.6.0-dev rig.

**Comment by drnoname82** [comment]
Changing the spelling back to "recieved" in enacted.json leads to a correct "Enacted" display on Nightscout.

**Comment by PieterGit** [comment]
Found the problem in Nightscout: 
https://github.com/nightscout/cgm-remote-monitor/blob/d407bab2096d739708f365eae3c78847291bc997/lib/plugins/openaps.js#L111-L112

I can make a PR to Nightscout later this week or this weekend (including adding a test to `tests/openaps.test.js`), but I don't mind if somebody beats me to it.

**Comment by drnoname82** [comment]
The fix has now been merged into the Nightscout dev branch. I think this issue can be closed.

**Comment by ELUTE** [comment]
It is not fixed in Dev for me. The issue is still there.

**Comment by drnoname82** [comment]
You are running OpenAPS 0.6.0-dev and updated your Nightscout to the latest dev version less than 7 days ago and still get the "Not enacted" message in the OpenAPS pill in Nightscout although the rig is looping without any problems?

**Comment by ELUTE** [comment]
Correct

**Comment by drnoname82** [comment]
Could you post an mLab devicestatus entry that should display as enacted but does not?

**Comment by ELUTE** [comment]
![screen shot 2017-09-18 at 5 26 23 pm](https://user-images.githubusercontent.com/7684327/30565508-8e3d0162-9c96-11e7-8392-40efc656c1b6.png)

**Comment by PieterGit** [comment]
@ELUTE It's fixed in Nightscout, not in oref0. Did you upgrade your Nightscout to the dev branch?

**Comment by drnoname82** [comment]
If you could copy and paste the text I could paste it into my database and see what happens.

**Comment by ELUTE** [comment]
@PieterGit I have always used Dev. I am running the latest commit

**Comment by ELUTE** [comment]
Apologies. My computer was caching. I will close now as it is resolved.
