### ISSUE TITLE
Feature request: User tuned DIA

### ISSUE THREAD

**Issue by Mackwe** [openaps/oref0#638]
At least some of the pumps are not very finely tuned to new insulin types and action curves. I know there is a project running to find the accurate numbers, but until then I would LOVE to be able to tell oref0 I want a DIA of 3.5. I can't do this on the pump (it has 3 or 4 as options). And if I modify the openaps report, it will fail to update a lot of other info gathered from the pump. Would it be too much work to add a parameter into preferences.json to overrule the pump setting? I.e. "if preferences.json contains a parameter called DIA, use that instead of what the pump reported". And allow for decimal numbers of course..

Thanks!

**Comment by scottleibrand** [comment]
This is already addressed with the exponential curves in 0.6.0-dev, which have a user-configurable peak time. We won't be modifying the existing bilinear curves, as those will be deprecated.

**Comment by Mackwe** [comment]
I understand your concern. My idea was not to go as far as modifying the existing curves. Simply by adding a DIA into preferences.json to be able to make a choice not available in the pumps until the time version 0.6.0 reaches master.

**Comment by Mackwe** [comment]
A DIA of 3 using the existing curves poses a risk to my T1. A DIA of 4 (without SMB) makes the algo too slow on reaction. And SMB is not advisable for his size/insulin requirements. Setting a DIA to 3.5 (or 3.75) would help here.

**Comment by scottleibrand** [comment]
If anyone is having such problems with the bilinear curves that they want to do that, I would rather they move to the exponential curves as soon as they hit dev (which could be as soon as this week).

**Comment by Mackwe** [comment]
Point taken. Can't wait!  =)
