### ISSUE TITLE
xDripAPS doesn't work with Token Based Auth.

### ISSUE THREAD

**Issue by dramageek** [openaps/oref0#651]
_Note: the actual issue is with the xDripAPS codebase, not oref0. That issue is located here:_ https://github.com/colinlennon/xDripAPS/issues/2

xDripAPS does not correctly parse Nightscout Token-based-auth URL's, and instead looks for a (nonexistant) API Secret.

Current workaround: Switch back to using API Secret for authentication.

**Comment by cluckj** [comment]
Was this fixed by @renegadeandy in https://github.com/renegadeandy/xDripAPS ?

**Comment by danamlewis** [comment]
Closing, per the xdrip issue link it was resolved.
