### ISSUE TITLE
When there's missing glucose data high temps should be canceled

### ISSUE THREAD

**Issue by jasoncalabrese** [openaps/oref0#70]
Currently we return early from determine basal and let the high temp run to completion.

**Comment by scottleibrand** [comment]
Still need to figure out how to do the same when BG data is too old.

**Comment by scottleibrand** [comment]
Do we also want to do this for old BG data, or is doing it for error states good enough?

**Comment by scottleibrand** [comment]
Closing for lack of interest.  Please reopen if that changes.
