### ISSUE TITLE
Bolus wizard record parsing and upload

### ISSUE THREAD

**Issue by scottleibrand** [openaps/oref0#709]
Further work needs to be done (preferably by someone who actually uses the MDT Bolus Wizard) to figure out where OpenAPS' parsing of of bolus wizard records is not behaving as intended, why, and how we might fix it (without breaking anything else).

Recent problem reports include https://gitter.im/nightscout/intend-to-bolus?at=59de4834614889d475a0c357 from @bdr1177, who only saw the carb portion and not the bolus portion of 0.6U that was delivered via the bolus wizard for 26 carbs.

Also, Petra and Erik Bängtsson provided a very detailed report, which I will post as a comment to this issue.

I think the next step is for someone to get a test rig and test pump set up, posting to a test NS instance, and try to reliably reproduce these issues, so they can begin digging into the actual pumphistory.json contents, compare that to the parsing and uploading code, and figure out where the gaps are.  We'll likely identify two different classes of issues: one (hopefully rare) class involves parsing of pumphistory, where for example bolus wizard records with only carbs and no bolus are incorrectly used by OpenAPS, or (possibly) that complete bolus wizard records are completely ignored.  The second (more common) class of issues is with NS uploads, where records that are properly recognized and used by OpenAPS do not show up in NS.

**Comment by scottleibrand** [comment]
From Petra and Erik Bängtsson:

If carbs are entered via the bolus wizard, but the user does not press ACT the last time to actually deliver the bolus, the carbs are nevertheless exported to Nightscout and included by OpenAPS in its calculation (it shows up in the OpenAPS-pill as COB as well as in papertrail).

I have attached a zip with logs and here are the times to look for: [GhostCarbEntries.zip](https://github.com/openaps/oref0/files/1376758/GhostCarbEntries.zip) All time entries are Central European Time  (UTC+1).

2017 Oct 10th 10:41. 40 carbs logged through bolus wizard on pump. No insulin delivered because ACT was not pressed the final time. Logged in Nightscout as carb correction and shown up as COB in the OpenAPS-pill.

2017 Oct 10th 17:28. 23 carbs logged through bolus wizard on pump. No insulin delivered because ACT was not pressed a final time. Logged in Nightscout as carb correction and shown up as COB in the OpenAPS-pill.

2017 Oct 10 17.34. 23 carbs and 0.65 u of insulin deliverd by pump through the bolus wizard. Both insulin and carb logged in Nightscout and used by OpenAPS.

The lunch bolus (at 10.41) was an accident - our 7yo normally does this without problem, enter carbs and delivers bolus via the bolus wizard, but this time he failed.
The dinner bolus (at ~17:30) was me stressing the system.

This was done with pull #694 of dev 0.6.0. A Minimed Paradigm 554 (MMT-554WWB) with software version 2.6A.

I have a couple of questions:

1. Is this expected behaviour? That the carbs should show up in Nightscout and in the COB-part of the OpenAPS-pill. I read somewhere that carbs given through the bolus wizard are not accounted for if not given with a bolus.

2. Does the fact that the carbs show up as COB in the OpenAPS-pill (and in papertrail logs) mean that these carbs are taken into account in the OpenAPS algorithm and affect the amount of temp basal given? In the case of the lunch bolus it probably saved our day because the system compensated. But it could of course mean that the system also delivers to much insulin.

A minor, but maybe related issue, is when a bolus/carbs pair from the bolus wizard only show the carb part in Nightscout. The insulin part does show up in the IOB-pill (as basal IOB, not Care portal IOB). If you are interested in these you will find them in the attached log at these time points:

2017 Oct 9th 10:41. 40 carbs logged. 1.15 u given by pump but not logged in Nightscout.
2017 Oct 9th 14:07, 30 carbs logged, 0.85 u given by pump but not logged in Nightscout.

Please tell me if there is something more we should test or give you any more data. Now that we are more used to OpenAPS we can more easly test stuff.

Thank you for everything you do. Nowadays we go to bed in the evening without a lump in our stomachs because OpenAPS are watching over our son.

**Comment by JELCRAWFORD** [comment]
We have also seen this issue intermittently and have not identified any specific pattern/sequence of events that seem associated.   I believe we have seen carbs only entries w/o associated insulin bolus.  I wonder if it is important for individuals seeing this behaviour to share their pump model as part of investigation.  We have a spare MDT pump, but not the same model as we are using - theoretically could set up a test rig, but not before the weekend at earliest.

**Comment by sulkaharo** [comment]
I tried to conclusively fix this back in the day and have related code (in JavaScript, a replacement for the bash-based tool). Can we commit as much test data to the repo as possible? This is a good place for unit tests / TDD.

**Comment by scottleibrand** [comment]
How do you want people to "commit as much test data to the repo as possible"?

**Comment by sulkaharo** [comment]
I was thinking of actual json dumps of the pump records, which reproduce the current unwanted behavior, and then implementing tests that load this data.

**Comment by sulkaharo** [comment]
Stuff I toyed with before is in https://github.com/sulkaharo/oref0-tools/blob/master/bin/oref0-mm-format-ns-treatments.js - the logic there can be simplified a lot

**Comment by scottleibrand** [comment]
So would you rather have people post the json to this issue, as I did with Bängtsson's .zip file, or something else?

**Comment by sulkaharo** [comment]
Posting the json here works!

The problematic use case we've encountered before is the Bolus Wizard logic where the pump times out from the UI after 30 seconds (and with accidental ESC presses) and this happening a lot in the daycare, which resulted in up to three erroneous carb entries to pile up in addition to the real entry with a bolus, causing the loop to high temp considerably.

AFAIK the earlier carb entries being sent to NS without bolus were all a case of the rig having pulled the records between the bolus wizard having been used for data entry and the bolus being completed. The logic for the data storage seems to be as follows:

1) If user enters any data to bolus wizard (non-zero carbs / BG value), a bolus wizard record is created with this data, regardless of what happens next. This entry is created whatever the reason for exiting the menu is (time out / ESC presses / confirming the bolus).

2) If user confirms the suggested bolus, a second bolus record is created, with meta-data from the previous entry. This entry is first created with 0 IU of bolus delivered and is updated each time the pump motor moves to deliver more insulin, to ensure the insulin record is exact in case of a power outage during the bolus delivery (so if you pull the battery during the bolus being delivered, IOB can still be calculated correctly).

AFAIK we can skip the first entry type in all cases and just parse the second entry type. To guarantee correct data, pulling pump records should be avoided during bolusing, as the bolus amount will be different from when the bolus has finished delivery, unless the record is subsequently updated correctly.

**Comment by scottleibrand** [comment]
I don't think we can eliminate the race condition of a bolus starting between the time we do a bolusing check and when we pull pumphistory.  So I think we instead need to figure out a mechanism for updating such records if we pull them and see they've changed.  Since OpenAPS doesn't keep any state, and just re-pulls the records from the pump each time, that probably means changing the way we do NS uploads to check not only whether a bolus wizard record already exists with the same (or later) timestamp, but actually checking the contents (or doing an upsert, or whatever) to make sure it gets uploaded in NS after having been uploaded without a bolus amount...

**Comment by JELCRAWFORD** [comment]
If you are explicit about what data you want we can post.  I'm assuming data that includes the targeted error will be important and may be more limiting due to the intermittent nature.  I don't think we've seen it in a few weeks, but could possibly go back and find them in historical data.

**Comment by sulkaharo** [comment]
@JELCRAWFORD The trick is - it's hard to say what data we need to reproduce the issue if we don't know exactly what the issue is. :) So if we got a couple pumphistory.json files that cover the time span where this issue appeared, it might help find out if this is a data issue or something else (or a mix of issues).

@scottleibrand NS already does upserts, so as long as the timestamp of the event doesn't change, the database should support data updates already.

**Comment by scottleibrand** [comment]
Yeah, but I don't think OpenAPS uses the upserts right now.  I think we instead do a check of the most recent treatment, and only try to upload treatments newer than that.

**Comment by JELCRAWFORD** [comment]
@sulkaharo  - about the trickiness - Agreed (though your ideas seem pretty good to me already, I must say!).  As indicated, we can certainly post if we see the problem and I can skim through history and see if we can find some examples and then try to pull the appropriate pumphistory.json.  A few weeks ago we had a couple of times in a 2 day span.  I'm nearly positive we’ve NOT seen this since 0.6.0 though…  but it sounds that others have.

**Comment by PetraBangtsson** [comment]
Hi everybody, Petra Bängtsson here. Nice to hear that there might be a solution to this problem.
Just one word about reproducibility: The issue where a bolus wizard entry is not completed correctly and a "ghost" carb entry is used by OpenAPS is easily reproduced. The issue where the insulin part of a bolus wizard entry is delivered by do not show up in Nightscout is not reproducible and rather intermittent, might be hard to catch.
Unfortunately we do not have a spare pump/rig but if this problems appear again I will add the pumphistory.json file to this feed.

**Comment by garykidd** [comment]
At suggestion of Scott Leibrand, I am posting some information relating to missing manual bolus correction treatment in NS.  Scott was able to quickly ascertain that despite the absence of the treatment in NS altogether (both in treatment section as well as within the normal viewing area for that period), that the IOB both before and after this manual bolus were found to be correct and therefore loop was functioning properly--just not displaying the results correctly within NS.

**Comment by PetraBangtsson** [comment]
The issue with missing insulin entry in Nightscout happened again. Today, 14 October at 12.57, 40 carbs were entered into the bolus wizard and a bolus of 1.3 u was given by the pump. The carbs, but not the insulin, show up in Nightscout. IOB pill is updated as if the insulin is present. The carbs are logged as carb correction in Nightscout. Time is in Central European Time (UTC +01), pump 554. Nightscout on Heroku. Logs here: 
[MissingInsulinEntry.zip](https://github.com/openaps/oref0/files/1384724/MissingInsulinEntry.zip)

One thought on logs: I'm always uncertain what logs to include for an issue like this. I also know that the logs wrap and if you are not quick enough the interesting parts would disappear. Would it be possible to make a script that collects the interesting files into a folder or a zip on the rig. Preferably this script should be able to trigger from Nightscout so you could start it from your phone if you are not able to connect to the rig at the moment. You could then access the saved files later. Just an idea...

**Comment by JELCRAWFORD** [comment]
We've now had 4 carb entry only incidents in the last 48hrs (so much for my low pump battery theory!). 

Is this where we are collecting .json data?

**Comment by scottleibrand** [comment]
@sulka can correct if I'm wrong, but I think we now understand the "only carbs uploaded to NS" issue well enough we don't need any more logs or json files for that. 

It might still be useful to get info to help us reproduce any instances of canceled bolus wizard entries showing up in COB though.

**Comment by sulkaharo** [comment]
If you have a pump model other than 554, please upload a sample of your pumphistory.json. One sample / pump model is enough. Please also post what exact pump model you got (model number, firmware version, ww/eu) and if you enter the BG when using the wizard.

**Comment by sulkaharo** [comment]
Scott yes that’s highly likely, but I’d love to see if the event format really is consistent across models.

**Comment by lsandini** [comment]
I have been plagued with this and asked about it on gitter a few weeks ago. The offered solution was to update my NS version to latest dev, I also went to latest oref 0.6.0dev at that time but it didn't fix it for me. Using a 715WW with 2.3A, normal boluses show up, but not when using the bolus wiz. Carbs and insulin are taken into account by openaps, they just don't appear as a dot in NS. Will try a different pump and see if it's model dependent. I have my pumphistory.json ready if you need it.

**Comment by lsandini** [comment]
Ok, just tested with same rig and different pump, 722WW with 2.4A, manual "normal" boluses appear in NS, but when administered using the bolus wizard, that fail to show up. 

They appear in the "treatments" page of the reports, and are taken into account by openaps, the white/blue dot is just missing.

**Comment by lsandini** [comment]
... and same rig, but with a 754WW with 2.6A, bolus wizard treatments appear normally.

**Comment by scottleibrand** [comment]
Might be good to capture the pumphistory records from two different model pumps for the same thing. If they're identical, that points to a race condition on the upload. If not, we might need to make the parsing model-aware.

**Comment by lsandini** [comment]
Here you go, I captured the pumphistory.json bits about bolus wizard events using the 3 different pumps and the same rig. It seems that with the 715 and 722, dots or commas are missing from the BG values and target values. (I use mmol/L in Finland). With the 754, the BG values are formatted correctly, see below:


  #754
  {
    "_type": "BolusWizard", 
    "bg": 6.0, 
    "bg_target_high": 6.0, 
    "_description": "BolusWizard 2017-11-01T16:40:33 head[2], body[15] op[0x5b]", 
    "timestamp": "2017-11-01T16:40:33", 
    "_body": "0f900096463700002800000e00283c", 
    "_head": "5b3c", 
    "unabsorbed_insulin_total": 0.35, 
    "correction_estimate": 0.0, 
    "_date": "a1e8100111", 
    "bolus_estimate": 1.0, 
    "bg_target_low": 5.5, 
    "carb_ratio": 15.0, 
    "food_estimate": 1.0, 
    "carb_input": 15, 
    "sensitivity": 7.0
  }, 
  
  #715 with BG target 4.0 - 5.0, sensitivity 3 mmol/l/U, carb ratio 1U:20g
  {
    "_type": "BolusWizard", 
    "bg": 44, 
    "bg_target_high": 50, 
    "correction_estimate": 0.0, 
    "unknown_byte[10]": 0, 
    "_description": "BolusWizard 2017-10-31T11:47:29 head[2], body[13] op[0x5b]", 
    "timestamp": "2017-10-31T11:47:29", 
    "_body": "1490141e28000a000010000a32", 
    "carb_input": 20, 
    "_head": "5b2c", 
    "unabsorbed_insulin_total": 1.6, 
    "_byte[5]": 0, 
    "unabsorbed_insulin_count": "??", 
    "_byte[7]": 0, 
    "_date": "9daf0b1f11", 
    "bolus_estimate": 1.0, 
    "unknown_byte[8]": 0, 
    "carb_ratio": 20, 
    "food_estimate": 1.0, 
    "bg_target_low": 40, 
    "sensitivity": 30
  }, 
  
  
  #722 with BG target 5.6 - 5.6, sensitivity 2.2 mmol/l/U, carb ratio 1U:10g
  {
    "_type": "BolusWizard", 
    "bg": 71, 
    "bg_target_high": 56, 
    "correction_estimate": 0.6, 
    "unknown_byte[10]": 0, 
    "_description": "BolusWizard 2017-11-01T13:29:10 head[2], body[13] op[0x5b]", 
    "timestamp": "2017-11-01T13:29:10", 
    "_body": "32900a1638063200000a003238", 
    "carb_input": 50, 
    "_head": "5b47", 
    "unabsorbed_insulin_total": 1.0, 
    "_byte[5]": 6, 
    "unabsorbed_insulin_count": "??", 
    "_byte[7]": 0, 
    "_date": "8add0d0111", 
    "bolus_estimate": 5.0, 
    "unknown_byte[8]": 0, 
    "carb_ratio": 10, 
    "food_estimate": 5.0, 
    "bg_target_low": 56, 
    "sensitivity": 22
  },

**Comment by lsandini** [comment]
Ok here is more of that. Taken with the 722 pump. 

I started a few bolus wizard events but exited with ESC before bolusing (eg at 15:42 and 15:49).

Then I did a normal bolus wizard event at 16:00:57, declaring BG 6.6 mmol/l, carbs 44g and the calculated bolus wa 4.8U:


{
    "_type": "TempBasalDuration", 
    "duration (min)": 30, 
    "_description": "TempBasalDuration 2017-11-04T16:05:04 head[2], body[0] op[0x16]", 
    "timestamp": "2017-11-04T16:05:04", 
    "_body": "", 
    "_head": "1601", 
    "_date": "84c5104411"
  }, 
  {
    "_type": "TempBasal", 
    "temp": "absolute", 
    "_description": "TempBasal 2017-11-04T16:05:04 head[2], body[1] op[0x33]", 
    "timestamp": "2017-11-04T16:05:04", 
    "_body": "00", 
    "_head": "3300", 
    "rate": 0.0, 
    "_date": "84c5104411"
  }, 
  {
    "programmed": 4.8, 
    "_type": "Bolus", 
    "type": "normal", 
    "_description": "Bolus 2017-11-04T16:00:57 head[4], body[0] op[0x01]", 
    "duration": 0, 
    "timestamp": "2017-11-04T16:00:57", 
    "_body": "", 
    "_head": "01303000", 
    "amount": 4.8, 
    "_date": "b9c0300411"
  }, 
  {
    "_type": "BolusWizard", 
    "bg": 66, 
    "bg_target_high": 56, 
    "correction_estimate": 0.4, 
    "unknown_byte[10]": 0, 
    "_description": "BolusWizard 2017-11-04T16:00:57 head[2], body[13] op[0x5b]", 
    "timestamp": "2017-11-04T16:00:57", 
    "_body": "2c900a1638042c000000003038", 
    "carb_input": 44, 
    "_head": "5b42", 
    "unabsorbed_insulin_total": 0.0, 
    "_byte[5]": 4, 
    "unabsorbed_insulin_count": "??", 
    "_byte[7]": 0, 
    "_date": "b9c0100411", 
    "bolus_estimate": 4.8, 
    "unknown_byte[8]": 0, 
    "carb_ratio": 10, 
    "food_estimate": 4.4, 
    "bg_target_low": 56, 
    "sensitivity": 22
  }, 
  {
    "_type": "CalBGForPH", 
    "_description": "CalBGForPH 2017-11-04T16:00:45 head[2], body[0] op[0x0a]", 
    "timestamp": "2017-11-04T16:00:45", 
    "_body": "", 
    "_head": "0a42", 
    "amount": 66, 
    "_date": "adc0500411"
  }, 
  {
    "_type": "CalBGForPH", 
    "_description": "CalBGForPH 2017-11-04T15:55:51 head[2], body[0] op[0x0a]", 
    "timestamp": "2017-11-04T15:55:51", 
    "_body": "", 
    "_head": "0a35", 
    "amount": 53, 
    "_date": "b3f74f0411"
  }, 
  {
    "_type": "TempBasalDuration", 
    "duration (min)": 30, 
    "_description": "TempBasalDuration 2017-11-04T15:54:42 head[2], body[0] op[0x16]", 
    "timestamp": "2017-11-04T15:54:42", 
    "_body": "", 
    "_head": "1601", 
    "_date": "aaf60f4411"
  }, 
  {
    "_type": "TempBasal", 
    "temp": "absolute", 
    "_description": "TempBasal 2017-11-04T15:54:42 head[2], body[1] op[0x33]", 
    "timestamp": "2017-11-04T15:54:42", 
    "_body": "00", 
    "_head": "333e", 
    "rate": 1.55, 
    "_date": "aaf60f4411"
  }, 
  {
    "_type": "TempBasalDuration", 
    "duration (min)": 30, 
    "_description": "TempBasalDuration 2017-11-04T15:51:08 head[2], body[0] op[0x16]", 
    "timestamp": "2017-11-04T15:51:08", 
    "_body": "", 
    "_head": "1601", 
    "_date": "88f30f4411"
  }, 
  {
    "_type": "TempBasal", 
    "temp": "absolute", 
    "_description": "TempBasal 2017-11-04T15:51:08 head[2], body[1] op[0x33]", 
    "timestamp": "2017-11-04T15:51:08", 
    "_body": "00", 
    "_head": "3332", 
    "rate": 1.25, 
    "_date": "88f30f4411"
  }, 
  {
    "_type": "CalBGForPH", 
    "_description": "CalBGForPH 2017-11-04T15:49:23 head[2], body[0] op[0x0a]", 
    "timestamp": "2017-11-04T15:49:23", 
    "_body": "", 
    "_head": "0a3e", 
    "amount": 62, 
    "_date": "97f14f0411"
  }, 
  {
    "_type": "CalBGForPH", 
    "_description": "CalBGForPH 2017-11-04T15:42:05 head[2], body[0] op[0x0a]", 
    "timestamp": "2017-11-04T15:42:05", 
    "_body": "", 
    "_head": "0a3c", 
    "amount": 60, 
    "_date": "85ea4f0411"
  }, 
  {
    "_type": "TempBasalDuration", 
    "duration (min)": 120, 
    "_description": "TempBasalDuration 2017-11-04T15:33:18 head[2], body[0] op[0x16]", 
    "timestamp": "2017-11-04T15:33:18", 
    "_body": "", 
    "_head": "1604", 
    "_date": "92e10f4411"
  }, 
  {
    "_type": "TempBasal", 
    "temp": "absolute", 
    "_description": "TempBasal 2017-11-04T15:33:18 head[2], body[1] op[0x33]", 
    "timestamp": "2017-11-04T15:33:18", 
    "_body": "00", 
    "_head": "3300", 
    "rate": 0.0, 
    "_date": "92e10f4411"
  }, 
  {
    "_type": "Prime", 
    "type": "manual", 
    "_description": "Prime 2017-11-04T15:23:15 head[5], body[0] op[0x03]", 
    "timestamp": "2017-11-04T15:23:15", 
    "_body": "", 
    "fixed": 0.0, 
    "_head": "030000000f", 
    "amount": 1.5, 
    "_date": "8fd72f0411"
  }, 
  {
    "_type": "Rewind", 
    "_description": "Rewind 2017-11-04T15:23:05 head[2], body[0] op[0x21]", 
    "timestamp": "2017-11-04T15:23:05", 
    "_body": "", 
    "_head": "2100", 
    "_date": "85d70f0411"
  }
]

**Comment by scottleibrand** [comment]
I just found and fixed one cause of incorrect "skipping bolus wizard entry with carbs and no insulin" messages: the bolus wizard and corresponding bolus record can be logged with timestamps that differ by 1 second.  The fix in commit 2eee14b6e44493e9f0442f6b33e980480290a325 (in https://github.com/openaps/oref0/pull/772 for now) is to look for records up to 1s apart.

**Comment by lsandini** [comment]
I think we have to focus on the decocare issue of having the BG values increased by a factor 10.

I issued a BW event with a 715WW pump and as expected, it didn't show up in NS. I went to the treatments page of the NS reports and the event was there, but the BG was "69" and not 6.9mmol/l. I just edited the BG value and ta-daa, the blue/white dot appeared correctly in NS.

The carbs and bolus were taken into account normally by openaps, 

So it's just a matter of decocare importing the pumphistory in a valid way.

**Comment by JELCRAWFORD** [comment]
We have seen issues with the mmol conversion for a long time, though I’ve not been able to identify a consistent pattern that produces it - we see as you do @lsandini - in treatments a bg will come in as 60 when it should be read as 6.0. As far as I can tell, this seems to produce a visualization problem primarily. Last week it compressed our graph for 24 hrs. Ironically, the compressed graph with flatter line by virtue of the compression effect of such a high bg in mmol’s results in less frustration to me :). We did not see negative consequences in the loop which would be more problematic.

**Comment by PieterGit** [comment]
Found a partial solution to the COB=0 issue (other than the 1 second difference Scott fixed). See 
https://github.com/openaps/oref0/issues/777 for discussion and PR 780 for a suggested (partial) fix. Please help test that fix.

**Comment by scottleibrand** [comment]
Closing this as we’ve replaced all the pumphistory parsing code in 0.7.0. If you see any more problems there please open a new issue.
