### ISSUE TITLE
Fatal loose object (stored in .git/objects) appearing on rig installed 0.6.0 dev no git

### ISSUE THREAD

**Issue by davidkeddydb** [openaps/oref0#710]
I unplugged this rig for a few days and just repowered it up and I get this message.  I can reinstall but I thought the no.git install now on 6.0 dev would eliminate this from happening?

Preflight fatal: loose object 3eaefb63478c5e334f4f6d568ba3d992ec15390d (stored in .git/objects/3e/aefb63478c5e334f4f6d568ba3d992ec15390d) is corrupt'
fail. Preflight fatal: loose object 3eaefb63478c5e334f4f6d568ba3d992ec15390d (stored in .git/objects/3e/aefb63478c5e334f4f6d568ba3d992ec15390d) is corrupt'
fail. SMB pump-loop failed. pump_loop_completed more than 15m old; waiting for 40s silence before mmtuning
Radio ok. Listening: .No pump comms detected from other rigs
Listening for 40s silence before mmtuning: .No pump comms detected from other rigs
mmtune: fatal: loose object 3eaefb63478c5e334f4f6d568ba3d992ec15390d (stored in .git/objects/3e/aefb63478c5e334f4f6d568ba3d992ec15390d) is corrupt'
"916.636", 0, -99 waiting for 78 second silence before continuing
Radio ok. Listening: .No pump comms detected from other rigs
Done waiting for rigs with better signal.
Unsuccessful supermicrobolus pump-loop at Fri Oct 13 15:00:44 EDT 2017

Starting supermicrobolus pump-loop at Fri Oct 13 15:01:02 EDT 2017 with 19 second wait_for_silence:
Waiting up to 4 minutes for new BG: ls: cannot access /tmp/pump_loop_completed: No such file or directory
Radio ok. Listening: .No pump comms detected from other rigs
Preflight fatal: loose object 3eaefb63478c5e334f4f6d568ba3d992ec15390d (stored in .git/objects/3e/aefb63478c5e334f4f6d568ba3d992ec15390d) is corrupt'
fail. Preflight

**Comment by scottleibrand** [comment]
You didn't delete your .git folder. If you moved/deleted ~/myopenaps/, that might mean you have one in your homedir. You can use ls -a to see hidden "dot" files/folders. 

Scott

**Comment by davidkeddydb** [comment]
Scott, thanks.  I followed the directions and removed the myoldopenaps directory but I missed the .git directory that was hidden. Thanks for the ls -a.  That will likely come in handy again at some point down the line.

**Comment by davidkeddydb** [comment]
ok, so I continued to have problems until I used ls -ld .?* and found the .gitconfig file which was hidden in root. It did not show with ls -a for anyone else getting a loose .git object error
