### ISSUE TITLE
keep bluetooth PAN connected while offline

### ISSUE THREAD

**Issue by thebookins** [openaps/oref0#711]
xDripAPS relies on the rig having a local IP address (e.g. 172.20.10.x on iOS) to which to send glucose data. This is usually accomplished using bluetooth tethering. In the case of loss of mobile service `/bin/oref0-online.sh` tries to re-establish an online connection by
1) trying wifi
2) trying to establish a BT PAN by cycling through all supplied MAC addresses
3) cycling networking.

On my iPhone this process disconnects any existing bluetooth-tethered devices and makes the xDripAPS endpoint unavailable.

To enable my son to go on camp shortly in a remote location with unreliable mobile service, I have edited `/bin/oref0-online.sh` to use BT PAN exclusively, and only test for a local IP address: https://github.com/thebookins/oref0/commit/ac09d4b9070e19e0d1a2ca9d3fdb32e832a5c937 (credit to @iainct for this suggestion).

This isn't a complete or elegant solution, and totally removes the code that preferentially connects to a wifi network if available. I'd welcome any comments as to whether or not this is a viable solution, and also how best to modify `/bin/oref0-online.sh` without taking out all the good bits.

**Comment by scottleibrand** [comment]
Check out the `offline` branch for some other alternatives.  That branch sets up a local-only wifi hotspot if it can't get online via wifi or BT...

**Comment by thebookins** [comment]
`offline` looks great @scottleibrand. Last time I checked it was still a WIP. I'm after rock-solid performance while my son is on camp (or as close as I can get) - do you see any problems with the above approach and then switching to `offline` when some more users have field-tested it?

**Comment by thebookins** [comment]
Looks like this is resolved with https://github.com/openaps/oref0/pull/716. Thanks @scottleibrand. Closing.
