### ISSUE TITLE
Edge case when SMB variables set in preferences, but not in enable line

### ISSUE THREAD

**Issue by danamlewis** [openaps/oref0#737]
@Kdisimone reported a possible edge case, where a new rig was set up, the preferences for SMB were added and turned to true, but was not added via the setup script (i.e. with safety catch phrases) or to the enable line.

Behavior resulted in it setting zero temps; calculating and attempting to SMB; but not succeeding with SMB. 

Possible proposed ways forward:
1) Remove the requirement of the safety phrases in the setup script, and just have people enable SMB by setting the requisite preferences in `preferences.json`
2) Add a safety guard against the above scenario by a stronger check for SMB in the enable line regardless of the preferences set.

Thoughts on option 1? People seem to know what they're doing nowadays with regards to self-selecting into SMB and otherwise waiting to get their heads wrapped around the basics before they get started.

**Comment by tynbendad** [comment]
i'm good with letting just preferences.json enable it.  simplification is better anyway, and it should be pretty clear you should read about/understand a variable in there before changing it.

**Comment by scottleibrand** [comment]
If we want to go with option 1, that would look like https://github.com/openaps/oref0/compare/dev...smb-in-preferences-only (It's ready to just hit the button to make that a PR if that's the consensus).

**Comment by Kdisimone** [comment]
I’d vote for preferences option...lol. Obviously my brain needs simple.

**Comment by jaylagorio** [comment]
``preferences.json`` only sounds good to me.

**Comment by scottleibrand** [comment]
@danamlewis or @kdisimone I'll leave it to one of you to open the PR if that's the way you want to go.

**Comment by bdr1177** [comment]
I'd also vote for the preferences option.

**Comment by scottleibrand** [comment]
#748 is now merged, so closing this.
