### ISSUE TITLE
Need boundaries on how much auto sens can adjust things

### ISSUE THREAD

**Issue by eyim** [openaps/oref0#76]
Was testing out the auto sens part lately.  One edge case was that I was running it using my backup pump with real bg data but fake pump data - everything was really screwed up and it came out with some really crazy results like 10X the sensitivity or something like that.  Given that sometimes people switch out pumps and other things like that, maybe worthwhile to put some safeguards on the range that it can adjust things

**Comment by scottleibrand** [comment]
https://github.com/openaps/oref0/commit/3eca297ad4173bc5fe68439cfc669b52f5898e81 should fix this.  Please reopen if not.

**Comment by scottleibrand** [comment]
Need to double check this is fixed in AMA as well, where I refactored a bunch of stuff.

**Comment by scottleibrand** [comment]
Applied to AMA as well.  Closing.
