### ISSUE TITLE
System locks up with BT tethering enabled but iPhone hotspot shut off

### ISSUE THREAD

**Issue by cbrenner** [openaps/oref0#762]
I found this reproducible bug using 0.5.5. With BT tethering enabled on rig but iPhone hotspot shut off, anytime the rig moves out of range from Wi-Fi and attempts to connect to disabled iPhone hotspot, the rig locks up and ceases to work. Always requires a hard reset to reboot rig. We keep the iPhone hotspot on all the time but there are random times when iOS seems to take it upon itself to disable the hotspot. I have read that this may be the result of "low power mode" being activated in iOS. Unfortunately, I cannot provide any logs because the rig is locked up once this happens and there is no papertrail to pull up. Everything looks normal right up to the transition out of Wi-Fi then rig goes silent.

https://gitter.im/nightscout/intend-to-bolus?at=59f894aad6c36fca31bc1627

**Comment by scottleibrand** [comment]
What do syslog and kernel.log show? Do you have a kernel panic / trace dump?

**Comment by cbrenner** [comment]
Syslog and kernel.log show nothing during the time of the problem.  The next event for both is when the rig went through the hard reset. What is a kernel panic / trace dump?  I'm guessing if I don't know what these are then I don't have them?

**Comment by scottleibrand** [comment]
When I've seen something similar it has been accompanied by scary messages in the logs indicating a kernel bug. If you don't have those it's probably a different issue.

**Comment by scottleibrand** [comment]
If anyone else is able to reproduce this, please speak up.  We don't see the same issue on our rigs running jubilinux 0.1.1.

**Comment by dramageek** [comment]
My rigs both have the same behavior mentioned above- if they're unable to gain network, they eventually panic. Plugging them in for serial comms pre-hard-reset results in nothing sent (putty connects, but no commands sent/received). Happens on both jubilinux 0.1.1 and 0.2.0.

I did find #803 earlier- is this an attempted fix for this bug?

**Comment by scottleibrand** [comment]
The symptoms I’m trying to fix with 803 include a kernel panic in syslog when unable to get a bnep0 IP with DHCP, which I normally observe while flying. Does your syslog show anything like that right before the rig dies?

**Comment by dramageek** [comment]
Syslog ends before the restart with " DHCPDISCOVER on bnep0 to 255.255.255.255 port 67 interval 13", but doesn't report errors. The next thing is the @^@^@^ of the restart. I've see it truncate lines too, but I can't find one in recent logs.

There is a stack and a call trace in kern.log:
`Nov 20 04:00:51 localhost kernel: [128650.987535] BUG: unable to handle kernel NULL pointer dereference at 00000010
Nov 20 04:00:51 localhost kernel: [128650.987657] IP: [<c17d507a>] l2cap_chan_send+0x9a/0xac0
Nov 20 04:00:51 localhost kernel: [128650.987746] *pdpt = 0000000035301001 *pde = 0000000000000000
Nov 20 04:00:51 localhost kernel: [128650.987826] Oops: 0000 [#1] PREEMPT SMP
Nov 20 04:00:51 localhost kernel: [128650.987893] Modules linked in: bcm4334x(O) kvm_intel kvm gpio_pca953x ti_ads7955 iio_basincove_gpadc ftdi_sio uvcvideo videobuf2_vmalloc videobuf2_memops videobuf2_core usb_f_acm u_serial g_multi li$
Nov 20 04:00:51 localhost kernel: [128650.988180] CPU: 1 PID: 25195 Comm: kbnepd bnep0 Tainted: G        W  O 3.10.98-jubilinux-edison #13
Nov 20 04:00:51 localhost kernel: [128650.988274] Hardware name: Intel Corporation Merrifield/BODEGA BAY, BIOS 466 2014.06.23:19.20.05
Nov 20 04:00:51 localhost kernel: [128650.988365] task: f4bc2760 ti: f4b34000 task.ti: f4b34000
Nov 20 04:00:51 localhost kernel: [128650.988430] EIP: 0060:[<c17d507a>] EFLAGS: 00010246 CPU: 1
Nov 20 04:00:51 localhost kernel: [128650.988499] EIP is at l2cap_chan_send+0x9a/0xac0
Nov 20 04:00:51 localhost kernel: [128650.988556] EAX: 0000069b EBX: 00000000 ECX: 0000001c EDX: f4abad6c
Nov 20 04:00:51 localhost kernel: [128650.988625] ESI: f5138c00 EDI: f5138e80 EBP: f4b35de4 ESP: f4b35d80
Nov 20 04:00:51 localhost kernel: [128650.988695]  DS: 007b ES: 007b FS: 00d8 GS: 0000 SS: 0068
Nov 20 04:00:51 localhost kernel: [128650.988757] CR0: 8005003b CR2: 00000010 CR3: 359ee000 CR4: 001007f0
Nov 20 04:00:51 localhost kernel: [128650.988826] DR0: 00000000 DR1: 00000000 DR2: 00000000 DR3: 00000000
Nov 20 04:00:51 localhost kernel: [128650.988893] DR6: ffff0ff0 DR7: 00000400
Nov 20 04:00:51 localhost kernel: [128650.988939] Stack:
Nov 20 04:00:51 localhost kernel: [128650.988970]  00000246 f5138e84 f4b35d94 c184726d f5138e80 0000001c c18415c0 00000000
Nov 20 04:00:51 localhost kernel: [128650.989109]  f6ffe690 f4b35dbc c12722cd f5138e94 f5138c00 f4b34000 f4abad6c 22222222
Nov 20 04:00:51 localhost kernel: [128650.989245]  22222222 22222222 22222222 f5138e80 f5138c00 f5138e80 f513b000 f5138c00
Nov 20 04:00:51 localhost kernel: [128650.989383] Call Trace:
Nov 20 04:00:51 localhost kernel: [128650.989442]  [<c184726d>] ? sub_preempt_count+0x3d/0x50
Nov 20 04:00:51 localhost kernel: [128650.989519]  [<c18415c0>] ? __mutex_lock_slowpath+0x250/0x370
Nov 20 04:00:51 localhost kernel: [128650.989599]  [<c12722cd>] ? __enqueue_entity+0x6d/0x80
Nov 20 04:00:51 localhost kernel: [128650.989680]  [<c17d9ee7>] l2cap_sock_sendmsg+0x67/0xd0
Nov 20 04:00:51 localhost kernel: [128650.989758]  [<c16b46cb>] sock_sendmsg+0x7b/0xb0
Nov 20 04:00:51 localhost kernel: [128650.989827]  [<c18429bf>] ? __schedule+0x3bf/0x7c0
Nov 20 04:00:51 localhost kernel: [128650.989897]  [<c1275b0a>] ? enqueue_task_fair+0xf0a/0x1610
Nov 20 04:00:51 localhost kernel: [128650.989988]  [<c16b472d>] kernel_sendmsg+0x2d/0x40
Nov 20 04:00:51 localhost kernel: [128650.990060]  [<c17e98ee>] bnep_session+0x3ee/0x800
Nov 20 04:00:51 localhost kernel: [128650.990132]  [<c126f340>] ? try_to_wake_up+0x190/0x240
Nov 20 04:00:51 localhost kernel: [128650.990210]  [<c126f450>] ? wake_up_state+0x20/0x20
Nov 20 04:00:51 localhost kernel: [128650.990280]  [<c1269f48>] ? complete+0x48/0x50
Nov 20 04:00:51 localhost kernel: [128650.990347]  [<c17e9500>] ? bnep_rx_control+0x3d0/0x3d0
Nov 20 04:00:51 localhost kernel: [128650.990418]  [<c1260784>] kthread+0x94/0xa0
Nov 20 04:00:51 localhost kernel: [128650.990484]  [<c1840000>] ? pskb_trim_rcsum.part.9+0xf/0x38
Nov 20 04:00:51 localhost kernel: [128650.990567]  [<c18490f7>] ret_from_kernel_thread+0x1b/0x28
Nov 20 04:00:51 localhost kernel: [128650.990640]  [<c12606f0>] ? kthread_create_on_node+0xc0/0xc0
Nov 20 04:00:51 localhost kernel: [128650.990708] Code: 8d 65 f4 5b 5e 5f 5d c3 90 8b 74 24 30 0f b7 46 2e 39 44 24 14 0f 87 5f 08 00 00 f6 05 2a 76 b9 c1 04 8b 5e 04 0f 85 0f 09 00 00 <8b> 43 10 8b 5c 24 14 8b 7c 24 30 8b 74 24 38 83 e$
Nov 20 04:00:51 localhost kernel: [128650.991373] EIP: [<c17d507a>] l2cap_chan_send+0x9a/0xac0 SS:ESP 0068:f4b35d80
Nov 20 04:00:51 localhost kernel: [128650.991470] CR2: 0000000000000010
Nov 20 04:00:51 localhost kernel: [128651.249089] ---[ end trace 61e8318898b62114 ]---
`

**Comment by scottleibrand** [comment]
That's the same kernel bug / panic that I see every time right before mine locks up.

Anyone care to do some kernel hacking / debugging?  ;-)

**Comment by scottleibrand** [comment]
Any other investigation anyone wants to do on this?  If not, I think I'll consider the BT crashes fixed by #803 and continue investigating the more general issue under https://github.com/openaps/oref0/issues/809
