### ISSUE TITLE
zombie carbs are back, after 2-hour sensor warmup period

### ISSUE THREAD

**Issue by tynbendad** [openaps/oref0#766]
we just had another case of openaps applying all the carbs consumed in the last several hours to the time after a sensor restart 2 hour warmup...
![cob0](https://user-images.githubusercontent.com/20666529/32263573-160dd654-bea0-11e7-8b97-75c9b0e10446.PNG)
![cob64](https://user-images.githubusercontent.com/20666529/32263574-1620c782-bea0-11e7-972c-8b632a5d6319.PNG)

root@benaps3:~/src/oref0# git log | head -4
commit e823688f55d4183c1faf9d255cbd13cddb5d1b2c
Author: Scott Leibrand <scottleibrand@gmail.com>
Date:   Thu Oct 26 20:34:19 2017 -0700

Starting supermicrobolus pump-loop at Tue Oct 31 22:54:02 MDT 2017 with 18 second wait_for_silence:utes for new BG: glucose.json newer than pump_loop_completed
Radio ok. Listening: ........................No interfering pump comms detected from other rigs (this is a good thing!) and valid. RefreshValueError: need more than 0 values to unpack.json
Checking pump clock: "2017-10-31T22:55:20-06:00" is within 1m of current time: Tue Oct 31 22:55:46 MDT 2017s than 1m old.  Temp refreshed
Autotune exists! Hoorah! You can use microbolus-related features.
{"carbs":78,"mealCOB":63,"currentDeviation":2.31,"maxDeviation":11.46,"minDeviation":6.09,"slopeFromMaxDeviation":-2.881,"slopeFromMinDeviation":0,"allDeviations":[2,6,7,11],"lastCarbTime":1509509462000}1-01T04:55:24.000Z","iobWithZeroTemp":{"iob":2.681,"activity":0.0261,"basaliob":-0.295,"bolusiob":2.976,"netbasalinsulin":-1.65,"bolusinsulin":7.8,"time":"2017-11-01T04:55:24.000Z"},"lastBolusTime":1509511658000,"lastTemp":{"rate":0,"timestamp":"2017-10-31T22:47:20-06:00","started_at":"2017-11-01T04:47:20.000Z","date":1509511640000,"duration":9.53}}
Carb Impact: -2.7 mg/dL per 5m; CI Duration: 0 hours; remaining CI (~2h peak): 15.8 mg/dL per 5mm): 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 6 6 7 7 8 9 9 10 10 11 12 12 13 14 14 15 15 16 15 14 14 13 13 12 11 11 10 10 9 8 8 7 7 6 5 5 4 3 3 2
60,56,53,52,51,52,54,56,60,64,69,75,82,90,99,108,118,130,142,154,167,178,190,201,211,221,231,240,248,256,264,271,278,284,289,294,299,303,306,309,311],"UAM":[116,104,93,82,71,61,52,42,39,39,39,39,39]},"COB":63,"IOB":2.681,"reason":"COB: 63, Dev: 8, BGI: -9.32, ISF: 71, Target: 90, minPredBG 75, minGuardBG 23, IOBpredBG 39, COBpredBG 311, UAMpredBG 39; minGuardBG 23<65 83m left and 0 ~ req 0U/hr: no temp required"}
No smb_enact needed. Temp refreshed: monitor/temp_basal.json: {"duration":83,"rate":0,"temp":"absolute"}
No bolus needed (yet). Settings refreshed. Edison on battery: 59%. Pumphistory-24 < 30m old
Settings less than 3 minutes old. Refreshed pumphistory and meal.json
IOB: 2.673
Completed supermicrobolus pump-loop at Tue Oct 31 22:56:47 MDT 2017

**Comment by scottleibrand** [comment]
Looks like it was reporting COB=0 for a few minutes after BG data came back just due to a lack of recent history, and then went back to trying to calculate it once it had enough data. It looks like it may have been calculating only the min_5m_carbimpact during the restart, rather than properly interpolating BG data as a straight line through the gap and calculating deviations from that based on insulin activity. 

Can you capture the glucose.json and pumphistory-merged.json covering that time period so we can try to repro and do some debugging?

**Comment by tynbendad** [comment]
attached current glucose.json and pumphistory-merged.json which cover the time period.

[monitor.zip](https://github.com/openaps/oref0/files/1434426/monitor.zip)

**Comment by tynbendad** [comment]
i've archived the myopenaps directory and pump-loop.log in case you need anything else, let me know.

**Comment by tynbendad** [comment]
fwiw I have been using (separately) 2 different workarounds to largely avoid this issue:
1. raised min_5m_carbimpact to 18 (the default is 8, and the value that works best for you may vary - i just used a bit of trial/error), which made the carbs degrade quicker but not too quick.
2. now we don't enter carbs at all since we are on fiasp with ​​smb always on and my kid doesn't bother bolusing or announcing (since he wasn't reliably doing it anyway).

**Comment by tynbendad** [comment]
Another workaround is of course to avoid gaps of cgm data... This is not entirely achievable but logger does avoid the weekly 2 hour gaps the receiver would have.

**Comment by scottleibrand** [comment]
We've also been using workarounds, mostly doing sensor swaps and restarts at times when there aren't too many COB.  It would probably be good if someone could fix / reimplement interpolation so it properly decays COB across gaps.  I wasn't successful the last time I tried that, and this hasn't been a very high priority for us since then.

If someone wants to help work on fixing and testing the interpolation, I'd be happy to help.

**Comment by danamlewis** [comment]
Closing due to this being a >2yo thread with no recent additions. If zombie carbs still exist in 0.7.0 and beyond, let's open a new issue with the latest pertinent logs and details to troubleshoot.

**Comment by sulkaharo** [comment]
FYI I just merged a fix to device status data handling in Nightscout that might have caused this in some cases.
