### ISSUE TITLE
date set fails repeatedly when dexcom receiver is not connected (and ntpdate is not present)

### ISSUE THREAD

**Issue by itsn0tm3** [openaps/oref0#776]
The DST changeover went well however all rigs kept trying to fix the time even when the time was correct.  2 issues:

1. Notably the rigs that did NOT have a dexcom receiver kept erroring out since it kept trying to set the receiver time too.  It should check to see if a receiver is connected first before trying to set it.

Also interestingly it kept saying the pump time was more than 1 minute off when it in fact wasn't.

2. It kept complaining ntpdate was not present (I installed it before the log below), so we should make sure ntpdate is installed as a prerequisite or fix the code to not use it.

Sample log:

Preflight OK. Profile less than 60m old and valid. Refreshed pumphistory and meal.json
Checking pump clock: "2017-11-05T01:12:43-06:00" is within 1m of current time: Sun  5 Nov 01:12:52 MST 2017
Pump clock is more than 1m off: attempting to reset it
Waiting for ntpd to synchronize... OK!
Setting pump and CGM time to Sun 5 Nov 01:12:52 MST 2017
{
  "raw": [
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0
  ],
  "requested": {
    "old": "2017-11-05T01:12:46",
    "params": [
      1,
      12,
      54,
      7,
      225,
      11,
      5
    ],
    "clock": "2017-11-05T01:12:54.912852"
  },
  "timestamp": "2017-11-05T01:12:55.752462",
  "clock": "2017-11-05T01:12:54"
}Traceback (most recent call last):
  File "/usr/local/bin/openaps-use", line 63, in <module>
    app( )
  File "/usr/local/lib/python2.7/dist-packages/openaps/cli/__init__.py", line 51, in __call__
    self.run(self.args)
  File "/usr/local/bin/openaps-use", line 57, in run
    output = app(args, self)
  File "/usr/local/lib/python2.7/dist-packages/openaps/uses/__init__.py", line 92, in __call__
    return self.method.selected(args)(args, app)
  File "/usr/local/lib/python2.7/dist-packages/openaps/uses/__init__.py", line 31, in __call__
    return self.method(args, app)
  File "/usr/local/lib/python2.7/dist-packages/openaps/uses/use.py", line 45, in __call__
    output = self.main(args, app)
  File "/usr/local/lib/python2.7/dist-packages/openaps/vendors/dexcom.py", line 130, in main
    program = self.get_program(args)
  File "/usr/local/lib/python2.7/dist-packages/openaps/vendors/dexcom.py", line 124, in get_program
    current_utc = self.dexcom.ReadSystemTime( )
AttributeError: 'NoneType' object has no attribute 'ReadSystemTime'
basal-only pump-loop failed. pump_loop_completed more than 15m old; waiting for 40s silence before mmtuning
Radio ok. Listening: .

**Comment by alimhassam** [comment]
I had the exact same issue, got worken up with an alarm saying i wasn't looping. 
 - Noticed similar `ReadSystemTime` error.
 - Noticed that `ntpdate was not present` message. *Should this be installed by the setup script?*
 - manually Installed  ntpdate.
problem didn't go away. Digged slightly more, and noticed that the timezone adjustment portion of `cat monitor/clock-zoned.json` hadn't got adjusted. I'm in EST time after the dst change it should have been `-05:00` but it was still at 
```
cat monitor/clock-zoned.json
2017-11-05T01:58:35-04:00
```
couple of minutes later it correctly went to 
```
cat monitor/clock-zoned.json
2017-11-05T02:00:05-05:00
```
and looping was sucessfull again.

I think the clock-zoned.json is calculated from https://github.com/openaps/openaps-contrib/blob/master/openapscontrib/timezones/__init__.py
there is either a bug in thta code occuring during that rewinded hour, or something in oref0 is passing an incorrcet parameter during that time.

**Comment by jmcrawford** [comment]
Either way, we need to have ntpdate installed if it's being referenced in the code.

**Comment by scottleibrand** [comment]
PR please.  It should probably go into openaps-install.sh

**Comment by itsn0tm3** [comment]
I'll try to do it!

**Comment by scottleibrand** [comment]
I ended up adding ntpdate to oref0-setup in #772.  Closing.
