### ISSUE TITLE
Stacktrace in pump loop and invalid "11 g carbs and no insulin"

### ISSUE THREAD

**Issue by PieterGit** [openaps/oref0#777]
With `oref0-version 0.6.0-dev5 [dev]` I noticed the following error in the pump loop:

```
Waiting up to 4 minutes for new BG: glucose.json newer than pump_loop_completed
Radio ok. Listening: .No interfering pump comms detected from other rigs (this is a good thing!)ofile less than 60m old and valid. Refresh    at Function.Module.runMain (module.js:497:10)s wizard entry with 11 g carbs and no insulin
 and meal.json
Checking pump clock: "2017-11-05T13:02:32+01:00" is within 1m of current time: Sun Nov  5 13:02:35 CET 2017s than 1m old.  Temp refreshed
```

Two questions:
1.  The Javascript stacktrace `Refresh    at Function.Module.runMain (module.js:497:10)s wizard entry with 11 g carbs and no insulin` seems to originate from `lib/meal/history.js`. But how is it called from the pump-loop, so that I can try to reproduce it from the commandline.

2. There were no wizard entries with no insulin. Probably related to https://github.com/openaps/oref0/issues/709#issuecomment-341946372

I looked up and noticed the follownig two 11g carbs, both more than 24h ago:
```
Saturday 4-11-2017
09:28	Meal Bolus				0.90u	11g
13:16	Meal Bolus	6.2 (BolusWizard)	0.20u	11g
```

Perhaps we should really limit the amount of carb data that is checked. Checking carb data from more than 24 hours ago does not seem usefull.

**Comment by PieterGit** [comment]
I could reproduce the `and no insulin` error with
```
#  oref0-meal monitor/pumphistory-merged.json settings/profile.json monitor/clock-zoned.json monitor/glucose.json settings/basal_profile.json monitor/carbhistory.json
skipping bolus wizard entry with 14 g carbs and no insulin
skipping bolus wizard entry with 11 g carbs and no insulin
```

I'll try to create a failing test and debug `lib/meal/history.js`. It says `"bwCarbs":0`  and `"bwFound":false` which is wrong.

**Comment by scottleibrand** [comment]
We need 24h+ of carbhistory for autosens to properly exclude carb absorption periods.

Was this with or without https://github.com/openaps/oref0/commit/2eee14b6e44493e9f0442f6b33e980480290a325 ?

**Comment by PieterGit** [comment]
This is without  (`dev` branch) and with (`optimize`  and `scott-dana-dev` branch). Unfortunately those branches don't work for me (see comment in PR 772) .  I'll dig into the pump history tonight or tomorrow night.

**Comment by PieterGit** [comment]
Found the offending record.  Timestamps are the same. In this case the suggestion was altered and with this 754WW pump produced a `"BolusWizard"` and a seperate `"Bolus"` record. Carbs input was in the `"carb_input":` field (not in `"carbs").

Should I fix `temp.bwCarbs = current.carbs;` to  `temp.bwCarbs = current.carb_input;` or
`temp.bwCarbs = current.carbs || current.carb_input;`  in this peace of code?

``` 
    } else if (current._type == "BolusWizard" && current.timestamp) {
            //console.log(pumpHistory[i]);
            var temp = {};
            temp.timestamp = current.timestamp;
            temp.carbs = current.carb_input;
            temp.bwCarbs = current.carbs;
```

**Comment by scottleibrand** [comment]
I made that change a few days ago in cc0467c3d3e251c0705b2c8a775d3367f011f95d (in the `optimize` branch).

**Comment by PieterGit** [comment]
Tested fix of PR 780. Works for me with 754WW pump. Once pump records are uploaded and downloaded to Nightscout the carbs are seen as `nsCarbs` instead of `bwCarbs` what I expected. But the `skipping bolus wizard entry with XXX g carbs and no insulin` message disappeared and the carbs are counted. Please review and merge to dev when ok.

**Comment by scottleibrand** [comment]
That behavior of pump carbs being recognized as nsCarbs instead of bwCarbs after upload to and download from NS is incorrect and would break our A52 safety checks.

**Comment by PieterGit** [comment]
Well this fix fixed the wrong COB=0 issue, which prevented SMB's and higher basal after a meal with BolusWizard, so it's a partial solution.

**Comment by scottleibrand** [comment]
My intuition is that we’d want to check both pumphistory and carbhistory, not just one or the other.

**Comment by PieterGit** [comment]
Pushed the fix, but unit test cobtest still fails with PR780.

```
not ok 4 cobhistory should dedupe entries
  AssertionError: expected 6 to be 5
      at Assertion.fail (node_modules/should/lib/assertion.js:180:17)
      at Assertion.prop.value (node_modules/should/lib/assertion.js:65:17)
      at Context.<anonymous> (tests/cobhistory.test.js:41:30)
```

If anybody can spot the error, please help. Otherwise I will work on it later this week.

**Comment by scottleibrand** [comment]
It looks like this was fixed by https://github.com/openaps/oref0/pull/954 - if we see any further problems, it'd probably be best to open a new issue/PR.
