### ISSUE TITLE
short-circuit pathway to set a zero-temp basal 

### ISSUE THREAD

**Issue by eyim** [openaps/oref0#78]
Given the frequency of communication errors, there are many times when a full loop cannot be completed but there is still some communication happening between openaps and the pump.  There are times therefore that it would be nice to have a simple command that can issue a temp basal to 0.

The scenario may be that the PWD is at school and the parent notices that bg is falling quickly.  The parent sees either via a Nightscout integration or other monitoring means that the loop isn't being completed.  Therefore, the parent can log into the openaps system remotely and issue a command to set a temp basal to 0.  This command may be able to get through to the pump even though the loop may fail at a more intensive communication step like pulling the pump-history

**Comment by scottleibrand** [comment]
I am actually thinking this should be fully automated. If preflight succeeds and we see BG is falling rapidly, we could set a zero temp first, and then attempt to do the normal loop (and replace it with whatever is appropriate).

**Comment by eyim** [comment]
Even better

**Comment by JaysonEwer** [comment]
Very cool.  I like that idea as well.

**Comment by scottleibrand** [comment]
I just implemented this in my wait-loop alias by adding `openaps get-bg && openaps enact &&` between preflight and gather.  My preflight alias does `openaps report invoke monitor/temp_basal.json`, the gather alias does `rm monitor/*`, and the enact alias does `rm enact/suggested.json; openaps invoke enact/suggested.json`, so it should be safe to refresh the recommendation and enact it solely based on updated BG and temp_basal info before refreshing pumphistory.  My main retry-loop alias does `openaps wait-loop || openaps loop`, so if the optimized wait-loop alias fails for any reason it does the conservative thing and refreshes everything before trying again.

```
openaps alias add retry-loop '! bash -c "openaps wait-loop || openaps loop"'

openaps alias add wait-loop '! bash -c "openaps preflight && openaps get-bg && openaps enact && openaps gather && openaps enact && openaps report invoke monitor/temp_basal.json 2>/dev/null >/dev/null && openaps upload && (openaps get-settings || openaps get-settings) 2>/dev/null >/dev/null && openaps wait-for-bg && openaps enact && openaps upload-ns-status >/dev/null"'

openaps alias add loop '! bash -c "openaps preflight && openaps gather && openaps get-settings 2>/dev/null >/dev/null && openaps enact && openaps upload"'

openaps alias add preflight '! bash -c "echo -n \"mmtune: \" && openaps mmtune && echo -n \"PREFLIGHT \" && openaps report invoke monitor/temp_basal.json 2>/dev/null >/dev/null && echo OK || ( echo FAIL; sleep 120; exit 1 )"'

openaps alias add enact '! bash -c "rm enact/suggested.json; openaps invoke enact/suggested.json && if (cat enact/suggested.json && grep -q duration enact/suggested.json); then ( rm enact/enacted.json; openaps invoke enact/enacted.json ; grep -q duration enact/enacted.json || openaps invoke enact/enacted.json ) 2>&1 | egrep -v \"^  |subg_rfspy|handler\" && cat enact/enacted.json | json -e \"if(this.duration === this.requested.duration){ this.recieved = true }\" | tee enact/enacted.json; else echo No action required; fi"'

openaps alias add gather '! bash -c "rm monitor/*; ( openaps get-bg | egrep \"reporting|Copied\" && echo -n R && openaps report invoke monitor/status.json 2>/dev/null >/dev/null && echo -n e && test $(cat monitor/status.json | json bolusing) == false && echo -n fr && openaps ns-meal-carbs && echo -n esh && ( (openaps monitor-pump || openaps monitor-pump) >/dev/null && echo ed ) || (echo; sleep 60; exit 1)) 2>/dev/null"'

openaps alias add get-settings "report invoke settings/model.json settings/bg_targets.json settings/insulin_sensitivities.json settings/basal_profile.json settings/settings.json settings/carb_ratios.json settings/profile.json settings/pumphistory-24h.json settings/pumphistory-24h-zoned.json settings/autosens.json"
```

**Comment by scottleibrand** [comment]
Quite happy with this since installing it. Will close the issue if no other input.
