### ISSUE TITLE
Advanced target adjustment overrides temp target when BG is high

### ISSUE THREAD

**Issue by JoseeT1Bionique** [openaps/oref0#784]
I experience this issue every time I eat pizza for lunch. 

Hi BG following Pizza, Open APS High temping to bring BG down. My problem is that I know I will walk 20 minutes at 16h30, so every day I have 6.6 temp activity target starting earlier but because my BG is High, the APS targets 4,4. I was under the understanding that a temps target was the priority, but this is not what I'm experiencing. In this context, I strongly believe it should. 

If I have a temps target even though my BG is up, it is because I know what is coming. This situation will make me crash; I will walk with a lot of IOB. Last time I crashed 6 points in 20 minutes, double arrows down, not safe.

I do not want to set my Hi temp target to false, for it is most of the time practical, but I do wish my temps target was seen in priority.

Thank you

![screenshot_2017-11-08-16-04-04](https://user-images.githubusercontent.com/30188775/32575145-334daf58-c4a1-11e7-903f-b0bba93bbc8c.png)

**Comment by scottleibrand** [comment]
What version of oref0 are you using?

**Comment by JoseeT1Bionique** [comment]
5.5, switching to Dev 6 later tonight.

**Comment by scottleibrand** [comment]
In 0.6.0-dev, since we've added the zero-temp predBGs as a better way to safely dose for high BG, we recommend disabling advanced target adjustment.  I think that is probably the best way to address what you're seeing.  (In 0.5.x, the temp target is honored, but advanced target adjustment is applied after the temp target, so if current BG is high enough it'll still reduce the target a lot.)  Additionally, with exercise_mode / high_temptarget_raises_sensitivity in 0.6.0-dev, you can make oref0 a lot more responsive to high temp targets.

**Comment by JoseeT1Bionique** [comment]
@scottleibrand, I had another episode of extreme HI following french fries, under counted cards. 
(Was unable to install Dev6 as planned and did not turn the «advanced target adjustment» setting to false.)

So as I'm rereading the doc and your comment, I think the documentation is incomplete or states the opposite of your comment up here and my experience with 0.5.x. http://openaps.readthedocs.io/en/latest/docs/Customize-Iterate/autosens.html?highlight=autotune%20temp%20target 

Written:
«... Note that a temp target will override the autosens-adjusted target.» 

I think it should read: 
«... Note that a manual Nightscout careportal or IFTTT temp target will override the autosens-adjusted target BUT WILL NOT override the autosens-advanced target adjustment. Because, in 0.5.x, the manual temp target is honored, but autosens-advanced target adjustment is applied after, so if current BG is high enough it'll still reduce the target to 80.»

Please confirm, I will do a Doc PR if need be.

**Comment by scottleibrand** [comment]
That sounds correct.

**Comment by JoseeT1Bionique** [comment]
I've done the doc pull request #1116 to claryfy actual way in 5.x

that being done, I know nothing about coding, so I know I'm totally unaware of what I'm asking work wise. But after pondering on that for a few days, I still believe temp targets should overrule advance temp adjustment, i.e. they should be applied last. Because, I know what is coming in my day and I want to avoid a going too low to fast/crashing in hypo situation. Very personal, but I prefer staying high a little longer than crashing. ► Context, I eat restaurant food with colleagues pizza or french fries, go back to work for a few hours. Set via IFTTT daily activity temps target from 15h30 to 17h00, because I daily walk 15 minutes to get to bus station, can't change or adjust that part. So every time, I crash. I would need to manually basal temp to 0 I guess to minimize damages. If so, how long would it need to be, not to cause a rebound high bg? But truly,  the way I see it, is that OpenAPS is there (still becoming) an APS to minimize T1 managing and not a thing we need to manually manage basal temps with all day long.   

Maybe once I get on Dev 6 and enable eSMB bg will not get so high anymore, and this will all become irrelevant... bur in the mean time for me or people staying on 5.x  feel it's a safety issue.

Letting this rest now, you decide if it's worth it or not :)

**Comment by scottleibrand** [comment]
We've already disabled advanced target adjustment in 0.6.0 by default, and will probably remove it entirely in a future version rather than trying to fix it.  In 0.6.0, temp targets are also much more powerful with exercise_mode (high_temptarget_raises_sensitivity) and low_temptarget_lowers_sensitivity.  The exercise_mode option in particular helps a lot for situations similar to what you're describing.
