### ISSUE TITLE
Zero temp but no SMB on tiny basals

### ISSUE THREAD

**Issue by bdr1177** [openaps/oref0#785]
With tiny basals and SMB enabled, long zero temps may be set even if no SMBs are actually delivered (see discussion here: https://gitter.im/nightscout/intend-to-bolus?at=59f89face44c43700a9e2e63 and here: https://github.com/openaps/oref0/pull/782#issuecomment-342859374). This is a problem for those with very small basals because it is not infrequent that you end up with a long zero temp in the absence of any SMBs.

**Comment by KensingtonB** [comment]
We are also having this issue.  Happy to help test if any proposed solutions, but no technical savvy to contribute ;)

**Comment by scottleibrand** [comment]
Sure, you can test #786 (assuming you're comfortable with 0.6.0-dev).

**Comment by scottleibrand** [comment]
Closing this now that #786 is merged.
