### ISSUE TITLE
cancel long zero temps if rig is not getting BG data

### ISSUE THREAD

**Issue by in-10-city** [openaps/oref0#788]
Just a note,  this happened to me today.  The fault is my own but would have been fixed with an option of not setting temps longer than 30 minutes or even one hour.  I had lunch at 12:30 and my sensor went out at 2:00 PM.  So I change my pod and wait for the 2 hour calibration process.  What I failed to do was pay attention to the fact that my pump had also been suspended for a long time and would continue to be suspended for the whole 2 hour calibration process.  

After 2 hours I check my BG one reading was 252 the other was 236.  I understand that I failed by not checking my BG more during this process.  But I also understand that if my normal basal would have been in place I would have gotten an additional 2.6 units which would have kept me more in line.

**Comment by scottleibrand** [comment]
One option to fix this kind of thing would be to have determine-basal check if BG is more than X minutes old, and set a neutral temp (or cancel temp) if so. Currently it only does that if you have a CGM plugged in and it's getting the error status code: missing data simply causes it to not do anything and let the currently running temp basal run to completion.

**Comment by in-10-city** [comment]
Is there a way to have determine-basal look at the last trend and make a decision based on that?  

For example:  
If I am trending up at 5 points every 5 minutes for the last 35 minutes then. then lost communications for x minutes, have it cancel temp basal if the temp basal is set lower than my default or suspended.  

Or if I am trending down at 5 points every 5 minutes for the last 35 minutes then. then lost communications for x minutes allow it to keep the temp basal if it is suspended or set lower than my stated default.

**Comment by scottleibrand** [comment]
Ok, I'm thinking we consolidate the "BG too old" and "CGM is calibrating or in ??? state" code into a single block of logic, which will:

Cancel high temp:
```
{"rate":0,"duration":0,"temp":"absolute","deliverAt":"2017-11-14T01:11:00.349Z","reason":"If current system time Mon Nov 13 2017 17:11:00 GMT-0800 (PST) is correct, then BG data is too old. The last BG data was read 12m ago at Mon Nov 13 2017 16:59:00 GMT-0800 (PST). Canceling high temp basal of 3.3"}
```
Shorten long zero temp to 30m:
```
{"rate":0,"duration":30,"temp":"absolute","deliverAt":"2017-11-14T01:11:42.771Z","reason":"If current system time Mon Nov 13 2017 17:11:42 GMT-0800 (PST) is correct, then BG data is too old. The last BG data was read 12.7m ago at Mon Nov 13 2017 16:59:00 GMT-0800 (PST). Shortening 59m long zero temp to 30m. "}
```
and let low temps run:
```
{"reason":"If current system time Mon Nov 13 2017 17:09:46 GMT-0800 (PST) is correct, then BG data is too old. The last BG data was read 10.8m ago at Mon Nov 13 2017 16:59:00 GMT-0800 (PST). Temp 1.25 <= current basal 1.3U/hr; doing nothing. "}
```

Thoughts?

**Comment by scottleibrand** [comment]
Closing since #796 is merged.
