### ISSUE TITLE
MDT BG refresh is too slow

### ISSUE THREAD

**Issue by scottleibrand** [openaps/oref0#799]
Per https://github.com/openaps/oref0/pull/796#issuecomment-344240696, "sometimes with a MDT rig it can be 15 mins before a update is received in a rig".  That is too slow: it shouldn't take that long.

We need some volunteers with Enlite CGM to help figure out how to improve this.  Most likely, it will involve porting the MDT pump-loop alias contents over to oref0-pump-loop and then optimizing it to work more reliably and faster.

**Comment by dougtakeuti** [comment]
On the issue of too long zero temps, could we possibly cancel zero temps when rig battery is low/about to die? Our batteries usually die around school dismissal. If she goes straight to after school activities and I don't get the chance to replace the battery, a long zero temp with OpenAPS offline will result in high BG around dinner time.

**Comment by scottleibrand** [comment]
That sounds like a separate topic: feel free to open a new issue, or even better make a PR.

**Comment by Bender1061** [comment]
this is the issue with the retrieval 
```
Starting oref0-pump-loop at Sun Nov 19 09:47:31 EST 2017 with 5 second wait_for_silence:
MDT CGM configured; not waiting
Radio ok. Listening: .No interfering pump comms detected from other rigs (this is a good thing!)
Preflight OK.
Attempting to retrieve MDT CGM data from pump
monitor/cgm-mm-glucosedirty.json  raised  'ReadPumpModel' object has no attribute 'iter_glucose_pages'
Traceback (most recent call last):
  File "/usr/local/bin/openaps-report", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/root/src/openaps/bin/openaps-report", line 82, in <module>
    app( )
  File "/root/src/openaps/openaps/cli/__init__.py", line 51, in __call__
    self.run(self.args)
  File "/root/src/openaps/bin/openaps-report", line 75, in run
    output = app(args, self)
  File "/root/src/openaps/openaps/cli/subcommand.py", line 52, in __call__
    return self.method.main(args, app)
  File "/root/src/openaps/openaps/reports/invoke.py", line 40, in main
    output = task.method(args, app)
  File "/root/src/openaps/openaps/uses/use.py", line 45, in __call__
    output = self.main(args, app)
  File "/root/src/openaps/openaps/vendors/medtronic.py", line 640, in main
    for rec in self.range( ):
  File "/root/src/openaps/openaps/vendors/medtronic.py", line 629, in range
    return self.pump.model.iter_glucose_pages( )
AttributeError: 'ReadPumpModel' object has no attribute 'iter_glucose_pages'

CGM data retrieval from pump disrupted, retrying in 5 seconds...
Reattempting to retrieve MDT CGM data
monitor/cgm-mm-glucosedirty.json  raised  Page size too short
Traceback (most recent call last):
  File "/usr/local/bin/openaps-report", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/root/src/openaps/bin/openaps-report", line 82, in <module>
    app( )
  File "/root/src/openaps/openaps/cli/__init__.py", line 51, in __call__
    self.run(self.args)
  File "/root/src/openaps/bin/openaps-report", line 75, in run
    output = app(args, self)
  File "/root/src/openaps/openaps/cli/subcommand.py", line 52, in __call__
    return self.method.main(args, app)
  File "/root/src/openaps/openaps/reports/invoke.py", line 40, in main
    output = task.method(args, app)
  File "/root/src/openaps/openaps/uses/use.py", line 45, in __call__
    output = self.main(args, app)
  File "/root/src/openaps/openaps/vendors/medtronic.py", line 640, in main
    for rec in self.range( ):
  File "/root/src/decocare/decocare/models/__init__.py", line 67, in __call__
    for record in page:
  File "/root/src/decocare/decocare/models/__init__.py", line 151, in download_page
    if self.cgm_paged_data(page.data).needs_timestamp():
  File "/root/src/decocare/decocare/models/__init__.py", line 146, in cgm_paged_data
    return cgm.PagedData.Data(page_bytes, larger=self.inst.larger)
  File "/root/src/decocare/decocare/cgm/__init__.py", line 78, in Data
    return klass(stream, **kwds)
  File "/root/src/decocare/decocare/cgm/__init__.py", line 84, in __init__
    raise DataTransferCorruptionError("Page size too short")
decocare.errors.DataTransferCorruptionError: Page size too short

CGM data retrieval from pump disrupted, retrying in 5 seconds...
Reattempting to retrieve MDT CGM data
MDT CGM data retrieved
MDT New cgm data reformatted
```
it's the constant erroring out when it's trying to get the cgm data from the pump, sure it does end up working after retrying several times, but this issue happens a lot. This would also be a resource hog on the system, and help drain the pump batteries even faster. 

if anyone has the expertise to understand what all of that means it would greatly help out the MDT users in the group.

**Comment by dougtakeuti** [comment]
John, I'm by no means an expert, but I can tell you what I observe. We are
currently using two rigs. One of them has a range of a couple of meters and
runs the master version from a couple months ago. We use this one in the
bedroom. The other one has a range of less than 50cm, runs the latest dev
and is used during the day, in the same pouch as the pump. I see the "page
size too short" in the pouch rig, when comms are not ideal, for instance,
when my daughter removes it from the pouch and places it on the table. I
have noticed an increase battery consumption and also Papertrail getting
close to the 10MB limit too soon.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Livre
de vírus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>.
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-11-19 12:54 GMT-02:00 John Benjamin <notifications@github.com>:

**Comment by Bender1061** [comment]
I have 7 rigs, and all of these get the issues, be it my rig during the day at work that is in my pocket inches from my pump, or my house rigs that are the older edison with breakout boards wired to the TI stick. distance does not seem to be the issue nor does comm strength, as I would think I would get errors like this when getting the pump history if it was something like that.

**Comment by Bender1061** [comment]
This really might be a decocare issue, but I don't know

**Comment by LilDucky** [comment]
I have seen the same errors and it is not related to pump comms as far as I can tell. mmtune is in the -60 to -70 region and it still happens. The rig has >10 meter range and it occurs when the pump and rig are on the same table.

**Comment by cjo20** [comment]
As has been suggested, I think this issue is down to RF failures. 

As @Bender1061 noted, it doesn't seem to be related to distance from the pump. I've found I get the highest success rate with my pump clipped to me (probably something to do with my body changing interference with the signal). The rig distance makes less difference.

I'm not sure it's anything software related, it could just be down to the pump not handling interference well. I've spent countless hours looking at the cc1110 configuration options to try and find a better solution, and I've not found one yet. As far as I can tell, it isn't a decocare issue, the failures are happening on a lower level in the spi code.

**Comment by scottleibrand** [comment]
So the underlying complaint was that CGM data would get way out of date.  If the only known issue causing that is an intermittent comms failure, do we just need to refactor the MDT pump-loop into oref0-pump-loop and make appropriate use of the retry() function there?

**Comment by Bender1061** [comment]
per @scottleibrand request here is some of the ns-loop.log. It's pretty boring. and I don't really think it is the problem with things taking too long to update, I think that is more of an issue with getting the data during the oref0-pump-loop. Instead of just checking the cgm data it has to run everything, which means the loop takes much longer to run. and if it keeps failing it just takes longer, cause if it fails a lot of the time it then does a mmtune. which can take a long time based on the time it waits. But here is the data you requested. 
```
Starting ns-loop at Wed Nov 22 19:30:04 EST 2017:
ns://JSON/shell/cgm/ns-glucose.json
reporting cgm/ns-glucose.json
ns://JSON/shell/settings/temptargets.json
reporting settings/temptargets.json
get-profile://text/shell/settings/profile.json
reporting settings/profile.json
Refreshed temptargetsns://JSON/shell/monitor/carbhistory.json
reporting monitor/carbhistory.json
 and meal-carbs
{"batteryVoltage":3836, "battery":66}
Uploaded
Starting ns-loop at Wed Nov 22 19:32:02 EST 2017:
ns://JSON/shell/cgm/ns-glucose.json
reporting cgm/ns-glucose.json
ns://JSON/shell/settings/temptargets.json
reporting settings/temptargets.json
get-profile://text/shell/settings/profile.json
reporting settings/profile.json
Refreshed temptargetsns://JSON/shell/monitor/carbhistory.json
reporting monitor/carbhistory.json
 and meal-carbs
{"batteryVoltage":3838, "battery":66}
Uploaded
Starting ns-loop at Wed Nov 22 19:34:03 EST 2017:
ns://JSON/shell/cgm/ns-glucose.json
reporting cgm/ns-glucose.json
ns://JSON/shell/settings/temptargets.json
reporting settings/temptargets.json
get-profile://text/shell/settings/profile.json
reporting settings/profile.json
Refreshed temptargetsns://JSON/shell/monitor/carbhistory.json
reporting monitor/carbhistory.json
 and meal-carbs
{"batteryVoltage":3834, "battery":65}
Uploaded
Starting ns-loop at Wed Nov 22 19:36:02 EST 2017:
```

**Comment by scottleibrand** [comment]
Sorry, I meant the pump-loop.log. Yes, the old ns-loop.log is nearly worthless. :-)

**Comment by Bender1061** [comment]
are you looking for more than what I posted above?

**Comment by cjo20** [comment]
http://paste.debian.net/997163/ Is this what you're looking for?

**Comment by danamlewis** [comment]
I believe this is resolved via a) some of the refactoring going into 0.7.0 (https://github.com/openaps/oref0/pull/973) and b) what we added in to 0.6.0 for not looping off of stale/old data (also related to ensuring safety from DIY calibration algorithms).
