### ISSUE TITLE
Setup Script Run Again

### ISSUE THREAD

**Issue by sjolundjohn** [openaps/oref0#801]
I am having problems with the setup script when trying to run it again.

The starting point is a functioning rig, where I have run the setup script successfully.

After doing a new pull of oRef, I run the following script:
`bash ~/myopenaps/oref0-runagain.sh`

The expected behavior is that it will run my exact code again. It doesn't. I get:
`oref0-setup --dir=/root/myopenaps --serial=XXXXX --cgm=G5-upload --ns-host=https://XXX.XXX.com --api-secret=XXX --max_iob=0 --radio_locale='US'`

1) The API Secret is incorrect and cut at 9 characters
2) Max IOB is set to 0 - this may be correct safety value, but not what I setup
3) The radio locale is set to US when it should be WW.

**Comment by scottleibrand** [comment]
Can you reproduce the problem on a new oref0-setup run with 0.6.0-rc1?  The oref0-runagain.sh gets created when you run oref0-setup, so it could've been created some time ago.

**Comment by sjolundjohn** [comment]
Exact same issue: I just did a pull of 0.6.0-rc1 and got the same behavior.

Expected return:
`# To run again with these same options, use: 
oref0-setup --dir=/root/myopenaps --serial=XXXXXX --cgm=G5-upload --ns-host=https://XX.XX.com --api-secret=XXXXXXXXXXXXXXXXXXXX --tty=/dev/ttyACM0 --max_iob=7 --enable=' autosens  autotune  meal ' --radio_locale='WW' --ww_ti_usb_reset='yes'`

Actual Return:
`# To run again with these same options, use: 
oref0-setup --dir=/root/myopenaps --serial=XXXXXX --cgm=G5-upload --ns-host=https://sjoscout.herokuapp.com --api-secret=XXXXXXXXX --max_iob=0 --radio_locale='US'`

**Comment by scottleibrand** [comment]
What does `cat ~/myopenaps/oref0-runagain.sh` show?  If you run oref0-setup interactively and answer all the questions, does it show your answers in the "To run again" line and subsequently in `cat ~/myopenaps/oref0-runagain.sh`?  Or does it mess them up?

**Comment by sjolundjohn** [comment]
It shows the correct response:
`root@edison2:~/myopenaps# cat ~/myopenaps/oref0-runagain.sh
# To run again with these same options, use: 
oref0-setup --dir=/root/myopenaps --serial=XXX --cgm=G5-upload --ns-host=XXX --api-secret=XXXX --tty=/dev/ttyACM0 --max_iob=7 --enable=' autosens  autotune  meal ' --radio_locale='WW' --ww_ti_usb_reset='yes' `

When I run the script again, the same behavior happens and it gets messed up again.

**Comment by scottleibrand** [comment]
I just tried this and wasn't able to reproduce.  Can you try the exact same command, XXs and all?

`oref0-setup --dir=/root/myopenaps --serial=123456 --cgm=G5-upload --ns-host=https://XX.XX.com --api-secret=XXXXXXXXXXXXXXXXXXXX --tty=/dev/ttyACM0 --max_iob=7 --enable=' autosens autotune meal ' --radio_locale='WW' --ww_ti_usb_reset='yes'
Setting up oref0 in /root/myopenaps for pump 123456 with G5-upload CGM,
NS host https://XX.XX.com, TTY /dev/ttyACM0, max_iob 7, advanced features  autosens autotune meal

# To run again with these same options, use:
oref0-setup --dir=/root/myopenaps --serial=123456 --cgm=G5-upload --ns-host=https://XX.XX.com --api-secret=XXXXXXXXXXXXXXXXXXXX --tty=/dev/ttyACM0 --max_iob=7 --enable=' autosens autotune meal ' --radio_locale='WW' --ww_ti_usb_reset='yes'`

**Comment by sjolundjohn** [comment]
When I am running I am using only the following:

`bash ~/myopenaps/oref0-runagain.sh`

Installing on two rigs at home and can test again as needed.

**Comment by scottleibrand** [comment]
Since I don't have a copy of your ~/myopenaps/oref0-runagain.sh (since it has your passwords in it) I need you to reproduce the problem using an oref0-setup run without any sensitive data.  That's why I asked you to run  `oref0-setup --dir=/root/myopenaps --serial=123456 --cgm=G5-upload --ns-host=https://XX.XX.com --api-secret=XXXXXXXXXXXXXXXXXXXX --tty=/dev/ttyACM0 --max_iob=7 --enable=' autosens autotune meal ' --radio_locale='WW' --ww_ti_usb_reset='yes'`

**Comment by sjolundjohn** [comment]
Ok - running setup. Here is the input:
`Setting up oref0 in /root/myopenaps for pump 123456 with G5-upload CGM, 
NS host https://XX.XX.com, TTY /dev/ttyACM0, max_iob 7, advanced features  autosens  autotune  meal 

# To run again with these same options, use: 
oref0-setup --dir=/root/myopenaps --serial=123456 --cgm=G5-upload --ns-host=https://XX.XX.com --api-secret=XXXXXXXXXXXXXXXXXXXX --tty=/dev/ttyACM0 --max_iob=7 --enable=' autosens  autotune  meal ' --radio_locale='WW' --ww_ti_usb_reset='yes'

Continue? y/[N] `

**Comment by scottleibrand** [comment]
That looks good.  Can you try copying and pasting your actual runagain string the same way and see whether it works properly or gives you the truncated version with the wrong max_iob?  If it's still wrong, can you try changing the API_SECRET and see if it still fails?  I wonder if your API_SECRET has some special characters in it that are throwing off `bash`...

**Comment by sjolundjohn** [comment]
That produced a different result.

`root@edison1:~# bash ~/myopenaps/oref0-runagain.sh
Setting up oref0 in /root/myopenaps for pump 123456 with G5-upload CGM, 
NS host https://XX.XX.com, TTY /dev/ttyACM0, max_iob 7, advanced features  autosens  autotune  meal 

# To run again with these same options, use: 
oref0-setup --dir=/root/myopenaps --serial=123456 --cgm=G5-upload --ns-host=https://XX.XX.com --api-secret=XXXXXXXXXXXXXXXXXXXX --tty=/dev/ttyACM0 --max_iob=7 --enable=' autosens  autotune  meal ' --radio_locale='WW' --ww_ti_usb_reset='yes'

Continue? y/[N] `

I will setup properly again and then see what happens.

**Comment by sjolundjohn** [comment]
My API Secret has a "&" - and it is cutting the password there.

**Comment by scottleibrand** [comment]
Ah, that would do it.  `&` is the bash special character for "run this process in the background".

**Comment by scottleibrand** [comment]
The proper way to escape `&` characters is with single quotes.  If you'd like you could try to figure out how to make oref0-setup (and cron, and .bash_profile, etc.) do that, or we could just add a note to the docs telling people not to use `&` in their API_SECRET.

**Comment by sjolundjohn** [comment]
The second option seems easier AND I will change my password so long.

**Comment by scottleibrand** [comment]
Ok, I've updated the docs accordingly.  Thanks for your help tracking this down.
