### ISSUE TITLE
Radio Reboot on Dev RC

### ISSUE THREAD

**Issue by sjolundjohn** [openaps/oref0#802]
Since installing latest Rev I am getting big connection issues.

Rebooting to fix radio errors!
The system is going down for reboot at Tue 2017-11-14 23:52:02 PST!

Keep getting this repeated on my rig that has a TI stick. Trying to step back and see what is causign it.

**Comment by sjolundjohn** [comment]
On My explorer board rig, when looking at Pump Loop Tail I get this:
`Listening for 40s silence before mmtuning: .No interfering pump comms detected from other rigs (this is a good thing!)
mmtune: TypeError: Odd-length string`

**Comment by sjolundjohn** [comment]
When I then run mmtune I get this on the explorer board:
`retry 0  (Do you need to run 'export RFSPY_RTSCTS=0' first?)`

**Comment by scottleibrand** [comment]
Double-check your serial number: I think I got `Odd-length string` when I typo'd my serial number as 5 digits instead of 6...

**Comment by sjolundjohn** [comment]
I always copy paste the entries so this is unlikely - I am stepping through to try to reproduce.

I was able to resolve by switching and synching master branch, installing, switching and synching to dev, running `npm run global-install` and then installing.

Doesn't help too much. WIll report back with what I find.

**Comment by scottleibrand** [comment]
Closing for now.  Please re-open if you see this again.
