### ISSUE TITLE
Autotune: carb_data instead of prepped_glucose_data used.

### ISSUE THREAD

**Issue by AdrianLxM** [openaps/oref0#814]
https://github.com/openaps/oref0/blob/dev/bin/oref0-autotune-prep.js#L91

Should this really read `carb_data = JSON.parse(fs.readFileSync(prepped_glucose_input, 'utf8'));` or rather `prepped_glucose_data = JSON.parse(fs.readFileSync(prepped_glucose_input, 'utf8'));` ?

**Comment by scottleibrand** [comment]
I don't think that code path has ever actually done anything.  I only vaguely remember why I had it in there when initially developing it, but apparently never ended up using it.  I just pushed https://github.com/openaps/oref0/compare/dev...cleanup to comment it out, if you're interested in testing to make sure that doesn't break anything.  I'll probably merge that for 0.6.1

**Comment by scottleibrand** [comment]
https://github.com/openaps/oref0/pull/828 is now merged to dev.  Closing.
