### ISSUE TITLE
glucose-fresh in `oref0-pump-loop.sh` references field not present in MDT data

### ISSUE THREAD

**Issue by cjo20** [openaps/oref0#827]
glucose-fresh executes this line:
` touch -d "$(date -R -d @$(jq .[0].date/1000 monitor/glucose.json))" monitor/glucose.json 2>/dev/null`
which requests the `date` field in the json records. MDT data doesn't have this date field. An example MDT record is:
```
  {
    "trend_arrow": "FLAT",
    "direction": "Flat",
    "name": "GlucoseSensorData",
    "date_type": "relative",
    "_tell": 3,
    "display_time": "2017-11-28T01:28:00+00:00",
    "packet_size": 0,
    "op": 97,
    "glucose": 194
  },
```

**Comment by cjo20** [comment]
Looks like it's possible to do the same thing in a horrible way involve sed from the `display_time` field:
`touch -t $(jq  .[0].display_time monitor/glucose.json | sed 's/[-T"]//g; s/://; s/:/\./; s/+.*//') monitor/glucose.json 2>&1` is as far as I've got so far (still testing)

**Comment by scottleibrand** [comment]
I think you're looking for `touch -d $(jq -r .[0].display_time monitor/glucose.json) monitor/glucose.json` or similar.

**Comment by cjo20** [comment]
Yup, that doesn't give any errors.

**Comment by cjo20** [comment]
Potential fix here: https://github.com/openaps/oref0/pull/845

**Comment by danamlewis** [comment]
Resolved via https://github.com/openaps/oref0/pull/845.
