### ISSUE TITLE
Hard Cutoff of basal below a certain level

### ISSUE THREAD

**Issue by eyim** [openaps/oref0#84]
There should be a level that cuts of the basal no matter what below a certain level.  There has been discussion to set this somewhere between 55 and threshold

**Comment by scottleibrand** [comment]
@eyim in Gitter: "In particular, where it affects us is if it has low temped him for a while maybe 2 hours and has significant negative iob then it will try to give him extra insulin to counteract that when in reality it doesn't need to. I had hoped the auto sensitivity stuff would help but I didn't find that"

**Comment by scottleibrand** [comment]
See also discussion with @tazitoo starting at https://gitter.im/nightscout/intend-to-bolus?at=56e4dcaa89dd3cce1005f682

**Comment by scottleibrand** [comment]
This has been merged to dev.  Please test and reopen if you see any bugs.
