### ISSUE TITLE
0.6.0: "skip_neutral_temps": true fails a safety check.

### ISSUE THREAD

**Issue by davidwagaps** [openaps/oref0#840]
Per @scottleibrand There is a safety check that doesn’t work right with skip_neutral_temps
Because its corrective action is to set a neutral temp.

skip_neutral_temps is helpful to minimize beeps/vibrations which has been known to wake up pump users or disturb their classmates & teachers (said pump users will remain anonymous of course).

Possible solution is to deprecate that setting and instead cancel the temp just before the top of the hour and then restart it just after.

**Comment by scottleibrand** [comment]
Please test https://github.com/openaps/oref0/pull/842 and see if it fixes this.

**Comment by davidwagaps** [comment]
Checks:
1. Does NOT cancel zero temp at :55 - pass
2. Otherwise cancels temp at :55 - pass
3. Resumes normal operation at :00 (sets temp if necessary sometime after
that) - pass
4. Does not set temp if temp = current pump basal setting (original "skip"
functionality) - pass
5. "reason":"Warning: currenttemp rate 0 != lastTemp rate 2.35 from
pumphistory; " - no longer appears in pill or log: pass

Looks good. Thanks so much!

**Comment by danamlewis** [comment]
Resolved via https://github.com/openaps/oref0/pull/842, so closing
