### ISSUE TITLE
Warning `SMB disabled (no enableSMB preferences active) ` is unclear

### ISSUE THREAD

**Issue by PieterGit** [openaps/oref0#853]
With oref0-version `0.6.1-dev [dev]` I noticed the following in the pump loop log.

```
SMB disabled (no enableSMB preferences active) 
```

Which seems untrue, because I have:
```
 "enableSMB_with_COB": true,
 "enableSMB_with_temptarget": true,
```

This is caused by this line 
https://github.com/openaps/oref0/blob/174ef43c7f5dfb7a9c3f578bf38a939d4bccb034/lib/determine-basal/determine-basal.js#L404
(master)

The error seems to imply that SMB is disabled, which is not true for all runs, but only for this run.
Wouldn't it be better to log this as, something like:
`Not issuing SMB. Either an enableSMB preference is disabled, or a required precondition for issuing SMB does not apply`

Can you please help me make this text more clear (I'm not a native English speaker). If so, I can proppose a PR to make the error message more clear.

**Comment by cjo20** [comment]
Something like `SMB disabled (no selected enableSMB criteria met)` might be better?

**Comment by PieterGit** [comment]
I was confused by the `SMB disabled` because it's only disabled for that run. On the contrary
`Autotune exists! Hoorah! You can use microbolus-related features.` is for all runs. So I would prefer something like `SMB disabled for this run (no selected enableSMB criteria met)`. 

This should of course only be shown when people use SMB. It's not relevant for non SMB users.

**Comment by GlennCoco** [comment]
I see that this is still happening, was there going to be a fix for this? I also get confused watching that in the logs. One of the reasons I put the enableSMB_always preference to true was because of this message and may also drive other users to do the same.

**Comment by scottleibrand** [comment]
I don't think anyone has yet PR'd in this suggested change.  If you'd like to, please go ahead.

**Comment by scottleibrand** [comment]
Thanks.
