### ISSUE TITLE
AttributeError: 'module' object has no attribute 'spiFromDesc'

### ISSUE THREAD

**Issue by endafarrell** [openaps/oref0#857]
Setting up an Edison+Explorer Block for the first time (ever).

I ran the oref0-setup, got this  (expected)
```
# To run again with these same options, use:
oref0-setup --dir=/root/myopenaps --serial=XXXXXX --cgm=xdrip --ns-host=https://XXXXXXX --api-secret=XXXXXXXXX --tty=/dev/spidev5.1 --max_iob=2 --enable=' autosens  autotune  meal ' --radio_locale='WW'
``` 

and some minutes later: 
```
Adding OpenAPS log shortcuts
Add NIGHTSCOUT_HOST and API_SECRET to /root/.bash_profile
sed: can't read .profile: No such file or directory
sed: can't read .profile: No such file or directory

Resetting spi_serial
Traceback (most recent call last):
  File "/usr/local/bin/reset_spi_serial.py", line 3, in <module>
    s = spi_serial.SpiSerial()
  File "/usr/local/lib/python2.7/dist-packages/spi_serial/spi_serial.py", line 11, in __init__
    self.dev = m.spiFromDesc("spi-raw-5-1")
AttributeError: 'module' object has no attribute 'spiFromDesc'
Schedule openaps in cron? y/[N]
```

The `AttributeError: 'module' object has no attribute 'spiFromDesc'` is unexpected. 

So far, this does not seem to have caused any issues with looping.

**Comment by scottleibrand** [comment]
Was this the first time running oref0-setup on this rig? Did it prompt you to reboot? If so, that is why: until reboot the SPI comms don’t work.

**Comment by endafarrell** [comment]
It was the first time running oref0-setup on that rig. It's been looping fine. given that a _lot_ goes by on the screen, and that once reboots are done, perhaps a note in the docs to say something like  "some errors will be seen in the logs, but all are expected to be cleared-up after reboots and the first successful loop have been completed" would be good.

**Comment by scottleibrand** [comment]
Yeah, sounds like a good docs PR if you’re up for it.

**Comment by jimrandomh** [comment]
Ran into this same error. I don't think the docs should have a catch-all "errors are okay" message; that's inviting people to ignore errors that are not okay. Better would be to list specific errors that are expected and known to be harmless.
