### ISSUE TITLE
Circadian Percentage Profile

### ISSUE THREAD

**Issue by Jane49** [openaps/oref0#864]
Due to illness I often need very large percentage increases for days at a time.  Before looping I used omnipod and found this relatively easy to deal with by running two profiles and percentaging upwards occasionally have hit 400%.  This happens 7 or 8 times a year.
With AAPS I got around this problem using Circadian Percentage Profile with two basal profiles, one being double my ‘regular’ profile and percentaging upwards (AAPS only goes up to 200%).  Occasionally I run low for a couple of days and then percentage below the regular profile.
This method was also very useful for regular monthly hormonal changes; many women could benefit.
A Circadian Percentage Profile preference in OpenAPS would be very valuable; it could enable timeshift and percentage change as used in AAPS. This could work with any Profile using a true/false preference to timeshift and/or change percentage.  It would make it easy to increase or decrease any profile (basal, bolus and sensitivity) by e.g. 300% for x hours during illness or on meds leading to major insulin resistance e.g. prednisolone, predicted monthly hormone cycles or any other events.  AAPS Profile switching is triggered by a Nightscout Careportal entry or Profile Switch; OpenAPS could use the same and add variables to preferences.json.   
It also enables the use of conditional statement based systems (e.g. IFTTT/Automate/Tracker) to automatically change the profile based on other inputs (e.g. calendar entries, physical location, medication entries).
•	Circadian Percentage Profile, timeshift and percentage changes could be enabled and set in preferences
o	Timeshift - this moves everything round the clock by the number of hours entered. So for example, when working night shifts change the number of hours to how much later/earlier you go to bed or wake up.
o	Percentage - this applies the same percentage to all parameters. If you set it to 300 it will up the basal rate by 300%. It should also raise the ISF and IC accordingly.  The loop algorithm continuing to work on top of the selected percentage profile.

**Comment by scottleibrand** [comment]
How do you envision this interacting with autosens?  (Do you use autosens?)

**Comment by Jane49** [comment]
My thought would be to reset ratio to 1 for the percentaged ISF?   
Don't know too much about autosens - have homework still to do.

**Comment by scottleibrand** [comment]
Most of the situations in which you’re talking about using autosens are already handled by autosens, at least to some degree. We also have the ability to set sensitivityRatio using high or low temp targets. So we need to figure out how CPP would interact with those features.
