### ISSUE TITLE
Problem with edison-battery.json logic in oref0-ns-loop on Raspberry Pi prevents OpenAPS pill updates

### ISSUE THREAD

**Issue by johnmales** [openaps/oref0#868]
Latest dev installation, fresh install of Raspbian Stretch on Pi3, fresh install of openaps/oref0 dev.

ns-loop.log showing:
`Couldn't generate ns-status.json`

`monitor/edison-voltage.json` is an empty file

Running `oref0-ns-loop` at the command line shows:
`Could not parse input data:  [SyntaxError: /home/pi/myopenaps/monitor/edison-battery.json: Unexpected end of input]`

Placing fake data in `monitor/edison-voltage.json`
e.g.:
`{"batteryVoltage":3873, "battery":69}`
allows oref0-ns-loop to correctly complete, OpenAPS pill in nightscout updates properly.

Some change to logic with regards to `edison-voltage.json` when running on a Pi is required. Will attempt to investigate.

**Comment by danamlewis** [comment]
Closing as resolved via https://github.com/openaps/oref0/pull/870
