### ISSUE TITLE
Make autotune its own repo and import from oref0 and NS

### ISSUE THREAD

**Issue by scottleibrand** [openaps/oref0#874]
Per https://github.com/openaps/oref0/pull/872, since we're now moving toward running autotune in both oref0 and in Nightscout, it would be best if we move autotune out into its own repo and NPM package, and import that into both oref0 and cgm-remote-monitor, so we don't have to maintain identical copies of the autotune libs in both repos.

**Comment by chadharper0131** [comment]
i like it uhlooott! Do Ittttt....... 👍 😆 😀 (remember.... 🗯 Jim Carrey in, umm..... *shiot! i forget!... the movie with the "dog" Van ... (to gas it up & put in the pump, you have to lift the "dogs leg"...)

**Comment by danamlewis** [comment]
Closing per #872
