### ISSUE TITLE
any delta < -1 will result in FortyFiveDown

### ISSUE THREAD

**Issue by efidoman** [openaps/oref0#880]
https://github.com/openaps/oref0/blob/4b01147136573aa94765a9b2cdeb1b5785f276c0/bin/oref0-mdt-trend.js#L98

I believe there may be an issue with the if/else series referenced above. The example I came across is if delta is -5, then the else if  .... < -1 becomes true and the direction gets set to FortyFiveDown when it should probably be DoubleDown based on a delta per minute average. I'm implementing this in bash for xdrip-js-logger and noticed this issue during my testing. Granted, it was translated to bash so perhaps this isn't an issue?

**Comment by efidoman** [comment]
changing the order to as follows may resolve the issue:
'''
		else if (delta < -3)
		{
			output_record.trend_arrow = "DOUBLE_DOWN";
			output_record.direction = "DoubleDown";
		}
		else if (delta < -2)
		{
			output_record.trend_arrow = "SINGLE_DOWN";
			output_record.direction = "SingleDown";
		}
		else if (delta < -1)
		{
			output_record.trend_arrow = "45_DOWN";
			output_record.direction = "FortyFiveDown";
		}
'''

**Comment by scottleibrand** [comment]
I believe your analysis is correct.  Want to open a PR to dev with that fix?

**Comment by efidoman** [comment]
Yes, I will do the PR now

**Comment by efidoman** [comment]
This issue was fixed in another PR.
