### ISSUE TITLE
`remainingCATime` is undefined when meal_data.carbs == 0

### ISSUE THREAD

**Issue by MilosKozak** [openaps/oref0#884]

**Comment by MilosKozak** [comment]
@scottleibrand any default value possibe?

**Comment by scottleibrand** [comment]
Testing out defaulting it to remainingCATimeMin (3h) in https://github.com/openaps/oref0/commit/e1448b206f45ba8db69a6205d8ef3381be92bec5

**Comment by MilosKozak** [comment]
can i add this to AAPS?

**Comment by scottleibrand** [comment]
I haven’t seen any problems with it.

**Comment by danamlewis** [comment]
Resolved; closing.
