### ISSUE TITLE
PI-hat problem with WW-pump: "retry 0  (Do you need to run 'export RFSPY_RTSCTS=0' first?)"

### ISSUE THREAD

**Issue by PieterGit** [openaps/oref0#887]
Having problems with WW setup:

```
root@pi3:~/myopenaps# openaps mmtune
...
The CC111x is located at /dev/spidev0.0
retry 0  (Do you need to run 'export RFSPY_RTSCTS=0' first?)
retry 0  (Do you need to run 'export RFSPY_RTSCTS=0' first?)
retry 0  (Do you need to run 'export RFSPY_RTSCTS=0' first?)
```

This i called from `oref0_init_pump_comms.py` which spawns `oref0-subg-ww-radio-parameters`
I tried setting `RFSPY_RTSCTS=0` but that doesn't help. Calling it with `oref0_init_pump_comms.py -v` gives:

```
2018-01-04 22:39:14,132 DEBUG Serial device (port) for pump is: /dev/spidev0.0
2018-01-04 22:39:14,133 DEBUG env RFSPY_RTSCTS=0
2018-01-04 22:39:14,133 DEBUG excuting ['oref0-subg-ww-radio-parameters', '/dev/spidev0.0', '--resetpy']
```

So it's called with: `oref0-subg-ww-radio-parameters /dev/spidev0.0 --resetpy`
and also with enabling `set -x ` I found out that the root cause is in `subg_rfspy` `reset.py`:

```
cd /root/src/subg_rfspy/tools && ./reset.py /dev/spidev0.0
retry 0  (Do you need to run 'export RFSPY_RTSCTS=0' first?)
retry 0  (Do you need to run 'export RFSPY_RTSCTS=0' first?)
retry 0  (Do you need to run 'export RFSPY_RTSCTS=0' first?)
```

I also tried disabling the `reset.py ` call, but then it fails on `change_setting.py` with same `retry 0` error.

Tested with Explorer HAT on RPI3 used PT-hat branch of spi_serial as @scottleibrand suggest in:
https://gitter.im/openaps/hardware-dev?at=5a4d3772232e79134dc135fc

Is the way to reset a PI-hat different than on an Explorer. Any hints to proceed?

**Comment by PieterGit** [comment]
Should I reflash and ccprog with the commands described on http://openaps.readthedocs.io/en/latest/docs/Resources/troubleshooting.html?highlight=ccprog#could-not-get-subg-rfspy-state-or-version-have-you-got-the-right-port-device-and-radio-type

or does it work differently for a PI HAT?

**Comment by PieterGit** [comment]
Reflashed 0.8 firmware with `./ccprog -p 16,18,7`  but doesn't help. Same error.

**Comment by silentium123** [comment]
Please help, i twice asking for help on gitter but did not find a solution
I few days ago i have the same error
retry 0  (Do you need to run 'export RFSPY_RTSCTS=0' first?)
and after reflashing radio chip i have each times errors during openaps instalation (i reflashing intel edison 5 times) and only then i reflash jubilinux 0.1 version i succsesfuly install openaps and system working well
But i am confussed that then then i make some change i cant to run comand "openaps init"
root@edison:~/myopenaps# openaps init
Traceback (most recent call last):
  File "/usr/local/bin/openaps", line 170, in <module>
    app( )
  File "/usr/local/lib/python2.7/dist-packages/openaps/cli/__init__.py", line 51, in __call__
    self.run(self.args)
  File "/usr/local/bin/openaps", line 155, in run
    builtins.dispatch(args, self)
  File "/usr/local/lib/python2.7/dist-packages/openaps/builtins.py", line 44, in dispatch
    command(args)
  File "/usr/local/lib/python2.7/dist-packages/openaps/init.py", line 6, in init
    if args.args[1] == '--nogit':
IndexError: list index out of range

P.S: sorry for poor english

**Comment by scottleibrand** [comment]
@silentium123 The Explorer HAT is not generally available yet, so this issue is probably different than yours. I’ll follow up on Gitter.

**Comment by silentium123** [comment]
What is Explorer Hat, is it right that at this time there are not solution to fix this error? Maybe i need to make new issue?
Thanks for answer!

**Comment by scottleibrand** [comment]
https://gitter.im/nightscout/intend-to-bolus?at=5a54e4a85a9ebe4f7566c28c

**Comment by PieterGit** [comment]
I just did a reinstall of explorer-hat branch 751f9bf13080d1f1e75eb7287541c9f44459cc09
No effect on `retry 0` behaviour. 
Also downgraded kernel from 4.9.73+ to 4.9.59+ no effect
Extra info  `/etc/rpi-issue` is `Raspberry Pi reference 2017-11-29`
I will do a complete reinstall on a fresh SD card this weekend.

**Comment by danamlewis** [comment]
Closing as I assume due to lack of activity this has successfully been resolved; please re-open if it's still an active issue.
