### ISSUE TITLE
After fresh install of dev branch, expected input files for loop to complete are not there

### ISSUE THREAD

**Issue by rkresha** [openaps/oref0#889]
```
Old pumphistory-24h refreshed
Old settings: ls: cannot access settings/profile.json: No such file or directory
Profile invalid: ls: cannot access settings/profile.json: No such file or directory
Couldn't refresh_old_profile
oref0-pump-loop failed.
```

The only way I have found to get around this is to go and manually run the reports to generate the profile.json
```
openaps report invoke settings/settings.json
openaps report invoke settings/bg_targets_raw.json
openaps report invoke settings/bg_targets.json
openaps report invoke settings/insulin_sensitivities_raw.json
openaps report invoke settings/insulin_sensitivities.json
openaps report invoke settings/basal_profile.json
etc
```
I could back my way into the fix in the scripts but someone more closely involved with the ".new" effort maybe able to get there quicker.

**Comment by CaptainBalou** [comment]
I saw the same. Got it fixed but have not found the exact component which caused the trouble. I try to investigate further when I am in a 'low carb situation'. I have just one rig so it's sometimes hard to destroy this rig with intent.

**Comment by scottleibrand** [comment]
Found the issue: there is now a proposed fix at https://github.com/openaps/oref0/issues/894 that just needs someone with an x12 pump to test for compatibility.

**Comment by danamlewis** [comment]
Closing as resolved in https://github.com/openaps/oref0/pull/894
