### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by metzlernsdb** [openaps/oref0#906]
After reading many facebook comments/threads, I was wondering if it would it be possible to request a way to turn autotune/autosens on and off. A true light switch version of on and off.

I know personally I would like to try turning it off and see the results, vs on.  Small basal needs (generally 0.4 units per hour or so) seems like I don't get much wiggle room.

Just throwing it out there.  I wasn't sure if anyone has wanted this before or not.  

If I can provide any more information, I would be happy to.

**Comment by scottleibrand** [comment]
You can turn it off by setting both the autosens min and max to 1. 

If you see worse results with autotune/autosens than without, please let me know so I can look at it with you and figure out what tweaks are needed to the algorithm to make it perform better.

**Comment by metzlernsdb** [comment]
I can't say that I've that myself, but from a recent FB post, some are saying it still controls your ISF (randomly? or maybe only certain rigs/people have that problem?)

I could try it myself to see.  If I set both to 1, is it now using the pump settings or is now using the last autotune setting?  

If using the last autotune setting, then I think having an on/off switch would still be important/easier, but maybe I'm mistaken.  I appreciate your help/advice.  (otherwise I need to delete the files, run the script without autotune, etc, right? - That would be the reasoning for my request if it's easy enough to add an on/off in a future release.

Thanks again!

**Comment by scottleibrand** [comment]
Setting both to 1 will disable autosens on the next settings refresh, reverting to the latest autotune settings. On the next autotune run, those will revert to pump settings.

**Comment by metzlernsdb** [comment]
Didn't know that!  That's perfect.  Is that new with 0.6 or has it always been that way?  Maybe I could PR the docs to say that in case anyone else has those questions.

**Comment by scottleibrand** [comment]
That part is unchanged. There also used to be an enable/disable option in oref0-setup, but it stopped working with the oref0-pump-loop refactor, so we just removed that and left autosens always enabled.
