### ISSUE TITLE
For using meal-assist it is essential to make sure that units is set to grams

### ISSUE THREAD

**Issue by MosiGitHub** [openaps/oref0#91]
it is possible to change the setting between "exchange" and "grams" in the bolus wizard menue of the pump under Carb. Units. Exchange is used to express how many insulin units are necessary to be given for 1 BE (10 to 12 grams of carbohydrate). In our case it was 0.6 units for 10 grams  of carbs. If the option "grams" is selected the input is how many grams of carbs are necessary for 1 unit of insulin. In this example 16. Meal-assist uses the carb_ratios.json for its calculations and expects the value entered in "grams". If the setting "exchange" is used, it calculates way to aggressive. It should be made clear in the docs how important it is to use the "grams" setting with meal-assist and to implement a verification which setting is used when the JSON-file is generated. If the setting "exchange" is used, the values should be refused and the error message should point to set the setting to "grams"

**Comment by scottleibrand** [comment]
$ openaps report invoke settings/profile.json && cat settings/profile.json
get-profile://text/shell/settings/profile.json
reporting settings/profile.json
{"max_iob":3,"type":"current","dia":3,"current_basal":1.15,"max_daily_basal":1.3,"max_basal":4,"min_bg":115,"max_bg":115,"sens":40,"carb_ratio":10}

**Comment by scottleibrand** [comment]
@MosiGitHub Can you please test https://github.com/openaps/oref0/commit/970a5a9d46477558b6c6516215c41109f415acd2 and make sure it prevents use of Exchange units for you?

**Comment by MosiGitHub** [comment]
@scottleibrand thankyou for your fast solution. We are presently on vacation. I will try to check it next week

**Comment by scottleibrand** [comment]
@MosiGitHub are we good to close this?

**Comment by MosiGitHub** [comment]
I was thinking more of a solution like this (see below). It is not yet tested, because I had lots to do in the last couple of weeks and I just wrote it in the last 5 minutes. But you are asking to close this subject therefor I wanted to make a suggestion how to let the loop run with "exchanges" instead of "grams". I will test it tonight, when my son is in bed and the other rig is running ... I expect that there are some mistakes especially the {} stuff ;-) But the idea behind is that "exchanges" defines how much insulin is needed for 10 or 12 grams of carbohydrates - depending on how you calculate a "BE". so it could be easily transfered to "grams" by dividing the carbohydrate value (10 or 12) by the factor from the pump. I did pretty much the same in the last couple of weeks in a static carb_ratio.json. If it is workinb I will make a PR out of this....
var getTime = require('../medtronic-clock');

function carbRatioLookup (inputs) {
    var now = new Date();
    var carbratio_data = inputs.carbratio;
    if (typeof(carbratio_data) != "undefined" && typeof(carbratio_data.schedule) != "undefined") {
        var carbRatio;
        if (carbratio_data.units == "grams") {
            //carbratio_data.schedule.sort(function (a, b) { return a.offset > b.offset });
            carbRatio = carbratio_data.schedule[carbratio_data.schedule.length - 1];

            for (var i = 0; i < carbratio_data.schedule.length - 1; i++) {
                if ((now >= getTime(carbratio_data.schedule[i].offset)) && (now < getTime(carbratio_data.schedule[i + 1].offset))) {
                    carbRatio = carbratio_data.schedule[i];
                    break;
                }
            }
        } else {
            if (carbratio_data.units == "exchanges") {
            //carbratio_data.schedule.sort(function (a, b) { return a.offset > b.offset });
            carbRatio = carbratio_data.schedule[carbratio_data.schedule.length - 1];

                for (var i = 0; i < carbratio_data.schedule.length - 1; i++) {
                    if ((now >= getTime(carbratio_data.schedule[i].offset)) && (now < getTime(carbratio_data.schedule[i + 1].offset))) {
                        carbRatio = (10/carbratio_data.schedule[i]);
                        break;
                    }
                }
            } else {
                console.error("Error: Unsupported carb_ratio units " + carbratio_data.units);
                return;
            }
        }
    return carbRatio.ratio;
    //profile.carbratio = carbRatio.ratio;
    } else { return; }
}

carbRatioLookup.carbRatioLookup = carbRatioLookup;
exports = module.exports = carbRatioLookup;

**Comment by MosiGitHub** [comment]
as I made a PR that should work with the setting "exchanges" as well, we can close this issue from my point of view
