### ISSUE TITLE
A lot of JavaScript/Bash errors/warnings

### ISSUE THREAD

**Issue by denisshevchenko** [openaps/oref0#928]
I tested code of `oref0` (`dev` branch) with `jshint v2.9.5`. Results:

```
oref0/lib   - 333 errors
oref0/bin   - 141 errors
oref0/www   - 126 errors
oref0/tests - 187 errors

      Total - 787 errors
```

After that I tested bash-scripts with `shellcheck 0.4.4`. Results - 525 warnings.

And later I tested Python-code with `pylint 1.6.5`:

```
% errors / warnings by module
-----------------------------

+-------------------------------+------+--------+---------+-----------+
|module                         |error |warning |refactor |convention |
+===============================+======+========+=========+===========+
|oref0_nightscout_check         |27.27 |17.96   |0.00     |10.83      |
+-------------------------------+------+--------+---------+-----------+
|oref0_subg_ww_radio_parameters |27.27 |13.59   |0.00     |9.64       |
+-------------------------------+------+--------+---------+-----------+
|oref0-dexusb-cgm-loop          |9.09  |28.64   |0.00     |18.61      |
+-------------------------------+------+--------+---------+-----------+
|oref0-autotune                 |9.09  |18.93   |12.50    |16.58      |
+-------------------------------+------+--------+---------+-----------+
|oref0-autotune-export-to-xlsx  |9.09  |11.65   |0.00     |22.00      |
+-------------------------------+------+--------+---------+-----------+
|oref0_autotune_export_to_xlsx  |9.09  |5.83    |0.00     |16.75      |
+-------------------------------+------+--------+---------+-----------+
|app                            |9.09  |0.97    |87.50    |2.54       |
+-------------------------------+------+--------+---------+-----------+
|oref0_init_pump_comms          |0.00  |2.43    |0.00     |3.05       |
+-------------------------------+------+--------+---------+-----------+
```

I'm absolutely sure that such a project mustn't have warnings/errors, especially **so much**! If you're using
Python, Bash and JavaScript - you should use static analysis tools.

**Comment by scottleibrand** [comment]
If you'd like to help clean up some of these, we'd welcome the help.  The main reason we haven't done so to date is that too many of the problems found by static analysis tools like jslint and shellcheck are either unimportant style things (like presence or absence of `;` at the end of lines) or are things where we're using some bash construct (like redirecting stderr to stdout, and stdout to /dev/null) in a way that they flag as something people normally do by mistake, but we're doing on purpose.

If you do decide to help clean up the code to conform to style and syntax checkers, I would try doing and PR'ing one change at a time, in such a way that it's easy to validate that nothing unintentional is being changed.  So for example, if you wanted to fix just all the missing semicolons, that should be its own commit (and preferably its own PR) so we can get that merged before moving on to more substantive changes.

And of course, feel free to jump into our chat rooms to discuss the best approach to cleaning things up.  https://gitter.im/openaps/oref0 might be the best place to start.

**Comment by denisshevchenko** [comment]
> too many of the problems found by static analysis tools like jslint and shellcheck are either unimportant style things (like presence or absence of ; at the end of lines) or are things where we're using some bash construct (like redirecting stderr to stdout, and stdout to /dev/null) in a way that they flag as something people normally do by mistake, but we're doing on purpose.

Ignoring of warnings (even "unimportant" ones) is a bad practice, please trust me (after 12 years in software development I definitely know it).

> If you do decide to help clean up the code to conform to style and syntax checkers, I would try doing and PR'ing one change at a time...

Good idea!

**Comment by denisshevchenko** [comment]
BTW, why some files are `readonly`?

**Comment by denisshevchenko** [comment]
Ok, I'll prepare PRs.
