### ISSUE TITLE
refactor medtronic specific code to the medtronic driver

### ISSUE THREAD

**Issue by AdrianLxM** [openaps/oref0#946]
This can be found in `determine_basal`:

```
    // if not in LGS mode, cancel temps before the top of the hour to reduce beeping/vibration
    console.error(profile.skip_neutral_temps, rT.deliverAt.getMinutes());
    if ( profile.skip_neutral_temps && rT.deliverAt.getMinutes() >= 55 ) {
        rT.reason += "; Canceling temp at " + rT.deliverAt.getMinutes() + "m past the hour. ";
        return tempBasalFunctions.setTempBasal(0, 0, profile, rT, currenttemp);
    }
```

IMHO this is very pump specific and not an actual therapy recommendation. It goes in the same category as setting a 90% TBR for one minute in order to not have the cancel alarms on other pumps.

Would it be possible to move this to the actual pump driver?

**Comment by scottleibrand** [comment]
I don’t think it would be practical to move this into the low-level pump driver code. However, it probably doesn’t make any sense to have profile.skip_neutral_temps as an option (controlling both behaviors) on non-Medtronic pumps either. If it’d be easier to get the desired behavior on non-Medtronic pumps, we could break them out into two profile options, and have the OpenAPS preferences.json parsing code set them both based on the contents of profile.skip_neutral_temps if the more specific option is not specified.

**Comment by AdrianLxM** [comment]
Having a flag `medtronic_only` (easy to disregard on other systems then ;) ) or `reduce_hourly_vibrations`  most certainly would help to port future versions.

Still believe it to be better to have the code where it belongs conceptually:

It also introduces a side effect as now the outcome of determine_basal does no longer depend only on the input variables. That is something you usually don't want in a library function.

**Comment by scottleibrand** [comment]
It does still depend on the inputs. Profile is an input. 

If you want to help re-do all the plumbing to put the code in the right conceptual location, that’d be great, but seems like a lot of work for little practical gain. 

Let’s just split the preferences for now?

**Comment by AdrianLxM** [comment]
For simplicity reasons: Yes, sure!
Academical discussion should not hinder practical progress ;)

What do you think about the idea to flag a LGS in `rT` and then do the logic with the current time in `oref0/bin/oref0-determine-basal.js`?

**Comment by scottleibrand** [comment]
I'm pretty receptive to refactoring if you are actually submitting a PR; far less so if you're asking me to prioritize doing it myself.  ;-)

**Comment by scottleibrand** [comment]
Closing due to lack of interest. Anyone can free to reopen (or open a PR) if they want to work on it.
