### ISSUE TITLE
Don't overreact to calibration jumps

### ISSUE THREAD

**Issue by scottleibrand** [openaps/oref0#949]
With oref0-g4-loop we now have calibrations available in glucose.json, so it'd be good to have oref0 disable SMB right after calibrations to avoid bolusing on a calibration uptick.

**Comment by jpcunningh** [comment]
I was considering the same problem over the last couple of days. Lookout and xdrip-js-logger can provide the last calibration value and time. What are the contents of a oref0-g4-loop calibration record?

However this is implemented, it would be nice to be able to post a calibration record to the oref0 xdrip server to accomplish similar results if xdrip is being used.

**Comment by scottleibrand** [comment]
I'm currently testing a change in the go-dexcom branch that pulls cal and mbg records from NS (https://github.com/openaps/oref0/commit/60213bc40fcb3887a6c771158f9d69607bbacffb) and stops processing older SGVs if it comes across a cal record (https://github.com/openaps/oref0/commit/07f1e555b11cabbc9d84d87cf8f34a1ae5b43454).

That will prevent calibration jumps from being included in the avgDeltas, and will prevent oref0 from responding aggressively when calibrating while rising, because it will need to get ~15m of data before it can calculate a longAvgDelta > 0.  But when BG is falling, the minDelta will be able to kick in on the second data point after the calibration.  We also now prevent looping entirely when both shortAvgDelta and longAvgDelta are exactly 0, so it will only cancel high temps and shorten long zero temps when there is only a single CGM reading after the last cal record.

**Comment by alimhassam** [comment]
Another approach, (which might or might not be a good idea - i'm not sure - but i'm just mentioning it for discussion) is to recalculate the past n svgs using the new calibration record. xdrip+ already has an option to do that, though it doesn't seem to update the previous entries in ns.

The approach suggested here also  seems a bit aggressive when previous calibration was actually correct, and it seems like it might unnecessarly limit the loop for 15m in that case.

**Comment by scottleibrand** [comment]
This will prevent SMBs or high-temps for up to 5m after a cal record, until the next SGV.  It will then limit (for 20-30m) the use of rising BG to justify SMBs and high-temping.  Given that the PWD can decide when to calibrate and should already be trying to avoid calibrating when BG is rising fast, that seems like an acceptable limitation to me.

I do agree we should consider how best to use the filtered and unfiltered values available from Dexcom sensors.  To date the main use case for them has been during sensor restart, but I can see retrospective recalibration being a useful enhancement in the future.  I think this PR is a good safety improvement in the meantime, though.

**Comment by alimhassam** [comment]
Ah, the title was saying 15m. I should review this more closely.

I personally, often calibrate before by evening meal. Will this stop/delay the smbs on the meal, if i calibrate, and then enter some carbs shortly after?

**Comment by scottleibrand** [comment]
As long as there is 30m between your calibration and the actual BG rise from the meal, it wouldn't affect you.  The expected rise from the carbs you entered will still be applied to the post-calibration SGVs, and it will SMB for those as normal: it will just ignore any positive deltas (since minDelta will be zero) until longAvgDelta starts getting calculated ~30m after the calibration.

**Comment by danamlewis** [comment]
@scottleibrand this is in 0.7.0 now, correct? If so, please comment with link or otherwise update.

**Comment by scottleibrand** [comment]
No, this is still in the go-dexcom branch: https://github.com/openaps/oref0/blob/go-dexcom/lib/determine-basal/determine-basal.js#L77-L83 and https://github.com/openaps/oref0/blob/go-dexcom/lib/glucose-get-last.js#L19-L22

**Comment by scottleibrand** [comment]
Implemented in #677 and modified in #717
