### ISSUE TITLE
Erroneous negative IOB calculated when basal schedule rises >2x

### ISSUE THREAD

**Issue by scottleibrand** [openaps/oref0#95]
@iainct reports at https://github.com/openaps/openaps/issues/88#issuecomment-204859700 that oref0 erroneously calculated a negative IOB based on a basal_profile.json that increases from 0.2 U/hr to 1.4 U/hr over the course of 60 minutes:

```
{ "i": 17, "start": "17:00:00", "rate": 0.2, "minutes": 1020 },
{ "i": 18, "start": "18:00:00", "rate": 0.8, "minutes": 1080 },
{ "i": 19, "start": "19:00:00", "rate": 1.4, "minutes": 1140 }
```

As oref0 currently calculates IOB based on the assumption that the currently scheduled basal profile is "close enough" to use for the last DIA hours' worth of pumphistory, this kind of basal profile is dangerous to use with oref0.

For now, we should detect when ( max_daily_basal / min_daily_basal ) > 3, and error out in that case.  In the long term, we should probably make oref0-calculate-iob smarter about using the basal scheduled at the time of each entry in pumphistory to calculate IOB as well.  I suspect we might want to keep the max/min > 3 check in place even after doing that, though.

**Comment by scottleibrand** [comment]
Coded up the 3x limit.  Can I get some feedback on whether to merge #96 to dev as a fix for this?

**Comment by loudnate** [comment]
You may want to consider using mmhistorytools to normalize temp basals (and suspends) against a basal schedule. It makes no estimations or assumptions about rates staying similar.

**Comment by cjo20** [comment]
This just hit the top of my "stuff to look at" list. Using this issue to track discussion about the best way of integrating mmhistorytools.

**Comment by thebookins** [comment]
Any reason why we can't use the iob report from the last loop run as a starting point for the iob calculation? Then we only need to assume that the current basal profile is "close enough" for the time since last run, not over the whole DIA.  Would also degrade nicely to current behaviour in the event of a break in looping. Sounds like mmhistorytools is the best solution going forward, but something like this might work in the meantime?

It means we're storing some state in the openaps implementation, which might be dangerous? Is it a deliberate design to not do this?

**Comment by scottleibrand** [comment]
Yes, we made a design decision to avoid relying on oref0 keeping any state. In addition to simplifying things generally, that means that we can have multiple rigs running oref0, and if one of them comes into range, it only needs to pick up the latest pumphistory and current temp to get up to speed. After that, all the rigs perform the same deterministic calculations and come to the same conclusion given the same inputs.

**Comment by thebookins** [comment]
OK, that makes sense. Thanks. Back to using pump history for the full DIA then.

**Comment by thebookins** [comment]
I've got a rig working with `pump-history-prepared.json` as the output of the mmhistorytools `prepare` command. Naturally I've had to modify `oref0/lib/iob` to accept the normalized pump history. Just wondering is it best to assume that some people will update oref0 but won't add the mmhistorytools device? Should the `iob` process include a switch for the type of history input, or is it OK to require users to update their reports?

**Comment by scottleibrand** [comment]
Nice!  Good progress.

We'll need to figure out some way to ensure backwards compatibility.  If we want to deprecate the old data format, we can add a deprecation warning, but for now we'll have to be able to parse both formats.  Ideally we could autodetect which they're using, and act accordingly, but if that's not possible then we'll need to add a switch that defaults to the old behavior.

**Comment by thebookins** [comment]
The old format uses `"_type"` while the new format uses `"type"` so we could use the existence of the `"_type"` key to switch to the old behaviour. Is that robust enough?

**Comment by cjo20** [comment]
Rather than adding something subtle like that, I'd add an extra field that makes it really obvious what is going on.

**Comment by scottleibrand** [comment]
Do we have that option?  If adding a field would require modifying mmhistorytools, perhaps just keying off the name of the type field would be sufficient...

**Comment by cjo20** [comment]
Not tested, but something like this as part of an openAPS alias:
`cat mm_tools_output.json | json -E "this.mmTools = true" > mm_tools_output_marked.json`

**Comment by thebookins** [comment]
That could work. There's another subtle issue - mmhistorytools doesn't have a field for percent type basal and oref0 doesn't include percent basals in iob. There is a human-readable description string, and we could look for a '%' character in this - but there's no guarantee that that description string won't change. Worth a PR to include a basal type field?

**Comment by loudnate** [comment]
The `normalize` command (which is the last step in the `prepare` shortcut command) converts percent-based temp basals to absolute (U/hour) in all cases.

**Comment by sulkaharo** [comment]
Whoa, only just noticed this; we have three >2x basal changes during the day in the current profile. @thebookins is the commit with the change public?

**Comment by cjo20** [comment]
Just to note that this is more of an issue with increasing basal doses (which will calculate negative IOB when it shouldn't) than decreasing basal doses (which will calculate positive IOB when it shouldn't).

**Comment by sulkaharo** [comment]
Noted! Guess the changes is this one: https://github.com/openaps/oref0/compare/dev...thebookins:wip/basal-aware-iob ? The IOB test doesn't pass on the committed code.

**Comment by sulkaharo** [comment]
Ah right, figured why the test wasn't working - our code now assumes the profile contains the default variables, so ```bolussnooze_dia_divisor: 2``` missing from the test caused the bolus snooze IOB to be miscalculated. We should change the tests to use the full profile object; the current method of passing in a profile that's missing variables that are actually passed in when the loop runs can cause the tests to not actually test the real loop behavior.

**Comment by thebookins** [comment]
@sulkaharo yes that's the branch. I'll tidy up tonight and implement the `mmTools` switch. The tests also need to be rewritten: the `history` object in the iob tests will be different depending on the value of `mmTools`.

@loudnate thanks for the clarification. How would you suggest excluding percent basals in the iob calculation? What about something like an optional argument `--exclude-percent-basals` for the normalize command?

**Comment by cjo20** [comment]
@thebookins I think the point of loudnate's comment was that mmhistorytools works out what the effective basal rate was in U/hr given the current basal rate and the percentage. This means that data leaving the tool all looks like it was generated on a U/hr basal rate.

**Comment by thebookins** [comment]
@cjo20 That's fine, and we could certainly calculate iob using the normalized output, but I was thinking we should match the current behaviour, which is to ignore percent-based temp basals (presumably because if there is one in the history it's a genuine - albeit temporary - basal rate change, and not an action of oref0).

**Comment by scottleibrand** [comment]
No; if that is the current behavior, it is entirely a side effect of not supporting percent basals at all. If you set the pump to percent basal mode, it totally disables OpenAPS, which will fail to set (absolute) temps until it is corrected. 

I think we should calculate IOB based on the normalized output for simplicity.

**Comment by sulkaharo** [comment]
https://github.com/openaps/oref0/compare/dev...sulkaharo:wip/accoutforbasalprofile now contains an alternate implementation that doesn't require mmhistorytools. (One less component to worry about.)

**Comment by thebookins** [comment]
https://github.com/openaps/oref0/compare/dev...thebookins:wip/basal-aware-iob2 is an attempt at allowing for mmhistorytools prepared data, and also defaulting to the current behaviour. Currently planning to use an optional argument in oref0-calculate-iob.js to switch between the two data sources. I'll remove the percent basal check (thanks @scottleibrand and @cjo20 and also plan to add tests for square wave boluses and suspend/resume.

@sulkaharo nice! Do you think the overhead of adding mmhistory tools outweighs its advantages?

**Comment by cjo20** [comment]
@sulkaharo One advantage of mmhistorytools is that it does additional cleaning up of the pump history (such as bolus wizard de-duplication)

**Comment by scottleibrand** [comment]
mmhistorytools also adds synthetic temp basal to zero records during pump suspends, so IOB would still be accurate afterward even if you don't temp to zero manually.

**Comment by sulkaharo** [comment]
I think the only argument for not using mmhistorytools is that it's yet another component to the system, which needs maintaining. It's also implemented in Python while rest of oref0 is in Javascript / shell, so this would (correct me if I'm wrong) be the first dependency that'd change it so oref0 is not self-contained in being able to read raw device data and then act on it. Would the module be rolled in as part of oref0 repo? @loudnate opinions? You seem to be shifting focus to Loop. Me and @jasoncalabrese have also discussed for a long time that we should refactor the codebase a little so we could directly share code between Nightscout and oref0 and this would potentially make this harder. So it's really just a question of maintenance and the future development of the codebase.

**Comment by cjo20** [comment]
I'm not sure the distinction between oref0 and not-oref0 is that important. Why would it be critical that someone should be able to pull/process device data without using anything at all other than the oref0 repo? We already have to pull code from several repos to get the system up and running (openaps, oref0, openaps-contrib, decocare), I don't see one more being an issue.

**Comment by thebookins** [comment]
IMHO I like the modularity that mmhistorytools allows, and the output is generic so you could imagine an equivalent historytools implementation for other pumps and this makes oref0 more device agnostic. The iob process then becomes simpler as it's not mixing up history parsing and iob tracking. I'm a newbie to this discussion though and not sure about the Javascript / Python issue. Glad for the discussion as we're keen to avoid the iob errors overnight.

**Comment by jasoncalabrese** [comment]
Also since we know that the current behaviour of oref0 isn't correct the best way to fix it for all users is to fix oref0.  Then when they update it will be more correct without having to reconfigure their loop.

If we go the mmhistorytools route it shouldn't be an option, we should rip out the current implementation and force everyone to switch to the new way, but thats really disruptive.

I hope I'm wrong, but it's my assumption that the python projects will see less maintenance going forward.

**Comment by cjo20** [comment]
Not implementing this change because the tool might be less well maintained going forward isn't a great idea. The nature of this change means it is predominantly an extra pass on the input data; it can be reimplemented at a later date in javascript if that is what someone wants to do. At that point, people can switch over to the oref0 implementation easily. 

Not breaking backwards compatibility seems to be a goal for the project; previous features have been tested to ensure that people weren't left with broken loops when they upgrade. To fit with the UX of the project, the new features will probably have to be separate oref0 commands, which will involve people changing their openaps.ini.

It might be worthwhile giving people a fixed switchover date; give log messages / notifications that people are using a deprecated method which will be going away in a future release. Then when enough time has been given, strip out the old method.

**Comment by sulkaharo** [comment]
Regarding data formats going forward: Nightscout currently expects the data in a format that's based on a slightly cleaned up log of MedTronic -style events; anyone adopting mmhistorytools will also need to go on passing the old format logs around for Nightscout visualization. Ideal case would be we could get to a place where our data is as device independent as possible and visualization friendly; what's the best way forward for that? The mmhistorytools data cleaning is great for IOB calculation but potentially not great for visualization (given it hides the original actions of the pump). 

Not breaking loops sounds like a good goal to me - there's been a couple changes where the loop behavior changed slightly with an update and a new config file was expected, but this was not obvious by reading the logs when running the loop. And how to fix breaking changes has definitely not been obvious in the errors.

Re: dependencies - we should consider importing the dependencies into the main repo, so 1) it can be guaranteed that dependencies are available if the repo is available, and 2) the exact version we expect of each dependency can be tested. Same goes for Nightscout btw, where we've had issues with dependencies on deploys. The left-pad debacle was kind of eye-opening in this regard.

**Comment by sulkaharo** [comment]
Hey mmhistorytools usage question: what's the right way to do time zone processing with the tools in the pipeline? I'm currently adding the time zone information to the logs, but looks like if I do this with the log processed with mmhistorytools, the IOB calculation fails (shows 0 IOB at all times).

**Comment by thebookins** [comment]
@sulkaharo With https://github.com/openaps/oref0/compare/dev...thebookins:wip/basal-aware-iob2 I'm doing something like this:
1. Add a report to run the history tool over the raw pump data:
    ```bash
      $ openaps report add raw-pump/pump-history-prepared.json JSON history prepare raw-pump/pump-history-raw.json --basal-profile raw-pump/selected-basal-profile.json
    ```
2. Change the report `monitor/pump-history.json` to take the output of step 1 as input (or create a new report using the tz device).
3. Add `remainder = --prepared` to the report `oref0-monitor/iob.json`

Doing this I get the expected IOB.

**Comment by sulkaharo** [comment]
So hey plan for immediate future: I'll PR the change that fixes the negative basal issue and basal rate issues in, while we look at all the work needed to get the mmhistorytools version in (as that requires writing instructions on needed changes to the loop setup). My patch doesn't require any changes to config.

**Comment by cjo20** [comment]
Might be worth documenting that it requires `lodash` to be installed.

**Comment by sulkaharo** [comment]
lodash is in the dependencies list in package.json; as far as I know there's no way to install oref0 without npm auto-installing the dependencies?

**Comment by cjo20** [comment]
I just pull the head of the code to my repo on my rig and it seems to pick up the updated code, without having to re-run npm install, hence not automatically pulling lodash.

**Comment by sulkaharo** [comment]
Right, guess you've used npm link to install oref0? Using the recommended ```npm install -g .``` to install from source copies the code to /usr/lib/node_modules/oref0/ and ensures the dependencies are installed, as well as ensuring that pulling a new version will need to be installed before it's actually taken into use.

**Comment by jasoncalabrese** [comment]
The easy way to get the global install and npm link setup is to use the little npm script I added a little while ago.

`npm run global-install`

You only need to do that when there are new dependencies or new oref0 tools.

**Comment by thebookins** [comment]
Did a quick experiment to compare the mmhistorytools and oref0 solution to this issue using a 12-hour pump history (see pic below). The basal iob is not the same for the two methods if some of the temp basal periods cross basal profile boundaries. Ideally in this situation we should split the temp basal into two (or more) normalized basals. (I think mmhistorytools does something like this.) It might be possible look up the basal profile for each synthetic micro bolus and then adjust the microbolus size up or down, but this could get messy. 
![plot](https://cloud.githubusercontent.com/assets/12263040/18021652/5130391a-6c2c-11e6-91ee-58ed830c7dfe.png)

**Comment by scottleibrand** [comment]
Nice analysis @thebookins.  I agree that would be ideal, and that's one of the reasons I'd like to support mmhistorytools.  But as your data shows, the IOB calculations are pretty darn close between the red and green, so I'm happy to :shipit: as-is and allow people to use mmhistorytools if they want the more precise IOB.

**Comment by thebookins** [comment]
Good plan @scottleibrand. I'm happy to have a go at writing the instructions to include mmhistorytools in the config if that would be useful. Any immediate plans to import mmhistorytools into the main repo?

**Comment by scottleibrand** [comment]
Happy to merge mmhistorytools support if it's done using additional config and fully backwards compatible with existing setups and @sulkaharo's fix.

**Comment by bewest** [comment]
It is backwards compat... it'd be simpler to use mmhistorytools all the time.  The recipes/templates all work, and it's installable via pip so it all works the same way.

**Comment by bewest** [comment]
Here's some example output using mmhistorytools and other stuff in tandem with getting it into NS: https://github.com/bewest/openaps-example/blob/master/effects/cumulative-results.json

**Comment by sulkaharo** [comment]
@thebookins that's an awesome analysis? Did you implement a tool to run that? Can you run the same against https://github.com/sulkaharo/oref0/tree/wip/split-temp-basals which implements splitting the temps the same manner as mmhistorytool, so the IOB should align much closer

**Comment by thebookins** [comment]
Hey @sulkaharo, no problem. I ran the analysis again, this time against your branch `wip/split-temp-basals` (the red 'oref0' line in the graph). Looks different but still not the same as mmhistorytools, unless I did something wrong.
![plot](https://cloud.githubusercontent.com/assets/12263040/18033245/ab15222a-6d61-11e6-8eee-e49a9ef756d3.png)

**Comment by cjo20** [comment]
Any chance you could share the method for generating those images? It'd probably be a useful tool to have for future development.

**Comment by thebookins** [comment]
@cjo20, @sulkaharo I've added my scripts for generating the above analyses at https://github.com/openaps/oref0/compare/dev...thebookins:wip/experiments. It's not an automatic tool yet, just a node and a python script that require some manual changes to generate the graphs. Note that to run against the mmistorytools method in https://github.com/openaps/oref0/compare/dev...thebookins:wip/basal-aware-iob2 you will need to set the boolean `prepared` in `experiment.js` to `true`. Hope it's useful.

**Comment by sulkaharo** [comment]
Found a bug with the help of the new test data; rewrote the splitter logic and pushed.

When I run the plotter, it processes data for some time and then spits out:

```
Traceback (most recent call last):
  File "plot.py", line 53, in <module>
    main()
  File "plot.py", line 24, in main
    starttime = datetime.strptime(data_original[0]["t"], '%I:%M:%S %p')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '11:00:00' does not match format '%I:%M:%S %p'
```
Any idea what might be going on? Wonder if this is a locale difference in how the experiment.js output works?

**Comment by thebookins** [comment]
Sounds like it's a timezone issue for sure. Your error message says 'time data 11:00:00 does not match...' I expect the tool to cover 18:00:00 to 06:00:00. I'm at +10, you're at +3 hence the 7 hour difference between 18:00:00 and 11:00:00. I did wonder if that would be a problem :smile:. I will have a look tonight and see if I can figure it out.

**Comment by thebookins** [comment]
@sulkaharo I have made a minor change to the python script to hard code the starting time (it's an arbitrary time scale anyway). I think the `toLocaleTimeString()` function is behaving differently (12-hour vs 24-hour time). Probably simplest to just ignore the timestamp for the moment.

**Comment by sulkaharo** [comment]
@thebookins can you also commit the mmhistorytools branch json output? I still have issues getting the branch going but would love to compare the outputs

**Comment by thebookins** [comment]
@sulkaharo I have committed the three output files (original, mmhistorytools, oref0). The `plot.py` script should work against this output now.

**Comment by thebookins** [comment]
Hi All,
I'm trying to understand the properties of the IOB object `netbasalinsulin` and `hightempinsulin`. They don't appear to be used in any downstream code (e.g. `determine-basal`). I also don't get why you'd want to keep track of undecayed basal insulin for the last DIA hours. Is this just legacy code? OK to remove in the mmhistorytools branch?

**Comment by scottleibrand** [comment]
Yes, that is legacy from the old way of doing meal assist. Advanced meal assist doesn't use them any longer. I was going to remove them after we release AMA to master, but you're welcome to do so in any branch that isn't going to be released soon.

**Comment by sulkaharo** [comment]
@thebookins awesome, the plot now aligns correctly and as expected, split-temp-basals pretty much matches the mmhistorytools output. Looks to me like there's a 0.05 unit difference in the early plot (split branch adding one extra microbolus for some reason) and the latter curve matches exactly.

![plot](https://cloud.githubusercontent.com/assets/1001330/18229771/7bb9ca36-728d-11e6-96c8-af1abaaed1a6.png)

**Comment by thebookins** [comment]
@sulkaharo great work! Nice to have this issue fixed. I'm still working on the alternate setup using mmhistorytools - I'll make sure it merges with yours and then put it out there for feedback. We use square boluses a bit and it would be nice to have them considered too.

**Comment by sulkaharo** [comment]
The branch is now merged as #202, so just merge with dev. We're still missing support for pump suspends, so that needs adding.

Re: square waves - we used those before looping but the loop should remove the need to use and the square prevents the loop from working when the square is taking effect. Can you describe how you're using them, so we can take those use cases better into account. :)

**Comment by thebookins** [comment]
Cool, I'll merge with dev then.

Re square waves: we've only been looping overnight for a few months now and don't have a mobile rig yet, so the loop isn't running at dinner, when our son tends to need a dual wave delivery to avoid going low later (we have played with basal rates but the dual tends to work best).

The square wave appears in the pump history shortly after starting it, with the `amount` equal to the insulin delivered up until that point. Then when the square is finished the `amount` field is updated to the total delivered. Unless I'm mistaken, that whole amount is added to IOB and decayed using the timestamp at the start, so the IOB will be underestimated for a bit after the square is finished.

**Comment by scottleibrand** [comment]
Did this end up getting merged?

**Comment by thebookins** [comment]
I have an alternate setup using mmhistorytools ready to go, but there was some concern about adding in another dependency. I can submit the PR if there is still interest. mmhistorytools should handle square waves and pump suspend/resumes.

**Comment by scottleibrand** [comment]
If we can figure out how to integrate it into oref0-setup so it gets all set up from scratch without any extra work on the user's part, I think that would address most of that concern.  Are you (or is anyone else in this thread) interested in doing that work?

**Comment by thebookins** [comment]
Happy to have a crack at it. Will post here when it's ready for review.

**Comment by thebookins** [comment]
I've PR'd my changes as https://github.com/openaps/oref0/pull/279. Hoping it's not too opinionated! The graph below compares the old behavior (blue) against this PR (green) and @sulkaharo 's fixes in oref0.

![plot](https://cloud.githubusercontent.com/assets/12263040/21215809/89bbd61e-c2f7-11e6-9bbd-24fb5d001fe5.png)

**Comment by scottleibrand** [comment]
Anyone care to test https://github.com/openaps/oref0/tree/wip/mmhistorytools-integration and let us know how it goes?
