### ISSUE TITLE
update the error messaging to prioritize the "old BG" warning

### ISSUE THREAD

**Issue by LongboatAline** [openaps/oref0#950]
Note from conversation:
_update the error messaging to prioritize the "old BG" warning over the "BG unchanged for 45m" one_

Background: even though the NS site was mirroring the current BG, the loop somehow snagged and got stuck with an old BG reading. 
Self-healed while looking for the error.

Conversation at [ITB](https://gitter.im/nightscout/intend-to-bolus?at=5aa92375a60157d62fe76736) 

Thanks!

**Comment by scottleibrand** [comment]
It looks like the loop was operating correctly and refusing to loop on an old BG, but because of the new "BG unchanged for 45m" safety check, it failed to display the normal "your BG is too old" warning.  I'd like to change that to make it more obvious to the user why they're not looping.

**Comment by danamlewis** [comment]
I believe this is resolved in 0.7.0; please re-open (or target a PR to dev branch for 0.7.1 or beyond) if this needs further optimization.
