### ISSUE TITLE
Feature Request: Lazy Carb Entry / Sensitivity

### ISSUE THREAD

**Issue by rkresha** [openaps/oref0#951]
Maybe this is already in the logic today, but was thinking that if people got into a bad habit of letting the rig do all of the work and weren't entering carbs, the sensitivity calculation would be all kinds of screwed up if the person started logging carbs. It'd be nice if the logic could detect this and reset the previous sensitivity calculation. Thoughts? I wanted to get the idea out there before I forgot

**Comment by th122** [comment]
Just a thought: I've often wondered why it's not (yet?) possible to mark out a carb entry as either "exact" or "guesstimate"  to assist sensitivity calculation.  On the recent experience of a full week of illness and resistance, I have been quite surprised how good the job of the sensitivity calculation has been! (There vwas little to no food involved, though, which may have helped.)

**Comment by alimhassam** [comment]
From my short experience, it seems like bad/guestimate carb entry has quite an effect on autotune. I'm wondering if this or other suggestions could help. maybe I should raise a separate issue/request. I'd like to find a way to get my hands on more data for better analysis.

**Comment by danamlewis** [comment]
@rkresha see https://github.com/openaps/oref0/issues/1278 for related proposal for no-bolus no-announce behaviors. Closing this issue in favor of discussing there in more detail.
