### ISSUE TITLE
Log rotate needs to be set to Daily vs. weekly

### ISSUE THREAD

**Issue by Sophieinthecloud** [openaps/oref0#961]
Devices are filling up because automated change of log rotation is not being set to daily instead of default weekly.  Need to automate this in setup script.  Thanks!

**Comment by Kdisimone** [comment]
Opps...was logged in as someone else there...actually is my issue.  Left over from the Looping get-together yesterday.  Sorry!

**Comment by danamlewis** [comment]
Resolved and will be pushed to master with 0.6.1 release
