### ISSUE TITLE
oref-determine-basal doesn't return after console.error("Could not determine last BG time")

### ISSUE THREAD

**Issue by scottleibrand** [openaps/oref0#97]
@johnmales noticed that he has "on several occasions run into the problem of the medtronic CGM data being stale - sometimes hours old - and oref0 going ahead and setting temp basals. Usually this circumstance happens with that decocare page loading bug and the downloaded cgm data getting “stuck” redownloading old data repeatedly." It looks like he's seeing the issue @ktomy is trying to fix in #54, namely that https://github.com/openaps/oref0/blob/master/bin/oref0-determine-basal.js#L39-L54 does not return early after https://github.com/openaps/oref0/blob/master/bin/oref0-determine-basal.js#L47 ("Could not determine last BG time").  That is a safety-critical bug that we need to get fixed ASAP and merged to both dev and master.  If we can do so by merging #54 that would be great; otherwise adding a `return` line might be sufficient.

**Comment by scottleibrand** [comment]
Has anyone seen this issue lately, or have we fixed the problems leading to its underlying conditions?

**Comment by johnmales** [comment]
I haven't seen this issue lately. 






On Sun, Dec 4, 2016 at 1:33 PM +1100, "Scott Leibrand" <notifications@github.com> wrote:












Has anyone seen this issue lately, or have we fixed the problems leading to its underlying conditions?
