### ISSUE TITLE
malformed curl command results in two requests

### ISSUE THREAD

**Issue by ryanpacker** [openaps/oref0#971]
Some folks who are using autotune from the command line are experiencing a parse error despite having all json files properly formatted. After deeper investigation, here's the flow of events causing the error:

- oref0-autotune is invoked from CLI
- ns-get is called on line 196
- for the common use case, CURL_AUTH is set on line 37 of ns-get
- the actual curl command is executed on line 60 of ns-get

Because of the quoting included on line 37, curl sees what is intended to be a single header flag and header as two separate arguments. The issued curl command ends up as follows:
`curl -m 30 -H '"api-secret:' '${API_SECRET}"' ...`

This results in two curl request being made. By setting env variable NIGHTSCOUT_DEBUG="1" you can see that the first request is made based on the following:
`Rebuilt URL to: ${API_SECRET}"/`

In most cases, that request will not resolve to anything, the connection will close, and curl will proceed with the second request. If for some reason, the first request resolves to a server that returns output (as is the case for the person I was assisting), the additional output will proceed the proper JSON response and in turn when the curl response is piped to jq, a parse error will occur. 

I believe line 37 of ns-get needs to be changed to
`CURL_AUTH='-H api-secret:'${API_SECRET}`

I have tested this on the mac in two environments, but much more thorough testing will be needed before releasing. I will fork the repo, commit a change, and submit a PR for review as soon as I can get back in front of a computer. Any early feedback is welcomed in the mean time.

**Comment by scottleibrand** [comment]
Before doing the PR, I would check that this isn’t already fixed in the dev or go-explorer-hat branches. If not, then please do go ahead and PR. Thanks!

**Comment by dirkgastaldo** [comment]
This "CURL_AUTH='-H api-secret:'${API_SECRET}" fixed my parse error ("parse error: Invalid numeric literal at line 1, column 7"). I can run Autotune on my Mac now. Thank you, Ryan, for troubleshooting this! And thank you, Scott, for Autotune!

**Comment by ryanpacker** [comment]
Good call, Scott. I checked those two branches, and the offending line is commented out in both. That fixes the bug for people who do not require an API_SECRET to connect to the API. I've fixed the issue in [my branch](https://github.com/ella7/oref0/blob/dev/bin/ns-get.sh) but with limited ability to test all the possible scenarios, I would defer to people much more familiar with the code on whether this should be merged. Let me know if you think I should submit a PR.

**Comment by scottleibrand** [comment]
Ah, yes, now I remember.  I think your fix is much more likely to work more broadly, especially for people who have token auth, so yes, let's go ahead and do a PR.  You can target it at https://github.com/openaps/oref0/tree/0.7.0 and it'll get plenty of testing before getting used too broadly.

**Comment by ryanpacker** [comment]
OK. [PR submitted](https://github.com/openaps/oref0/issues/971). Thanks.
