### ISSUE TITLE
issue with pump comunication

### ISSUE THREAD

**Issue by gaston2010** [openaps/oref0#987]
hello everyone, 
this is my first time with OpenAPS and I am having issues connecting the rig with the pump. I followed all the instructions and the rig is working perfect but somehow is not closing the loop with the pump (minimed 715)... any clue??? thanks in advance
This is the error log I am receiving:

Starting oref0-pump-loop at Wed Apr 25 12:52:02 -03 2018 with 3 second wait_for_silence:
Waiting up to 4 minutes for new BG: ls: cannot access /tmp/pump_loop_completed: No such file or directory
Radio ok. Listening: .No interfering pump comms detected from other rigs (this is a good thing!)
Preflight OK. Old settings: AssertionError
ls: cannot access settings/profile.json: No such file or directory
Profile invalid: ls: cannot access settings/profile.json: No such file or directory
AssertionError
Couldn't refresh_old_profile
oref0-pump-loop failed. pump_loop_completed more than 15m old; waiting for 40s silence before mmtuning
Radio ok. Listening: .No interfering pump comms detected from other rigs (this is a good thing!)
Listening for 40s silence before mmtuning: .No interfering pump comms detected from other rigs (this is a good thing!)
mmtune: "916.684", 5, -51 No wait required.
Unsuccessful oref0-pump-loop at Wed Apr 25 12:54:06 -03 2018
grep: monitor/temp_basal.json: No such file or directory

**Comment by tim2000s** [comment]
Are you using a US or WW pump (check the back - if WW serial number ends WWS) and do you have remote options enabled on the pump?

**Comment by tim2000s** [comment]
Also - jump in gitter for this kind of thing.

**Comment by gaston2010** [comment]
hi tim, thanks so much for your reply.
we are using a US pump.
yes I have the remote options enabled but with values 000000.

I am trying everything again from scratch to see if there was something
wrong with nightscouts.

thanks agan!

2018-04-25 17:03 GMT-03:00 Tim Street <notifications@github.com>:
